### ISSUE TITLE
Opting-out cache is not working

### ISSUE THREAD

**Issue by USvER** [turbolinks/turbolinks#100]
Opting-out cache is not working. Page visit always show preview.

This have no effect.
```
<meta name="turbolinks-cache-control" content="no-cache">
```
```
<meta name="turbolinks-cache-control" content="no-preview">
```

**Comment by packagethief** [comment]
Hey @USvER, I'm not able to reproduce this issue. Your cache directives are correct. Can you provide any more details, or a minimal sample that demonstrates the problem?

**Comment by USvER** [comment]
Will try to create isolated example to reproduce this issue.

```
rails 5.0.0.beta3
turbolinks-source 5.0.0.beta2
turbolinks 5.0.0.beta2
```

```html
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>
    <meta content='no-cache' name='turbolinks-cache-control'>
```

**Comment by sstephenson** [comment]
@USvER You’ll need to run `bundle update turbolinks-source` to upgrade to the latest version. We added support for `<meta name="turbolinks-cache-control">` in beta3.

**Comment by USvER** [comment]
@sstephenson now it works. Thanks!
