### ISSUE TITLE
about restoration visits

### ISSUE THREAD

**Issue by wenweih** [turbolinks/turbolinks#104]
Hi, I am confuse that using turbolings with third-party libraries.  
using [typed.js](https://github.com/mattboldt/typed.js) in my home page , everything is ok with application visits
![ok](https://cloud.githubusercontent.com/assets/3449692/15514100/fd1bc97c-2219-11e6-8f93-0960025fc588.gif)

but when i navigate with the browser’s Back or Forward buttons to home page again , something went wrong, show multiple cursor .
![not](https://cloud.githubusercontent.com/assets/3449692/15514164/538b44cc-221a-11e6-9416-b60b3e497be3.gif)
All js in my Rails app are put in application.js  
```
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require jquery.timeago
//= require semantic
//= require jquery.timeago.zh-CN
//= require headroom
//= require typed
//= require jQuery.headroom
//= require highlight.pack
//= require home

document.addEventListener("turbolinks:load", function() {
  $("#header").headroom();
  $("time.timeago").timeago();
  $('.ui.sidebar').sidebar('attach events', '.toc.item');
  $('.person-description').typed({
    strings: ['hello world'],
    loop: true,
    showCursor: true,
    startDelay: 500,
    backSpeed: 10,
    backDelay: 1500,
    typeSpeed: 80,
    contentType: 'html'
  });
});
```
I was too tired to figure it out.  Who can help me?  thank you very much . 🍺

**Comment by wenweih** [comment]
😢 finally, I remove typed-cursor before typed.js was initialized
```
$('.typed-cursor').remove();
```
anyway, thanks all.

**Comment by mikevic** [comment]
I have the same problem - what exactly was the solution?

**Comment by wenweih** [comment]
@mikevic   
```$('.typed-cursor').remove();``` in ```turbolinks:before-cache``` event  
[preparing-the-page-to-be-cached](https://github.com/turbolinks/turbolinks#preparing-the-page-to-be-cached)

**Comment by nickmjones** [comment]
For anyone else who comes looking, I fixed this issue with the following implementation:

```
$(document).on 'turbolinks:before-cache', ->
  $('typing').remove()
  return

ready = ->
  $(".typing").typed
    strings: [
      "customers.",
      "champions.",
      "fans.",
      "advocates.",
      "promoters."
    ],
    typeSpeed: 100
    backDelay: 3000
    loop: true
    contentType: 'text'

$(document).ready ready
$(document).on 'turbolinks:load', ready
```

The variable here is the name of your targeted element (`.typing` for me). I realize this is a closed issue, but I figured if I could save someone else 20 minutes I would. 👍
