### ISSUE TITLE
Scroll problem when back button used

### ISSUE THREAD

**Issue by woto** [turbolinks/turbolinks#108]
Hi, it seems that nobody didn't report about this problem yet. And i even can't understand is it only my problem or is this a bug in turbolinks.

I have a scroll problem (i don't use any javascript for scrolling logic in my application).
All works fine until 'back button in browser' used. After that all visits on a new pages automatically 'prescrolled'. I've recorded video if i described the problem unclear. Thank you.

https://youtu.be/Jt39CTMBcZc

**Comment by packagethief** [comment]
Hey @woto. Thanks for the video. It looks like you're using the Opera browser. Does the same thing happen in other browsers?

**Comment by woto** [comment]
@packagethief Damn! You are right. There are no problems in Google Chrome. 
By the way i'm using old version of Opera 35.0. After upgrading to Opera 37.0 problem also gone.

**Comment by packagethief** [comment]
Great! It's nice when the fix is so simple ;-)
