### ISSUE TITLE
request.referer not working

### ISSUE THREAD

**Issue by heyogrady** [turbolinks/turbolinks#109]
Is Turbolinks 5 compatible with using `request.referer` in a Rails controller to fetch the referring URL?

No matter when I call `request.referer`, it returns the URL from the initial page load, not the previous visit. I'm not sure if it's a bug, or if there's a different way to do this in Turbolinks 5 that I haven't figured out yet...

**Comment by heyogrady** [comment]
Gahhhh nevermind... it was my own separate issue

![](https://media.giphy.com/media/14aUO0Mf7dWDXW/giphy.gif)

**Comment by asja22** [comment]
i have the same problem. but it happen to in production only. in development it working fine.
