### ISSUE TITLE
Method to check HTTP response status before rendering?

### ISSUE THREAD

**Issue by vlucas** [turbolinks/turbolinks#112]
I have read the documentation looking for a way to inspect the HTTP response and status code, and then NOT render the page based on the response, but I can't find a way to do this.

My use case is that if the server returns 500, I want to display a custom message myself with JS instead of navigating the user to the bad looking error page (rendering it with Turbolinks). I see the `turbolinks:request-end` event, but the docs don't mention any way to prevent rendering within that event.

Is there any way I can do this with Turbolinks?

**Comment by sstephenson** [comment]
Currently there’s no way to prevent rendering, but we’re open to exploring that in the future. 

Could you describe what exactly you’d want to do differently in the case of a 500? Note that by that point, the URL will have already changed, so you don’t want to see the previous page. You don’t want to break the back button for future navigation, either.

**Comment by vlucas** [comment]
Yeah - Basically I would just like to intercept the process to NOT change the URL or "visit" the page, and instead show a formatted popup message with JavaScript. So in effect, I am looking for a way to "cancel" the page visit after I have an opportunity to inspect the raw HTTP response object.

**Comment by vlucas** [comment]
I have seen some workarounds where people hit the URL with AJAX, then use Turbolinks to just replace the page content and set history, etc. but it would be really nice to have this built-in so I don't have to duplicate all the AJAX work that Turbolinks is already doing for me.
