### ISSUE TITLE
Initialize new content - responding to page updates

### ISSUE THREAD

**Issue by SqueezedLight** [turbolinks/turbolinks#118]
Hi guys,
i'm trying to initialize new content, loaded via ajax (infinite scrolling, loading items via a "more" button).

Fortunately the docs describe this case under "Responding to page updates":

> Turbolinks may not be the only source of page updates in your application. New HTML can appear at any time from Ajax requests, [...], and this content will need to be initialized as if it came from a fresh page load.

Thats exactly what i'm trying to do - but how do i tell Turbolinks that there is new content on the page? The API only gives me ```Turbolinks.visit()``` which is not helpful in this case. What am i missing?

Thanks a lot!

**Comment by packagethief** [comment]
Inserting new content in response to an XHR request is outside Turbolinks' purview. How you insert and initialize new content, whether it comes from infinite paging or anywhere else, is entirely up to you! There's no need to inform Turbolinks about it. 😉 

The general pattern I've seen used for infinite paging is to request the next page with XHR and return a JavaScript response that appends the results to the current page. If you need to initialize the loaded content (say, to format dates or animate elements), you can fire a custom JavaScript (for example, `infinite-page:load`) and listen for it in your application much in the same way you listen for `turbolinks:load`. When it fires, initialize your page.

An alternative would be to use [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) to observe each page of results as its added to the DOM. Then you wouldn't need a custom event, and you wouldn't need to distinguish between content loaded by Turbolinks, and content loaded by infinite paging.

**Comment by SqueezedLight** [comment]
Hi @packagethief thanks a lot for your response. Unfortunately, i may have not described the issue very well...

Infinite scrolling and adding the new content to the feed works - always has. The problem occurs when navigating away from the feed and going back with the browsers' back button. In this case the newly added content is not shown. The page is restored from the Turbolinks Cache - but in the state of the initial page load. 

I'm using react and the new content is initialized as if it is on an initial page load. All my components are aware of the new posts - only Turbolinks is not...
