### ISSUE TITLE
Deprecated CoffeeScript

### ISSUE THREAD

**Issue by yordis** [turbolinks/turbolinks#121]
This is just my suggestion. Any feedback/suggestion is base on my experience.

Back in time, I could understand that CoffeeScript had some needs for the once that don't understand and/or want to use vanilla Javascript, with some features enhancements and easy way to implement some of the tedious stuff from Javascript or even avoid common mistakes. Today, ES6 have a very good state and probably most of the pain of Javascript go away. From the code base I don't see anything that we really need from CoffeeScript anymore.

I can't properly read the current code base, even when Javascript is my main programming language, I read the code and most of the time I am actually `guessing` which frustrated me. I can't agree that CoffeeScript indentation and style is actually cleaner, depends of where you come from and what are you used to that could be true or false, but realistic, **most of the people know Javascript (when ever you hate or not, you understand it)**

The only reason I am creating this ticket today, is because I want to fully understand how Turbolinks is doing the job, probably for make contributions which up to this point we had `19 issues`, and frustrated me that much the fact that is CoffeeScript instead of Javascript, I have no time for learn something CoffeeScript and fighting with everything about Javascript, because even when compiles down to Javascript is so different that you have troubles actually programming and I just want to be productive.

**Comment by packagethief** [comment]
Thanks for the feedback, @yordis. I understand that CoffeeScript isn't everyone's favorite and that having to learn it can be a barrier to contributing. As you've alluded to though, our use of CoffeeScript is a personal choice, and one that we remain quite happy with.

I sincerely hope this won't discourage you from contributing to Turbolinks in the future.

**Comment by yordis** [comment]
@packagethief with all the respect, in my opinion, the main issue with the Javascript community is the implementations based on personal choice, no even technical choice, personal one as you said.

This is one of the problem with open source projects, and this is how we re-invent the wheel or replicate the wheels, adding and adding more packages resolving the same issue just because someone decide that personally don't like the implementation for X reason, or sometimes the repo owners don't want to change something even when could be a technical and engineering reason (I am not saying this situation right now) so on and so on.

Realistically I would avoid any interaction with Turbolink base code and probably just open issues and wait until someone resolve it in the main project or just create a fork where I can apply my own philosophy (and boom, that's how you create another useless project)

I hope you do something like Node and IO, or Rails and Rails API, where they actually realize that could work together for the good future of the community and no the personal one.

I hope you get into the road that everyone is (at least most of them)

Either way mate, I am just trying to make a point, I really appreciate the effort you put on this project but I can't agree on this one, technically, there is no reason anymore.
