### ISSUE TITLE
Repeat form sending with F5 don't work

### ISSUE THREAD

**Issue by Fudoshiki** [turbolinks/turbolinks#126]
**Rails 4.2 with turbolinks**
1. Open form with method: :put (edit action)
2. Enter invalid data
3. Submit
4. Got rendered page with errors (update action)
5. Press F5
Expected: *browser send form again as PUT request*

**Rails 5.0.0.rc2 with new turbolinks**
1. Open form with method: :put (edit action)
2. Enter invalid data
3. Submit
4. Got rendered page with errors (update action)
5. Press F5 
Expect: *browser send form again as PUT request*
Got: *browser send request GET on update action (route error) but expected PUT again*

Without turbolinks works on both rails app

**Comment by sstephenson** [comment]
Please see [Redirecting After a Form Submission](https://github.com/turbolinks/turbolinks#redirecting-after-a-form-submission) in the documentation.
