### ISSUE TITLE
Invalid detection of URL visitability

### ISSUE THREAD

**Issue by nicholasrq** [turbolinks/turbolinks#127]
Hello there.

I've faced an issue when `Turbolinks` detects is given location visitable or not incorrectly.

Here's the case: I have URLs with custom query-like syntax e.g.

```
/search/Moscow-RU-to-Any-ES-departure-01.07.2016-for-6-nights-2-adults-0-kids-1..5-stars
```

So now `Turbolinks` will try to understand if this URL is HTML or not by getting an extension of the page but in this case `getExtension` will return wrong value because URL ends with `.5-stars` and `Turbolinks` will think that this is actual extension. So the next check of `locationIsVisitable` will return `null`.

I understand that this is not a common issue but it will be great if `Turbolinks` will detect any URLs. And it's obvious that `Turbolinks` itself shouldn't support all variations of URLs but it should offer some kind of middleware or extensions support to allow developers customize the way how `Turbolinks` detects visitability of URLs.

**Comment by sstephenson** [comment]
Hi @nicholasrq,

This has come up before (see #15). 

Turbolinks needs to be able to guess whether a link points to an HTML resource or not, so it won’t attempt to follow links to other resources like images and files. It does this by [checking to see whether the URL has an extension, and if so, whether it matches “.html,” “.htm,” or “.xhtml.”](https://github.com/turbolinks/turbolinks/blob/a083aadfe3544bd2a5d39f1b3fdf99c3fcf1f487/src/turbolinks/location.coffee#L36-L37)

If your URLs have things that look like file extensions in them, my first suggestion is to add a final “.html” extension to the end. If you can’t change your URLs, the solution for now is to override `Turbolinks.Location.prototype.isHTML` as described in https://github.com/turbolinks/turbolinks/issues/15#issuecomment-186639159.
