### ISSUE TITLE
Getting an error when using IE9

### ISSUE THREAD

**Issue by balvig** [turbolinks/turbolinks#128]
Different one from https://github.com/turbolinks/turbolinks/issues/89 😢 

In a project with only jQuery and turbolinks beta5 loaded, am seeing the following error when opening the page in IE9:

```
SCRIPT438: Object doesn't support property or method 'replaceState' 
```

Let me know if there is more I can provide to help with the debugging!

**Comment by sstephenson** [comment]
Fixed. Thanks for the report!

**Comment by balvig** [comment]
Wow, thanks a lot for the prompt response @sstephenson, much appreciated! 🙇
