### ISSUE TITLE
JavaScript part of turbolinks on npm 

### ISSUE THREAD

**Issue by justin808** [turbolinks/turbolinks#13]
Copied from https://github.com/turbolinks/turbolinks-classic/issues/658. Many details can be found there.

@sstephenson, we probably just need a package.json added, and then either one of us can publish to https://www.npmjs.com/package/turbolinks

I can submit a PR for this if you like.

**Comment by kibs** [comment]
I have disabled asset pipeline and use webpack instead, so Turbolinks on NPM would be great. But wouldn't it also require or make sense to implement some kind of module.export into it? So when using webpack/browserify it can be required, and not be put on the window object?

**Comment by Fudoshiki** [comment]
also want to see torbolinks on elixir/phoenix, +1

**Comment by saneef** [comment]
+1 for the npm

**Comment by justin808** [comment]
@sstephenson @packagethief Given that the npm repo is live, we should either add the package.json here or I should do it from a fork and push up the latest.

**Comment by justin808** [comment]
@sstephenson @packagethief Unless there's object, this weekend I'll try pushing this from my own fork to npm. It's somewhat more official if people grabbing the npm version get this from the official repo, but we do this for jquery-ujs and nobody has complained.

FWIW, we had 72K downloads of the "unofficial version" last month: https://www.npmjs.com/package/jquery-ujs
https://github.com/shakacode/jquery-ujs

**Comment by sstephenson** [comment]
The reason we haven’t published Turbolinks to npm is because we don’t have a CommonJS module wrapper around the library. 

I’m guessing most people are going to expect `require("turbolinks")` to work, which in turn suggests they’d want to avoid automatic initialization and the global `Turbolinks` object, which means the process for getting Turbolinks working becomes significantly more involved and requires additional documentation, not to mention changes to the native adapters … which is really something I’d just like to avoid entirely.

**Comment by justin808** [comment]
@sstephenson I'm not sure on the commonjs part being essential. I just want to have the file included like I include jquery-ujs. It's a global there as well. 

Examples:

* https://github.com/shakacode/react_on_rails/blob/master/spec%2Fdummy%2Fapp%2Fassets%2Fjavascripts%2Fapplication_non_webpack.js.erb#L9 which gets included here: https://github.com/shakacode/react_on_rails/blob/master/spec%2Fdummy%2Fapp%2Fassets%2Fjavascripts%2Fapplication_static.js#L22

* https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/app%2Fassets%2Fjavascripts%2Fapplication_non_webpack.js#L5
which gets included here:  https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/app%2Fassets%2Fjavascripts%2Fapplication_static.js#L14

**Comment by sstephenson** [comment]
Is it fair to say this is more about supporting Webpack than having the package published to npm? I.e. if we were to document this, we would have a section in the readme under Installation called “Insatllation with Webpack” rather than “Installation with npm,” right?

**Comment by javan** [comment]
FWIW, Trix, which *is* published on NPM, has a similar issue (https://github.com/basecamp/trix/issues/119) that's broader than using Webpack. There's also Browserify, require.js, and who knows how many other module loaders.

**Comment by justin808** [comment]
FWIW, the maintainer of browserify rails moved to webpack!

https://github.com/browserify-rails/browserify-rails/pull/153#issuecomment-200659517

I'd recommend supporting webpack and then let those interested submit PRs later or other module systems.

**Comment by sstephenson** [comment]
OK, great. 👍

@justin808 Could you open a pull request that adds a package.json file and Webpack instructions to the readme?

**Comment by justin808** [comment]
@sstephenson Is there a standard license to pick: https://docs.npmjs.com/files/package.json#license

**Comment by sstephenson** [comment]
MIT

**Comment by justin808** [comment]
Done! See #58 

I've even deployed to Heroku here: http://www.reactrails.com/

![2016-03-26_19-25-39](https://cloud.githubusercontent.com/assets/1118459/14063970/d3b9af0a-f388-11e5-82e2-06c526218ff1.png)

**Comment by sstephenson** [comment]
Published 5.0.0-beta3 to npm: https://www.npmjs.com/package/turbolinks
