### ISSUE TITLE
Uncaught SecurityError: Failed to execute 'replaceState' on 'History'

### ISSUE THREAD

**Issue by dingn1** [turbolinks/turbolinks#133]
If I had download link that downloads file  from a server, the file would be successfully downloaded if I specify `data-turbolinks="false"` but the next link I clicked would have the error Uncaught SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL `the download url I just clicked`. Anybody have any idea? Or is it just a bug somewhere?

**Comment by pierre-pretorius** [comment]
Does the html link go to one of your controllers but then you redirect it to an external url or is the link directly to the external url?  An easy workaround/fix in the interim is perhaps to add target="_blank" to the link.

**Comment by dingn1** [comment]
Which link are you talking about? I have target="_blank" for the download link already

**Comment by pierre-pretorius** [comment]
I'm talking about the download link.  It is very strange that you get a SecurityError on any link click after you click a link with target="_blank".  Can you reproduce the bug in a sample app?

**Comment by sstephenson** [comment]
Closing because I’m not able to reproduce this issue. Feel free to open again with a minimal test case demonstrating the problem.
