### ISSUE TITLE
Working with data-turbolinks-permanent

### ISSUE THREAD

**Issue by hovancik** [turbolinks/turbolinks#134]
So here is what I am doing (in my rails app): 

Inside my app template I have element with cart's total price. It gets updated when I add something on different pages, or when I change amount of some product in Cart view. 

Let's say that I am on HP and add some product.  Then I  go to Cart, change amount and go back to HP with browser's back button. 

Tootal price will be changed to previous  value, as is predicted in readme (https://github.com/turbolinks/turbolinks#persisting-elements-across-page-loads). 

If I add `data-turbolinks-permanent` to my cart element, it will fix the problem with going back with browser button. 

But when I am in Cart view and I'm changing amount, the price is not updated as well.

**Comment by sstephenson** [comment]
You need to make sure the permanent element exists on every page. In your case, that means it needs to be present on the Cart page, too. If your design calls for it not to be visible on that page, consider hiding it with CSS instead of omitting it from the document.
