### ISSUE TITLE
Show progressbar on change state (not only loading page url)

### ISSUE THREAD

**Issue by matheusdsm** [turbolinks/turbolinks#136]
I need to show progress bar in any user action,
the progress bar is only showing when user go 
to a page.
I wanna know, how to make progress bar show when changing state.

Thanks :)

**Comment by CyberianIce** [comment]
[nProgress](https://github.com/rstacruz/nprogress) is simple, free, opensource plugin, compatible with TurboLinks. It is designed exactly for this purpose and easily configurable and customizable.

Have fun!

**Comment by sstephenson** [comment]
Duplicate of #93 (rationale: https://github.com/turbolinks/turbolinks/issues/93#issuecomment-221897734).
