### ISSUE TITLE
Non-minified (debuggable) JS distribution of turbolinks?

### ISSUE THREAD

**Issue by nikku** [turbolinks/turbolinks#137]
I'd like to get a deeper understanding how the library works by debugging it. The only stuff that is [distributed to work in the browser](https://github.com/turbolinks/turbolinks/blob/master/dist/turbolinks.js) is obscured though. 

Any hints how to create a non-minified, bundled version of the library?

**Comment by glennfu** [comment]
Checkout the project, and modify `.blade.yml` line 15: change `js_compressor: uglifier ` to `js_compressor:`

Then you can run this to build it and copy it into your project:
```
~/path/to/turbolinks/bin/blade build && cp ~/path/to/turbolinks/dist/turbolinks.js ~/path/to/your/app/assets/javascripts/turbolinks.js
```

Now you're running from your own compiled source, with no minification.

**Comment by sstephenson** [comment]
No plans to include an unminified version in the source tree, but you can build one yourself using @glennfu’s instructions above.
