### ISSUE TITLE
What will be included in the iOS and Android "adapters"?

### ISSUE THREAD

**Issue by digerata** [turbolinks/turbolinks#14]
I'm curious to know what is coming out with the "adapters." I'm super excited to see what's there. Are these projects with a shell that we can compile and run in the simulator? Or is this just a framework that we can build into a shell app?

Any thoughts on timing? I.e., before or after Turbolinks 5 is final?

**Comment by sstephenson** [comment]
> Are these projects with a shell that we can compile and run in the simulator? Or is this just a framework that we can build into a shell app?

Both. We have a framework and a demo app for each platform. 

> Any thoughts on timing? I.e., before or after Turbolinks 5 is final?

No specific dates to announce right now, but we’re still planning on opening everything up by the time Rails 5.0.0 is final.

The only blocker is documentation, which @packagethief and I are writing right now :)

**Comment by pietervisser** [comment]
That's really exciting! Do you need some help with something?

**Comment by digerata** [comment]
Thanks for the info. That's is really incredible!
