### ISSUE TITLE
Touch events bleeding through successive page loads on Turbolinks 5

### ISSUE THREAD

**Issue by markbao** [turbolinks/turbolinks#142]
I have a Rails 5, Turbolinks 5 app that loads successive pages in a folder-like way. A problem I'm running into on iOS is that touch events seem to be bleeding through successive page loads, such that a touch event on a link to another page, which leads to Turbolinks loading that page, then sets a hover state on the element at the touch event's position on the *next* page.

Example below from the Simulator; notice how, after the page loads, it sets a hover state on the element where the cursor is.

Per related issue #54 I've removed the `active` state on the elements, but the issue persists. I'm not sure if this is a Turbolinks issue per se, but wanted to check if it was (or if others here have experienced it). I've been able to solve this issue by using Fastclick, but that's clearly a subpar solution.

![smaller1](https://cloud.githubusercontent.com/assets/27594/16850660/056910c2-49b5-11e6-8f3a-b0c799306e9c.gif)

**Comment by sstephenson** [comment]
Thanks for the detailed report. Given that there are no touch event handlers in Turbolinks, I don’t think this is a problem with Turbolinks itself.

You might want to try creating a minimal test case without Turbolinks: install a link click handler that replaces the page’s body and see if it exhibits the same behavior. If so, you can consider filing a Radar issue with Apple.
