### ISSUE TITLE
Is there a similar event to onbeforeunload?

### ISSUE THREAD

**Issue by nearapogee** [turbolinks/turbolinks#146]
Is there a similar event to onbeforeunload?

Looking for a way to attach onto an event when transitioning off of a page with or without a turbolinks link. Is that possible?

Thanks!

**Comment by sstephenson** [comment]
Listen for `turbolinks:before-render` to be notified just before Turbolinks replaces the `<body>` element.

You can combine this with `window.onbeforeunload` to create an unofficial `turbolinks:unload` event:

```js
var dispatchUnloadEvent = function() {
  var event = document.createEvent("Events")
  event.initEvent("turbolinks:unload", true, false)
  document.dispatchEvent(event)
}

addEventListener("beforeunload", dispatchUnloadEvent)
addEventListener("turbolinks:before-render", dispatchUnloadEvent)
```

**Comment by sergiy17** [comment]
@nearapogee  https://github.com/turbolinks/turbolinks#full-list-of-events

**Comment by masudhossain** [comment]
> @nearapogee https://github.com/turbolinks/turbolinks#full-list-of-events

And which one is suppose to fix this issue?

**Comment by westonganger** [comment]
@sstephenson could we possibly get this "unofficial" event added? Its seems to be quite essential functionality.

**Comment by nearapogee** [comment]
That was 5 years ago... but I think @sstephenson fix worked for me. Basically create a meta event that is triggered both by the browser and turbolinks. Make sense?

By the way, thanks @sstephenson I am just a few years late in saying that!
