### ISSUE TITLE
Disable auto-start?

### ISSUE THREAD

**Issue by ex0rcist** [turbolinks/turbolinks#148]
Is there a way to disable autostart? Suppose I want to make A-B test with turbolinks enabled and disabled, the only way  to disable them I've found is to move them to separate manifest and conditionally include with `javascript_include_tag 'turbolinks_manifest.js'`

**Comment by sstephenson** [comment]
You have a few different options here:

1. Call `Turbolinks.controller.stop()`. This will [disable Turbolinks](https://github.com/turbolinks/turbolinks/blob/55af148d880a3f80654a3a4cde9c8c41dadac861/src/turbolinks/controller.coffee#L29-L35) for the current page.
2. Add [`data-turbolinks="false"`](https://github.com/turbolinks/turbolinks#disabling-turbolinks-on-specific-links) to your page’s `<body>` element. This will prevent Turbolinks from handling link clicks on the page, but programmatic calls to `Turbolinks.visit()` will still go through Turbolinks.
3. Use Turbolinks as a [CommonJS module](https://github.com/turbolinks/turbolinks#installation-using-npm). In this case, you must explicitly call `Turbolinks.start()` to install it on the page.
