### ISSUE TITLE
URLs with decimals do not get rendered

### ISSUE THREAD

**Issue by aaronvb** [turbolinks/turbolinks#15]
This might be a unique case, but I found this difference when migrating an existing project from classic that uses decimals in the URL path. Turbolinks 5 seems to have dropped support for that.

Example use case:
````
/products/canon-85mm-f-1.2-portrait-lens
````

The above URL will not render and instead reload.

I found the difference in the regex used to parse the URL extension.

https://github.com/aaronvb/turbolinks/blob/master/src/turbolinks/location.coffee#L34

`/\.[^.]*$/`

Which will match`.2-portrait-lens` as the extension.

https://github.com/turbolinks/turbolinks-classic/blob/master/lib/assets/javascripts/turbolinks.coffee#L462

`/\.[a-z]+$/`

Which will not have a match.

Was this change intended?

I've created a branch using the classic regex and supporting tests: https://github.com/aaronvb/turbolinks/tree/fix_get_extension_for_decimals

**Comment by sstephenson** [comment]
I think it’s more likely that Turbolinks Classic’s regex was a little too loose. 

I’m not aware of any rule, formal or informal, saying file extensions can’t start with digits. Two common counterexamples off the top of my head: `.7z` and `.3gp`.

In your case I’d suggest explicitly including a `.html` suffix in your links. I’m also open to discussing ways we can make this behavior customizable.

**Comment by aaronvb** [comment]
Good points, I did not think about those types of file extensions.

I would still like to get this to work without appending `.html` in my URLs if possible. What do you think about an option to ignore the extension altogether? ie: `data-turbolinks-ignore-extension=true` Although I can't think of another reason to want to ignore the extension other than my case.

**Comment by sstephenson** [comment]
Yeah, I don’t think a link annotation really makes sense here, but maybe we can come up with a way to make the [`isHTML` condition](https://github.com/turbolinks/turbolinks/blob/e870d0ea2dda7b68144f5bdcae46417d5754a01c/src/turbolinks/controller.coffee#L227-L228) configurable.

**Comment by aaronvb** [comment]
If we don't use link annotation, the only way to configure isHTML would be to pass an option to the Turbolinks.visit() function, correct? I don't think that wouldn't apply in my case because I'm generating the URLs in the view.

**Comment by sstephenson** [comment]
I’d prefer to make it globally configurable so your application can define its own rules for what constitutes an “HTML link.” 

You can already do this by overriding `Turbolinks.Location.prototype.isHTML`. We should just move that somewhere else and provide an official API for it.

**Comment by aaronvb** [comment]
That makes sense. Would the rule be for the entire URL or just the last path component? I'm thinking just the last path component needs to be configurable and if so, what do you think about allowing a custom regex in the config?

**Comment by aaronvb** [comment]
Another idea, which might be more simple, would be an option to define whether or not Turbolinks renders URLs with extensions at all, and instead loads them(window.location).

**Comment by sstephenson** [comment]
I think the appropriate level of configuration is at the URL level. Otherwise, eventually someone will want to consider some part of the URL other than the extension, and then we’ll need two separate APIs.

I don’t think we’re going to be able to address this before 5.0.0 ships. For now, I’d suggest you override `isHTML` somewhere in your application’s JS bundle after you load Turbolinks:

```js
Turbolinks.Location.prototype.isHTML = function() {
  var extension = this.getExtension()
  return extension == null ||
    extension === ".html" ||
    extension.match(/^\d/)
}
```

**Comment by aaronvb** [comment]
Sounds good. Overriding `isHTML` is what I'm currently doing and it works in my case. We can close this issue and come back to it at a better time.

Thanks for your time @sstephenson

**Comment by sstephenson** [comment]
Sounds good! 👍
