### ISSUE TITLE
duplicated items bug

### ISSUE THREAD

**Issue by ctf0** [turbolinks/turbolinks#154]
- first load
![1st](https://cloud.githubusercontent.com/assets/7388088/17274596/ddc7ece6-56e8-11e6-8474-f0e7d17f8d90.jpg)

- when visit a link
![2nd](https://cloud.githubusercontent.com/assets/7388088/17274597/ddd06e02-56e8-11e6-9934-735a0b195b69.jpg)

**Comment by ctf0** [comment]
a possible fix

```js
$(document).on('turbolinks:load', function() {
    $('head').find(function() {
        $('script').each(function() {
            $(this).siblings("[src='" + $(this).attr('src') + "']").remove();
        });
        $('link').each(function() {
            $(this).siblings("[href='" + $(this).attr('href') + "']").remove();
        });
    });
});
```

**Comment by sstephenson** [comment]
It looks like you’re using some sort of script that loads stylesheets dynamically (`loadCSS.js`?). That’s likely not going to be drop-in compatible with Turbolinks.

Please carefully review the guidelines in [Building Your Turbolinks Application](https://github.com/turbolinks/turbolinks#building-your-turbolinks-application). When stylesheet tags are explicitly listed in the `<head>` of the document you return from the server, Turbolinks will correctly identify existing stylesheets and avoid inserting them twice. But it can’t do this if a script is generating its own stylesheet tags.

**Comment by ctf0** [comment]
@sstephenson  its not related to `loadCss.js` because as u can see there are 2 links for google analytics while there is only one for fb_sdk which both of them gets loaded async without any interfering from my side.

same goes with the other js files, most of them dont get replicated, so definitely its not an issue with a specific script ,and as u said TL will check if something already in the head tag and avoid duplicating it, but apparently it does that partly .
