### ISSUE TITLE
Do meta tags matter?

### ISSUE THREAD

**Issue by anarchocurious** [turbolinks/turbolinks#158]
IMHO, one of the major advantages Turbolinks has over heavier front-end frameworks is the effortless SEO gained through the progressive enhancement approach.

The issue of meta tags in the head section has come up [several](http://stackoverflow.com/questions/19463978/rails-4-and-turbolinks-meta-tags-not-changing) [times](http://stackoverflow.com/questions/18491651/how-to-use-turbolinks-and-have-meta-tags-specific-to-each-page-for-seo) [before](http://joanswork.com/turbolinks-and-ga/), but has yet to be addressed by an authority anywhere I've seen. My intuition has been that since web-scrapers do not bother executing JavaScript, that Turbolinks does not update meta tags is irrelevant; each link is followed and requested as an isolated page, meta tags and all.

My intuition is wrong. A co-worker pointed out to me that Google [does execute some JavaScript when crawling a page](http://searchengineland.com/tested-googlebot-crawls-javascript-heres-learned-220157). Given this, it seems reasonable that if Google crawls the site as a single page app, it may miss out on the meta tags for the other pages.

Does anyone know if this is true? Or, indeed, a reliable way to verify if this is true?

Thanks!

**Comment by packagethief** [comment]
Thanks for the question!

> that Turbolinks does not update meta tags is irrelevant

Unlike earlier versions, Turbolinks 5 does update meta tags, and any other provisional elements in the document `<head>`.

I'm skeptical that Google's crawler is simulating link clicks and navigating with Turbolinks, but if it is, it should see dynamically inserted meta tags just fine.

**Comment by anarchocurious** [comment]
@packagetheif Thank you for the prompt response! I agree that it seems unlikely that Google is simulating link clicks, the author of the article I linked claims to have demonstrated event simulation at least under some circumstances in section 2. 

Regardless, since Turbolinks 5 *does* update the meta tags, my question is no longer relevant.  I'm going to close my issue.
