### ISSUE TITLE
page:load not firing when turbolinks is loaded using Require.js

### ISSUE THREAD

**Issue by deepeeess** [turbolinks/turbolinks#160]
Hi,

It appears the an initial page:load event will not fire when using Turbolinks with Require.JS.  Subsequent page loads will cause the event to fire.  For example, the console for this will render "it is supported", but not "turbolinks:load listener from require" upon initial page load.  It will, however, render "turbolinks:load listener from require" for subsequent page visits.  I've tried various organizations of this but all exhibit similar symptoms.  I am using the commit from head (55af148d880a3f80654a3a4cde9c8c41dadac861).

```
require (['turbolinks'], function(turbolinks) {
  var Turbolinks = require("turbolinks");
  Turbolinks.start();
  if (Turbolinks.supported) {
    console.log("it is supported");
    document.addEventListener("turbolinks:load", function() {
       console.log("turbolinks:load listener from require");
    })
  }
});
```

**Comment by domchristie** [comment]
Turbolinks (currently) requires that it be loaded before the `DOMContentLoaded` is triggered, as it relies on that event to then dispatch `turbolinks:load`. With this in mind, be sure Turbolinks is not loaded via `async`.

I'll close this issue as it's been inactive for a while, but feel free to reply if you continue to have problems.
