### ISSUE TITLE
Body gets populated twice in one load

### ISSUE THREAD

**Issue by Kiszko** [turbolinks/turbolinks#161]
Take the following example.

```
<?php sleep(1); // mock some server-side processing ?>
<!DOCTYPE html>
<html>
<head>
	<title>Home</title>
	<link rel="stylesheet" href="/turbolinks.css">
	<script src="/turbolinks.js"></script>
</head>
<body>
	<h1>Home</h1>
	<a href="/">Home</a>
	<h2><?= rand() ?></h2>
</body>
</html>
```

On the second click of the `Home` link (and every click after) the body content get's populated twice. This is represented with the `rand()` number function. What happens is you see a new number and then another new number - when this, of course, should only happen once.

What in the hell is going on? Something peculiar in the cache?

Guidance appreciated.

**Comment by sstephenson** [comment]
This is Turbolinks’ preview cache in action. Please see [Understanding Caching](https://github.com/turbolinks/turbolinks#understanding-caching) in the documentation for details about what the preview cache is, why it’s there, and how to detect or disable it.

**Comment by Kiszko** [comment]
My bad.

**Comment by sstephenson** [comment]
No problem! It can be surprising if you’re not expecting it. I’m open to suggestions about how we can make it more obvious.
