### ISSUE TITLE
Make Turbolinks progress bar beatiful like github.com/caarlos0/nprogress-rails.

### ISSUE THREAD

**Issue by mrkongo** [turbolinks/turbolinks#162]
How can I make Turbolinks progress bar beautiful like github.com/caarlos0/nprogress-rails ?

**Comment by sstephenson** [comment]
See [Displaying Progress](https://github.com/turbolinks/turbolinks#displaying-progress) in the documentation for details on how to style the Turbolinks progress bar element.

If you want to use a third-party progress bar instead, you can hide Turbolinks’ progress bar with CSS, and listen for the `turbolinks:request-start` and `turbolinks:request-end` events to determine when to show and hide your custom progress bar.
