### ISSUE TITLE
Turbolinks appears to be ignoring 302 redirects

### ISSUE THREAD

**Issue by jrguenther** [turbolinks/turbolinks#163]
We're in the process of implementing global sessions for client domains that we're serving with one Rails app. To do so, we use a sequence of redirects to transfer the session to the new domain. I can talk more about the specifics on that implementation if it becomes relevant.

Let's say someone creates a session on the main app domain (A), and then tries to access a page on domain (B) that points to a site on the app, we bounce the request through two 302 redirects before ending back up on the page they requested.

If a page is open on domain B and you click a link on the page, the next page the person sees should be the page rendered as if they are logged in. However, they see the page as if the session has never transferred.

The stack trace is:
```
t.BrowserAdapter.r.reload	
t.BrowserAdapter.r.visitRequestFailedWithStatusCode
t.Visit.r.requestFailedWithStatusCode
(anonymous function)
t.HttpRequest.r.endRequest
t.HttpRequest.r.requestFailed
(anonymous function)
```
which eventually calls `window.location.reload()` and nothing changes. I'm confused. If I call `window.location.reload()` from the console, the page refreshes as expecting showing the logged in state. We removed turbolinks and everything works as expected, so we're fairly confident that our server-side code is good.

Any idea what's happening?

**Comment by jrguenther** [comment]
I was able to solve this issue by add CORS headers to the request responses and modifying Turbolinks to set `withCredentials = true`.

Would you be open to PR that adds withCredentials to the XHR to object? Or is it a security concern?

**Comment by sstephenson** [comment]
I’m not sure it makes sense as a default, but you should be able to set that property in the [`turbolinks:request-start` event](https://github.com/turbolinks/turbolinks#setting-custom-http-headers) without modifying the source:

```js
document.addEventListener("turbolinks:request-start", function(event) {
  var xhr = event.data.xhr
  xhr.withCredentials = true
})
```

**Comment by jrguenther** [comment]
I spoke too soon. Using CORS headers is a pain as each browser seems to handle them slightly different. Seems like a lot of overhead just to use Turbolinks. There must be an easier way. So, back to my original question.

Any idea why the fallback to `window.location.reload` doesn't change the page?

**Comment by sstephenson** [comment]
Can you describe the sequence of events step-by-step, with actual URLs? I’m having trouble piecing together the flow.

**Comment by jrguenther** [comment]
If we define the domains I mentioned in my first post as:

- Domain A: `localhost:3000`
- Domain B: `sophia.ffindex.com:3000`

I click a link `sophia.ffindex.com:3000` that is pointed to `/` and get the following requests  in Rails.

```
Started GET "/" for 127.0.0.1 at 2016-08-11 15:21:29 -0700
Processing by StaticPagesController#show as HTML
  Parameters: {"id"=>"index"}
Redirected to http://localhost:3000/get_session?redirect_domain=sophia.ffxindex.com
Filter chain halted as :set_custom_domain_session rendered or redirected
Completed 302 Found in 1ms (ActiveRecord: 0.0ms)

Started GET "/get_session?redirect_domain=sophia.ffxindex.com" for 127.0.0.1 at 2016-08-11 15:21:29 -0700
Processing by CustomDomainsController#get_crossdomain_session as HTML
  Parameters: {"redirect_domain"=>"sophia.ffxindex.com"}
Redirected to http://sophia.ffxindex.com:3000/set_session
Completed 302 Found in 0ms (ActiveRecord: 0.0ms)

Started GET "/" for 127.0.0.1 at 2016-08-11 15:21:29 -0700
Processing by StaticPagesController#show as HTML
  Parameters: {"id"=>"index"}
  Rendering static_pages/index.html.erb within layouts/application
Completed 200 OK in 86ms (Views: 85.2ms | ActiveRecord: 0.0ms)
```

With Preserver Log checked, I get the following output:

<img width="801" alt="screen shot 2016-08-11 at 3 28 14 pm" src="https://cloud.githubusercontent.com/assets/1348928/17607102/547bc414-5fd8-11e6-9bf7-bc3376782f76.png">

I expect the XHR error from the cross domain redirect, then Turbolinks calls `window.location.reload()` which initiates the request sequence I've posted above.

**Comment by jrguenther** [comment]
Here's the browser network log in case it helps.

<img width="1421" alt="screen shot 2016-08-11 at 3 52 03 pm" src="https://cloud.githubusercontent.com/assets/1348928/17607606/a28775b0-5fdb-11e6-87d7-76776fb92322.png">

**Comment by jrguenther** [comment]
After inspecting the headers on the request, I can see that when Turbolinks calls `reload` the cookies are not being set. It looks like there is a problem in our logic because of flag to prevent infinite redirects we set when the transfer is initiated with Turbolinks. When Turbolinks does the reload, our code thinks the session is transferred. So all in all - not a Turbolinks problem. Thanks for being willing to take a look.
