### ISSUE TITLE
Proposal: Adding turbolinks scope in addition to root

### ISSUE THREAD

**Issue by helmut** [turbolinks/turbolinks#164]
What are your thoughts on adding a turbolinks scope meta variable?

`<meta name="turbolinks-scope" content="app">`

This would work in a similar fashion to the turbolinks root meta variable but not rely on the current URL location. So all pages that have the same turbolinks scope would be grouped together just like those within the same root. So if you navigate into another scope there would be a full refresh.

The reason that this would be handy is that the root meta doesn't help when you want to separately scope a page that is below another root. Some sites have multiple applications that don't share the same `<head>` and resources but do overlap in the scope.

Eg.
`<meta name="turbolinks-root" content="/">`
`<meta name="turbolinks-root" content="/app">`
`<meta name="turbolinks-root" content="/app/module">`

So the '/' root scope would work however it seems there is no way to have the / scope and the /app scope and the /app/module scopes not conflict and be completely separate from each other.

With this new tag you could have 
`<meta name="turbolinks-scope" content="">` // You could omit this entirely (default)
`<meta name="turbolinks-scope" content="app">` // All pages within the app scope
`<meta name="turbolinks-scope" content="app-module">` // All pages within the app-module scope

I do not think that this would break BC and would allow finer tuning of scope in addition to the root meta var. Let me know if that doesn't make sense. Or I am missing some other way of implementing this idea that already exists.

**Comment by sstephenson** [comment]
I’m not entirely sure I understand the use case, but you ought to be able to achieve this behavior with the [`data-turbolinks-track=reload` annotation](https://github.com/turbolinks/turbolinks#reloading-when-assets-change).

```html
<meta name="turbolinks-scope" content="app" data-turbolinks-track="reload">
```

If you put that in your `<head>`, any pages you visit without an identical tag will trigger a full reload.

**Comment by helmut** [comment]
Thanks for your reply! Not sure we are on the same page. Perhaps I'll give you a bit more of a run down of my use case. Cheers for hanging in here with me...

I have two applications running on my site - App A and App B. 

App A is located at `example.com/appa` and the other App sits at `example.com/appa/appb`. App B is nested beneath the folder of App A, however these are two very different applications. They do not share any of the same assets and have completely different ways of working. However they both would like to use Turbolinks. So in order to keep them separate I would need to add some configuration.

Let's say I put a meta root tag on all of the pages for App A like so:
`<meta name="turbolinks-root" content="/appa">`

Then I put another meta root tag on the other App like so:
`<meta name="turbolinks-root" content="/appa/appb">`

However this would not fix my problem, because technically the `/appa/appb` root is below the `/appa` root so there would not be a full page reload when navigating from App B to App A.

This is why I suggest a scope variable rather than depend on the root path structure.

Put this is the head of all pages related to App A
`<meta name="turbolinks-scope" content="appa">`

And put this in the head of all pages related to App B
`<meta name="turbolinks-scope" content="appb">`

Then when you navigate between scopes a full page load is requested.

Does that help at all?

**Comment by helmut** [comment]
Yes that worked. Sorry to bother you. I guess for me the title of the section "Reloading When Assets Change" was not indicative of the functionality that I was looking for even though it could have been used for it. I was thinking something along the lines of running multiple turbolink enabled applications under the same root. Anyway thanks for your time.
