### ISSUE TITLE
Turbolinks don't update url after redirect(url) calling in rails routes.rb

### ISSUE THREAD

**Issue by gambala** [turbolinks/turbolinks#169]
Turbolinks gem is smart, and react to `redirect_to` rails method properly. But in rails we can also use redirect(url) method in routes.rb, like this:

```
Rails.application.routes.draw do
  namespace :account do
    resources :ads
    root to: redirect('account/ads')
  end
end
```

If we go to the /account route with turbolinks turned on, we will see /account/ads index page, but url in browser (`window.location`) will be `/account`.

Temporary (or permanent and proper?) solution - create, for example, `account/welcome_contoller.rb` with one liner index action: `redirect_to [:account, :ads]`, and replace `root to: redirect('account/ads')` in routes.rb by `root to: 'welcome#index'`.

But maybe turbolinks will learn how to react to redirect() method, won't it?

**Comment by artemave** [comment]
Two months no response. Is turbolinks dead?

**Comment by nateberkopec** [comment]
@artemave See #201 and [this](https://github.com/turbolinks/turbolinks/pull/124#issuecomment-239826060)

**Comment by artemave** [comment]
@nateberkopec fair enough, but the same applies to most of the open source. Yet some projects are active whilst others aren't.

So my question remains the same. Except, perhaps, to be more polite `s/dead/no longer active/`.

**Comment by javan** [comment]
If you're interested in investigating a fix, here's how the [turbolinks-rails] (https://github.com/turbolinks/turbolinks-rails) gem extends [`ActionController#redirect_to`](https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/redirecting.rb#L53-L60): https://github.com/turbolinks/turbolinks-rails/blob/master/lib/turbolinks/redirection.rb

A similar extension would be needed for [`ActionDispatch::Routing#redirect`](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/routing/redirection.rb#L175-L187).

**Comment by artemave** [comment]
@javan thanks for the pointing to the right direction.

This seems to do the trick: https://github.com/artemave/turbolinks-rails/commit/ed2023d2013b3544c7518c05dd3dea148af7676f

But how do I test it?

**Comment by domchristie** [comment]
Closing as this is an issue with turbolinks-rails (PR: https://github.com/turbolinks/turbolinks-rails/pull/17)
