### ISSUE TITLE
How to display Progress

### ISSUE THREAD

**Issue by wenweih** [turbolinks/turbolinks#17]
Is Turbolinks 5 progress bar enable by default ? In [turbolinks-classic](https://github.com/turbolinks/turbolinks-classic),we can set ```Turbolinks.ProgressBar.enable();``` for Rails App ,but for Turbolink 5 ,[official document](https://github.com/turbolinks/turbolinks/tree/docs#displaying-progress) just mention how to overridden default progress bar style, I don't know how to display it for my Rails App , who can help me ,thx. 😊

**Comment by naveed-ahmad** [comment]
@wenweih looks like its enabled, actually looks like there is no option to disable progressbar for browser adapter :)

https://github.com/turbolinks/turbolinks/blob/master/src/turbolinks/browser_adapter.coffee#L9

**Comment by sstephenson** [comment]
You don’t need to do anything to enable the progress bar—it’s on by default.

The progress bar only appears when a page takes longer than 500ms to load.

**Comment by wenweih** [comment]
Thanks @naveed-ahmad @sstephenson 👏

**Comment by mcaskill** [comment]
Is there a way to customize the "progress" feature?

For example, provide the markup and CSS in advance or replace the bar with a different kind of animation (like a spinner overlaying the page).

In that same vein, is there a way to implement animated page transitions?

**Comment by sstephenson** [comment]
> Is there a way to customize the "progress" feature?
>
> For example, provide the markup and CSS in advance or replace the bar with a different kind of animation (like a spinner overlaying the page).

See the documentation for details on [customizing the appearance of the progress bar with CSS](https://github.com/turbolinks/turbolinks#displaying-progress).

You can’t customize the markup of the progress bar. However, you could hide it and listen for the `turbolinks:request-start` and `turbolinks:request-end` events to display your own indeterminate activity indicator. (If you show your own indicator, you’ll want to make sure to append it to `document.documentElement` instead of `document.body` so Turbolinks doesn’t cache it.)

> In that same vein, is there a way to implement animated page transitions?

Not currently.

**Comment by forgecube** [comment]
Should we have an configuration option to change the 500 ms threshold?

It serves as valuable feedback when clicking a link, even if it shows up for a split second.

**Comment by sstephenson** [comment]
I'm open to making the 500ms threshold configurable. I think you'll find in practice that _always_ showing the progress bar has the effect of making short page loads feel much longer, but ultimately that's for you to decide.

**Comment by svoboda-jan** [comment]
Hi,

found this issue searching for a  solution  to custom markup and delay threshold.

We have a specific UI (game) where we need to display a custom fullscreen loader and sooner than the default 500ms threshold. I think this should be configurable.

For our use case I came up with the following workaround:
(in `application.js` after `//= require turbolinks`)

```javascript
// we don't use animated progress
Turbolinks.ProgressBar.prototype.refresh = function() {}
// custom css
Turbolinks.ProgressBar.defaultCSS = ""

// creates progress bar with custom markup
Turbolinks.ProgressBar.prototype.installProgressElement = function() {
  return $('body').before($('<div class="overlay"></div><div class="wait"><i class="fa fa-hourglass-o fa-spin"></i></div>'));
}

// removes progress bar with custom markup
Turbolinks.ProgressBar.prototype.uninstallProgressElement = function() {
  $(document).find('.wait, .overlay').remove();
}

// changes the default 500ms threshold to show progress bar
Turbolinks.BrowserAdapter.prototype.showProgressBarAfterDelay = function() {
  return this.progressBarTimeout = setTimeout(this.showProgressBar, 50);
};
```

**Comment by Kiszko** [comment]
"Should we have or is there a configuration option to change the 500 ms threshold?"
"I'm open to making the 500ms threshold configurable."

Pretty please! Seems like the kind of thing that should be easily configurable.

**Comment by joexanderson** [comment]
Yes, please do make this configurable. I am working on a web app based on Laravel. It would be nice to experiment with different thresholds to see how responsive the app feels.

**Comment by gregblass** [comment]
@sstephenson This is working great for me for a custom loading indicator:

    document.addEventListener("turbolinks:request-start", function() {
	    $('#progress').show();
    });

    document.addEventListener("turbolinks:request-end", function() {
	    $('#progress').hide();
    });

One final thing I'm trying to do with it is to only fire on a get request. Any idea how I'd go about doing that from within those functions?

**Comment by Mavvie** [comment]
For @joexanderson and others looking for a workaround: it seems really easy to do, following @svoboda-jan's advice.
I just added the following to the bottom of my application.js:
``` js
Turbolinks.BrowserAdapter.prototype.showProgressBarAfterDelay = function() {
  return this.progressBarTimeout = setTimeout(this.showProgressBar, 50);
};
```

Coffeescript version:
```coffee
Turbolinks.BrowserAdapter.prototype.showProgressBarAfterDelay = ->
  this.progressBarTimeout = setTimeout(this.showProgressBar, 50)
```

Replace the `50` with whatever you'd like the delay to be.
