### ISSUE TITLE
Progress bar doesn't show up when delay is caused by server-side processes

### ISSUE THREAD

**Issue by jessfrisch** [turbolinks/turbolinks#171]
I'm having an issue where I can't get the progress bar to show up at all (vanilla or nprogress) no matter what I do.  The page in question has a 2-3 second delay because I'm running several network calls (the users expect this -- it's an external log database query page).  

I was hoping to use the built in progress bar so the users would know the query had successfully started, but i'm getting absolutely nothing.  I'm assuming it's because in the controller, I run the searches, which takes a long time, and then render the view, which takes no time at all.  Does turbolinks not start the progress bar until the view starts getting rendered?  Is there any way to still use the progress bar in this situation?

Thanks--

**Comment by packagethief** [comment]
Hi Jess. I'm not exactly sure what's going on. The progress bar is displayed [at the start of every Turbolinks visit request, after a 500ms delay](https://github.com/turbolinks/turbolinks/blob/master/src/turbolinks/browser_adapter.coffee#L19-L24). The server's response time doesn't matter.

Note that this will only occur for Turbolinks navigation. If you're making a non-Turbolinks request, say, an XHR post, the progress bar won't be shown.

Is it possible you're not making a Turbolinks request? Any other information you can provide would be helpful!

**Comment by jessfrisch** [comment]
I sure hope I'm making a turbolinks request!  Here's the info:

In the Gemfile:
`gem "turbolinks", "~> 5.0.0"`

In application.js
`//= require turbolinks`

The controller:
```ruby 
def index
    @search = Search.new(search_params)
    @search.search! if params[:search] // this is what takes all the time
end
```

Both get and post go to the index action, which renders the conventional view with form and results on the same page.

Thanks for your help!

**Comment by packagethief** [comment]
How are you linking to the index action? You won't see the progress indicator when making a POST, since that wouldn't be a Turbolinks request. Turbolinks will only step in when clicking a standard HTML `a[href]` link that hasn't been declared `data-turbolinks=false`.

If it's only the POST action that carries the `search` param, then I wouldn't expect the progress indicator to show.

**Comment by jessfrisch** [comment]
Yes--okay--I understand now.  For some reason, I was under the impression that Turbolinks now operated on every page refresh, not just clicked links.  Thanks for clearing it up.  I guess I'll need to find an alternative progress bar.

**Comment by packagethief** [comment]
No problem! My personal preference is to show an activity indicator that's closer to the action at hand. For example, replacing the "Search" button with some loading text or a spinner animation. The Turbolinks progress bar is suitable for showing navigation progress, but isn't a good replacement for local activity indicators.

See [#93 (comment)](https://github.com/turbolinks/turbolinks/issues/93#issuecomment-221897734) for the rationale behind reserving the progress bar exclusively for navigation.
