### ISSUE TITLE
Turbolinks triggers exception on IE8

### ISSUE THREAD

**Issue by jonwolfe** [turbolinks/turbolinks#173]
We've been relying on the statement that "In unsupported browsers, Turbolinks gracefully degrades to standard navigation," but unfortunately that's not the case with IE8 -- it's triggering javascript exceptions.

I don't expect TL to do anything on such an old browser, of course. That's not the issue. But if you make the claim that it gracefully degrades, please verify the claim so that we don't make incorrect assumptions.

<img width="693" alt="screen shot 2016-09-02 at 10 10 43 am" src="https://cloud.githubusercontent.com/assets/5140/18212160/4e31c692-70f6-11e6-96d9-cd5873a3fbe4.png">

**Comment by javan** [comment]
Thanks! Got a fix ready in #174 that we'll get into the next release. In the meantime you could add a polyfill for `addEventListener` (here's one https://gist.github.com/jonathantneal/3748027). It won't enable Turbolinks, but it should shush that error.

**Comment by jonwolfe** [comment]
Thank you, Javan!
