### ISSUE TITLE
Is it possible to disable the progress bar on successful form submission redirects?

### ISSUE THREAD

**Issue by gregblass** [turbolinks/turbolinks#176]
I've got a material design spinner in the center of the screen (a more standard design pattern for mobile) as a replacement for the standard progress bar.

It looks and works great - however, when I do a redirect_to in the controller on a successful form submission, Turbolinks returns:

```
Turbolinks.clearCache()
Turbolinks.visit("http://test.lvh.me:3000/admin/settings", {"action":"replace"})
```
and it triggers the loader. I've already got loaders on my form buttons, and I just want to use those since they are much less jarring on a form submission.

Wondering if and how this might be possible (or not possible).

**Comment by gregblass** [comment]
Here's what I ended up doing to accomplish this. It builds off of @svoboda-jan 's code from another thread:

```
// we don't use animated progress
Turbolinks.ProgressBar.prototype.refresh = function() {}
// custom css
Turbolinks.ProgressBar.defaultCSS = ""

// creates progress bar with custom markup
Turbolinks.ProgressBar.prototype.installProgressElement = function() {
  return $('body').before($('<div id="mobile-progress">DERP</div>'));
}

// removes progress bar with custom markup
Turbolinks.ProgressBar.prototype.uninstallProgressElement = function() {
  $(document).find('#mobile-progress').remove();
}

// changes the default 500ms threshold to show progress bar
Turbolinks.BrowserAdapter.prototype.showProgressBarAfterDelay = function() {
  return this.progressBarTimeout = setTimeout(this.showProgressBar, 50);
};

// don't show progress bar on replace (after a form submit)
Turbolinks.BrowserAdapter.prototype.visitRequestStarted = function(visit) {
	this.progressBar.setValue(0);
	if (visit.action == "replace") {
		return;
	} else if (visit.hasCachedSnapshot() || visit.action !== "restore") {
		return this.showProgressBarAfterDelay();
	} else {
		return this.showProgressBar();
	}
}
```

I'll have to be careful about API changes but this works!

**Comment by gregblass** [comment]
Blah this is pretty flawed because its showing the loader on the page restore after the cache. I think I just need to stick with the default turbolinks loader because of that.

**Comment by ionurboz** [comment]
Thx @gregblass
