### ISSUE TITLE
Pre-Compiled Version?

### ISSUE THREAD

**Issue by teamcoltra** [turbolinks/turbolinks#180]
You have instructions for both node and rails, but do you have a pre-compiled version of TL for a basic HTML site? I guess I could install node an compile it myself, but I feel like it has to exist already.

**Comment by sstephenson** [comment]
Yep! You can find the latest release version at this URL:

https://raw.githubusercontent.com/turbolinks/turbolinks/master/dist/turbolinks.js

**Comment by teamcoltra** [comment]
Awesome, thanks for a fast response.

**Comment by nateberkopec** [comment]
For anyone coming here via Google, you can switch "master" in the URL to the tag/version number you wish to lock to, e.g. https://raw.githubusercontent.com/turbolinks/turbolinks/v5.0.0/dist/turbolinks.js
