### ISSUE TITLE
Duplication inline elements in HEAD

### ISSUE THREAD

**Issue by Fudoshiki** [turbolinks/turbolinks#187]
`application.slim`

```slim
doctype html
html lang=locale
  head
    meta charset='utf-8'
    title == yield :title
    meta name='description' content=yield(:description)
    style { application layout styles }
```

after signed in layout will  be `signed.slim`

```slim
doctype html
html lang=locale
  head
    meta charset='utf-8'
    title == yield :title
    meta name='description' content=yield(:description)
    style { signed layout styles }
```

result

```html
<style> application layout styles </style>
<style> signed layout styles </style>
```

Turbolinks not replace but adds second style tag, how can I say Turbolinks that need replace old style tag?

**Comment by nateberkopec** [comment]
I wonder if there's a way `data-turbolinks-track` could be modified when working with inline elements. 

Perhaps a new value like `replace` could be used. If the element on the old and new page have the same ID, and `data-turbolinks-track`=`replace`, then the element from the old page is tossed out.

**Comment by Fudoshiki** [comment]
This will be nice feature

**Comment by Fudoshiki** [comment]
I think Turbolinks must always get inline styles only from new loaded page, by this need to be discussed

Now Turbolinks always twice replaces title, meta, stylesheets, javascripts in head, favicons on visit.
Once from cached snapshot and after from new page. Issue, if in `head` placed inline css or js content will be changed, on new page we got 2 versions.
Also csrf tags updates twise on visit

**Comment by slehmann36** [comment]
I am experiencing this issue too. Are there any updates on this? Thanks!

**Comment by Kiszko** [comment]
What's the solution to this?

**Comment by Fudoshiki** [comment]
@nateberkopec
Is there any planned rethinking of Turbolinks inline elements philosophy in the near future by the Turbolinks Team or can I tackle this issue? If so, what goals should I pursue so that the work is not in vain?

Regards

**Comment by Fudoshiki** [comment]
https://github.com/Fudoshiki/turbolinks/commit/2ace88c83d31b8e5cf335c65982ab4ce28df0957

**Comment by aried3r** [comment]
Hey @Fudoshiki, should this really be closed? It's still an issue and I don't see a PR.
Thanks for posting your solution, though!

**Comment by Fudoshiki** [comment]
Turbolinks idea is placing common styles in head and per page styles in body https://github.com/turbolinks/turbolinks/issues/249#issuecomment-387150385
