### ISSUE TITLE
Use Turbolinks only on assets and part of the website

### ISSUE THREAD

**Issue by Rubioli** [turbolinks/turbolinks#188]
In my application, I have disabled `turbolinks` since it made issues with ad loading and facebook comment, but I really like how `turbolinks` makes the site faster.

Is it possible to only use `turbolinks`on assets and parts of the website that doesn't have any ads inside? Like modify which parts of the page or which page can use `turbolinks`.

For instance, I don't have any ads in my homepage and I would like to have it there.

**Comment by WaKeMaTTa** [comment]
check this https://github.com/turbolinks/turbolinks#disabling-turbolinks-on-specific-links

**Comment by Rubioli** [comment]
Thanks @WaKeMaTTa This is only by adding it to each link and its not useable as what Im try to achieve. I want to add `turbolinks` to all assets and some part of the same page.

*For example:*
My page is based on 2 mail parts: `<div class="left">Left side</div>` &  `<div class="right">Right side</div>` and I only want to have turbolink load on `class="left" / left side`

**Comment by WaKeMaTTa** [comment]
And using this https://github.com/turbolinks/turbolinks#persisting-elements-across-page-loads

like this:

```html
<div class="left">Left side</div>
<div class="right" data-turbolinks-permanent>Right side</div>
```

**Comment by Rubioli** [comment]
That @WaKeMaTTa I test it with my Facebook comment and Facebook comments didnt load.

Here is my code:
```
                .fb-turbolinks{"data-turbolinks-permanent" => ""}
                  .fb-comments{'data-lazy-widget'=>'navid', 'data-href' => "http://ocubee.com#{post_path(@post)}", 'data-numposts' => '3', "data-width" => '718'}
```

I also added `.fb-turbolinks{"data-turbolinks-permanent" => ""}` for my facebook sdk code and still not loading.

**Comment by WaKeMaTTa** [comment]
`i don't know if will help but try this:

```RUBY
.fb-turbolinks{data: {turbolinks: 'permanent'}}
```

**Comment by Rubioli** [comment]
great thanks :)
