### ISSUE TITLE
Redirect and reload full page

### ISSUE THREAD

**Issue by ericenns** [turbolinks/turbolinks#19]
I have a turbolink-enabled link that, on condition, should be redirected to a fully reloaded page (different layout). When I do:

    redirect_to path, turbolinks: false

the request is still a XHR request though and it doesn't like the response which is a full HTML document (the layout gets corrupted). Bug?

An example for this is when a users session is destroyed any link will redirect them to the sign in page, which has a different layout and should have a full page reload.

**Comment by packagethief** [comment]
Hey @ericenns. I don't think this is a bug. When you perform a redirect on the server, XHR will transparently follow it. There's nothing we can do about that–it's just the way XHR works.

To work around this, you can redirect using JavaScript but _without_ Turbolinks. Return a JavaScript response that performs `window.location = destination`. It will be evaluated by the browser in response to the XHR and you'll be redirected to the destination will a full reload.

**Comment by ericenns** [comment]
Ok so I tried your suggestion, but the javascript returned isn't being evaluated.

I have set the content_type to 'text/javascript'
And response_body to 'window.location=destination'

**Comment by packagethief** [comment]
Oh, of course–I'm sorry for steering you wrong. Turbolinks won't evaluate JavaScript in the XHR response. I was incorrectly thinking a standard XHR issued from Rails, which is configured to eval the response.

I can't think of a solution off the top of my head–I'll get back to you.

**Comment by ericenns** [comment]
Ok I figured something out:

    $(document).on('turbolinks:request-end', () ->
      if event.data.xhr.status == 401 and not event.data.xhr.response.startsWith("<")
        eval(event.data.xhr.response)
    )

It will still show my javascript on the browser while it request the new page, but at least I don't have a mangled document.

**Comment by synth** [comment]
I solved this with the following line in our controller action :)

```
          render js: "window.location = '#{url};'"
```
in Rails 5, it does some evaluate javascript in XHR response when form has `remote: true`.
