### ISSUE TITLE
Animation firing twice when visiting a cached page

### ISSUE THREAD

**Issue by Arif59** [turbolinks/turbolinks#190]
I'm using [Animate.css](https://daneden.github.io/animate.css/) and I have a div with the `animated` and `fadeIn` classes. The div fades in fine on initial visit, but when it's visited a second time (i.e. once the page is already cached by turbolinks), the fadeIn animation occurs twice -- once when the cache preview is shown, and once after the page is actually loaded.

**Comment by nateberkopec** [comment]
You have two options:

* You can disable preview on that page. Add `<meta name="turbolinks-cache-control" content="no-preview">` to the `head`.
* You can do something during the preview to hide the animation, like removing the `fadeIn` class. [Here's how to do that](https://github.com/turbolinks/turbolinks#detecting-when-a-preview-is-visible).
