### ISSUE TITLE
Twice ajax request

### ISSUE THREAD

**Issue by grinsteindavid** [turbolinks/turbolinks#195]
Hi! Each time I'm redirected to another page by a link and in that page there is an AJAX get request with a ready event binded, the request is send twice ( with ready, because with turbolinks:load sends a lot of request and can reach more than 10 )  instead of one time.

Here is the code for the component:

```
<script type="text/javascript">
function main(e) {
  $.ajax({
    url: 'products',
    type: 'GET',
    success: function(data, textStatus, xhr) {
      console.log('working!');

      $('.product-list-container').empty();

      $.each(data, function(index, val) {
        $('.product-list-container').append('<div class="product"> <div class="row"> <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3"> <div class="product-img"> <img src="'+val.img_url+'" class="img-thumbnail"> </div> </div> <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9"> <div class="product-info"> <p>'+val.info+'</p> </div> </div> </div> </div>');
      });
    },
    error: function(xhr, textStatus, errorThrown) {
      console.log(textStatus);
    }
  });
}
$(document).ready(main);
</script>

<section class="product-list-container">
</section>
```

**Comment by nateberkopec** [comment]
Sort of sounds like the preview cache executing the tag. If you add `  <meta name="turbolinks-cache-control" content="no-preview">` to the top of the page with this component, does that solve the problem?

**Comment by nateberkopec** [comment]
[Another solution might be to modify your code so that it does not execute when the preview attribute is present.](https://github.com/turbolinks/turbolinks#detecting-when-a-preview-is-visible)

**Comment by grinsteindavid** [comment]
thanks it works! there is a full documentation? the readme is not enought. How turbolinks-cache-control fix this? it was a event issue?

**Comment by domchristie** [comment]
Closing as solved / inactive
