### ISSUE TITLE
Redirect (Turbolinks-Location) example

### ISSUE THREAD

**Issue by rafaelpimpa** [turbolinks/turbolinks#200]
Could anyone show me a Turbolinks-Location example using only Javascript?

I've tried something like this but it's not working:

```
document.addEventListener("turbolinks:request-end", function(event) {
  var xhr = event.data.xhr;
  xhr.setRequestHeader('Turbolinks-Location', './build');
});

Turbolinks.visit('./build/permalink', {action: 'restore'});
```

The visit command works fine, keeps the scroll position and calls the controller (it's a php application), but the url should go back to '/build' instead of '/build/permalink'.

Thanks for now.

**Comment by sandinmyjoints** [comment]
You need to add the `Turbolinks-Location` to the server response, not the request.

**Comment by SqueezedLight** [comment]
How to set headers on server side:

### Rails
In rails this is done for `redirect_to` automatically by the `Turbolinks` gem.

### PHP
In PHP you can do something like this: `header('Turbolinks-Location: /redirected_path');`

### node.js
in node.js this works: `res.header('Turbolinks-Location', '/redirected_path');`

**Comment by domchristie** [comment]
Closing as resolved by https://github.com/turbolinks/turbolinks/issues/200#issuecomment-364039452. Thanks!
