### ISSUE TITLE
Force an application visit for specific pages instead of restoration visit

### ISSUE THREAD

**Issue by aguynamedben** [turbolinks/turbolinks#202]
Hi, thanks for all your hard work on Turbolinks 5. We're close to deploying it, and it's very promising.

Here's my app flow for a community Q&A site:

1. Main feed page that lists all the questions with answers nested underneath them. Stack is:
`[Index]`

2. User clicks through to a question permalink page. Stack is:
`[Index][Show]`

3. User adds an answer to the question. This happens via UJS form submission. The answer is appended to the page with JavaScript. Stack is still:
`[Index][Show]`

4. User hits back button to go back to main feed page. The back button triggers a _restoration visit_. The user doesn't see the new answer they've given on the main feed page, because the answer was cached before they added their  #answer.

Question: How can I force the back button to trigger an _application visit_ instead of a _restoration visit_? Is there any way to do this? From reading the docs and playing with it, I can't find a way. This seems like a fairly common need, especially on UGC sites with a feed concept or other sites with a lot of CRUD flows.

I'd imaging it would be similar to the "Opt out of caching" settings.

```html
<head>
  <meta name="turbolinks-force-visit-type" type="application">
</head>
```

Pages with this <meta> tag would force an _application visit_ instead of a _restoration visit_. Just as with any _application visit_, the Turbolinks cache would still be used to fetch a page preview, but a new network request would be triggered in the background to get the updated version of the page.

### Disable caching for the main feed page
This would work, but it's unfortunate because caching the flow of clicking in and out of a question from the main feed page is where Turbolinks caching is most powerful. Caching this flow was why were were interested in Turbolinks in the first place.

### Ad-hoc updating the main feed page with lots more JavaScript
This could work, but is a bunch of code to maintain. The best solution here is to force the back button to do an _application visit_.

### Try to intercept the back button click and use Turbolinks.visit myself
This seems like it's a hack that goes far around the expectations of Turbolinks. Even if I got this working, I'm not sure if it would break other things Turbolinks expects.

**Comment by packagethief** [comment]
Hey @aguynamedben. Thanks for the kind words!

What about [clearing the Turbolinks cache](https://github.com/turbolinks/turbolinks#turbolinksclearcache) after Step 3 above, when a new answer is added? This will ensure you get a fresh page when clicking back, if you've made changes. If you're just clicking in and out, you'll still reap the benefits of caching.

[That's what the Rails adapter does before redirecting after a non-GET XHR request](https://github.com/turbolinks/turbolinks-rails/blob/10fabf0e3885c63e9d6ea698f929a8c5ad491a73/lib/turbolinks/redirection.rb#L30-L31). We assume that a non-GET XHR is likely to have changed state on the server, rendering the local cache invalid. In lieu of a more complicated invalidation mechanism, we simply clear the entire cache.

**Comment by aguynamedben** [comment]
@packagethief Thanks for the direction, it helps to have your input. At first, that approach seemed somewhat heavy-handed (clearing the entire cache) and clumsy (having to call `Turbolinks.clearCache()` in various places), but I guess that's part of the reality of cache invalidation. =) That's probably the best approach given the current abilities of Turbolinks. After trying that out some last night, I'm not sure how strongly I feel about this feature request anymore. I'll close this issue and pursue that approach.

One more detail about our app that helped me understand the problem was that our ApplicationController has this:
```rb
  def set_cache_headers
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Wed, 21 Jun 1989 00:00:00 GMT"
  end
```

The HTTP cache settings we (and many other web apps) have instruct the client to *always* get the page from the server when hitting the back button. This is why I was surprised that Turbolinks didn't do _application visit_ behavior when hitting the back button—my app never did the "real" back button behavior in the first place. Perhaps a warning in the README saying "Step 1, inspect your current Cache-Control headers!" would help prepare users for the dynamics of _restoration visits_ and cache invalidation a bit more.

Anyways, I think it'd be cool if Turbolinks could be configured to do an _application visit_ when hitting the back button, so that users would experience the perceived performance gains that make _application visits_ awesome, but the alternative of sprinkling `Turbolinks.clearCache()` around my app works for now.

**Comment by aguynamedben** [comment]
One more thought... have you seen anybody using ActionCable + calls to `Turbolinks.clearCache()` to clear the Turbolinks cache from the server-side?

My Answer model could send an ActionCable message down to clients signifying "there was a new answer added" and client-side JavaScript could receive the message and call `Turbolinks.clearCache()` as appropriate. I'm not sure if that's a bad idea, probably??? 🤔
