### ISSUE TITLE
Turbolinks and PHP server

### ISSUE THREAD

**Issue by SPopenko** [turbolinks/turbolinks#203]
Hy guys, need I something special to start using turbolinks at some php server?

For example I have this demo server: https://github.com/Learnosity/learnosity-demos/tree/master
I made integration with turbolinks.js  via script tag. 

The issue is that all pages, when I run them  throw ios application, are treated as external pages and ios SDK try to open them in Safari. Looks like turbolink could not detect links as same-origin links. 

Any ideas, recommendations?

**Comment by kevincupp** [comment]
If accessing a file directly, Turbolinks currently only accepts `.htm`, `.html`, and `.xhtml` files. You could get around it by using a common PHP file to route requests based on a URI, basically to make the URLs look like paths (like `index.php/some/path`, and optionally rewrite the URL with your server software to remove index.php if you want).

If the maintainers are interested in supporting direct PHP file requests, adding `php` to the regex here should do it. https://github.com/turbolinks/turbolinks/blob/master/src/turbolinks/location.coffee#L37

**Comment by SPopenko** [comment]
@kevincupp thank you for information!
