### ISSUE TITLE
How to design single view for Mobile and Desktop ?

### ISSUE THREAD

**Issue by kirantpatil** [turbolinks/turbolinks#205]
Hi,

I don't know how to create Reusable mobile web views across platforms as done by Basecamp.

Could anyone please shed more light on this issue?

Regards,
Kiran.

**Comment by fordfischer** [comment]
Sure - check out this awesome video of a talk by Sam Stephenson about exactly that!
https://www.youtube.com/watch?v=SWEts0rlezA

**Comment by kirantpatil** [comment]
Dear @fordfischer, I seen that video but need a hands on working code to understand. 

I am looking for sample working code that can be accessed by desktop browser and in either android/ios mobile.

**Comment by kirantpatil** [comment]
I am looking for webviews as shown in the below screenshot in the dummy project.

![screenshot from 2016-11-08 14 51 49](https://cloud.githubusercontent.com/assets/1178055/20093507/1dfdfff2-a5c3-11e6-81e6-85dfcaac22ee.png)

**Comment by kirantpatil** [comment]
Sorry for confusion here.  I am looking for how to design single view for Mobile and Desktop?

**Comment by fordfischer** [comment]
@kirantpatil are you asking about responsive layouts? Like using flexbox or Bootstrap/Foundation grids? I don't think Turbolinks has anything to do with the content of your view or making the same content work well for different screen sizes.

**Comment by kirantpatil** [comment]
Please provide some guidelines.

**Comment by kirantpatil** [comment]
@fordfischer, thanks for suggestion.
