### ISSUE TITLE
Turbolinks unbinding bootstrap tab links after loading page from cache

### ISSUE THREAD

**Issue by BrianBos** [turbolinks/turbolinks#208]
So I've been using turbolinks for most of my rails project and I've recently started using turbolinks 5. In my latest project, I added bootstrap tabs to display different kinds of info depending on the user's intention when visiting that page. Everything works well on the first load of the page but after navigating through the app and going back to the page with tabs, the tabs no longer work. Weird thing is normal links work, just the tab-links with href="#tab_id" don't work.

After some extensive research and scouring the developer tools for insights, I found that loading a cached page omits some event listeners on the page due to how turbolinks works. I don't see why only links pointing to a different section of the same page have issues.

Any insights or possible work-arounds for this? I wan't to continue using turbolinks so turning it off isn't really an option for me over this one issue.

**Comment by denvist** [comment]
The same bug with using [fotorama](http://fotorama.io/) :(

**Comment by domchristie** [comment]
When a particular JS behaviour only works on the first page load, this tends to indicate that it is not being initialised on Turbolinks page transitions. It is often a good idea to initialise third-party libraries on `turbolinks:load` (+ tear them down on `turbolinks:before-cache` if necessary).

As your issue also relates to same-page anchor links, you may be experiencing the bug detailed in https://github.com/turbolinks/turbolinks/issues/75
