### ISSUE TITLE
Wrong MIME Type from Turbolinks

### ISSUE THREAD

**Issue by shinnyx** [turbolinks/turbolinks#209]
I added a custom MIME type in `mime_types.rb`
```ruby
Mime::Type.register "text/html", :amp
```

and all requests from turbolinks are being treated as AMP request.
> Processing by UsersController#index as AMP

If I remove `//= require turbolinks` it falls back to
> Processing by UsersController#new as HTML

So.. is this a bug?

**Comment by nateberkopec** [comment]
No, this would be expected behavior if you register "text/html" as the "AMP" mimetype.

**Comment by shinnyx** [comment]
@nateberkopec thanks for the clarification.

**Comment by jeffreybasurto** [comment]
Why would this be the expected behavior?  I'm running into a similar issue where a link behaves one way in turbolinks but another way without.
