### ISSUE TITLE
IE10 doesn't seem to work in 5.0.0.beta2

### ISSUE THREAD

**Issue by basschoen** [turbolinks/turbolinks#21]
IE10 is showing a progress bar, Ajax request works fine, but content doesn't get replaced.

**Comment by packagethief** [comment]
Thanks for the report, @basschoen. Confirmed.

The problem appears to be that we're using `Element.dataset` to set data attributes, which is [unsupported in IE < 11](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_data_attributes#Issues).

> Internet Explorer 11+ provides support for the standard, but all earlier versions do not support dataset. To support IE 10 and under you need to access data attributes with getAttribute()  instead.

We can switch to `setAttribute` and `removeAttribute` instead.
