### ISSUE TITLE
Refreshing a permanent item

### ISSUE THREAD

**Issue by rubendinho** [turbolinks/turbolinks#210]
Hi there ,

I am really enjoying Turbolinks 5 - thanks for the awesome work.  

Is there a way to force the refresh of a _permanent_ item, without doing a complete page reload?

Consider the following example:
I have a side-nav marked as permanent that displays a list of the user's favorite movies with some information.  User navigates to the movies detail page, and for some reason decides to remove "Predator" from his list. Is it possible to force a refresh of sidenav as part of a resulting  `Turbolinks.visit` action?  

I understand I could remove the "Predator" element from the sidenav using Jquery, but if there are some calculations in the sidenav that depend on the count/value of the removed item, I would have to rerun them as well.

Thanks in advance.

**Comment by nateberkopec** [comment]
You could remove the `data-turbolinks-permanent` attribute from the element before navigation.

**Comment by rubendinho** [comment]
@nateberkopec - many thanks.  super simple and did exactly what I needed.
