### ISSUE TITLE
Is it possible to extend the turbolinks:before-cache event listener per page?

### ISSUE THREAD

**Issue by gregblass** [turbolinks/turbolinks#211]
I've got the following code to do stuff before any page is cached:

    document.addEventListener("turbolinks:before-cache", function() {
      // Do Stuff
    });

This works great for general/app wide code.

I've also got one page in particular that I want to run some extra stuff - but only for that page. Is there a way to 'extend' this and add more to it in a script tag on a particular page?

**Comment by nateberkopec** [comment]
Idea: `addEventListener` behind a guard and remove the event listener after it fires:

```javascript
if($("#MyPage")){
document.addEventListener("turbolinks:before-cache", function() {
  // Do Stuff
  // removeEventListener
});
}
```

**Comment by gregblass** [comment]
That'll do, thanks!
