### ISSUE TITLE
Any interest in changing the XHR request to be pluggable?

### ISSUE THREAD

**Issue by JohnB** [turbolinks/turbolinks#215]
More specifically, I'd like to swap out XHR (which I think creates a new connection to the server) with a websocket connection. Of course, the server side of that socket would have to deal with rendering the correct route - but I'm using Elixir as the server so I think it would be quite do-able.

What I'm unclear on is what changes would be needed in the coffeescript (not my native language) to make the transport pluggable. Ideally, the websocket-based connection would fire off all the callbacks that the existing XHR-based implementation does.

Yes, I could write some JS on the page to manage the socket and update the DOM, but I really like the simplicity of using standard server-created links for navigation and perma-linking, while getting the speed of a websocket.

**Comment by sstephenson** [comment]
It’s not officially “pluggable,” but you can experiment with this now by overriding [`Turbolinks.HttpClient`](https://github.com/turbolinks/turbolinks/blob/master/src/turbolinks/http_request.coffee) with your own implementation. No need to use CoffeeScript—write it whatever flavor of JS you prefer, and assign your class at runtime.

The constructor should accept a delegate, a location, and a referrer, and expose `send` and `cancel` methods. It should also fire `turbolinks:request-start` and `turbolinks:request-end` events as needed.

The delegate passed to the constructor is an object that implements the `requestStarted`, `requestCompletedWithResponse`, `requestFailedWithStatusCode`, and `requestFinished` methods. Your HttpClient implementation will need to call these methods on the delegate at the appropriate time.

**Comment by sstephenson** [comment]
Depending on your requirements, you might also have success using [Service Workers](https://developers.google.com/web/fundamentals/getting-started/primers/service-workers) to intercept Turbolinks’ requests and tunnel them over a web socket connection. That wouldn’t require any changes to Turbolinks itself, but it would currently only work in Firefox and Chrome.

**Comment by nateberkopec** [comment]
Linking #152
