### ISSUE TITLE
Why does the before-visit event not get called when navigating via history?

### ISSUE THREAD

**Issue by joelmoss** [turbolinks/turbolinks#216]
This is driving me mad, and I can't understand why this would be the case. Is it a technical limitation, or a design decision?

**Comment by sstephenson** [comment]
It's a technical limitation. The purpose of the before-visit event is to give your app a hook for canceling application visits before they begin. In the case of history navigation, the user has already clicked the Back button and the URL has changed. There's no way to cancel that.

**Comment by joelmoss** [comment]
The problem is that I can usually get around that using the `beforeunload` event, but that won;'t work with TL . Oh well :( thx anyway

**Comment by sstephenson** [comment]
See #146 for an alternative to the beforeunload event.

**Comment by joelmoss** [comment]
Yeah I've seen that, but I want to be able to cancel the event (navigating) based on some behaviour
