### ISSUE TITLE
Reload page after showing preview during restoration

### ISSUE THREAD

**Issue by benoitongit** [turbolinks/turbolinks#218]
Hi,

There are cases where sometime It would be nice to, after restoration, show the cache preview and then refresh the page. I currently opt out from cache, but the 'wow' fast feeling when clicking back is gone.

I was wondering if there was any way to achieve this? or if it's a feature that could be included in Trubolinks at some point?

Thanks,
Benoit

**Comment by domchristie** [comment]
This was duplicated by a more recent issue which includes a possible solution: https://github.com/turbolinks/turbolinks/issues/413 Hope that helps.
