### ISSUE TITLE
Turbolinks and Mkdocs

### ISSUE THREAD

**Issue by Unforgiven-wanda** [turbolinks/turbolinks#223]
Hello,
I am trying to use Turbolinks on an Mkdocs project with the material theme. When adding the Turbolinks file to my project however the Mkdocs' javascript file just stops working.
The file does not rely on JQuery, what's more, on the page's first load, the script (some scroll events and a search script) seems to works fine, however when navigating it stops working.

What's even more strange is that other personal scripts relying on JQuery work just fine however much I navigate. 

I have no idea why it's behaving this way.  Is there some way to force a .js file to reload on each visit? Any tips might help at this point.

Thank you and good day.

**Comment by domchristie** [comment]
If third-party scripts only work on the first page load, this indicates that they are only being initialised once, for example on `DOMContentLoaded` or `$(document).ready`. After the initial page load, Turbolinks loads pages in via XHR and so these events are not called again. Depending on the library, you might be able to manually initialise it on `turbolinks:load` (and tear it down on `turbolinks:before-cache`). Hope that helps.
