### ISSUE TITLE
Turbolinks.visit: target: "_blank"?

### ISSUE THREAD

**Issue by gregblass** [turbolinks/turbolinks#224]
Is it possible to pass target: "_blank" into Turbolinks.visit to open a new tab? 

My use case is printing a page, so I want to send the user to that page via turbolinks.visit, then issue the print javascript command, then close it after...thus I need to use Turbolinks.visit instead of a direct link.

**Comment by joeldrapper** [comment]
Hey, out of interest, why do you need to open a new tab to issue the print command?

**Comment by gregblass** [comment]
I'm doing a lot of back-end/generation work in a background job, and I want to display a loader in the mean time while that happens. I'm bringing back like 100 pages of data in some cases, and I can improve performance by loading a new tab and placing that HTML in it, and then printing - rather than putting that HTML in a hidden 'print' div on the page (also I think thats just kind of hackish).

**Comment by gregblass** [comment]
I also think the user experience is nicer when generating documents to open a new tab with a simple grey background and a white document in the middle representing each page. They can also then continue on with their lives while the generation happens in that new tab and still use the software in the original tab.

**Comment by joeldrapper** [comment]
So you want to load a new Window with a new layout, presumably completely new HTML, CSS, and JavaScript too. Why not just load the the page in the browser with a normal link? I’m struggling to see how Turbolinks would benefit you, in this case.

**Comment by gregblass** [comment]
You're right. Turbolinks becomes unnecessary. I ended up doing it without a turbolinks visit and it worked just fine. Thanks!
