### ISSUE TITLE
Specific cache restore event

### ISSUE THREAD

**Issue by Startouf** [turbolinks/turbolinks#225]
I am dynamically switching from a view with a google map to a view without a google map, and I want to successfully cope with the user pressing "back" on his browser.

I want to be able to run some javascript after a cache restore event. Looking at the Readme, I can only see `turbolinks:render`. There used to be a `page:restore` event in previous versions of turbolinks, do we have something similar for turbolinks 5 ?

How can I execute code when the cache restores a view when the user presses back ?

**Comment by domchristie** [comment]
Turbolinks doesn't have an event to indicate a page restoration, but internally it binds to the `popstate` event, so you should be able to handle that event to run your code. Hope that helps.
