### ISSUE TITLE
Turbolinks 5 - Safari and Android  turbolinks:load not fired

### ISSUE THREAD

**Issue by demural** [turbolinks/turbolinks#226]
On Rails 5 project event `turbolinks:load` is not fired on safari(tested on Safarii installed on Windows) and Android build in browser( tested on 4.1.2 - I do not have other version to test) .

My installed gems:
```    
turbolinks (5.0.1)
turbolinks-source (5.0.0)
```

Only first event fired on mentioned browsers:
```
 $(document).ready(function(){
        console.log('ready');
    });
    document.addEventListener("turbolinks:load", function() {
        console.log('turbo 2 ready');
    })
    $(document).on('turbolinks:load', function(){
        console.log('turbo 2 ready');
}
```

**Comment by grantzau** [comment]
Same problem on Safari Version 10.0.3 (12602.4.8) on a Mac (OS 10.12.3)

**Comment by joshuacronemeyer** [comment]
Testing on browserstack with an iphone4 running safari on iOS 6 the turbolinks:load event never fires, so none of the JS on the page gets initialized. This is another rails 5 project. 

Am I perhaps missing some code that would have turbolinks:load degrade gracefully on an older browser?

**Comment by grantzau** [comment]
The documentation referes to http://caniuse.com/#search=pushState and http://caniuse.com/#search=requestAnimationFrame

@joshuacronemeyer on iOS 6.1 the requestAnimationFrame is supported, but with prefix, and as far as I can see, the Turbolinks doesnt support the prefix

@demural pushState requires Android build in browser 4.3 and requestAnimationFrame requires 4.4, but it should work with Safari. Make sure, that the console displays not only errors by selecting "All" from the "All, Errors, Warnings, Logs" list in the top of the console?

**Comment by richpeck** [comment]
What's the fix? - I have same issue

**Comment by IvRRimum** [comment]
Having the same issue

**Comment by javan** [comment]
It's generally a bad idea to add event listeners on `document` in a `$(document).ready` callback. You'll miss any events fired before jQuery executes the callback.

Don't do this:
```js
$(document).ready(function() {
  $(document).on("turbolinks:load", function() {
    console.log("turbo 2 ready")
  })
})
```
Do this:
```js
$(document).on("turbolinks:load", function() {
  console.log("turbo 2 ready")
})
```

**Comment by IvRRimum** [comment]
We figured it out. 

document.addEventListener('turbolinks:load', ready);

This solved the issue!

**Comment by freakuency** [comment]
I am having the same issue, javascript isnt running in smartphones but working perfectly in Desktops.
PS: @IvRRimum 's solution also not working .
