### ISSUE TITLE
Bug: redirect_to redirecting via HTTP instead of HTTPS

### ISSUE THREAD

**Issue by marcamillion** [turbolinks/turbolinks#228]
I am experiencing the same error as was solved in [Turbolinks-classic here](https://github.com/turbolinks/turbolinks-classic/issues/570), yet I am using TL 5.0.1.

Was the fix they included in TL-classic also included in TL 5? Or is this an outstanding issue with TL 5?

The only way I got it working was to disable TL on that 1 link, so it certainly was a TL issue.

**Comment by fjyaniez** [comment]
Hi,

I also found this bug in 5.0.1.

**Comment by mclosson** [comment]
I am also experiencing this problem with turbolinks 5.0.1 regardless of redirecting to a _url or _path generated method.  And the workaround was as described above to add:

data: { turbolinks: false } 

to the call to link_to(...)

**Comment by nconroy** [comment]
I am experiencing this bug on 5.1.1 as well

**Comment by domchristie** [comment]
I've not been able to reproduce this. Here is an app with a link which redirects to another path: https://ancient-castle-17652.herokuapp.com. The redirect works as expected and is all done over HTTPS.

Are you still experiencing this, and if so, could you add some more details about your case (preferably with a live demo)? Thanks.
