### ISSUE TITLE
Event for restoration visits?

### ISSUE THREAD

**Issue by philipqnguyen** [turbolinks/turbolinks#230]
I have a wysiwyg editor on a web page. If the user forgot to save their changes, and they navigate away, I want to prompt them that they have unsaved changes. If they click on other links, I can intercept it with `tubolinks:before-visit`. However, I cannot find any events that are fired before a restoration visit (back or forward button on the browser). 

Are there solutions for this? If not are there plans to add something like `turbolinks:before-restore`?

**Comment by joeldrapper** [comment]
The `before-cache` event appears to be fired when pressing the back button, so you could possibly use that to trigger a save.

**Comment by panoply** [comment]
use `turbolinks:before-render` event and querySelect your WYSIWYG using the `event.data.newBody`

**Comment by domchristie** [comment]
This issue has been duplicated by #264, where there is a bit more discussion on the topic.

Turbolinks restoration visits depend on the `popstate` event which is not cancellable, so unfortunately I don't think displaying a prompt is possible (see also: https://github.com/turbolinks/turbolinks/issues/216#issuecomment-265200209). FWIW I have had some success with a different approach: saving form values automatically in session session storage, then if the person revisits the form, restore the values from the store. Hope that helps.

**Comment by xhafan** [comment]
@domchristie Thanks for the tip about saving form values into a session storage. I ended up saving the form values into the local storage so it can survive page unloading, with a custom implementation for record versioning and expiration. If anybody is interested in the implementation, you can grab it [here](https://gist.github.com/xhafan/f23e5e299699b90af60d8b7598acda08).

Previously I had a solution around page unload and turbolinks:before-visit, and the app showed an ugly mix of default browser and custom dialogs, but it could not handle the back and forward buttons. With the saving of values into the local storage, this "dialogs" solution feels pretty lame.
