### ISSUE TITLE
Enable Turbolinks on Specific Links

### ISSUE THREAD

**Issue by agusmakmun** [turbolinks/turbolinks#231]
I see the doc talked about;

```html
<a href="/" data-turbolinks="false">Disabled</a>
<a href="/" data-turbolinks="true">Enabled</a>
```

But, in my case I want only enable this turbolinks **_only_** if the `<a` element has attribute `data-turbolinks="true"`.

an example;

```html
<script>
  // bind on data-turbolinks attributes
  $('[data-turbolinks]').turbolinks();
</script>

<body>
  <!-- by default link, it disabled -->
  <a href="/page/other/">I click turbolinks is not Enable</a>

  <!-- by attribute, it enable -->
  <a href="/page/" data-turbolinks="true">I click turbolinks is Enable</a>
</body>
```

**Comment by packagethief** [comment]
You can do this by adding `data-turbolinks=false` to the `<body>` and explicitly enabling individual links. This approximates an "opt-in only" mode, where Turbolinks is disabled by default.

```html
<body data-turbolinks="false">
  <a href="/one">Disabled by default</a>
  <a href="/two" data-turbolinks="true">Explicitly enabled</a>
</body>
```

**Comment by agusmakmun** [comment]
I already do it, but I don't know still doesn't work for me...

**Comment by packagethief** [comment]
I'm not sure why it wouldn't work. I just tested locally to confirm, and it's working like I expect. What doesn't work?

**Comment by agusmakmun** [comment]
I mean, it still doesn't work well for my dropdown...

**First Codition (dropdown not work)**

> I visited my link with `data-turbolinks="true"` and then click the dropdown menu, my dropdown menu is doesn't work.

**Second Condition (dropdown is work)**

> By visiting the other links that _(without `data-turbolinks="true"`)_, my dropdown is worked well.

Please checkout my demo video; https://goo.gl/kNjnIK
