### ISSUE TITLE
[FAQ] turbolinks vs onsenui

### ISSUE THREAD

**Issue by kirantpatil** [turbolinks/turbolinks#232]
Hi,

I would like to know the tradeoff between these two turbolinks and [onsenui](https://github.com/OnsenUI/OnsenUI) technologies.

Why should I use turbolinks instead of onsenui  or both of them complement each other?

Please throw some light on it.

Thanks.

**Comment by pierre-pretorius** [comment]
This should be asked on stackoverflow as it's not an "issue" or problem with this gem.  I think this issue can be closed.

**Comment by kirantpatil** [comment]
Yeah closing this. I kept it to know if some one is as confused as me.
