### ISSUE TITLE
XSS Vulnerability

### ISSUE THREAD

**Issue by dnprock** [turbolinks/turbolinks#234]
We ran Burp Suite security scanner through our code base and it identifies a vulnerability in turbolinks gem.

Here's the line that may cause script injection:

https://github.com/turbolinks/turbolinks/blob/c73e134731ad12b2ee987080f4c905aaacdebba1/src/turbolinks/history.coffee#L17

The tool recommends to escape location variable to prevent script injection. Something like:

htmlEncode = function(value) {
  return $('< div />').text(value).html();
}

Would this be a vulnerability or is it already addressed?

**Comment by taq** [comment]
Just run the Burp Suite and also got this, more than 2 years from the original question. Is something to worry about?

**Comment by mtschirs** [comment]
AFAIK this is a false positive. Burp (2.0) reports the following:
```
Data is read from window.location and passed to the 'wrap()' function of function of JQuery via the following statement:
l.Location.wrap(window.location)
```
However, the identified 'wrap' function is not from jQuery, but located in https://github.com/turbolinks/turbolinks/blob/master/src/location.ts#L10 and wraps the given URL string within a turbolinks Location object. It does not seem to be vulnerable to DOM based XSS.
