### ISSUE TITLE
[Chrome] origin violation with HTTPBasicAuth credentials in URL

### ISSUE THREAD

**Issue by 2called-chaos** [turbolinks/turbolinks#237]
This could be a Chrome issue only but maybe you guys can help me decide.

When accessing an URL protected with HTTPBasicAuth while having the credentials in the URL (http://user:pass@domain) turbolinks raises an DOMException and it - and all custom javascript with it - aborts.

```
Uncaught DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'http://test.de/admin' cannot be created in a document with origin 'http://test.de' and URL 'http://user:pass@test.de/admin'.
    at i.t.History.i.update (...)
    at i.t.History.i.replace (...)
    at n.t.Controller.n.startHistory (...)
    at n.t.Controller.n.start (...)
    at Object.t.start (...)
```

Could reproduce with:

  * Chrome 56.0.2924.87 (64-bit) on OS X

Could not reproduce with:

  * Firefox 51.0.1 (64-Bit) on OS X
  * Safari 9.1.1 on OS X

Is it a Chrome fault (by having a broken origin check or by not stripping the credentials somewhere) or is it up to turbolinks to handle this?

**Comment by domchristie** [comment]
Technically I think this should be handled by:

https://github.com/turbolinks/turbolinks/blob/c340c42e2ece8c057aec611074971462a6e76c71/src/turbolinks/controller.coffee#L237-L238

which is called when a visit is triggered programmatically or via a click.

This can be tested by:

```js
var currentLocation = Turbolinks.Location.wrap('http://test.de/admin')
var newLocation = Turbolinks.Location.wrap('http://user:pass@test.de/admin')
newLocation.isPrefixedBy(currentLocation)
```

If this returns `false` then `visit` should set the location to trigger a full page load:

https://github.com/turbolinks/turbolinks/blob/c340c42e2ece8c057aec611074971462a6e76c71/src/turbolinks/controller.coffee#L41-L48

I'll close this issue for now, but feel free to reopen this issue if you're still having this problem. Thanks.
