### ISSUE TITLE
Button text while loading

### ISSUE THREAD

**Issue by jarkelen** [turbolinks/turbolinks#239]
Hi,

When I press a button and it takes a little bit of time to load the partial view, I see that the button has a disabled state and also another text, like "submit". Is it possible to set this text somewhere to a different text? I have a Dutch site, so I would like to have the value "versturen" instead.

Regards,
John

**Comment by Fudoshiki** [comment]
In rails you can set attribute `data-disable-with` for inputs[type='submit'] and button tag 
http://api.rubyonrails.org/classes/ActionView/Helpers/FormTagHelper.html

Provided by https://github.com/rails/jquery-ujs in Rails up to 5.0 and rails-ujs in Rails 5.1 and upper

**Comment by domchristie** [comment]
Closing as fixed/inactive
