### ISSUE TITLE
Before-cache body of new page

### ISSUE THREAD

**Issue by amnesia7** [turbolinks/turbolinks#240]
Hi,

I've seen that you can access the `<body>` of the new page before rendering it using `event.data.newBody` when using `turbolinks:before-render`.

Is there a way to access the `<body>` of the new page when using `turbolinks:before-cache` ?

Col

**Comment by franlab** [comment]
Do you mean the `body` of the old page?

I am having a problem since I cannot access `event.data.newBody`

**Comment by packagethief** [comment]
@franlab, do you happen to be observing the event with jQuery? If so, you'll need to use `event.originalEvent.data.newBody` to access it.

**Comment by domchristie** [comment]
@amnesia7 accessing the new body in `before-cache` isn't available in the current API. May I ask what you need it for?

**Comment by amnesia7** [comment]
I don't need this anymore so I'm going to close this issue and just reopen it in future should the need occur
