### ISSUE TITLE
Load JS on initial page load

### ISSUE THREAD

**Issue by gentle-noah** [turbolinks/turbolinks#243]
Hey there, my engineering team and I have spent 10+ hours scouring the internet looking for a reason as to why our JS is not working on initial page load.  Once we engage with navigating around our application we get our desired results, however, if we hard refresh the page, the JS stops working. We have tried every imaginable variation on the `javascript_include_tag`, we have tried `jquery.turbolinks`, we have used every possible event handler (and most combinations) provided by Turbolinks 5 -- but still no luck.

We have this piece of JS:

```
function validateForms() {
  validateInput();

  $('.validate').keyup(function(event){
    validateInput();
  });

  $('input:checkbox .validate').click(function(event){
    validateInput();
  });

  function updateBtnStatus(status) {
    var submit = $('input[type="submit"]');
    if (status === 'enable') {
      submit.removeAttr('disabled');
      submit.removeClass('disabled');
    } else {
      submit.prop('disabled', true);
      submit.addClass('disabled');
    };
  };

  function validateInput() {
    var valid = 0;
    var inputLength = $('input.validate').length;
    $('input.validate').each(function(){
      if($(this).val() !== '') { valid++ ; }
    });
    if(valid === inputLength) {
      updateBtnStatus('enable')
    } else {
      updateBtnStatus('disable')
    }
  };
}

$(document).ready(validateForms);
$(document).on('turbolinks:load', validateForms);
```

and this in our head:

`= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'` - we've tried adding evel false, async true, defer true with no luck.

We can't seem to find any actual resolution to this issue with in your open or past issues or anywhere on SO. So, here we are! Hi!

A solution or some direction would be worth it's weight in gold to us in this moment.

**Comment by packagethief** [comment]
Hey! What doesn't work, exactly? Your function isn't called on the initial load? It's called but doesn't behave like you expect?

The "turbolinks-load" event fires on the initial page load too, so you don't need the $.ready handler. What happens if you remove it?

**Comment by gentle-noah** [comment]
Hey @packagethief - thanks for the quick response!

So the JS is being triggered, we are able to hit the proper `debugger` statements and receive the expected state. The issue seems to be that we are actually unable to tigger the `removeClass` or `.remove()` on the `submit` object once we get into a validated state. 

The interesting part, is that we were finally able to get this to work by throwing `Turbolinks.visit(location);` in at the top of our `applicaiton.js` file after calling in all of our requirements. This, to me, points to something going on with Turbolinks and not our own code. We get a blink when the page is being rerendered by Turbolinks and then everything works great. 

Is there something with Turbo links that would prevent us from being able to manipulate that DOM element?

The function I'm talking about hitting with success is the following:

```
function updateBtnStatus(status) {
    var submit = $('input[type="submit"]');
    if (status === 'enable') {
      submit.removeAttr('disabled');
      submit.removeClass('disabled');
    } else {
      submit.prop('disabled', true);
      submit.addClass('disabled');
    };
  };
```

**Comment by gentle-noah** [comment]
Additional follow up:

If I remove `$(document).ready(validateForms);` -> the JS stops working as expected completely. 

If I remove `$(document).on('turbolinks:load', validateForms);`-> the JS only works when I reload the page and even then it only works partially. 

The only solution I've found to get the JS to trigger and behave properly is by running the `Turbolinks.visit(location);`, which leads to some undesired behavior (page reloads every time there is a new page fetched - expected behavior for using this function).

**Comment by gentle-noah** [comment]
Removed Turbolinks and the issue went away, but we have since resolved the issue and been able to remove `Turbolinks.visit(location)`. Turbolinks was getting pissed about us not having our functions in separate `on('turbolinks:load, ...` blocks.
