### ISSUE TITLE
Turbolinks with PHP7?

### ISSUE THREAD

**Issue by fdagostino** [turbolinks/turbolinks#244]
Hi!
Can Turbolinks work with PHP7?

Do I have to implement anything in server side in addition to include turbolinks.js?

Thanks

**Comment by nateberkopec** [comment]
Check out https://github.com/turbolinks/turbolinks-rails for an example of what is implemented serverside for Turbolinks.

**Comment by christophwolff** [comment]
With Turbolinks 5 there is nothing to implement on the serverside.

**Comment by fdagostino** [comment]
Thanks @nateberkopec  & @christophwolff will check both and confirm.

**Comment by domchristie** [comment]
I think the main thing to consider is how to handle redirects. turbolinks-rails overrides Rails' [`redirect_to`](https://github.com/turbolinks/turbolinks-rails/blob/e9ebf31c04ede37f29624e52cd74ad2ea12c5bee/lib/turbolinks/redirection.rb#L9-L21) method to send down some JavaScript which then calls `Turbolinks.visit`. [Redirecting after a form submission](https://github.com/turbolinks/turbolinks#redirecting-after-a-form-submission) is handled in a similar way, but the Turbolinks cache is also cleared.
