### ISSUE TITLE
Please compile to dist without uglifier

### ISSUE THREAD

**Issue by mean-cj** [turbolinks/turbolinks#245]
Hello Thank you for your project

Please compile to dist without uglifier
I didn't epertise with coffee script

Thank you.

**Comment by nateberkopec** [comment]
Lots of other projects seem to compile a `project.js` and `project.min.js`, so I'm OK with this.

**Comment by mean-cj** [comment]
Thank you so much for your response.

**Comment by nateberkopec** [comment]
I'm just a contributor, not a maintainer. You should re-open this issue.

**Comment by packagethief** [comment]
I don't object to distributing an unminified version, but it will require some build and documentation updates. If your primary interest is in reviewing the JavaScript, though, you can disable uglifier and rebuild:

- Edit [.blade.yml](https://github.com/turbolinks/turbolinks/blob/e7c5392/.blade.yml#L15) and remove the `js_compressor` line
- Run `./bin/blade build`

**Comment by preetpalS** [comment]
@mean-cj If you want readable JavaScript code, just use [beautify-web/js-beautify](https://github.com/beautify-web/js-beautify). You can copy and paste the contents of the minified JS file in `dist`  to [jsbeautifier.org](http://jsbeautifier.org/) for more readable JS code.

**Comment by domchristie** [comment]
Closed by https://github.com/turbolinks/turbolinks/pull/445
