### ISSUE TITLE
turbolinks:load have reinitialize on other page

### ISSUE THREAD

**Issue by mean-cj** [turbolinks/turbolinks#246]
Hello

I found problem when use event handle by turbolinks:load 
When i click link goto other page 
this handle from Test Page has been reinitialize on other page
--------------------

**First open Test Page by url**
$(document).on('turbolinks:load', function(){
 console.log(1);
});
result is 1

**click link goto other page , after page load**
result is 1 

------------------------------------------------------------------
Next, I have other idea, when goto Test Page
can be set attribute for reinitialize script by random parameter
same as $.getScript on jquery have add random parameter ?_=32141254215 
or attribute for disable cache only this js file

example Callback every goto Test Page
<script src="my-script.js" data-turbolinks-refresh="true"></script>
http://domain.com/my-script.js?_=45646456564

---------Current Doesn't Work-----------
```
    <script src="jquery.min.js"  data-turbolinks-eval="false"></script>
    <script src="turbolinks.js" data-turbolinks-eval="false"></script>
    <script src="my-script.js" ></script>
```

**my-script.js**
```
$(function(){
  console.log(1);
});
```
**First open page by url**
result is 1

**click link to next page**
result is empty

**click link to Test Page**
result is empty

Thank you.

**Comment by panoply** [comment]
#364 may help you.

**Comment by domchristie** [comment]
`turbolinks:load` is triggered on every page load. If you add `$(document).on('turbolinks:load', handler)` in the body of the first page, it will call the handler of every subsequent page load, unless the handler is removed. I hope that helps.
