### ISSUE TITLE
Enable turbolinks for non-GET requests similar to turbolinks-classic

### ISSUE THREAD

**Issue by printercu** [turbolinks/turbolinks#247]
Hi!

Is there any reason not to make turbolinks work as in previous versions? From old readme:

```
* `POST :create` => resource successfully created => redirect to `GET :show`
  * Turbolinks **ENABLED**
* `POST :create` => resource creation failed => render `:new`
  * Turbolinks **DISABLED**
```

UPD. For example `devise` would work by default with turbolinks.

**Comment by focused** [comment]
Is #251 similar to this issue

**Comment by domchristie** [comment]
Closing as duplicate of #60. I have added some more detail explaining the complexity in https://github.com/turbolinks/turbolinks/issues/60#issuecomment-423437233
