### ISSUE TITLE
Styles get left in head?

### ISSUE THREAD

**Issue by Kiszko** [turbolinks/turbolinks#249]
When navigating between pages, stylesheets unique to a page, get left in the head. Even with `no-cache` enabled. Do we have control over what stylesheets / scripts we want to persist and what we want to be freshly loaded, between requests?

**Comment by nateberkopec** [comment]
> When navigating between pages, stylesheets unique to a page, get left in the head. Even with no-cache enabled.

This is current turbolinks behavior, yes. See #187.

**Comment by Pushplaybang** [comment]
This is the expected behaviour for turbolinks.

@Kiszko  - what I would recommend, and use with great success, is looking into inlining your critical path CSS in the head, and then loading page or component specific styles in the footer.

This has had the advantage of speeding up rendering on my site tremendously. and reducing page load.   I do the same with javascript and have seen a massive performance boost.

**Comment by Fudoshiki** [comment]
This is wrong way for inline css style tag in head, it must load only style tag from new page

**Comment by Fudoshiki** [comment]
My own solution https://github.com/Fudoshiki/turbolinks/commit/2ace88c83d31b8e5cf335c65982ab4ce28df0957

**Comment by Pushplaybang** [comment]
@Fudoshiki  - I disagree, using low specificity cascading styles allow you to load the frame of the page, and basic above the fold components, 

Additional page specific critical CSS can be loaded after the body opening tag, though I eventually dropped this.

**Comment by Fudoshiki** [comment]
Inline css this is page content, turbolinks must load only inline styles which present on page, but no transit from previous page

**Comment by Fudoshiki** [comment]
We speak about 
```slim
head
  style
    | some styles
```

**Comment by Fudoshiki** [comment]
Current behaviour
```slim
head
  style
    | some styles
```
click on link
result
```slim
head
  style
    | some styles
  style
    | some styles
```
double style tag with same styles

**Comment by Pushplaybang** [comment]
turbolinks does not reload the head.  but merges,

> During rendering, Turbolinks replaces the current <body> element outright and merges the contents of the <head> element. The JavaScript window and document objects, and the HTML <html>  element, persist from one rendering to the next.

These styles should either be scoped or only low specifricity as I described, and should only be an issue if your CSS/SCSS is poorly structured.

**Comment by Fudoshiki** [comment]
scoped css not valid from W3C specifications
turbolinks must merge link rel=style tags but not inline tags

**Comment by Pushplaybang** [comment]
@Fudoshiki no.  and scoping CSS is perfectly valid.  

Structure your components by page.

```scss

.home {
  .banner {}
  .whatever {}
}
```

this isn't a bug, its a design.

**Comment by Fudoshiki** [comment]
https://css-tricks.com/saving-the-day-with-scoped-css this is not valid now

**Comment by Pushplaybang** [comment]
@Fudoshiki no.

I mean, simply create a "scope" using page or component specific classes.

**Comment by Fudoshiki** [comment]
I don't want load all styles for all pages on each page

**Comment by Pushplaybang** [comment]
then drop your inline style tag after the opening body tag.

**Comment by Fudoshiki** [comment]
example please

**Comment by Pushplaybang** [comment]
simply add your style tag outside of the head.

```
head
  style // global styles
body
  style // page specific
```

**Comment by Fudoshiki** [comment]
I like your point

**Comment by Pushplaybang** [comment]
I would also suggest that if you find you've got mountains of page specific CSS, see if:
 - you can structure your styles to be more general
 - see if you have missed potential components
 - re-consider your design decisions, you should have a great deal of shared structure, and form, particularly above the fold, to create a seamless user experience.

**Comment by Pushplaybang** [comment]
@Kiszko  - would you consider closing this issue please, if you are satisfied.

**Comment by kireerik** [comment]
I think a backward compatible solution could be to introduce a `data-turbolinks-pageSpecific` attribute or something like that. However for example `meta` attributes are erased and then injected. So I think the same behavior should be the default for inline `style` and `script` elements defined in the `head`. In this case we could have a `data-turbolinks-permanent` or a `-global` attribute or something like that for example. Which would mean the current behavior for those inline head elements.

**Comment by domchristie** [comment]
Resolved by https://github.com/turbolinks/turbolinks/issues/249#issuecomment-387147519 Thanks!
