### ISSUE TITLE
Readme should list supported browsers 

### ISSUE THREAD

**Issue by felixbuenemann** [turbolinks/turbolinks#25]
The API section for Turbolibks.supported links to an anchor with supported browsers that's missing.

**Comment by packagethief** [comment]
Hey @felixbuenemann. The [Supported browsers](https://github.com/turbolinks/turbolinks#supported-browsers) section lists the browser APIs we depend on, each of which link to http://caniuse.com for more details.

I'd rather we avoid listing every supported browser, but for posterity, they appear to be the following. Unverified, of course.

- IE >= 10
- Firefox >= 23
- Chrome >= 24
- Safari >= 6.1
- Mobile Safari >= 7.1
- Opera >= 15
- Android >= 4.4

**Comment by felixbuenemann** [comment]
Sorry, for some reason the link to '#supported-browsers' under `Turbolinks.supported` in the API section wasn't working for me when I opened the issue, maybe because I was on the mobile site. It seems to be working fine now. I agree that the existing section gives enough information.

**Comment by packagethief** [comment]
Ha, that was my first thought – that the link must be broken. When I tested and saw that it wasn't, I assumed you must have meant something else. Sorry for misunderstanding!
