### ISSUE TITLE
jQuery window load not executed with Turbolinks (Turbolinks, jQuery, Foundation Magellan)

### ISSUE THREAD

**Issue by mitosch** [turbolinks/turbolinks#252]
Hi there,

In my app I'm using Turbolinks & Foundation. Foundation has several plugins, bound to window.onload events. One is Magellan.

Code snippet of foundation.magellan.js:
```javascript
        };
    $(window).one('load', function(){
      if(_this.options.deepLinking){
```
Source: https://github.com/zurb/foundation-sites/blob/develop/js/foundation.magellan.js#L81

The only way I could find to make Foundation Magellan working was with the following code in my app:
```javascript
$(document).on('turbolinks:load', function() {
  $(window).trigger('load');
  // ...
});
```

But this looks "odd".

Any help is appreciated.

Thanks!

Mischa

**Comment by azeezahmed** [comment]
Hi, Can you try [jquery-turbolinks](https://github.com/kossnocorp/jquery.turbolinks) and let us know if your issue is fixed?

**Comment by mitosch** [comment]
Sorry, I didn't mentioned it, that this is already in place:
![image](https://cloud.githubusercontent.com/assets/922559/24186867/a2f4139c-0eda-11e7-891d-5f730342a988.png)

**Comment by mitosch** [comment]
Analyzed this a little bit deeper:

foundation.magellan.js is calling jQuery.one():
```javascript
$(window).one('load', function(){
```

So it is executed once for the window load event. See jQuery documentation:
> The handler is executed at most once per element per event type.
Source: http://api.jquery.com/one/

In a standard setup (without Turbolinks) this means every time a page is loaded. With Turbolinks this could mean, that it is executed once and jQuery removes the event after the first load (assumption).

**Comment by domchristie** [comment]
Hi @mitosch 

If it's possible, you may want to consider manually initialising the library on `turbolinks:load`, rather than relying on automatic initialisation. Otherwise your solution to trigger `load` on `turbolinks:load` might be the best option.
