### ISSUE TITLE
jQuery handler (datepicker) removed after hitting back button on Turbolinks site

### ISSUE THREAD

**Issue by chrismanderson** [turbolinks/turbolinks#253]
I know much has been written about the interaction between jQuery and Turbolinks. I think I've read all of it in trying to debug this issue and I would love to know once and for all how to fix, what I would assume, is a fairly common bug.

My issue is that when I successfully attach a jQuery picker to an element, navigate to another page, and click the browser back button, the handler is no longer attached and the date picker does not appear. If I navigate back to the page by clicking, say a 'Back' link,  it works properly.

![screen recording 2017-03-24 at 01 30 pm](https://cloud.githubusercontent.com/assets/418258/24306248/568113b2-1096-11e7-833d-e8d383776930.gif)

I attached the handler via the instructions in the Turbolinks readme, and tear it down as well.

```
document.addEventListener("turbolinks:load", function() {
  $("#delivery_date").datepicker();
})

document.addEventListener("turbolinks:before-cache", function() {
  $("#delivery_date").datepicker('destroy')
})
```

I'm trying to determine if this is a case that flat out does not work in Turbolinks. Or if the issue lies in 1) my setup, 2) Turbolinks, 3) the plugin, 4) anything else. I feel like I've tried virtually every combination of the Turbolinks events listed in the readme, but I cannot get the handler to reinitialize after hitting the back button.

I've included a [sample repo](https://github.com/chrismanderson/turbolinks-error) and a [demo](https://young-river-94040.herokuapp.com/) and I'm happy to provide any other information if need be. This issue is so simple and I feel like there has to be a simple solution to it, but I am coming up against a wall.

Thanks!

**Comment by javan** [comment]
We ran into the same issue in Basecamp too. Took forever to figure out. Here's our fix:
```coffee
# The jQuery UI date picker widget appends a shared element to the
# body which it expects will never leave the page, but Turbolinks
# removes that shared element when it rerenders. We satisfy that
# expectation by removing the shared element from the page before
# Turbolinks caches the page, and appending it again before
# Turbolinks swaps the new body in during rendering.
#
# Additionally, returning to the cached version of a page that
# previously had date picker elements would result in those date
# pickers not being initialized again. We fix this issue by finding
# all initialized date picker inputs on the page and calling the
# date picker's destroy method before Turbolinks caches the page.

document.addEventListener "turbolinks:before-cache", ->
  $.datepicker.dpDiv.remove()

  for element in document.querySelectorAll("input.hasDatepicker")
    $(element).datepicker("destroy")

document.addEventListener "turbolinks:before-render", (event) ->
  $.datepicker.dpDiv.appendTo(event.data.newBody)
```

**Comment by chrismanderson** [comment]
This solution worked for me! Thanks so much for the tip. I'd love to figure out a way to make this more of a 'first party' solution in Turbolinks and will be thinking through various options.
