### ISSUE TITLE
How do I tell turbolinks enabled?

### ISSUE THREAD

**Issue by IsaacHub** [turbolinks/turbolinks#254]
I have a typical website with 4 different pages(_Home, About, Gallery, Contact_), just with HTML, CSS and JAVASCRIPT.

I have placed `<script type='text/javascript' src='turbolinks.js'></script>` immediately after `<head>` tag in all 4 files. 
**Is this the usual/correct way to do it?**
**Is turbolinks enabled now?**
**Do I need to add any data attributes to all `<a>` tags and `<body>` tags?**
I'm confused.

**Comment by packagethief** [comment]
That's really it! No additional attributes or configuration is required.

To confirm, you can use the Network tab in Chrome's developer tools. You should see that Turbolinks pages are requested with XHR.

<img width="507" alt="screen shot 2017-03-30 at 11 17 07 am" src="https://cloud.githubusercontent.com/assets/10987/24511839/d09ae832-153a-11e7-8636-68a130f50d65.png">
