### ISSUE TITLE
Does Turbolinks remove page specific `scripts` when navigated away?

### ISSUE THREAD

**Issue by ankitrg** [turbolinks/turbolinks#255]
I read the docs and came across the following line:

> When you navigate to a new page, Turbolinks looks for any <script> elements in the new page’s <head> that aren’t present on the current page. Then it appends them to the current <head> where they’re loaded and evaluated by the browser. You can use this to load additional JavaScript files on-demand.

So as it loads the page specific scripts on page load but does it remove them after one navigates to another page?

**Comment by grosser** [comment]
yes, all scripts stay on the page ... it just replaces the body ... scripts stay running

**Comment by nateberkopec** [comment]
What @grosser said. The script element itself is removed, but the code has already been executed, so it's still live on the page. There's no way to roll that back.

**Comment by whodidthis** [comment]
I think there should be some mention of using `turbolinks.start()` in a script placed at the end of `<body>` tag. I'm an idiot so i just had some bad times with it. 😆 😭

**Comment by domchristie** [comment]
Closing as fixed

**Comment by archonic** [comment]
Follow up question: If you want to unload JS between turbolinks visits, how would you do that? I have two libraries which conflict but are page specific. Is my only option to force a full-page load for those pages?
