### ISSUE TITLE
Turbolinks doesn't seem to work with relative links with parameters

### ISSUE THREAD

**Issue by tasso85** [turbolinks/turbolinks#256]
Hi,

I am trying turbolinks on our webapp.

We already have a "master listener" on all link clicks event, so I thought of disabling turbolinks on the body using `data-turbolinks="false"` and then replace our handler with `Turbolinks.visit(...)`.

However, I tried from the console too, the clicks on the link still result in a full page reload.

Is there anything else I might need to set? I tried reading the README and the wiki, but I didn't find anything relevant.

**Comment by tasso85** [comment]
One example of link failing to load through turbolinks is passing from `/modules.php?name=User_Profile` to `/modules.php?name=piano_sicurezza`, which causes a full page reload.

**Comment by grantzau** [comment]
There shouldn't be any problems with relative links, most websites uses that.

**Comment by tasso85** [comment]
After further testing, I noticed that, when the call to `Turbolinks.visit(url)` seems to "fail", by issueing a normal page navigation instead, it returns an object like that when logged is like this:

```
Object {
  absoluteURL: "URL WHERE I TRIED TO NAVIGATE",
  requestURL: "SAME AS ABOVE"
}
```

When I test the only address which is loaded correctly, I get a different object instead:

```
turbolinks:visit {
  target: HTMLDocument → /,
  isTrusted: false,
  eventPhase: 0,
  bubbles: true,
  cancelable: false,
  defaultPrevented: false,
  composed: false,
  timeStamp: 1492781909168000,
  cancelBubble: false,
  originalTarget: HTMLDocument → /,
  explicitOriginalTarget: HTMLDocument → /
}
```

In the first case, it seems like a plain object, while the second looks more like an event instead; however this does not help in identify the issue which causes it not to work properly.

**Comment by tasso85** [comment]
I **think** I might have found the problem here.

I see, in the minified distribution code, that there is a check whether the visited location has an extension and, if it has one, if it is one of `htm`, `html` or `xhtml`.

However, all of our link are towards php files, for example a link might look like `/folder/index.php?p=1&x=2`.

How do I enable turbolinks for such links?

**Comment by nateberkopec** [comment]
I would fork it and change this line: https://github.com/turbolinks/turbolinks/blob/c73e134731ad12b2ee987080f4c905aaacdebba1/src/turbolinks/location.coffee#L37

**Comment by packagethief** [comment]
No need to fork, though. You can override `Turbolinks.Location.prototype.isHTML` locally after loading Turbolinks. See https://github.com/turbolinks/turbolinks/issues/15#issuecomment-186639159.

**Comment by nateberkopec** [comment]
^^^ Listen to this guy, I don't know how to JavaScript 😆

**Comment by tasso85** [comment]
In the end I did what @packagethief suggested, and it worked, I think this should be documented though.

**Comment by domchristie** [comment]
Closing as solved by https://github.com/turbolinks/turbolinks/issues/256#issuecomment-296217525
