### ISSUE TITLE
hold click on Turbolinks enabled link disabled the smooth scrolling on Chrome

### ISSUE THREAD

**Issue by StarWar** [turbolinks/turbolinks#259]
In my rails website using Turbolinks 5, hold click on Turbolinks enabled links disabled the scrolling Behaviour. I have to drag scroll instead of two finger scroll. I've also tried on some other turbolinks enabled websites as well and was able to reproduce it in incognito as well.

How to reproduce:
1. Inspect element, select mobile device
1. Hold and Click on Turbolinks enabled link, as if you're selecting the link or hold enough that Link element is now selected, hold and click the link.
2. Now smooth scrolling stopped working, I need to drag to scroll the page.

Not sure if it's Turbolinks issue or Chrome.

Thanks,

**Comment by domchristie** [comment]
I've not been able to reproduce this on Chrome iOS or Android, so perhaps it has been fixed? Closing for now, but feel free to reopen if you're still experiencing this issue.
