### ISSUE TITLE
[BUG] Turbolinks duplicates icons

### ISSUE THREAD

**Issue by ConsoleTVs** [turbolinks/turbolinks#262]
The icons get duplicated every request on the page. if you visit the main page and have icons, you visit another, press the back button and they render twice, so they can keep beeing added without stop.

![image](https://cloud.githubusercontent.com/assets/6124435/25182042/b89f144a-2513-11e7-851c-c0e9fee293f8.png)

It only happens with UIKit 3 icons.

**Comment by javan** [comment]
How are those icons rendered? `<img>` tags?

**Comment by ConsoleTVs** [comment]
Seems uikit uses js to load them...

**Comment by javan** [comment]
Are you calling any uikit js in your app? On `turbolinks:load` for example.

**Comment by ConsoleTVs** [comment]
It's imported as a js, nothing else called.

Sample example:

```
<span uk-icon="icon: check"></span>
```

**Comment by SaphiLC** [comment]
it duplicates a lot of things created by uikit... and also makes uikit grid jump a lot (the big just its because the sticky in the image)

jumps:
https://files.gitter.im/uikit/uikit/egmb/jumps.gif
sticky:
https://files.gitter.im/uikit/uikit/D5Sn/image.png

i wonder if there is a solution for all this.

**Comment by domchristie** [comment]
It looks like [UIKit uses MutationObservers](https://github.com/uikit/uikit/search?q=mutationobserver&unscoped_q=mutationobserver), so you will need to tear down the icon components on `turbolinks:before-cache` to prevent duplication (see https://getuikit.com/docs/javascript at the bottom).
