### ISSUE TITLE
onbeforeunload on back button - prevent user from losing unsaved changes

### ISSUE THREAD

**Issue by feliperaul** [turbolinks/turbolinks#264]
I saw #146 and #216 but still can't find a way to solve a simple requirement: show an alert asking the user to confirm navigating away if he has unsaved changes.

If I bind `$(window).on('beforeunload' ...`, it will fire when reloading the page, clicking a bookmark or typing a new url in the addressbar, but it won't fire on back button (and also, obviously, won't fire on clicking on internal links).

If I also bind `$(document).on('turbolinks:before-visit', function(event) { ... }`, this solves the internal links (I can show a confirm alert and use `event.preventDefault()` to stop navigation if there are unsaved changes), but this also won't fire on browser back button. 

The suggestion in #146 suggests binding to `$(document).on('turbolinks:before-render'`, but I can't seem to find a way to show the dialog and cancel navigation if the users clicks cancel, as `event.preventDefault()` doesn't cancel navigation in `turbolinks:before-render`

So: how to prevent user from losing unsaved changes when he uses the back button ?

**Comment by mttdffy** [comment]
+1 Also trying to solve this problem

**Comment by timonbandit** [comment]
+1 trying to exit full screen in player on back button instead of navigation to previous page

**Comment by tomgong** [comment]
+1 Having the same problem showing a confirm dialogue before leaving a page via back button.

**Comment by maguri** [comment]
Has been this solved?, I have the same issue pressing the back button. 🙁

**Comment by timonbandit** [comment]
@maguri drop it :)
I wrote my own realization. it's much more effective and faster.

**Comment by maguri** [comment]
where is this "realization"?

**Comment by timonbandit** [comment]
@maguri in private repo ;) 
It's just an advice.
Could be better to stop searching how to resolve this problem with turbolinks and write your own.

**Comment by maguri** [comment]
Yeah sure,
Thats what I will have to do at the end!

Thanks @timonbandit 🤙🏼 !

**Comment by timonbandit** [comment]
@maguri :+1:

**Comment by maguri** [comment]
**JQuery** This has resolved my need: `window.onpopstate`

**Comment by dsmalko** [comment]
@maguri How do you cancel navigation?

**Comment by maguri** [comment]
As is logic in this thread, I am using **turbolinks**:
- I set a `var` if my data changes on `turbolinks:load` 
- And **alert** when *reload*, *go back*, *close windows*...

- Add the `class` => `prevent_unsaved_data-js` to the input or to the form you want to prevent unsaved data.
```javascript
var unsavedData = "Your unsaved data will be lost!";

function askConfirm() {
  if (needToConfirm)
    return unsavedData;
}

$(document).on('turbolinks:load', function(){
  needToConfirm = false;

  $(".prevent_unsaved_data-js :input").on('change', function() {
    needToConfirm = true;
  });

  $('form').submit(function(){
    needToConfirm = false;
  });

  window.onpopstate     = askConfirm;
  window.onbeforeunload = askConfirm;
```

To touch up when user goes to other links, I use this:
```javascript
$(document).on('turbolinks:before-visit', function(){
  return !(needToConfirm && !confirm(unsavedData));
});
```

**Comment by dsmalko** [comment]
Problem is turbolinks:before-visit isn't fired for back button and window.onpopstate don't prevent turbolinks from navigation.

**Comment by leouofa** [comment]
+1 Having a similar issue. Any ideas?

**Comment by maguri** [comment]
As @timonbandit told me one day, drop it. I desisted and implemented my backend solution using server session.

**Comment by andypearson** [comment]
Just run into this as well.

The docs for `turbolinks:before-visit` explicitly states "except when navigating by history" so I wonder if there needs to be an additional `turbolinks:before-history-change` (or similar) event that could be hooked in these cases.

**Comment by domchristie** [comment]
@andypearson is correct: `popstate` is not cancelable, so preventing a Back/Forward action is not possible.

Turbolinks clones the `<body>` when caching, which includes input values (but not those of `<select>` controls, see #238), so navigating back/forwards should be relatively safe, i.e. the person should lose their work. If you want to make this behaviour more robust, then you may wish to store input values in session storage, and then hydrate them on `turbolinks:load`. This approach is similar to what GitHub does with comment boxes just like this one :)
