### ISSUE TITLE
Turbolinks 5 and jQuery compatibility 

### ISSUE THREAD

**Issue by lauroengineer** [turbolinks/turbolinks#265]
I have a hidden field that's activated when clicked on the link using jQuery. When clicking on the link, the field appears just for a second and then disappears. 

```javascript
  $('.use-different-card').on "click", ->
    $(".card-on-file").hide()
    $(".card-fields").removeClass("hidden")
```

When I remove turbolinks,  jQuery seems to work just fine.

I've tryied adding [compatibility.coffee](https://github.com/turbolinks/turbolinks/blob/master/src/turbolinks/compatibility.coffee) but I had no luck. 

And using: 

`$(document).on "turbolinks:load", ->`

This is my source tree. 
```
//= require jquery
//= require jquery_ujs
//= require jquery.turbolinks
//= require turbolinks
//= require turbolinks-compatibility
//= require_tree .
```

**Anything suggestion on what to try next?**

**Comment by javan** [comment]
If the element with `.use-different-card` is an `<a>`, you need to cancel the `click` event:
```coffee
$('.use-different-card').on "click", (event) ->
  event.preventDefault()
  $(".card-on-file").hide()
  $(".card-fields").removeClass("hidden")
```
or
```coffee
$('.use-different-card').on "click", ->
  $(".card-on-file").hide()
  $(".card-fields").removeClass("hidden")
  false
```

**Comment by lauroengineer** [comment]
@javan that was really helpful. Both worked!

Thanks you!
