### ISSUE TITLE
Turbolinks, async and DOMContentLoaded

### ISSUE THREAD

**Issue by nateberkopec** [turbolinks/turbolinks#266]
See #28, where `defer` fixed the user issue but not really corrected Turbolinks behavior.

As pointed out by @domchristie in https://github.com/rails/rails/pull/23012#issuecomment-171804917, we can't make the default rails template application.js `async` or `defer` because [Turbolinks installs a handler of DOMContentLoaded](https://github.com/turbolinks/turbolinks/blob/af205f541c76fb01f6de7e1855362b888ba3c4e5/src/turbolinks/controller.coffee#L20), which may fire *after* Turbolinks execution if these attributes are used.

`async` and `defer` are really important attributes for front-end performance, and they're actually extremely compatible with how Turbolinks apps work. Since Turbolinks apps render HTML on the server, no Javascript is required to actually display the initial content, so it doesn't make sense that a simple Turbolinks app's JS bundle should block the browser HTML parser. Turbolinks should be designed to work well with `async` and/or `defer`.

A possible solution looks like checking [`document.readyState`](https://stackoverflow.com/questions/9237044/async-loaded-scripts-with-domcontentloaded-or-load-event-handlers-not-being-call) and I can open a PR to that effect if the maintainers agree that this looks like a solution.

**Comment by nateberkopec** [comment]
Hit enter too quickly on this, text above now reflects what I actually wanted to say :)

**Comment by Fudoshiki** [comment]
Any update?

**Comment by javan** [comment]
Sounds reasonable to me. I think a change like this would fix it:
```diff
--- a/src/turbolinks/controller.coffee
+++ b/src/turbolinks/controller.coffee
@@ -17,7 +17,10 @@ class Turbolinks.Controller
   start: ->
     if Turbolinks.supported and not @started
       addEventListener("click", @clickCaptured, true)
-      addEventListener("DOMContentLoaded", @pageLoaded, false)
+      if document.readyState is "loading"
+        addEventListener("DOMContentLoaded", @pageLoaded, false)
+      else
+        @pageLoaded()
```

**Comment by nateberkopec** [comment]
I'll throw a PR together.

**Comment by packagethief** [comment]
Gah,

**Comment by packagethief** [comment]
Oops, clicked close by accident!

**Comment by Fudoshiki** [comment]
Hello, any progress?

**Comment by kaspth** [comment]
@Fudoshiki feel free to volunteer the necessary PR if you're in a hurry 😉

**Comment by Fudoshiki** [comment]
I apologize, I'm in no hurry, just a solution for already there is above)

**Comment by nateberkopec** [comment]
Closed by ^^^^

**Comment by srghma** [comment]
the commit was reverted by https://github.com/turbolinks/turbolinks/commit/7a8c696ff84545ce0d50fab48065a39d784888f7 (why?)

turbolinks doesnt support async on https://github.com/turbolinks/turbolinks/commit/2a4a43bd79b9ecd50b45ca68b191a5ad10f01640
