### ISSUE TITLE
Turbolinks in a static site

### ISSUE THREAD

**Issue by Appwerks** [turbolinks/turbolinks#267]
Is it possible to use Turbolinks in a static site? I have not been able to make it work on even the simplest demo sites (three simples sites with a few links and some FPO content for testing) and don’t know if it’s due to something I am doing wrong/missing or because Turbolinks is not suitable for static sites.

You can check the demo site at https://turbolinksdemo.appwerks.com

The first page renders OK. Clicking on any of the links takes one to the appropriate page but there only output of an inline script is rendered (the sacript uses the text in the H1 tag that does not get rendered). Clicking on the back button does the same on the previous page but also brings up an infite loading indicator in the browser tab.

Thanks in advance for any feedback and insights you may be able to share.

**Comment by Appwerks** [comment]
Commenting out scripts in the body tag fixed the rendering issue so it appears that the inline scripts were the problem. I thought this issue was resolved prior to the final release.

**Comment by nateberkopec** [comment]
What were the inline scripts? Can you add them back to your demo page?

**Comment by Appwerks** [comment]
Give it a try now. I have removed them trying a few things to figure pout what the cause of the issue is.

**Comment by nateberkopec** [comment]
The behavior you're seeing [is the way `document.write` works](https://developer.mozilla.org/en-US/docs/Web/API/Document/write):

> Note: as document.write writes to the document stream, calling document.write on a closed (loaded) document automatically calls document.open, which will clear the document.

**Comment by Appwerks** [comment]
Ah, I see. I rewrote those scripts to not use ```document.write``` and now everything works correctly. Learned something today including the need to read Javascript documentation when I run into those issues.

Thanks a lot for helping me out. I really appreciate it.
