### ISSUE TITLE
How Do You Stop Videos from Playing Automatically?

### ISSUE THREAD

**Issue by hes63** [turbolinks/turbolinks#268]
Hello,

I'm brand new to writing code and I'm writing my first website.   I embedded a video on one page but every time the page loads the video plays automatically.  I want viewers to be able to view the video when they want to, not automatically.  This is not a YouTube video, it's one that I took myself.  Here's the code:

    <iframe src="../J3D%20Images/Siftex Video.m4v" width="275" height="175" alt="J3D Home Page Image" >

Any help that can be provided would be very appreciated.

Thank you

Hes63

**Comment by javan** [comment]
Use a [`<video>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video) instead of `<iframe>`. Media elements don't play automatically.
