### ISSUE TITLE
How to disable turbolinks in Rails 5? 

### ISSUE THREAD

**Issue by lauroengineer** [turbolinks/turbolinks#269]
I need to disable turbolinks in Rails 5 in a specific page.  Adding the fowling in the div tag `“data-no-turbolink”` is not working. 

Any suggestions?

**Comment by nateberkopec** [comment]
[The tag for disabling Turbolinks has changed in Turbolinks 5.](https://github.com/turbolinks/turbolinks#disabling-turbolinks-on-specific-links)

**Comment by lauroengineer** [comment]
Thanks @nateberkopec 

I tried adding `<%= link_to episode.title, episode, :"data-no-turbolink" => false %>` but on show view my script for my video is not loading. 

Am I missing something else?

**Comment by javan** [comment]
Change `"data-no-turbolink"` to `"data-turbolinks"`: `<%= link_to episode.title, episode, :"data-turbolinks" => false %>` (or `<%= link_to episode.title, episode, data: { turbolinks: false } %>` ).

**Comment by lauroengineer** [comment]
Thanks @javan, 

That was really helpful. Any idea how to the   `data: { turbolinks: false }` to a loop?

`<%= link_to episode do  data: { turbolinks: false }%>`

**Comment by lauroengineer** [comment]
Thanks for the help @javan 👍
