### ISSUE TITLE
page transition reloads favicons

### ISSUE THREAD

**Issue by grosser** [turbolinks/turbolinks#273]
```erb
<head>
<%= favicon_link_tag asset_path('favicon.svg'), type: 'image/svg' %>
...
</head>
```

now on every page transition this icon is loaded (can see it in the network tab)

I tried `, 'data-turbolinks-track': 'reload'` and `, 'data-turbolinks-permanent': true` without success ... even tried not rendering it when page was requested via turbolinks ... same result :(

<img width="801" alt="screen shot 2017-04-29 at 11 42 50 am" src="https://cloud.githubusercontent.com/assets/11367/25557938/fd899408-2cd0-11e7-9857-d23cfa4fe841.png">

**Comment by Fudoshiki** [comment]
https://github.com/turbolinks/turbolinks/issues/187

**Comment by grosser** [comment]
Yeah I saw that ... but wanted to make a separate issue since I thought my
usecase is more narrow / common.

**Comment by domchristie** [comment]
I think this is a browser bug. It could be related to URL changes via `history.pushState` or `history.replaceState`, triggering the browser to reload the favicon as hinted at on this [discourse thread](https://what.thedailywtf.com/topic/15725/discourse-url-changes-after-scroll-cause-the-browser-to-request-the-favicon-over-and-over-and-over-at-least-in-chrome).

I have managed to reproduce this with an SVG favicon, however, if it is a PNG, then it disappears from the list of requests in the Network tab altogether! 😖 (Chrome v69). Most bizarre, and unfortunately I don't think this is something that Turbolinks can fix 😞
