### ISSUE TITLE
JavaScript error breaks all other JS due to no page refreshes

### ISSUE THREAD

**Issue by gregblass** [turbolinks/turbolinks#277]
I've got a fairly large app that I just launched and there have been a couple of times where the client reached out to me because JS stuff wasn't working. They hit an error in my JS somewhere else, and then since there are no page refreshes using turbolinks, all other JS broke.

Has anyone successfully implemented something that will force a full page reload in the event of a JS error so that subsequent page JS is not broken?

I know that I should just fix the errors. Working on that (need some client side error notifications).

**Comment by grosser** [comment]
```
  window.onerror = function(msg, url, line, col, error) {
    ... reload the page ...
  };

```

**Comment by gregblass** [comment]
So thats a decent way to go about it, except that experience might be a bit jarring. I'd more ideally like to set a flag so that the next turbolinks page load becomes a full page load.

**Comment by gregblass** [comment]
Here's the solution I came up with:

```
// If a JS error occurs in the browser, the software can be left in 
// a bad state depending on how badly the JS console decides to crash.
// Subsequent errors can continue to be triggered because the page is
// never reloaded - so force a full page reload on the next page visit.

var jsErrorHasOccurred = false;

window.onerror = function() {
 jsErrorHasOccurred = true;
}

document.addEventListener("turbolinks:before-visit", function() {
  if (jsErrorHasOccurred == true) {
    var url = event.data.url;
    
    event.preventDefault(); // Cancel the turbolinks request
    window.location.href = url; // Do a regular page visit to clear the JS console
  }
});
```

**Comment by jhubert** [comment]
@gregblass I'm struggling to figure out where the `event` variable is coming from in that handler? Do you have a global event variable somewhere?

**Comment by packagethief** [comment]
@jhubert, it's relying on the global [`Window.event`](https://developer.mozilla.org/en-US/docs/Web/API/Window/event) property. I'm guessing this was an oversight (I've done it myself). The property should generally be avoided:

> You should avoid using this property in new code, and should instead use the Event passed into the event handler function. This property is not universally supported and even when supported introduces potential fragility to your code.
