### ISSUE TITLE
`turbolinks:load` event in deferred scripts no longer always trigger on page load in 5.0.1

### ISSUE THREAD

**Issue by RavenXce** [turbolinks/turbolinks#278]
The `turbolinks:load` event is now no longer firing in v5.0.1 during:

i. Initial page load
ii. After form submissions

## How to reproduce
1. Clone: https://github.com/RavenXce/turbolinks-defer - the app has been configured to do an alert on `turbolinks:load`
2. Go to `/`.
3. Note that _no_ alerts happen
4. Navigate to another page using the link (GET request)
5. Note that a load alert happens
6. Click form button (POST request)
7. Note that _no_ alerts happens

## Expected Result
`turbolinks:load` events (alerts) happen on every navigation event

## Actual Result
`turbolinks:load` events (alerts) happen only on normal GET navigation after the initial load

## Additional Notes

Locking the gem to `5.0.0` fixes the issue. See the [5.0.0 branch](https://github.com/RavenXce/turbolinks-defer/tree/5.0.0).

However, I had to lock `turbolinks-source` to `5.0.0` too - `5.0.1` is used otherwise which causes the issue to continue. (why? is this another issue?).

Probably relevant: https://github.com/turbolinks/turbolinks/commit/69d353ea73d10ee6b25c2866fc5706879ba403e3

**Comment by nateberkopec** [comment]
Thanks so much for providing some code. This is really complex behavior, so it's really hard to discuss in the abstract.

Unfortunately, your repro has the same actual result in 5.0.0 for all steps. I'm digging more into it now.

**Comment by RavenXce** [comment]
@nateberkopec do note my tailnote - I had to lock turbolinks-source too. Did you try that?

**Comment by nateberkopec** [comment]
Ha! I actually didn't. That's probably a bug too, probably should've changed the gemspec there. I'll open a separate issue.

OK, now I think I'm seeing what you're seeing! Finally! Digging in...

**Comment by javan** [comment]
Thanks for sample app, @RavenXce! It makes the issue pretty clear. If `turbolinks:load` event handlers are installed *after* turbolinks.js is required, they won't run on first page load `document.readyState` is not `loading` ([this condition](https://github.com/turbolinks/turbolinks/blob/63c02c7251e3a562dbd0c4aff2a38991cf5e71f6/src/turbolinks/controller.coffee#L23-L24)).

Installing the event handlers *before* turbolinks fixes it, e.g.:
```diff
--- a/app/assets/javascripts/application.js
+++ b/app/assets/javascripts/application.js
@@ -12,6 +12,6 @@
 //
 //= require jquery
 //= require jquery_ujs
-//= require turbolinks
 //= require globals
+//= require turbolinks
```

We're planning to revert the change in https://github.com/turbolinks/turbolinks/pull/274 and release v5.0.2 until we have a fully baked async solution for v5.1.0.

**Comment by nateberkopec** [comment]
> If turbolinks:load event handlers are installed after turbolinks.js is required, they won't run on first page load 

I think this also means the original PR doesn't really fix the desired behavior for `async` either, since if your event handlers are installed after Turbolinks is in included in your bundle, `turbolinks:load` already went off and you have nothing to attach to.

**Comment by javan** [comment]
Ok, [v5.0.2](https://github.com/turbolinks/turbolinks/releases/tag/v5.0.2) is out. This issue should be resolved.

@nateberkopec, yeah, I think `turbolinks:load` needs to be dispatched asynchronously still. Something like:
```diff
--- a/src/turbolinks/controller.coffee
+++ b/src/turbolinks/controller.coffee
@@ -21,7 +21,7 @@ class Turbolinks.Controller
       if document.readyState is "loading"
         addEventListener("DOMContentLoaded", @pageLoaded, false)
       else
-        @pageLoaded()
+        requestAnimationFrame(@pageLoaded)
```
Let's revisit down the road now that we better understand the problem.

**Comment by RavenXce** [comment]
@javan No problem, thanks for figuring it out & pushing the new version so quickly!
@nateberkopec Thanks for helping as well! 🍰

**Comment by nateberkopec** [comment]
@RavenXce No, thank *you* for the quick repro!
