### ISSUE TITLE
turbolinks:load and async script loading

### ISSUE THREAD

**Issue by SqueezedLight** [turbolinks/turbolinks#28]
Hi guys,
currently i'm trying to implement async script loading like that:
 ```
<%= javascript_include_tag 'application', async: true %>
```

It seems the ```turbolinks:load``` event does not fire on initial page load in this case. Everything works fine when navigating through pages. 
I have the following code in my ```application.js```:
```
document.addEventListener("turbolinks:load", function() {
  console.log("turbolinks:load fired!")
});
```

What am i missing?

Thanks a lot for your help.

**Comment by packagethief** [comment]
Hey @SqueezedLight --

Confirmed. Looks like this is because we fire the initial `turbolinks:load` event in response to `DOMContentLoaded`, which will likely already have fired by the time Turbolinks is loaded asynchronously.

If you need the initial load event you'll have to avoid using `async` for now.

**Comment by SqueezedLight** [comment]
Hi @packagethief 
Thanks for the confirmation. Good to hear it is not just me ;)

I'll try to work around this. Shouldn't be that hard... But i definitely wanna use async loading. I'll have a look what works in my case.

**Comment by nateberkopec** [comment]
@SqueezedLight You could try `defer`, which delays script execution until DomContentLoaded but also unblocks the document parser.

`defer` is supposed to execute scripts in order, but that behavior is buggy. Just treat `defer` as if it was `async` and don't count on order in the document guaranteeing execution order.

**Comment by SqueezedLight** [comment]
@nateberkopec YES, that did it. Very simple workaround. Thanks a lot for that hint!
