### ISSUE TITLE
<html> tag attributes

### ISSUE THREAD

**Issue by woto** [turbolinks/turbolinks#288]
Hi! Is there a way to change html tag attributes?
For example on some pages i want to use technique from Bootstrap 4 example to make sticky footer
https://v4-alpha.getbootstrap.com/examples/sticky-footer/

```
html {
  position: relative;
  min-height: 100%;
}
```

i wanted to add html#sticky and this css

```
html#sticky {
  position: relative;
  min-height: 100%;
}
```

but i'm unable to do this, because turbolinks doesn't reload html tag attributes. It will be cool if the are no limits in turbolinks to do this.
By the way, for now i made it with inline styling.
Thanks.

**Comment by domchristie** [comment]
Closing as this has been duplicated by #288
