### ISSUE TITLE
Clicking remote links on turbolinks cached pages before new page is loaded

### ISSUE THREAD

**Issue by johnam** [turbolinks/turbolinks#294]
I'm seeing that if a remote link is clicked on a turbolinks cached page after it is requested (navigating back to the page) and before turbolinks:load:

1. if the click is done early in the cycle, ajax:success event is triggered on the remote link, and the remotely loaded content is not displayed after turbolinks:load

2. if the click is done later in the cycle, ajax:success event is not triggered, and the remotely loaded content is displayed

I have a listener for ajax:success on document (loaded once on first page load) to act on the remotely loaded content. In the 2nd scenario, this fails because the ajax:success event is not triggered and the remotely loaded content is displayed.

Scenarios 1 and 2 occur for me with Chrome 58.0.3029.110 Sierra 10.12.5. In Firefox and Safari, I haven't seen the remotely loaded content being displayed (scenario 1, with clicks anytime during the cycle).

**Comment by domchristie** [comment]
I was not able to reproduce this. Are you still experiencing this issue?
