### ISSUE TITLE
Turbolinks not clearing cache

### ISSUE THREAD

**Issue by jonhue** [turbolinks/turbolinks#303]
I've got three issues.

**First case:**

In some cases I append notices and alerts to the page, those should obviously be removed from the cache. In order to do that I added the required line of JavaScript:

```js
function componentsNotificationsFlashModalHide() {
    setTimeout(function() {
        if ( $('.flash-modal.flash:not(.invisible):hover').length != 0 ) {
            componentsNotificationsFlashModalHide();
        } else {
            $('.flash-modal.flash:not(.invisible)').fadeOut(250);
            Turbolinks.clearCache();
        };
    }, 4500);
};
```

Essentially, when the notification fades out, the cache should get cleared, so the next visit will fetch a new version of the page from the server.
Instead, the cached version remains as the notification does whenever coming back to the page, until I issue a full reload of the page manually.

---

**Second case:**

In my app the root template exists in two states on two separate templates and controllers depending on whether the user is signed in or not. I tried to prevent any problems by appending ...

```haml
%meta{ name: 'turbolinks-cache-control', content: 'no-cache' }
```

... to both document's head's.
Still, whenever a user signs in and visits the root document, the wrong version is being displayed and vice versa. 

---

**Third case:**

In some cases after signing in (and getting redirected to the previous or root url) the server issues an additional redirect from the page the user lands on. 

So for example a userflow could look like:
```
root_url -> login_url => root_url =!> some_other_url

-> manual
=> redirect
=!> redirect which is not working
```

That's clearly turbolinks related. After issuing a redirect manually, the server immediately redirects the user to `some_other_url`.

---

*Rails version: 5.1.0.rc2*

**Comment by javan** [comment]
> **First case**

`Turbolinks.clearCache()` won't prevent the current page from being cached. It clears any previously cached pages, and pages aren't cached until just before navigate away from them.

Instead, use the `turbolinks:before-cache` event to reset your flash messages. Something like:

```js
document.addEventListener("turbolinks:before-cache", function() {
   $(".flash-modal.flash").remove()
})
```
See https://github.com/turbolinks/turbolinks#preparing-the-page-to-be-cached

> **Second case**, **Third case**

How are you performing redirects? Standard `redirect_to` in your controllers? I would try adding some Rails logging to record what redirects are being issued and what templates are rendered.

If you can create a minimal example app to share, we may be able to help more.

**Comment by jonhue** [comment]
@javan What you suggested seems not to work. It just caches everything regardless. 

Furthermore, I got an **additional case**:

When clicking a link with `remote: true` and `method: :put`, it appears that turbolinks responds automatically without providing a template for that specific format with:

```js
Turbolinks.clearCache()
Turbolinks.visit("http://lvh.me:3000/", {"action":"replace"})
```

But instead of reloading the page, it fetches the cached version which in this case cannot be intended. 

---

I will start working on an example app, to help fix these problems.

**Comment by arpit016** [comment]
@jonhue I am also facing this issue, I submit a form with `remote: true` and `method: :post`, and since no JS template have been defined Turbolinks responds exactly like you mentioned. But nothing gets changed on the page and it shows the cached version only. 

Did you find any solution to it?

**Comment by domchristie** [comment]
@jonhue are you still experiencing this?
