### ISSUE TITLE
Proposal: Annotate pages for full page reloads

### ISSUE THREAD

**Issue by javan** [turbolinks/turbolinks#311]
There are some 3rd party JavaScript libraries that simply do not play well with Turbolinks. Google's API client, for example, holds on to `gapi` singletons that rely on dynamically created `<iframe>`s, and after TL-navigating the singletons still exists but the `<iframes>` are gone, which results in erorrs. jQuery UI's date picker is another example: https://github.com/turbolinks/turbolinks/issues/253#issuecomment-289101048.

To that end, I'd like to propose a new `<meta>` tag for opting *in* to full page reloads. You can already hack this behavior together by adding a unique, tracked, head element like: 
```html
<meta name="foo" content="[something unique]" data-turbolinks-track="reload">
```

I'd like to see a more intention revealing tag like:
```html
<meta name="turbolinks-page-control" content="reload">
```

This idea stems from https://github.com/basecamp/google_sign_in/commit/3388a4b0d2c3e9af16895f4b42bb71c33e7136e4, which fixed https://github.com/basecamp/google_sign_in/issues/4.

**Comment by henrik** [comment]
Example of this: https://github.com/turbolinks/turbolinks/issues/321#issuecomment-330685212

**Comment by brendon** [comment]
This is kind of related I think: https://github.com/turbolinks/turbolinks/issues/191
