### ISSUE TITLE
data-turbolinks-permanent and cache: flash of wrong content

### ISSUE THREAD

**Issue by jemminger** [turbolinks/turbolinks#314]
I've got a counter element in my app, which can be dynamically updated via js.  The element always starts out empty in the dom, then on page load it is updated with the current count from localStorage.

When I navigate to other pages, everything seems fine until the current count in localStorage changes.  Navigation to other pages will then show the last value, then the current value after it is updated via js.

I see the same behavior whether the counter element has the "data-turbolinks-permanent" attr or not.

What I want is for TL to ignore the counter element and let me control its display and content manually.  Is this possible?

**Comment by jemminger** [comment]
Currently I've found a workaround: Hide the counter element in the before-cache event, and restore its visibility as needed on load.

**Comment by Spone** [comment]
Hi Jeff, have you tried using the [Persisting Elements Across Page Loads](https://github.com/turbolinks/turbolinks#persisting-elements-across-page-loads) feature for this?

**Comment by jemminger** [comment]
@Spone Yes, with or without the `data-turbolinks-permanent` attr it was still happening.

**Comment by jemminger** [comment]
No `id` on the element.  Is that necessary?

**Comment by domchristie** [comment]
Yes:

> Designate permanent elements by giving them an HTML `id` and annotating them with `data-turbolinks-permanent`.
> https://github.com/turbolinks/turbolinks#persisting-elements-across-page-loads
