### ISSUE TITLE
Turbolinks does not ignore formats where it should not inject itself

### ISSUE THREAD

**Issue by codeodor** [turbolinks/turbolinks#315]
I recently upgraded an app from Rails 4.2 to 5.1.  I have a link that look like this:

```
 <%= link_to "Print Labels",
            contacts_path(params.except(:action, :controller, :id).merge(location_id: location, format: 'pdf')),
            :class => 'btn btn-default' %>
```

The link takes the current params and sets the format to PDF to generate the link.

Prior to the upgrade, this worked fine. 

After the upgrade, Turbolinks is intercepting the link and trying to send this request via XHR, which means the request headers won't allow PDF as a response, so it shows gibberish in the browser window instead of downloading the PDF.

My guess is that the prior version was noticing the format was not one that Turbolinks should handle, and automatically excluding itself, and that now, it no longer does that.

I added `data: { turbolinks: false }` to the link, and it works again, but I thought you'd like to know about this regression.

**Comment by codeodor** [comment]
Note that I made a large jump in Turbolinks versions: from 2.4.0 to 5.0.1, so this regression could have happened any time in between.

**Comment by codeodor** [comment]
I see https://github.com/turbolinks/turbolinks/blob/master/src/turbolinks/location.coffee#L37 is looking at the extension.

So maybe the issue is in Rails, where it is not making the extension correct based on my passing the `:format` key into the path helper?

**Comment by packagethief** [comment]
That's what I was just going to ask, @codeodor. Does the URL as rendered end in ".pdf"?

**Comment by codeodor** [comment]
No, it sure doesn't. I'll open an issue over there.
