### ISSUE TITLE
Signature different on redirect

### ISSUE THREAD

**Issue by brandonhilkert** [turbolinks/turbolinks#318]
I've been digging in to a really weird issue and tracked it down to the `reload` setting for asset changes. 

The issue started out as a flash message not appearing some of the time when being redirected to a credit card page as a result of a `before_action` in a controller. When I removed `'data-turbolinks-track' => 'reload'` from the js and css tags, it worked as expected.

Digging deeper, I was finding that the credit page was being loaded twice. [Another GH issue with similar behavior](https://github.com/turbolinks/turbolinks/issues/204) mentioned a potential asset change. We have a single manifest for JS and CSS, so I didn't think it was that, but it certainly exhibited the behavior as if they were the different.

I loaded the Turbolinks source in to our Rails app and threw some debugging in. At the [point where the head signatures are compared](https://github.com/turbolinks/turbolinks/blob/master/src/turbolinks/snapshot_renderer.coffee#L32), i printed the current and new head signature. 

We have about 50 lines in there, but the only difference is:

Current:

```
<script src="/assets/jquery.self-bd7ddd393353a8d2480a622e80342adf488fb6006d667e8b42e4c0073393abee.js?body=1" data-turbolinks-track="reload" style="">
```

New:
```
<script src="/assets/jquery.self-bd7ddd393353a8d2480a622e80342adf488fb6006d667e8b42e4c0073393abee.js?body=1" data-turbolinks-track="reload">
```

Notice the presence of the `style=""` attribute in the current. Oddly, when I load the login page (the page where this whole thing starts), it doesn't have that `style=""` attribute.

I have no idea where it's coming from, but it's definitely causing things to be reloaded. Clearly, Turbolinks is doing the right thing by invalidating and doing a full page reload, so I'm not sure this is bug here, but was hoping given your experience with Rails, someone could pinpoint where this could be happening.

I could remove the `reload` attribute on the asset tags, but I'd prefer to keep it on in case we add different asset manifests in the future.

Thanks!

**Comment by packagethief** [comment]
Great diagnosis. But wow, I have no idea what could be adding a `style` attribute to the script tag!

To debug, you could try using a `MutationObserver` on the `<script>` element and watching it for attribute changes:

```javascript
observer = new MutationObserver(function(mutation) {
  console.log(mutation)
})

element = document.head.querySelector("script[data-turbolinks-track]")
observer.observe(element, { attributes: true })
```

This might help you pinpoint where it's happening.

**Comment by javan** [comment]
`<script src="/assets/jquery.self-...js?body=1" data-turbolinks-track="reload" style="">`

Do your script tags have closing `</script>`s? Could be something funky with unclosed or mismatched tags in your `<head>`.

> We have about 50 lines in there

Does that mean you have 50 `<script>`/`<style>` tags? You could try removing most of your scripts (leaving Turbolinks in of course) and see if the problem persists. If it doesn't, start adding them back in until that `style` attribute returns.

**Comment by brandonhilkert** [comment]
The 50 script tags was just due to the js files listed in the manifest that the dev environment will load individually in the view:

The layout:
```
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
```

Enumerating each file with fingerprint:

<img width="1277" alt="screen shot 2017-08-31 at 4 34 44 pm" src="https://user-images.githubusercontent.com/744212/29951540-588f4d80-8e91-11e7-9337-e6a6f73cda69.png">

I removed every JS file but these:

```js
//= require jquery
//= require jquery_ujs
//= require turbolinks/index
```
And it still happens. I added the Mutation Observer and sure enough, there's 2 of them to the script tag:

<img width="902" alt="screen shot 2017-08-31 at 9 17 07 pm" src="https://user-images.githubusercontent.com/744212/29951598-c28757d2-8e91-11e7-801e-0c2c958647d8.png">

Is there a way to get a reference to the script that caused the mutation? I might be veering outside of my pay grade ;)

**Comment by brandonhilkert** [comment]
When I view source on page load:

```
<link rel="stylesheet" media="all" href="/assets/application.self-2c5b223e03c87a775f3ce1cefbbef5efb996d3f2fba00d3fef3c5ba270445ed6.css?body=1" data-turbolinks-track="reload" />
<script src="/assets/jquery.self-bd7ddd393353a8d2480a622e80342adf488fb6006d667e8b42e4c0073393abee.js?body=1" data-turbolinks-track="reload"></script>
<script src="/assets/jquery_ujs.self-784a997f6726036b1993eb2217c9cb558e1cbb801c6da88105588c56f13b466a.js?body=1" data-turbolinks-track="reload"></script>
<script src="/assets/turbolinks/index.self-c6487a013ba2ab560b57e92892f3246d6d669221d0225ac361c86f77b348a831.js?body=1" data-turbolinks-track="reload"></script>
<script src="/assets/turbolinks/helpers.self-4fe08e3b2f8ed06140c1926f93a4a382de0d15716894660576efe83d3843798e.js?body=1" data-turbolinks-track="reload"></script>
<script src="/assets/turbolinks/location.self-d2d4716f0b0603083a9134dd30904393037136a6eccf18ae7f87a980d5f2fb9f.js?body=1" data-turbolinks-track="reload"></script>
```

But viewing in chrome dev tools:

<img width="893" alt="dom" src="https://user-images.githubusercontent.com/744212/29951834-5d3b9198-8e93-11e7-8b54-ebce430e0d5c.png">

So something is definitely adding it after the fact, as the MutationObserver shows above.

**Comment by brandonhilkert** [comment]
Found it. We have google maps in our head:

```
    <script type="text/javascript" src="//maps.googleapis.com/maps/api/js?libraries=places&key=<%= Rails.application.secrets[:google_maps_browser_key] %>"></script>
```

Removing it fixes the issue. So dumb.

**Comment by brandonhilkert** [comment]
Interestingly...when I look in production, it appears to do this to the first `script` tag in the head:

<img width="925" alt="prod" src="https://user-images.githubusercontent.com/744212/29952408-2d8777f6-8e97-11e7-9b92-0134541c04db.png">

It just so happens in dev, the `application.js` `script` tag is the first one, so it adds it to that.
