### ISSUE TITLE
Think turbolinks is causing issue with Amazon ads

### ISSUE THREAD

**Issue by Adeering** [turbolinks/turbolinks#320]
Im trying to integrate amazon affiliate ads into my rails 5 app using turbolinks and I think the embedded script is conflicting with turbolinks...unfortunately there are no errors being thrown so not 100% sure but everything seems to be pointing towards it.  So here is the script that is added to my page:

```
<div class="row ad-row">
      <% equipment = @recipe.equipment_list.present? ? raw(@recipe.equipment_list.map{|equipment| equipment}.join(", ")) : "cookware" %>
      <script type="text/javascript">
        amzn_assoc_placement = "adunit0";
        amzn_assoc_search_bar = "true";
        amzn_assoc_tracking_id = "livingrecipe-show-recommendation-20";
        amzn_assoc_search_bar_position = "bottom";
        amzn_assoc_ad_mode = "search";
        amzn_assoc_ad_type = "smart";
        amzn_assoc_marketplace = "amazon";
        amzn_assoc_region = "US";
        amzn_assoc_title = "Shop Required Equipment";
        amzn_assoc_default_search_phrase = '<%= escape_javascript(equipment) %>';
        amzn_assoc_default_category = "All";
        amzn_assoc_linkid = "78aa42b54ebf16f31c5239f132e3d7a0";
        amzn_assoc_rows = "1";
      </script>
      <script src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US"></script>
    </div>
```
When the page loads this is what the element looks like when I inspect it in the browser:
![capture](https://user-images.githubusercontent.com/3308735/30295659-32c91fc8-96f6-11e7-99d4-d5cc5ab05d6d.PNG)
So it seems to generate a div element but doesnt fill it with anything.

**Comment by snex** [comment]
I am having the same issue, although I do get a console error and no div is generated. Error is

>Error : adType is not defined
>  render @ onejs?MarketPlace=US:1`

**Comment by abdennour** [comment]
Any news?

**Comment by domchristie** [comment]
Some third-party libraries don't play nicely with Turbolinks, particularly if they rely on `DOMContentLoaded` to initialise. It's difficult to tell in this case, but if the Amazon Affiliate Ads API provides a way to manually initialise the ads (rather than adding the two `<script>` elements), then that might be something to investigate.
