### ISSUE TITLE
Turbolinks redirects with anchors

### ISSUE THREAD

**Issue by jeffreyguenther** [turbolinks/turbolinks#323]
I’m in the midst of working on a client app and am noticing something strange and can’t figure it out.

**Scenario** 1
Visit /articles/1

1. Click link that goes to /blocks/new
2. In the controller redirect to /articles/1#block_1

In this case, the viewport is not scrolled to the newly created block and the HTML for the block is on the page.

**Scenario 2**
1. Visit /articles/1
2. Click link that goes to /blocks/1/edit
3. In the controller redirect to /articles/1#block_1

In this case, the viewport is scrolled to the block_1.

I can’t figure out why we’re seeing this behaviour. Is it possible that Turbolinks uses the old /articles/1 from the cache when responding to the redirect in the new case and because the anchor doesn’t exist until the new page is retrieved, it doesn’t update the scroll position?

If I add the data-turbolinks=“false” to the new link, the viewport is scrolled as expected. This leads me to think Turbolinks affects the viewport positioning on redirect. Is that true?

**Comment by domchristie** [comment]
Just to clarify:

1. when you visit `/blocks/new` do you then `POST` a form which creates a new block, then redirects to `/articles/1#block_1`?
2. if so, are you submitting the form via XHR?
3. are you using Ruby on Rails?

(I have created a demo app (where all the answers to the above are "yes", and cannot reproduce the issue.)

**Comment by jeffreyguenther** [comment]
Yes, I'm using Ruby on Rails (4.2.9).
The link to `blocks/new` makes a GET request with a single param.

```
  def new
    page = UserContent::UserContent.find(params[:content_id])

    block = ::Blocks.seed_by_name(page, params[:type], page.blocks.count)

    redirect_to content_path(page, dom_id(block))
  end
```
Should I be using `create` and and POST request instead?

**Comment by domchristie** [comment]
Aha, I see :)

turbolinks-rails will clear the Turbolinks cache on a redirect, after a non-GET request (see: https://github.com/turbolinks/turbolinks#redirecting-after-a-form-submission and https://github.com/turbolinks/turbolinks-rails/blob/master/lib/turbolinks/redirection.rb).

> Should I be using create and and POST request instead?

I suppose that would be more Rails-y given that it creates a new record … and it will also solve your Turbolinks caching issue 🎉. `link_to 'New Block', blocks_path, method: :post` should do the trick (which requires JS to create and submit a form). `button_to 'New Block', blocks_path` will work without JS.

Hope that helps.

**Comment by jeffreyguenther** [comment]
Thank you, sir! I'll verify this work on Monday and close the issue afterward. Thank you for your help!

**Comment by jeffreyguenther** [comment]
Using a non-GET request does this trick! Thank you for the guidance!
