### ISSUE TITLE
Rails partial js.haml rendered as plain text

### ISSUE THREAD

**Issue by iamonkara** [turbolinks/turbolinks#327]
Using *Turbolinks 5.0.1* on existing *Rails 5.1.4* app

I am stuck on a this problem for a full day now. I have `form` with attribute `remote: true` being submitted to a url `/app/do-something.js` the controller sends a response using the following block

```ruby
          respond_to do |format|
           format.js {
             render  partial: "somewhere/something", status: :ok , locals: {var1: "abc"}
           }
          end

```
the file `somewhere/something.js.haml` has javascript content, like so 
```javascript
:plain
  alert("This alert should be shown");
```
instead of the alert pop-up being rendered plain text `alert("This alert should be shown");` is rendered in browser i.e. javascript evaluation does not happen.

If I disable Turbolinks everything works fine. Any idea what I might be doing wrong?

FYI, I am tempted to use the workaround relying on websockets to send the javascript back and evaluate on client side, but it seems like an overkill.

**Comment by iamonkara** [comment]
FYI,  I am tempted to use the workaround relying on websockets to send the javascript back and evaluate on client side, but it seems like an overkill.

**Comment by iamonkara** [comment]
Update:

I have tried to set request headers on `turbolinks:request-start` event but it **doesn't seem to be fired** 

```javascript
(document).on("turbolinks:request-start", function(event) {
  alert("turbolinks:request-startED");
  var element = $(event.target);
  var xhr = event.data.xhr;
  if(element.attr("id") == "sharing_critical_info"){
    console.log("Request Header --> ",xhr.getRequestHeader());
    xhr.setRequestHeader("Accept", "text/javascript")
  }
});
```

I even tried with `document.addEventListener("turbolinks:request-start", function(event) {` but still nothing.

**Comment by domchristie** [comment]
I have tried to reproduce your situation with a new Rails app, but have been unable to do so. I have used the following:

**posts/_form.html.erb**
```erb
<%= form_with(model: post) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title, id: :post_title %>

  <%= form.label :body %>
  <%= form.text_area :body, id: :post_body %>

  <%= form.submit %>
<% end %>
```

**posts_controller.rb**
```rb
  def create
    @post = Post.new(post_params)
    respond_to do |format|
      format.js { render partial: 'posts/foo', status: :ok , locals: {var1: "abc"} }
    end
  end
```

**posts/_foo.haml.js**
```
:plain
  alert("This alert should be shown");
```

Are you able to post a demo of the broken behaviour?

**Comment by iamonkara** [comment]
@domchristie Thanks for chiming in. Here is the mini app to demo the problem https://github.com/iamonkara/turbolinks-rails-js-problem 

the main difference is 

* `form_tag` with `remote: true, format: :js` and 
* form is submitted using javascript `form.submit()`

the problem is still javascript not evaluated by browser and rendered as plain text. Looking at the request headers I see this

`Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8` 
clearly `text/javascript` is absent **I think this is because of Turbolinks??**

**Comment by domchristie** [comment]
> form is submitted using javascript form.submit()

It seems that `form.submit()` is not guaranteed to trigger `onsubmit`, meaning that the form submission may not be intercepted and sent via XHR. I think your best option is to trigger a submit event using the `fire` method in rails-ujs.

```js
Rails.fire(form, 'submit')
```

(via https://github.com/rails/rails/issues/29546#issuecomment-313981539)

**Comment by iamonkara** [comment]
@domchristie Thanks for that excellent pointer. It not only works but is more elegant than `$.ajax` option which I ended up using as a workaround.
