### ISSUE TITLE
Turbolinks.reload()

### ISSUE THREAD

**Issue by enatividad** [turbolinks/turbolinks#329]
Please make a method that behaves just like window.location.reload() which would likewise:
- reload the current document
- preserve the current state of the current document (scroll position, etc.)
- not create a new entry in the history

but wouldn't have to:
- re-run all javascript code (because it isn't a full page reload)
- make the user look at the page being rendered from scratch

and ideally would:
- clear the current page cache via Turbolinks.clearCache()

This can be useful for a use case like this:
- An activate/deactivate user button is present in a "user list" page. When the button is clicked, the button should change in both color and text. If the deactivated user is at the bottom part of the page, Turbolinks.reload() would automatically scroll down to the same location, without flashing the cache of the current page.

You don't have to do this, but I might as well give "asking for a feature a shot". Thanks in advance!

**Comment by javan** [comment]
You can do `Turbolinks.visit(window.location)` to "reload" the current page.

**Comment by domchristie** [comment]
To preserve the scroll position, and prevent creating a new history entry, you could try the following:

```js
;(function () {
  var scrollPosition
  
  document.addEventListener('turbolinks:load', function () {
    if (scrollPosition) {
      window.scrollTo.apply(window, scrollPosition)
      scrollPosition = null
    }
  }, false)
  
  Turbolinks.reload = function () {
    scrollPosition = [window.scrollX, window.scrollY]
    Turbolinks.visit(window.location, { action: 'replace' })
  }
})()
```

To prevent the page from flickering as it scrolls from the top to the desired position, add the `no-preview` cache directive in the page's `head`:

```html
<meta name="turbolinks-cache-control" content="no-preview">
```

**Comment by domchristie** [comment]
Closing as solved

**Comment by aksharj** [comment]
@domchristie / @javan ,

i am trying to use `Turbolinks.visit(window.location)` but it does not seem to work and page does not reload. 

It works if i provide a different page url in the application.

any ideas on what I could be missing?

Thanks.

**Comment by sj26** [comment]
I find `Turbolinks.visit()` will refresh the current page
