### ISSUE TITLE
how to use this with a message bus?

### ISSUE THREAD

**Issue by vesper8** [turbolinks/turbolinks#339]
I've been using this for a few weeks and all works well, but there was this one problem that was really stumping me

Tonight I spent an hour debugging it and found out what was happening.

In my vue application I use a message bus. So in a few places I have these ```Bus.$on('this_and_that')``` listeners and in other parts of my app I have ```Bus.$emit('this_and_that')```. I have dozens of these scattered through my app.

I was noticing that using turbolinks and vue-turbolinks, everytime I would visit a new page.. anything emitted to one of my Bus listeners would fire 2, 3, 4 etc times.. everytime I loaded a new page it would fire these events one extra time

In retrospect I see this makes sense.. although **I thought I read somewhere that when the Vue teardown occurred the listeners were destroyed**? not in my case I guess

I really struggled to find the correct way to prevent this from happening. I needed something that was the opposite of turbolinks:load. I wanted to attach the ```Bus.$on``` listeners only the first time my vue app was loaded (I have the same vue app on every page of my site)

I couldn't figure it out so I hacked something up. I simply used vuex to store the number of "page loads" which is initialized to 0, then on one of my top components in a beforeDestroy hook I increment the pageLoads state in the vuex store

And finally, I wrapped my ```Bus.$on``` calls with ```if(this.pageLoads === 0) { ... } ``` so it only happens on the very first load

This is suuper ugly.. and worse I had to wrap like 25 ```Bus.$on``` calls with this ugliness

**What am I doing wrong here?? what was I supposed to do?**

**Comment by javan** [comment]
Have you seen https://github.com/turbolinks/turbolinks/wiki/VueJs-and-Turbolinks?

**Comment by vesper8** [comment]
yes and I've been using vue-turbolinks from day one

**Comment by cannikin** [comment]
I'm using Vue as well, but not as a single-page app, it just controls a subset of the page: one user can leave notes about another. When the note function is clicked a little pane slides in from the side and the content of that pane is all handled by Vue. When that pane opens I subscribe to some MessageBus events and then when the pane is removed OR the user navigates away I unsubscribe.

For page navigation I listen for `turbolinks:before-cache` which is fired when Turbolinks is about to go to another page. In there I `MessageBus.unsubscribe('/notes')`, delete any event handlers that were added, cleanup the DOM and finally call `$destroy()` on my Vue instance. 

For the user manually closing the notes pane I added a callback to that same logic above.

So, I can open/close the notes pane multiple times, or go back/forward in the browser and everything subscribes/unsubscribes as it should.

**Comment by domchristie** [comment]
> I needed something that was the opposite of turbolinks:load

As @cannikin mentions, `turbolinks:before-cache` is the event you're after.

I'm not familiar with Vue, but I use a similar events/message bus system, and it sounds like my approach is similar to that of @cannikin's: each of my components has a `destroy` method which tears down any event listeners. Then on `turbolinks:load` call destroy on all the active components.
