### ISSUE TITLE
Writing a library to support both turbolinks classic and new

### ISSUE THREAD

**Issue by justin808** [turbolinks/turbolinks#34]
Is there any harm in setting the data-turbolinks-track when using Turbolinks 5?

Better to omit it for Turbolinks 5?

```erb
   <%= env_stylesheet_link_tag(static: 'application_static',
                               hot: 'application_non_webpack',
                               media: 'all',
                               'data-turbolinks-track' => true)  %>

     <%= env_javascript_include_tag(static: 'application_static',
                                    hot: 'application_non_webpack',
                                    'data-turbolinks-track' => true) %>
```

**Comment by justin808** [comment]
OK -- I see this is still in Turbolinks 5:

## Reloading When Assets Change

Turbolinks can track the URLs of asset elements in `<head>` from one page to the next, and automatically issue a full reload if they change. This ensures that users always have the latest versions of your application’s scripts and styles.

Annotate asset elements with `data-turbolinks-track="reload"` and include a version identifier in your asset URLs. The identifier could be a number, a last-modified timestamp, or better, a digest of the asset’s contents, as in the following example.

```html
<head>
  ...
  <link rel="stylesheet" href="/application-258e88d.css" data-turbolinks-track="reload">
  <script src="/application-cbd3cd4.js" data-turbolinks-track="reload"></script>
</head>
```

Note that Turbolinks will only consider tracked assets in `<head>` and not elsewhere on the page.

**Comment by packagethief** [comment]
Right, but note that in Turbolinks 5 the attribute value must be "reload".
