### ISSUE TITLE
Rails installation: a simple question

### ISSUE THREAD

**Issue by knzudgt** [turbolinks/turbolinks#35]
In the installation section it is suggested to Include `dist/turbolinks.js` in the application’s JavaScript bundle. What a 'JavaScript bundle' is?
I need turbolinks for a `Ruby on Rails` application. Is the above requirement also necessary for Rails or should I instead refer only to the 'Rails integration' section?

**Comment by packagethief** [comment]
Hey @knzudgt. For a Rails app you can just use the Rails installation instructions.

Sorry for the confusion–"JavaScript bundle" is a bit obscure. It refers to the collection of JavaScript, often concatenated by a build system, that you include in your pages. A build system isn't necessary, of course, and for non-Rails apps you can just include `turbolinks.js` as usual with a `<script>` tag.
