### ISSUE TITLE
Turbolinks is not defined error (in 5.1)

### ISSUE THREAD

**Issue by dwightwatson** [turbolinks/turbolinks#352]
I've just upgraded my app to Turbolinks 5.1 and I believe I've identified an issue when loading Turbolinks as a module (rather than through the traditional asset pipeline). I created a fresh Rails app with Webpacker and was able to easily reproduce the issue as well.

Here's the error showing in the console...

![image](https://user-images.githubusercontent.com/1100408/34700054-e9f6f4da-f534-11e7-8a9d-2d4264169e15.png)

Clicking through to the source seems to indicate that the error is occurring inside Turbolinks, rather than any issue with application-level code.

![image](https://user-images.githubusercontent.com/1100408/34700062-f33d9896-f534-11e7-903d-68e4872d4e1b.png)

Here's how I'm loading Turbolinks in my application, but I've tested the `require()` style code listed in the README and I experience the same issue.

```js
import Turbolinks from 'turbolinks';

Turbolinks.start();
```

**Comment by dwightwatson** [comment]
If it helps - when I lock on to `5.0.3` in my `package.json` (leaving the gem version on `5.1.0`) then it goes back to working as expected.

**Comment by javan** [comment]
Shoot, sorry about that! I've identified the problem and will publish another release tomorrow.

**Comment by javan** [comment]
I just published v5.1.1 to npm with a fix
