### ISSUE TITLE
Could we have a changelog?

### ISSUE THREAD

**Issue by henrik** [turbolinks/turbolinks#353]
Turbolinks 5.1 was just released, and it would have been super helpful to see a changelog.

I looked at the commit list, which also works, of course, but is a bit lower-level.

I think it'd be completely fair to introduce one from now on, without having to invest the time in filling it in for every version going back. The community could always contribute that after the fact, if there is a demand.

What do you think?

**Comment by sstephenson** [comment]
There’s a high-level changelog for each release on the Releases page: https://github.com/turbolinks/turbolinks/releases

**Comment by henrik** [comment]
@sstephenson Thank you! I looked for the "Releases" page but mistakenly assumed it would be in the top tab bar.

**Comment by sstephenson** [comment]
I would welcome a PR that links to the Releases page in the readme :)

**Comment by henrik** [comment]
Yeah, I was just thinking about PRing a CHANGELOG.md that links to the Releases page – I think I've seen that before, and it might be easier to spot than a link in the README itself :)
