### ISSUE TITLE
Safari standalone Webapps

### ISSUE THREAD

**Issue by cseelus** [turbolinks/turbolinks#357]
I don't know if a fix for this is within the scope of Turbolinks, but wanted to report it anyhow:

Within a Turbolinks enabled Rails app that is used as a Safari standalone webapp, links where `turbolinks="false"` is set will open in Safari, when they should open inside the standalone Safari webapp.

This can be mitigated with [a little bit of JavaScript](https://gist.github.com/kylebarrow/1042026#gistcomment-2250553).

**Comment by domchristie** [comment]
Thanks for the tip!
