### ISSUE TITLE
Sprockets::FileNotFound, couldn't find file 'turbolinks' with type 'application/javascript'

### ISSUE THREAD

**Issue by bbtdev** [turbolinks/turbolinks#358]
Hello,
https://gist.github.com/bbtdev/ac7aeb2a4c0facf03efcb50efd6cf43d

This is a json api, and I am adding some functionality back, but this issue I can figure it out, since the gem is installed
bundle info turbolinks
 * turbolinks (5.1.0)
        Summary: Turbolinks makes navigating your web application faster
        Homepage: https://github.com/turbolinks/turbolinks
        Path: /home/bogdan/.rvm/gems/ruby-2.5.0/gems/turbolinks-5.1.0

Thank you

**Comment by packagethief** [comment]
Hey @bbtdev. Looks like you also have `gem 'jquery-turbolinks'` in your Gemfile. You'll need to [remove that for Turbolinks 5](https://github.com/kossnocorp/jquery.turbolinks/issues/56).
