### ISSUE TITLE
How to redirect?

### ISSUE THREAD

**Issue by SaphiLC** [turbolinks/turbolinks#359]
im using php, i set the header header('Turbolinks-Location:' $url); i get a 302 response from that route, but i either get a redirect loop or i get the new page but the url is the "transition" route, not sure how to say it :S

i tried with "redirect_to" (url/language/en(or es or others)?redirect_to=/route), the language gets changed and shows in the page but the url stays as url/language/en?redirect_to=/route instead of url/route :(

**Comment by SaphiLC** [comment]
looks like using 
```
<a data-turbolinks-action href=
```
gives the output im looking for, but not sure if thats the correct way of doing it (?)

**Comment by SqueezedLight** [comment]
Maybe this is related? #362 
It may have to do with the http status codes of the server responses.

**Comment by domchristie** [comment]
This has been clarified in the README as of https://github.com/turbolinks/turbolinks/pull/415.
