### ISSUE TITLE
Option to set the cache size

### ISSUE THREAD

**Issue by mintuhouse** [turbolinks/turbolinks#36]
I didn't want to use the cache option as it is taking more time to debug the two renders (one from cache and other normal). It would be good to have an option similar to `Turbolinks.pagesCached(size)` to restrict the size.

**Comment by mintuhouse** [comment]
I am currently using below hackish way to achieve the same, if anyone wants to set it before the option is available 
````
Turbolinks.Controller.prototype.clearCache = function() {
  return this.cache = new Turbolinks.Cache(requiredSize); // requiredSize == 0 in my case
}
Turbolinks.clearCache();
````

**Comment by sstephenson** [comment]
Do you really want to adjust the cache size? Or do you just want to turn it off entirely?

**Comment by mintuhouse** [comment]
I wanted to turn it off entirely to check if an issue I was facing was because of pages being cached.

**Comment by sstephenson** [comment]
OK. Closing this for now.

In the next release, you’ll be able to opt out of caching on a per-page basis using a `<meta>` tag:

```html
<meta name="turbolinks-cache-control" content="no-cache">
```

See #8 for details.

**Comment by mibamur** [comment]
+1
