### ISSUE TITLE
Help Crunch live agent support chat not working with turbolinks 

### ISSUE THREAD

**Issue by usama-ashraf** [turbolinks/turbolinks#360]
I'm working on a project using rails 5 and turbolinks 5 ,i have integrated HelpCrunch live agent chat,its not working with turbolinks page change.

**Comment by SqueezedLight** [comment]
So what is the problem? See here for guidelines on reporting issues: https://github.com/necolas/issue-guidelines/blob/master/CONTRIBUTING.md#bugs

Without more informations it may be better to close here...?

**Comment by shiroyaspandiar** [comment]
<script type="text/javascript">
  (function(w,d){
    w.HelpCrunch=function(){w.HelpCrunch.q.push(arguments)};w.HelpCrunch.q=[];
    function r(){var s=document.createElement('script');s.async=1;s.type='text/javascript';s.src='https://widget.helpcrunch.com/';(d.body||d.head).appendChild(s);}
    if(w.attachEvent){w.attachEvent('onload',r)}else{w.addEventListener('load',r,false)}
  })(window, document)
  </script>

  <script type="text/javascript">
    var user = user;
    var custom_data = custom_data;
    HelpCrunch('init', 'PROJECT_NAME', {
      applicationId: APPLICATION_ID,
      applicationSecret: 'APPLICATION_SECRET',
      user: {
      email: '<%= current_user.email %>',
      name: '<%= current_user.first_name %> <%= current_user.last_name %> <%= current_user.profile_type %>', 
      user_id: '<%= current_user.id%>',
      company: '',
      custom_data: {
      profile_type: '<%= current_user.profile_type%>',
      },
      }
    });
    HelpCrunch('updateUser', user);
    HelpCrunch('updateUserData', custom_data);
    HelpCrunch('showChatWidget');
  </script>


The above code to call the Helpcrunch chat widger, i have added this to layout file , its loading on first time when the page loads but when i navigate to any other page ,it doesn't load. because i'm using turbolinks and i have tried adding this above code to below function but it didn't help,
I'm using rails 5
$(document).on('turbolinks:load', function() {
});

**Comment by usama-ashraf** [comment]
```
<script type="text/javascript">
  (function(w,d){
    w.HelpCrunch=function(){w.HelpCrunch.q.push(arguments)};w.HelpCrunch.q=[];
    function r(){var s=document.createElement('script');s.async=1;s.type='text/javascript';s.src='https://widget.helpcrunch.com/';(d.body||d.head).appendChild(s);}
    if(w.attachEvent){w.attachEvent('onload',r)}else{w.addEventListener('load',r,false)}
  })(window, document)
  </script>

  <script type="text/javascript">
    var user = user;
    var custom_data = custom_data;
    HelpCrunch('init', 'PROJECT_NAME', {
      applicationId: APPLICATION_ID,
      applicationSecret: 'APPLICATION_SECRET',
      user: {
      email: '<%= current_user.email %>',
      name: '<%= current_user.first_name %> <%= current_user.last_name %> <%= current_user.profile_type %>', 
      user_id: '<%= current_user.id%>',
      company: '',
      custom_data: {
      profile_type: '<%= current_user.profile_type%>',
      },
      }
    });
    HelpCrunch('updateUser', user);
    HelpCrunch('updateUserData', custom_data);
    HelpCrunch('showChatWidget');
  </script>
```

> 
> The above code to call the Helpcrunch chat widger, i have added this to layout file , its loading on first time when the page loads but when i navigate to any other page ,it doesn't load. because i'm using turbolinks and i have tried adding this above code to below function but it didn't help,
> I'm using rails 5 with turbolinks 5, Help Crunch is a live agent support chat , how to fix this with turbolinks?
```

$(document).on('turbolinks:load', function() {
});
```

**Comment by SqueezedLight** [comment]
What do you mean "it doesn't load"? Do you get something like `HelpCrunch not defined`? What's the error.

Personally i would place most of your js code within the html `<head>`. See the Turbolinks readme for details. As far as my assumptions go, the relevant code lines are the `HelpCrunch()` calls. Try something like the following in your html `<footer>` (as i said the rest goes probably in the `<head>`)
>>>
$(document).on('turbolinks:load', function() {
HelpCrunch('updateUser', user);
HelpCrunch('updateUserData', custom_data);
HelpCrunch('showChatWidget');
});
>>>

jQuery has to be available for this. Beside the `HelpCrunch` thing.

But the very first thing to test is, if your setup is alright:
>>>
$(document).on('turbolinks:load', function() {
console.log("Do you see me?");
});
>>>

You should see this log on the initial page load, and on every subsequent turbolinks click. This is the first thing to check. If this doesn't work you have to fix it first.

Back in the days there was another potential pitfall: If everything works without Turbolinks, the problem might be, that the `HelpCrunch` plugin uses `$(document).ready()`. But with Turbolinks the "new ready function" is `$(document).on('turbolinks:load',...)`. I do not know if this is still a problem in rails/turbolinks 5 - but try to google it, to check if it may cause problems in your case.

**Comment by usama-ashraf** [comment]
@SqueezedLight Thank you so much for the help, 
i just tried your solution and it worked for me.
I have put the javascript in` <head>`  and functions call in` <footer>` within the  ```
$(document).on('turbolinks:load', function() {
});
```
and now its working smooth
Thanks again sir..!

**Comment by SqueezedLight** [comment]
Glad it worked!
Please close the issue ;)
