### ISSUE TITLE
Versions 5.1.1, 5.0.3, and 5.0.2 all pulled from rubygems

### ISSUE THREAD

**Issue by joelmichael** [turbolinks/turbolinks#361]
Not sure why this is the case, but seems like it's probably unintentional.

https://rubygems.org/gems/turbolinks/versions

**Comment by javan** [comment]
Hi, sorry for the confusion. No gems were pulled, but I can see why it might look that way.

There are two gems to consider:
* https://rubygems.org/gems/turbolinks (Rails)
* https://rubygems.org/gems/turbolinks-source (JavaScript source)

The *turbolinks-source* gems has versions 5.0.2 and 5.0.3. There weren't any associated changes to the *turbolinks* gem so no new versions were released.

The only change in Turbolinks [v5.1.1](https://github.com/turbolinks/turbolinks/releases/tag/v5.1.1) is a fix for the npm package so it was never published as a gem.
