### ISSUE TITLE
Turbolinks warning when loading within a <script> in <body> is not entirely correct

### ISSUE THREAD

**Issue by aried3r** [turbolinks/turbolinks#365]
So I get this warning, implemented in https://github.com/turbolinks/turbolinks/pull/343.
```
Suppress this warning by adding a `data-turbolinks-suppress-warning` attribute to: %s <script src="/assets/application-bda16edc5948093b1d9ca0635d78d9a6f74db1b9b012fd187eb46396811e0c19.js" data-turbolinks-track="true" data-turbolinks-eval="false" integrity="sha256-vaFu3FlICTsdnKBjXXjZpvdNsbmwEv0YfrRjloEeDBk="></script>
```

Since we already use `data-turbolinks-eval="false"` this warning is not necessarily correct. We do not evaluate it on every page load, but yes, we should move it to the `<head>` at some point. But I think it should respect the `data-turbolinks-eval="false"` nonetheless. What do you think?

Also, there's an `%s` in there which should probably be removed or was supposed to print something.

**Comment by domchristie** [comment]
Thanks for the suggestion. Including Turbolinks in the `<body>` can also prevent the [reloading feature](https://github.com/turbolinks/turbolinks#reloading-when-assets-change) from working properly. With this in mind, it's probably best that we display this warning even if data-turbolinks-eval="false" is set. Please use the `data-turbolinks-suppress-warning` attribute to suppress this as suggested.

The `%s` should be removed when the `<script…` substituted :/ I can't reproduce this behaviour in Safari, Chrome, or Firefox on macOS. Which browser are you using?

**Comment by aried3r** [comment]
The `%s` is gone, maybe it was fixed in the new release.

I see, if the reloading might not work it's worth displaying it. Maybe this can also be added to either the warning or the README?

**Comment by domchristie** [comment]
Hi @aried3r, thanks for your suggestion. I've have looked over the README and the console warning, and am having difficulty finding a natural place to include this. Breaking the reloading feature is one possible issue, but including Turbolinks in the `<body>` can also cause other problems such as duplicate event handlers and the like (_unless_ it's not re-eveluated). To avoid any confusion, I think it's best that we stick to a simple message ("include your application JavaScript bundle in the `<head>`, not the `<body>`"). Hope that's okay, and thanks again.
