### ISSUE TITLE
Issue with browser back and forward button

### ISSUE THREAD

**Issue by przbadu** [turbolinks/turbolinks#367]
### Problem

I am using [Progressbar](https://kimmobrunfeldt.github.io/progressbar.js/) for drawing circle.
The problem is, when I visit another page and come back and forth with browser back and forward button, then there are n number of progressbar created.

### Demo

![glitch](https://user-images.githubusercontent.com/4189129/36971142-f481f5f6-2092-11e8-8b99-e23c5a05d161.gif)

### Demo Project to reproduce this issue:

https://progressbar-issue.herokuapp.com/

**Comment by Pushplaybang** [comment]
idempotency becomes a lot more important with a library like this, 

@stevenpetryk  - I would guess the same, @przbadu  - can you share source code or confirm?

**Comment by domchristie** [comment]
Turbolinks caches the page in the state it was left in. When navigating "Back" it restores the page from the cache then triggers a `turbolinks:load` event.

I can see from your application.js file that you are initialising the `ProgressBar.Circle` on `turbolinks:load`, so given the above, your code is creating progress bars on pages that already have progress bars :/

To fix this, you'll need to [`destroy`](https://progressbarjs.readthedocs.io/en/latest/api/shape/#destroy) the `ProgressBar.Circle` on `turbolinks:before-cache`. Something like the following should do the trick:

```js
;(function () {
  var progressBar
  
  $(document).on('turbolinks:load', function () {
    percent = $(".percent").first().data("value");
    progressBar = new ProgressBar.Circle("#progress", {
      // …
    })
      
    // …
  })
  
  $(document).on('turbolinks:before-cache', function () {
    progressBar.destroy()
  })
})()
```

Hope that helps.
