### ISSUE TITLE
window.$ mysteriously undefined in the navigation's lifecycle

### ISSUE THREAD

**Issue by legshooter** [turbolinks/turbolinks#369]
Hey,

I've been banging my head against the wall for some time now, scouring the web with no results.

I have a pretty straightforward setup, where in `app.js` I have:
```javascript
import 'jquery' from './jquery-wrapper';
import 'init' from './init'; 
import 'turbolinks' from 'turbolinks';
turbolinks.start();
// document.addEventListener('turbolinks:click', log);
// document.addEventListener('turbolinks:before-visit', log);
// document.addEventListener('turbolinks:visit', log);
// document.addEventListener('turbolinks:request-start', log);
// document.addEventListener('turbolinks:request-end', log);
// document.addEventListener('turbolinks:before-render', log);
// document.addEventListener('turbolinks:render', log);
document.addEventListener('turbolinks:load', init);

function log() {
    console.log(window.$);
}
```
All `jquery-wrapper` does is import `jQuery` and attach it to `window`. Works great on initial page load!

Trouble starts when navigating - the first call to `$` (inside `init()`) errors out because it's undefined.

So I added all the above listeners, and the console shows:
```javascript
08:12:53.113 turbolinks.js:38 ƒ (A,t){return new u.fn.init(A,t)}
08:12:53.116 turbolinks.js:38 ƒ (A,t){return new u.fn.init(A,t)}
08:12:53.118 turbolinks.js:38 ƒ (A,t){return new u.fn.init(A,t)}
08:12:53.121 turbolinks.js:38 ƒ (A,t){return new u.fn.init(A,t)}
08:12:54.004 turbolinks.js:38 ƒ (A,t){return new u.fn.init(A,t)}
08:12:54.012 turbolinks.js:38 ƒ (A,t){return new u.fn.init(A,t)}
08:12:54.296 turbolinks.js:38 undefined
08:12:54.308 sidebar.js:6 Uncaught TypeError: $ is not a function
    at HTMLDocument.C (sidebar.js:6)
    at Object.ZJja.i.dispatch (turbolinks.js:5)
    at t.notifyApplicationAfterPageLoad (turbolinks.js:6)
    at t.visitCompleted (turbolinks.js:6)
    at t.complete (turbolinks.js:5)
    at t.<anonymous> (turbolinks.js:5)
    at turbolinks.js:5
C @ sidebar.js:6
ZJja.i.dispatch @ turbolinks.js:5
t.notifyApplicationAfterPageLoad @ turbolinks.js:6
t.visitCompleted @ turbolinks.js:6
t.complete @ turbolinks.js:5
(anonymous) @ turbolinks.js:5
(anonymous) @ turbolinks.js:5
requestAnimationFrame (async)
t.render @ turbolinks.js:5
t.loadResponse @ turbolinks.js:5
t.visitRequestCompleted @ turbolinks.js:5
t.requestCompletedWithResponse @ turbolinks.js:5
(anonymous) @ turbolinks.js:5
t.endRequest @ turbolinks.js:5
t.requestLoaded @ turbolinks.js:5
(anonymous) @ turbolinks.js:5
XMLHttpRequest.send (async)
t.send @ turbolinks.js:5
t.issueRequest @ turbolinks.js:5
t.visitStarted @ turbolinks.js:5
t.start @ turbolinks.js:5
t.startVisit @ turbolinks.js:6
t.startVisitToLocationWithAction @ turbolinks.js:5
t.visitProposedToLocationWithAction @ turbolinks.js:5
t.visit @ turbolinks.js:5
t.clickBubbled @ turbolinks.js:6
(anonymous) @ turbolinks.js:5
08:16:07.803 $
08:16:07.806 ƒ (a,b){return new n.fn.init(a,b)}
```
So` $` is attached to `window` on all events up to `turbolinks:render`, where it is suddenly no longer attached, and then when `init()` is called from `turbolinks:load`, it obviously errors out because `window.$` is undefined. The last bit is where I manually try and invoke `$` from the console, and it appears to be defined!

Is this some sort of a bug? For the life of me I cannot find the culprit or even a trace of anyone having similar trouble (Just a lot of misunderstandings around `page:load` turning to `turbolinks:load` and the latter firing on `DOMContentLoaded`). The only thing stopping me from migrating from pjax.

Thanks

**Comment by domchristie** [comment]
I've not been able to reproduce. Are you able to share the contents of `jquery-wrapper` and `init`?

**Comment by adrienpoly** [comment]
@legshooter I suppose you are using jquery in a Wepack environment. If so you might be interested in this video which explains very well how to perfectly configure jQuery in a Webpack environment. I had similar issues like yours with server generated JS and `$ undefined`. Following the recommendations of @rossta, I have completely removed those issues form my app. 
https://www.youtube.com/watch?v=fKOq5_2qj54

This video has been an eye-opener for me to optimize my webpack configuration in Rails.

**Comment by rasmuscnielsen** [comment]
I recently had this exact problem in a Laravel application.

I found that it was a debug-package, barryvdh/laravel-debugbar, that injected some scripts in the body (presumably some jQuery) that crashed the applications own jQuery throughout a visit-cycle.

You could check your <body> to see if any additional scripts are loaded that might cause this behavior.

**Comment by domchristie** [comment]
Thanks @adrienpoly and @rasmuscnielsen for the pointers on this 👍
