### ISSUE TITLE
Is there any chance that Turbolinks could work with CSP nonce?

### ISSUE THREAD

**Issue by christophrumpel** [turbolinks/turbolinks#370]
With Content Security Policy you can set a CSP nonce in your header. This nonce also is put into every inline script on your site. This way you can make sure this script or style code is from you. But when you use Turbolinks the header stays the same, but the nonce from the server is different. This causes an error.

Is there any chance/way to support CSP nonces with Turbolinks?

**Comment by jeremy** [comment]
Think we'd need to reuse the original nonce from the first page load for subsequent Turbolinks requests, huh? Means stashing it in session, like CSRF tokens.

Are you using Rails 5.2 with CSP + nonce support currently?

**Comment by christophrumpel** [comment]
Hey @jeremy , actually I am using Laravel an PHP :-)

So you mean we should use the same nonce again and change it to the old one in the HTML from the servers request? Don't think that this would be secure.

Maybe the point is that I can't use CSP nonces and Turbolinks. Because I don't think it is possible to change the request header with JS ?=) 🤔

**Comment by jeremy** [comment]
Same situation as a single-page app that wants to "inject" a script after the initial page load. Or a lazy JS loader that does chunked async script loading. They need to be informed of the current nonce so it can be reused for subsequent requests, but only within the context of the initial page load. Turbolinks is similar: one initial page load with subsequent requests backed by the initial nonce.

Example: See https://github.com/webpack/webpack/issues/455 for how webpack is provided a nonce at JS runtime for async script loading.

**Comment by migueldemoura** [comment]
I had issues with CSP (https://github.com/turbolinks/turbolinks/issues/330) and the progress bar's injected `<style>` tag. You can fix this by simply whitelisting the style sha256 hash.

**Comment by christophrumpel** [comment]
Thx @jeremy and @migueldemoura . I tried the sha flow and it worked. I somehow thought I can't use that here because the script is changing due to GA or Facebook, but actually, it is just about the lines in my code which don't change. I also wrote my findings up in an article. https://christoph-rumpel.com/2018/03/content-security-policy-hash-algorithm-and-turbolinks
