### ISSUE TITLE
This issue backlog needs some love 💔

### ISSUE THREAD

**Issue by stevenpetryk** [turbolinks/turbolinks#375]
Hey there, 

This repo has a big backlog going back to 2016, a lot of which are just people misusing the library or reporting correct behavior as a bug.

I thought this was worth mentioning. I can help close out outdated issues, if you'd like—I'm very familiar with the library. I've been looking to get back into contributing to open source lately.

cc @sstephenson @packagethief

**Comment by packagethief** [comment]
> I can help close out outdated issues, if you'd like—I'm very familiar with the library.

That would be wonderful, @stevenpetryk. The list is sufficiently long that I find it daunting. Feel free to mention me on any issues if you'd like a second opinion.

**Comment by Pushplaybang** [comment]
I too would be happy to help answer and close issues.  

Would be nice to have a 2 mod, vote to close an issue, but even then sometimes someone just needs a pointer to right place in the docs.  

Very keen, let me know.

**Comment by domchristie** [comment]
The issues list should now be mostly bugs and enhancements. Some relate to server-side problems, some are concerned with security, whereas others are seemingly browser quirks which we could possibly workaround.

I've asked for some more details on a few issues. These can/will be closed if we don't hear back within a reasonable time.

I'll close this issue now, but feel free to chip in if you have any ideas on the open issues. Thanks!

**Comment by domchristie** [comment]
Thanks @kaspth! Yes, the issues have taken a couple of weeks to get through. I've tried to verify as many of the problems as possible, so hopefully I've been fair when closing issues. I also have a couple of pull requests lined up, which should fix a some bugs. They require a bit more testing, but they should be up soon.
