### ISSUE TITLE
Best approach to refresh a table on the fly

### ISSUE THREAD

**Issue by jpic** [turbolinks/turbolinks#377]
Consider a list view with a search form and a table, the table must refresh on search form input.

For example, user opens [/list](https://github.com/yourlabs/crudlfap/blob/master/src/crudlfap_filtertables2/jinja2/crudlfap_filtertables2/list.html), types "foo" in the search field, the [StimulusJS controller](https://github.com/yourlabs/crudlfap/blob/master/js/controllers/autosubmit_controller.js) will automatically replace the table content after making a request.

But currently, this doesn't update the browser URL. Should I use pushState manually when the controller updates the table, or did I miss a feature from Turbolinks ?

TYIA

**Comment by packagethief** [comment]
@jpic, yes that's what I'd do. There's no Turbolinks API for this yet, though it's been proposed in #61.

**Comment by jpic** [comment]
Confirms that seems to work for me.
