### ISSUE TITLE
turbolinks:before-cache doesn't do what I expect

### ISSUE THREAD

**Issue by EdwardIII** [turbolinks/turbolinks#38]
Hey, not sure if this is a bug or just that I have broken expectations?

I've put a sample project together here and description of the issue & how to replicate:

https://github.com/EdwardIII/turbolinks-events

**Comment by sstephenson** [comment]
Hi Edward,

I think you’re misunderstanding how jQuery’s `remove` method works.

```coffee
$(document).on 'turbolinks:before-cache', ->
    $('body').remove('.spinner-wrap')
```

First you need to select the elements you want to remove, and then you call `remove()`.

```coffee
$(document).on 'turbolinks:before-cache', ->
    $('body .spinner-wrap').remove()
```

Closing because this doesn’t seem to be an issue with Turbolinks.

**Comment by EdwardIII** [comment]
Rookie error, sorry!
