### ISSUE TITLE
Unable to load page specific scripts using turbolinks..

### ISSUE THREAD

**Issue by srikanthcx** [turbolinks/turbolinks#382]
Please provide the best solution to put the external page specific scripts with the turbolinks. I am using content for tag to render script at the bottom of the page, So it's not working with the turbolinks load. Please find my below code.
```
<% content_for :script do %>
		<%= javascript_include_tag 'https://www.gstatic.com/firebasejs/4.13.0/firebase.js', defer: true %>
		<script type="text/javascript" defer>
			alert('coming');
			initFirebase(<%= @household_pickup.scrap_collector_id %>, <%= @user_address.latitude %>, <%= @user_address.longitude %>);
		</script>
	<% end %>
```

**Comment by Pushplaybang** [comment]
you'll likely want to look at the `turbolinks:load` event, 

```js
document.addEventListener('turbolinks:load', () => {
  // do your stuff here
});
```

While I'm not working in a rails environment as I'm using turbolinks to help wordpress not suck so much, this should all work the same.  I have some minimal global scripts, loaded in the head, like turbolinks.  and the rest of my JS loaded specifically per page.

**Comment by domchristie** [comment]
If I am understanding this correctly, the inline script tag is being executed before the external firebase script has loaded. Is that right?
