### ISSUE TITLE
Proposal: Change rails-ujs form remote request if method :get to Turbolinks.visit 

### ISSUE THREAD

**Issue by iggant** [turbolinks/turbolinks#385]
when we have 

`  <%= form_with model: @client,
                url: edit_some_path_here,
                method: :get,
                local: false do |f| %>
`

and there for when we render some view as the response nothing happens at the browser page. 

but I expect, that turbolinks will handle this and will make Turbolinks.visit instead of rails-ujs form submission.

**Comment by domchristie** [comment]
Closing as duplicate of #272
