### ISSUE TITLE
`event.data` is undefined in `turbolinks:request-end`

### ISSUE THREAD

**Issue by mrhead** [turbolinks/turbolinks#39]
According to the doc I should be able to access `XMLHttpRequest` object with `event.data.xhr`, but `event.data` is undefined. This is the code which I use:

```coffee
$(document).on "turbolinks:request-end", (event) ->
  console.log(event.data)
```

It is the same in Google Chrome, Safari and Firefox with `5.0.0.beta2`.

Am I doing something wrong here, or is it a bug?

**Comment by mrhead** [comment]
I just tried `turbolinks:click` and `turbolinks:before-visit` events and it is the same there.

**Comment by sstephenson** [comment]
If you observe the events with jQuery, you must first access the original DOM event with `event.originalEvent`.

```coffee
$(document).on "turbolinks:request-end", (event) ->
  console.log(event.originalEvent.data)
```

There’s really no need to use jQuery here, though:

```coffee
document.addEventListener "turbolinks:request-end", (event) ->
  console.log(event.data)
```

**Comment by mrhead** [comment]
Thank you @sstephenson!
