### ISSUE TITLE
How to detect after :load, or :render this Load Action have before cache "preview" ?

### ISSUE THREAD

**Issue by ionurboz** [turbolinks/turbolinks#392]
This my code:
```
$(document).on("turbolinks:load", function(e) {
    if (e.originalEvent.data.timing.visitStart) {
        $(document).find('body').addClass('loading loaded clicked');
    } 
    else {
        $(document).find('body').addClass('loading loaded');
    }
});
```
I want it:
```
$(document).on("turbolinks:load", function(e) {
    if (e.originalEvent.data.timing.visitStart) {
        $(document).find('body').addClass('loading loaded clicked');
    } 
    elseif(e.originalEvent.data.timing.render-after-cache){
        $(document).find('body').removeClass('loading');  
        /* I WAS NEED REMOVE LOADING CLASS IF THE CACHED PAGE LOAD */
    }
    else {
        $(document).find('body').addClass('loading loaded');
    }
});
```

**Comment by ionurboz** [comment]
Maybe: `event.data.newBody` resolve but i dont find.

**Comment by domchristie** [comment]
I'm not sure I understand what you are trying to do. `event.data.newBody` is available on `turbolinks:before-render` events. There is no `turbolinks:after-cache` event.

A page might be rendered in a few different ways:

- on the initial page load
- by tapping a link to a new page (an "Application visit")
- by tapping "Back" or "Forwards" (a "Restoration visit")
- by tapping a link that has previously been visited (displaying a preview as part of an Application visit)

Each can be detected using the following event handlers:

```js
$(document).on('turbolinks:load', function (event) {
  if (!event.originalEvent.data.timing.visitStart) {
    // INITIAL PAGE LOAD
  } else if (!event.originalEvent.data.timing.requestStart) {
    // LOADED FROM CACHE AS A RESTORATION VISIT
  } else {
    // LOADED FROM REQUEST
  }
})

$(document).on('turbolinks:render', function () {
  if (document.documentElement.hasAttribute("data-turbolinks-preview")) {
    // PREVIEW
  }
})
```

And if you want to display some kind of loading styles when a visitor taps a links, you may want to add an event listener to `turbolinks:visit` to add your class names.

Hope that helps.
