### ISSUE TITLE
would it be possible to build/support webpack?

### ISSUE THREAD

**Issue by pravi** [turbolinks/turbolinks#394]
Rails 5.1 now supports using webpack, so would it be possible to support building using webpack?

**Comment by javan** [comment]
Yes, you can use the npm package: https://github.com/turbolinks/turbolinks#installation-using-npm

**Comment by pravi** [comment]
@javan I want to package turbolinks for debian and hence I cannot use the prebuilt files provided by npm. I should build it from source. Can I build it without blade or any other ruby gems but using only node tools like webpack/coffeescript. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=902178 for more details.

**Comment by javan** [comment]
Can you explain what the https://packages.debian.org/buster/node-turbolinks page is? Is it different from the npm package in some way? Why does it need to built from source using webpack?

**Comment by pravi** [comment]
We want every package in main section of debian to be built from source using the tools available in main (this is the policy of debian project).  Since blade is not yet available in debian and webpack is already available, we are trying to reduce the work required to include turbolinks in debian. 

If using webpack is not possible, we have to package blade and all its dependencies first and then build turbolinks using it. We have kept that as second option in case we are not able to use webpack to build turbolinks.

We don't want any change from the npm distributed files, but only make sure it is generated in debian using the tools available in debian. This package will be installed globally and will be used by turbolinks-source gem (ruby-turbolinks-source package) via symbolic links.

With this patch (changing sprockets syntax with commonjs require syntax) https://salsa.debian.org/js-team/node-turbolinks/blob/master/debian/patches/use-commonjs-require.patch webpack could build turbolinks. But we need to confirm if that works as expected before proceeding.

**Comment by pravi** [comment]
Another example package where we use webpack https://salsa.debian.org/js-team/node-d3-format/blob/master/debian/rules#L11

**Comment by javan** [comment]
Webpack isn't an option currently so you'll either need to use blade or just pull in the already-compiled `turbolinks.js` file from any of these sources:
* https://github.com/turbolinks/turbolinks/blob/master/dist/turbolinks.js
* https://github.com/turbolinks/turbolinks-source-gem/blob/master/lib/assets/javascripts/turbolinks.js
* https://unpkg.com/turbolinks/dist/turbolinks.js

**Comment by pravi** [comment]
@javan with help from Jishnu, Harish and Joseph we are able to build turbolinks with webpack. We [converted sprockets style requires to commonjs syntax with a patch](https://salsa.debian.org/js-team/node-turbolinks/blob/master/debian/patches/use-commonJS-notations.patch) and used [webapck provide plugin in webpack configuration file](https://salsa.debian.org/js-team/node-turbolinks/blob/master/debian/webpack.config.js) and used [3 commands](https://salsa.debian.org/js-team/node-turbolinks/blob/master/debian/rules#L11)  (which could be combined if coffee-loader module and -p option of webpack is used)

If you'd like to use it (directly or as an alternate build option), we can send a pull request, else we will maintain this as a patch in debian package.
