### ISSUE TITLE
Packaged README.md is empty

### ISSUE THREAD

**Issue by pvalena** [turbolinks/turbolinks#396]
in gem file on rubygems.org.

**Comment by javan** [comment]
This repo isn't packaged as a gem. Which one are you referring to?

1. https://rubygems.org/gems/turbolinks → https://github.com/turbolinks/turbolinks-rails
1. https://rubygems.org/gems/turbolinks-source → https://github.com/turbolinks/turbolinks-source-gem

**Comment by pvalena** [comment]
Sorry, I've missed that. I meant turbolinks-source:

```bash
$ gem unpack turbolinks-source-5.1.0.gem
Unpacked gem: '/home/test/tmp/turbolinks-source-5.1.0'
$ l turbolinks-source-5.1.0/README.md
-rw-r--r--. 1 test test 0 Jun 26 22:29 turbolinks-source-5.1.0/README.md
$ cat turbolinks-source-5.1.0/README.md
$ # empty file
```

**Comment by domchristie** [comment]
This is probably one for the [turbolinks-source-gem](https://github.com/turbolinks/turbolinks-source-gem) repo. PR added: https://github.com/turbolinks/turbolinks-source-gem/pull/3
