### ISSUE TITLE
Using turbolinks progress bar for custom javascript requests ?

### ISSUE THREAD

**Issue by jpic** [turbolinks/turbolinks#397]
Hello !

What's the best way to use the same progressbar as turbolinks for custom post requests ?

Thanks !

**Comment by packagethief** [comment]
The API is pretty small: `show()`, `hide()`, and `setValue()`. The value should be a number between zero and one. Here's a quick example:

```js
const progressBar = new Turbolinks.ProgressBar()

// Request started
progressBar.setValue(0)
progressBar.show()

// Request finished
progressBar.setValue(1)
progressBar.hide()
```

This will show the progress bar and start a synthetic trickle. If you're using XHR you can show actual progress by incrementing the value in response to the `onprogress` event. See [Turbolinks.HttpRequest](https://github.com/turbolinks/turbolinks/blob/bd415ae3c28efd43add174f4a72a7887ab707d11/src/turbolinks/http_request.coffee#L62-L72) for an example.
