### ISSUE TITLE
Problem with assert_redirected_to in rspec-rails 3.7 and Rails 5.2

### ISSUE THREAD

**Issue by danascheider** [turbolinks/turbolinks#398]
Hi there, I'm having an issue I hope you can help me out with. I can't find information about it anywhere, but Turbolinks is showing up in the stack trace, and [this post](https://stackoverflow.com/questions/27956998/why-is-there-a-wrong-number-of-arguments-error-when-using-redirect-to-in-rails-4) on StackOverflow suggests somebody has had a similar issue with an older version of Turbolinks. When you get a chance I'm hoping you can point me in the right direction.

## Environment ##

- Rails 5.2
- RSpec-Rails 3.7
- Turbolinks 5.1.1

## Summary ##
`assert_redirected_to` is returning an error saying I've given 0 arguments when I have included an argument. Although the test still fails in Turbolinks 2.5.4, this particular error seems to be limited to Turbolinks 5.

I'm getting the following error when I use RSpec's `redirect_to` matcher (which calls the Turbolinks `assert_redirected_to` method):
```
  1) Admin registrations new sign-up redirects to home
     Failure/Error: expect(subject).to redirect_to(root_path)

     ArgumentError:
       wrong number of arguments (given 0, expected 1..2)
     # /Users/dana/.rvm/gems/ruby-2.5.1@inview-info-site/gems/rack-test-1.0.0/lib/rack/test.rb:116:in `request'
     # /Users/dana/.rvm/gems/ruby-2.5.1@inview-info-site/gems/turbolinks-5.1.1/lib/turbolinks/assertions.rb:37:in `turbolinks_request?'
     # /Users/dana/.rvm/gems/ruby-2.5.1@inview-info-site/gems/turbolinks-5.1.1/lib/turbolinks/assertions.rb:6:in `assert_redirected_to'
     # ./spec/requests/devise/admin_registrations_spec.rb:11:in `block (3 levels) in <top (required)>'
```

## Details ##
My test code looks like this:
```
RSpec.describe "Admin registrations", type: :request do
  describe "new sign-up" do
    subject { get new_admin_registration_path }

    it "redirects to home" do
      expect(subject).to redirect_to(root_path)
    end
  end
end
```
And my controller code looks like this:
```
class Admins::RegistrationsController < Devise::RegistrationsController
  def new
    redirect_to root_path
  end
end
```
I did have the same issue with tests using non-Devise controllers.

I don't understand why I'm getting this error given that I am passing `root_path` to the `redirect_to` matcher. I used byebug to verify that `root_path` is defined when the test runs (its value, as expected, is "/").

Using byebug, I've traced the issue to the `turbolinks_request?` method - specifically, the call to the `request` method. This is the point where the error is raised.

Apologies in advance if this issue is not with Turbolinks - I appreciate your time looking into this.

**Comment by domchristie** [comment]
> Using byebug, I've traced the issue to the turbolinks_request? method - specifically, the call to the request method. This is the point where the error is raised.

This is odd! I've tried to reproduce with the environment you detailed but have been unable to do so. It looks like `request` is being called on a `Rack::Test::Session` (see [`Rack::Test::Session#request`](https://github.com/rack-test/rack-test/blob/b854dff819ae602382fedcd4b3b12dea93dabf34/lib/rack/test.rb#L116-L120)) rather than an `ActionDispatch::Request ` 🤔 So I'm guessing something might be configured differently? If you've not managed to solve this, please copy this issue to https://github.com/turbolinks/turbolinks-rails/issues Thanks.

**Comment by danascheider** [comment]
Thank you!

**Comment by Mziserman** [comment]
@danascheider did you fix it ?

**Comment by drborges** [comment]
Same here... In my `rails_helper.rb` I had to remove `config.include Rack::Test::Methods, type: :request`.
