### ISSUE TITLE
When click Back in the browser, injected <style> is persisted

### ISSUE THREAD

**Issue by kurko** [turbolinks/turbolinks#407]
### Preface

This is a development problem, not a production one (I guess, unless Turbolinks will load 404 and 503 pages).

### Context

My page has N `<header>` tags. The Rails error page also has a `<header>` tag.

### Steps to reproduce

1. click a link such that the resulting page is a Rails error, e.g

    <img width="758" alt="screen shot 2018-07-28 at 14 30 37" src="https://user-images.githubusercontent.com/70312/43359078-d9685f6a-9272-11e8-8de6-498cacb1b42c.png">

2. the Rails error page has a `<style>` tag with `header` styles (the big red bar).
3. click the Back browser button.

**The problem:** the page now (my app) has all `<header>` coloured _red_.

**The culprit:** the `<style>` tag is carried back over to the previous page, applying the error page's  styles to the app page.

Should we remove any `<style>` when the back button is clicked, letting Turbolinks merge it again on the page?

**Comment by absolux** [comment]
@kurko The problem of styles may come from rails itself
https://github.com/rails/rails/blob/3000c1490565b3a21376d6444cb6fe24dfe4e383/actionpack/lib/action_dispatch/middleware/templates/rescues/layout.erb#L31-L35

the styles are applied globally in the default `layout` rescue template, instead of being wrapped within an `id` or a `class`, as for example here
https://github.com/RailsApps/learn-rails/blob/8e6eb5f6e030d2bf43cdc66df1ba9b40b11efe19/public/404.html#L7-L53

**Comment by domchristie** [comment]
@kurko how are you including your main application JavaScript file? This shouldn't happen if you include the main it in the `<head>` and include the `data-turbolinks-track="reload"` attribute.

e.g.

```erb
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
```

Rails error pages do not contain any JavaScript (as show in [layout.erb](https://github.com/rails/rails/blob/3000c1490565b3a21376d6444cb6fe24dfe4e383/actionpack/lib/action_dispatch/middleware/templates/rescues/layout.erb#L31-L35)), so if you include the above in the `<head>` then when Turbolinks loads the error page, it tracks the changes to the assets, and performs a full reload (See [Reloading When Assets Change](https://github.com/turbolinks/turbolinks#reloading-when-assets-change)). Hope that helps.
