### ISSUE TITLE
turbolinks:load event is fired before body content changes

### ISSUE THREAD

**Issue by arielscherman** [turbolinks/turbolinks#411]
I'm building a code blog on a `rails 5.1.6` app that uses `turbolinks 5.2.0`.

I want to do a really simple thing, which is highlight the code (using a js plugin) after the content is loaded, so I added this to the page:

```coffee
coffee:
  $(document).on "turbolinks:load", ->
    Highlighter.init()
```

That works well on a fresh load. However, when you're in another page and you click a link to go there, the `turbolinks:load` event is fired before the content is updated, so the highlight doesn't work.

If I do this:

```coffee
coffee:
  $(document).on "turbolinks:load", ->
    debugger
    Highlighter.init()
```

The debugger line is called before the new content is rendered.

However, the docs says:

> You can observe the turbolinks:load event in place of DOMContentLoaded to set up JavaScript behavior after every page change

So unless I'm missing something, this is an issue because it's not working as expected.

**Comment by domchristie** [comment]
Closing as this has been [answered on StackOverflow](https://stackoverflow.com/a/52065647/783009).
