### ISSUE TITLE
Upgrade guide

### ISSUE THREAD

**Issue by ajb** [turbolinks/turbolinks#42]
I just finished reading the README (it looks great!), and Turbolinks 5 seems pretty similar to Turbolinks 2. However, I'd love to be able to upgrade by following a simple checklist. Is this something that's on the horizon for a stable release?

**Comment by packagethief** [comment]
Thanks @ajb!

I think an upgrade guide would be a great addition to the wiki.

One notable difference is the event names. They've all been renamed in Turbolinks 5, and some have been removed. We've created a [compatibility shim](https://github.com/turbolinks/turbolinks/blob/master/src/turbolinks/compatibility.coffee) that maps Turbolinks Classic events to their version 5 equivalents where possible. Reading that file should give you a pretty good idea of the differences.

Some element annotations have also changed:

- To opt out on a per-link basis, `data-no-turbolink` is now `data-turbolinks=false`
- To track assets, `data-turbolinks-track=true` is now `data-turbolinks-track=reload`
- To disable the preview cache (formerly known as the transition cache) on a per-page basis, `<any-element data-no-transition-cache>` is now `<meta name="turbolinks-cache-control" content="no-preview">`
