### ISSUE TITLE
Benchmarks/Case-Studies

### ISSUE THREAD

**Issue by acornforth** [turbolinks/turbolinks#426]
I realise as I write this, that benchmarks are often not very useful and primarily used to market things, but can we see any case studies? before deciding whether to implement turbolinks on future projects, i would like to get a tangible idea of what performance impact would be seen,i work on all sizes of project, small and large, and everywhere inbetween, so case-studies examples from across the spectrum would be amazing.
I would welcome benchmarks or anecdotal evidence from anyone who has implemented this...
Thanks

**Comment by javan** [comment]
> I would welcome benchmarks or anecdotal evidence from anyone who has implemented this

▶️https://youtu.be/SWEts0rlezA?t=649

**Comment by gingerlime** [comment]
Also curious about this. We're actually trying to measure the effect of Turbolinks on some of our pages. Any suggestions on how to measure the difference with/out Turbolinks in a more scientific/consistent way?

**Comment by domchristie** [comment]
> Also curious about this. We're actually trying to measure the effect of Turbolinks on some of our pages. Any suggestions on how to measure the difference with/out Turbolinks in a more rigorous/consistent way?

The [Chrome devtools Performance tab](https://developers.google.com/web/tools/chrome-devtools/evaluate-performance/reference) is your friend here. It goes beyond analysing asset sizes and download speeds (often improved with minification, compression, and caching), and presents the time taken to parse, compile, and execute JavaScript. Activity on the main thread impairs user interactivity, making it feel sluggish. By comparing the main thread "Scripting" times of a Turbolinks page transition with one when Turbolinks has been removed, we can see how well it performs.

As an example, I work on a social networking site. The JavaScript contains about 50-60 components and behaviours bundled into the main application.js file, along with jQuery and a few jQuery plugins. Other scripts include webfont loading and third-party tracking. It's not huge, but it's not miniscule. 

Almost all app components are initialised on `turbolinks:load`, which is switched to `ready` for the first audit here. For a normal page load, **214ms** is spent "Scripting":

![Screen Shot 2019-10-05 at 15 46 17](https://user-images.githubusercontent.com/111734/66266849-7b7f8e80-e822-11e9-97cb-e9c4f69cb327.png)

For the same page, loaded _with Turbolinks_ (no cache/previews), it's just **59ms**:

![Screen Shot 2019-10-06 at 10 22 18](https://user-images.githubusercontent.com/111734/66267225-4b39ef00-e826-11e9-95ec-861fe0db73b8.png)

_Look at all the things it's not doing!_

The blocks highlighted in red, represent component/behaviour initialisation, and take roughly the same amount of time\*. Clearly a lot of heavy lifting is performed on the initial page load. The later activity represents the webfont loading and setting up third-party tracking. With Turbolinks, none of that is needed yet the outcome is the same 🎉

\* As Turbolinks maintains JS state, we take advantage by memoising things like Websocket services. This is partly why the Turbolinks component initialisation is slightly faster.

---

See also: Addy Osmani's [JavaScript Start-up Optimization](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/javascript-startup-optimization)
