### ISSUE TITLE
Autofocus not entering input

### ISSUE THREAD

**Issue by jonsgreen** [turbolinks/turbolinks#428]
I am finding that with autofocus on an input on a page that although it gets focus styling there is no text cursor and I don't automatically enter the input unless I leave the tab and return. Everything works fine on Firefox but not on Chrome (Version 69.0.3497.100) or Safari. Is this somehow expected behavior?

**Comment by domchristie** [comment]
I'm not able to reproduce this: transitioning to a page with an `autofocus` input then typing, seems to fill the input as expected. Are you able to link to a minimal example to demonstrate the issue?

**Comment by jonsgreen** [comment]
@domchristie well it seems like the hardest problem is with Safari. You can try going to this url: https://pims-staging.herokuapp.com/users/sign_in. It may take a little while to load but when it does you will notice that although the username field looks highlighted for focus the cursor is not entered in the field. You can enter bad credentials and see similar results. However if you switch to another tab in the same Safari window and come back it may fix itself. This problem disappears if we remove turbolinks. It is quite puzzling.

**Comment by jonsgreen** [comment]
@domchristie Thanks for the tip! That was very helpful in allowing me to isolate the problem. We had introduced the following code essentially: 
```
$(document).on('turbolinks:load', function() {
  window.getSelection().removeAllRanges();
});
```
