### ISSUE TITLE
No website URL on the Github project next to description

### ISSUE THREAD

**Issue by szTheory** [turbolinks/turbolinks#433]
This may sound silly, but it makes getting to the Turbolinks docs harder. I couldn't easily find a link to the docs in the README, either. Thanks.

**Comment by domchristie** [comment]
Hi @szTheory 
I'm not sure I understand. There is no Turbolinks website, and all the docs are all in the README. Would you be able to clarify what other docs/website you are referring to?

**Comment by szTheory** [comment]
Oh sorry, got Turbolinks confused with Stimulus.
