### ISSUE TITLE
inline script tag not evalute

### ISSUE THREAD

**Issue by M0H3N** [turbolinks/turbolinks#435]
Hello 
I  have some inline script tags at the bottom  of html body . in my localhost its ok . after initial page load and navigating between pages all inline script tags evaluated with no problem . but at server all of my script elements not execute . I inspected the page and  noticed that inline scripts commented after navigating . 
I dont know what is the problem . can anybody help me ?
thanks

**Comment by domchristie** [comment]
Hi @M0H3N 
Turbolinks wouldn't comment out scripts, so it sounds like your production server is configured differently to your localhost.
I'll close this issue for now, but feel free to reopen if you still feel it's a bug with Turbolinks.
Thanks.

**Comment by M0H3N** [comment]
@domchristie 
yes Im using cloudflare on production server .  I disabled the  Rocket Loader feature on cloudflare and the problem was solved
