### ISSUE TITLE
Compatibility with Matomo analytics

### ISSUE THREAD

**Issue by brigriffin** [turbolinks/turbolinks#436]
This is might not really be an issue but more of a question or a best practice recommendation which could be useful for others too and a good enhancement for the FAQ or README documentation of Turbolinks.

I would like to use Matomo analytics (matomo.org) as open source web analytics software on a Rails 5.2 website. It works similarly like google analytics where you have to add their inline javascript code at the bottom of all pages right before the closing body tag.

Here is an example of that code:
```
<script type="text/javascript">
  var _paq = _paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//webstats.mydomain.org/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', '10']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
```

So the problem I encounter here with this code at the bottom of my pages is that I can see the visitors properly in the matomo back-end but if the user navigates to another page, matomo does not recognize that the user has switched page and it logs another visit on the very same page although the user has changed page on the website in the mean time.

If I entirely disable Turbolinks the different visited pages get all logged correctly so this is why I am here really. I would love to use both Turbolinks and Matomo together as both are great but it looks like I first need to figure out how to add this inline javascript code the "turbolinks-way" hence my issue here. Does anyone have any recommendations or already managed to have Matomo working correctly on a Rails 5 website with turbolinks?

**Comment by domchristie** [comment]
Given that it works in a similar way to Google Analytics, you may find the following helpful: https://github.com/turbolinks/turbolinks/issues/73#issuecomment-210697862. You will need to replace the Google Analytics-specific function calls with the Matomo equivalents (e.g. I'm guessing that `ga("send", "pageview")` is equivalent to `_paq.push(['trackPageView'])`.

I also thought the following may help: https://developer.matomo.org/guides/spa-tracking. Although conceptually Turbolinks isn't considered to be a single-page application, some of the principles still apply when it comes to tracking page views.

**Comment by 2called-chaos** [comment]
Maybe [this can help you](https://gist.github.com/2called-chaos/6c4f587e26b3eda5c1e5f3e7e4548bd1)(coffeescript) a bit, that's what we've been using for years (which is why it's still called piwik). AppOS is our internal thing but it basically just calls the functions appropriately (e.g. documentLoad is DOMContentLoaded and pageLoad is `turbolinks:load`)

**Comment by kemenaran** [comment]
Following the Matomo guide, I just added a snippet of Javascript after the tracker code:

```html
<script type="text/javascript">
  // [Matomo tracking code goes here]

  // Send Matomo a new event when navigating to a new page using Turbolinks
  // (see https://developer.matomo.org/guides/spa-tracking)
  (function() {
    var previousPageUrl = null;
    addEventListener('turbolinks:load', function(event) {
      if (previousPageUrl) {
        var loadTimeMs = event.data.timing.visitEnd - event.data.timing.visitStart;
        _paq.push(['setReferrerUrl', previousPageUrl]);
        _paq.push(['setCustomUrl', '/' + window.location.href]);
        _paq.push(['setDocumentTitle', document.title]);
        _paq.push(['setGenerationTimeMs', loadTimeMs]);
        _paq.push(['trackPageView']);
      }
      previousPageUrl = window.location.href;
    });
  })();
</script>
```

If Turbolinks is enabled, and is compatible with the current web browser, subsequent page loads will be sent to the Matomo tracker.

**Comment by domchristie** [comment]
Closing as resolved by the above.
