### ISSUE TITLE
Body no longer has ID/class when navigating via Turbolinks

### ISSUE THREAD

**Issue by kthibodeaux** [turbolinks/turbolinks#437]
When navigating via Turbolinks in the latest version of MS Edge, the body looses its classes and ID.  This does not happen in any other browser.

This is using the latest Turbolinks (5.2.0)

**Comment by domchristie** [comment]
I've not been able to reproduce this using the following environment: http://mybrowser.fyi/report/5c0eb9a5a6b88e00146f374b (or on Edge 18.18262). Could you produce a live/minimal example to demonstrate this?

**Comment by kthibodeaux** [comment]
Creating a basic app doesn't seem to be enough. I will work on trying to find the exact conditions that make this happen.

Thanks!

**Comment by domchristie** [comment]
Thanks @kthibodeaux. Often issues arise due to conflicts with third-party scripts, so that might be worth checking out.
Thanks again.

**Comment by kthibodeaux** [comment]
@domchristie I have managed to produce with a minimal app!

https://github.com/kthibodeaux/demo_app

It looks like when there is an audio tag above the rest of the layout (which there likely should not be) then on Edge the body tag loses its attributes.  It continues to work on other browsers.

**Comment by domchristie** [comment]
Hi @kthibodeaux Thanks for digging into this further, and for creating a demo.

As it's quite an obscure browser-specific bug, I think the simplest solution is the one you suggested: avoid placing audio elements outside the body. It may also be worth raising this bug on https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/, too. Thanks again.
