### ISSUE TITLE
Script injection vulnerability

### ISSUE THREAD

**Issue by jdelStrother** [turbolinks/turbolinks#438]
I think I have a potential script injection vulnerability in Turbolinks.  Is there a private place I should disclose it, or would you rather I just posted it here?

**Comment by packagethief** [comment]
Thanks @jdelStrother. Can you contact us over at Basecamp? We'll investigate and report back.

https://basecamp.com/about/policies/security/response

**Comment by jdelStrother** [comment]
Thanks - I've sent an email.

**Comment by rebootcode** [comment]
9 months any update on it?

**Comment by sstephenson** [comment]
This was fixed by #454.
