### ISSUE TITLE
Expose configuration options for progress bar, caching, turbolinks root, etc

### ISSUE THREAD

**Issue by ajb** [turbolinks/turbolinks#44]
Making sure that `<meta name="turbolinks-cache-control" content="no-preview">` is added on every page of HTML we serve is kinda a chore, and I'm scared that something will get missed. What do the authors think of adding it as a configuration option?

**Comment by packagethief** [comment]
I can see it being a chore if you have to add it to each page manually. I'd think most people would be using a layout though, no?

**Comment by ajb** [comment]
Yeah, we've got a couple different layouts. Also, it gets sent over the wire each time, which is one of those things that isn't actually a big deal, but feels inefficient.

It seems like there might be a desire to keep Turbolinks free of configuration options -- hence the `<meta name="turbolinks-root">`, hiding the progress bar with `visibility: hidden`, changing the caching behavior with `<meta name="turbolinks-cache-control">`...

I think it's far more pragmatic to expose these as config options, like they were in turbolinks-classic, and I suspect others might feel this way as well. I'll update the issue title to more accurately reflect this.

**Comment by packagethief** [comment]
> It seems like there might be a desire to keep Turbolinks free of configuration options

I wouldn't go quite that far ;-) However, I do think that adding configuration options on a whim can blind you to the best defaults, and can suggest usage you don't necessarily intend or encourage. We should consider each option carefully.

> I think it's far more pragmatic to expose these as config options, like they were in turbolinks-classic

I think the options we have so far make sense at the page level.

For example, caching options are per-page because they're intended to be used selectively, for the rare case when you need to deviate from the defaults. It's perfectly reasonable to want default caching behavior everywhere but a few pages, and unlikely that you'd ever want to disable caching entirely. The lack of an on/off switch reflects that.

I can see wanting to disable cached previews entirely, but I'm not sure it's common enough to warrant an on/off switch. The presence of a switch suggests that globally disabling previews is something you're likely to do, which I don't necessarily think is the case and wouldn't want to encourage.

Of course, others might feel differently, and I'm happy to discuss it further. I really have nothing against configuration options. I just think they need to make a strong case for themselves :grin:

**Comment by ajb** [comment]
> The presence of a switch suggests that globally disabling previews is something you're likely to do, which I don't necessarily think is the case and wouldn't want to encourage.

This is where we differ: I think the preview cache is one of the stranger features in TL, and I much preferred when it was disabled by default. The preview cache will have _seriously undesirable behavior_ if there are pages that load slowly or if there is network latency. (https://github.com/turbolinks/turbolinks-classic/issues/330)

I appreciate (and am in awe of) the speed of Basecamp 3, but not every Rails app is going to be as fast. This prevents TL from being a "drop-in solution" for all Rails app. I'm not familiar with Rails 5's defaults, but I feel like the preview cache needs to be _disabled_ by default or TL needs to be removed from the default-generated app.

An unrelated point is that tags like `<meta name="turbolinks-root">` are kinda an abuse of meta tags, no? Why should options for a _JavaScript_ library be specified in the HTML?

**Comment by daniel-rikowski** [comment]
>  I think the preview cache is one of the stranger features in TL, and I much preferred when it was disabled by default.

Judging from my personal experience I have to agree with this assessment.

I tried the transition cache several times, but I always ended up disabling it. The perceived speed was impressive, but I never could get my apps fast enough and always ran into the mentioned side effects.

IMHO the preview cache is the icing on top of a (mostly) static site or an already fast application, but for slower setups/apps it does more harm than good.


> I can see wanting to disable cached previews entirely, but I'm not sure it's common enough to warrant an on/off switch.

I believe that is the core question: How many developers/apps actually use the preview cache successfully? I can't image it is the majority, but of course I can be wrong.

Perhaps there should be "2G Tuesdays" for Rails and Turbolinks developers, too. :wink:

**Comment by sstephenson** [comment]
> The preview cache will have seriously undesirable behavior if there are pages that load slowly or if there is network latency. 

In general, the slower your pages are to load, the less effective Turbolinks is at speeding up navigation. If all your pages are slow to load, why use Turbolinks at all?

Consider the on-by-default preview cache to be a bit of vinegar. Most requests should complete in under a second, and preferably in under 500ms. Use techniques like [Russian-doll caching](https://www.nateberkopec.com/2015/07/15/the-complete-guide-to-rails-caching.html) and lazily-loaded Ajax content to make that happen.

> An unrelated point is that tags like `<meta name="turbolinks-root">` are kinda an abuse of meta tags, no? Why should options for a JavaScript library be specified in the HTML?

I don’t think so at all. In fact, I’m struggling to think of a more appropriate way to set page-specific behavior. A JavaScript API seems like it’d be much more cumbersome.

Closing this for now, but my ear’s on the ground with regard to the on-by-default preview cache.

**Comment by ajb** [comment]
Thanks Sam, appreciate your time and thoughtful response. We can certainly live with opting-out via `meta` tags once we upgrade.
