### ISSUE TITLE
Chrome back button re-runs included javascript

### ISSUE THREAD

**Issue by adamdebono** [turbolinks/turbolinks#442]
I am running into an odd bug where my javascript code is being re-run after using the browser's back button. I can replicate this 100% of the time when navigating back to a 404 page, but there may also be other instances when this occurs. I have only been able to see this in Chrome.

Steps to replicate:
1. Load the website
2. Navigate to a 404 page (with a broken link)
3. Navigate away from the 404 page
4. Click the browser's back button

The website uses a combination of sprockets and webpack, and both scripts are run twice. Include statements:
```slim
= javascript_pack_tag('application', 'data-turbolinks-track': 'reload')
= javascript_include_tag('application', 'data-turbolinks-track': 'reload')
```

Turbolinks is on the latest version (5.2.0) and is initialised from webpack:
```javascript
import turbolinks from 'turbolinks'
turbolinks.start()
```

To be clear, this is not an issue with certain pieces of code running after Turbolinks events have been triggered, I am seeing errors caused by setup code running twice. For example:
```javascript
class CustomButton extends HTMLElement {
    ...
}
document.registerElement('custom-button', CustomButton)
```
Which then creates the following error:
```
Uncaught DOMException: Failed to execute 'registerElement' on 'Document': Registration failed for type 'video-pip-container'. A type with that name is already registered.
```

**Comment by domchristie** [comment]
Hi @adamdebono, are you able to post a link to a minimal site which demonstrates the issue?

**Comment by domchristie** [comment]
@adamdebono just looking into this further. Does your 404 page include your application JavaScript bundles?

**Comment by adamdebono** [comment]
@domchristie I don't really have time at the moment to split this out into a minimal site, but I can provide any configuration files you want. I could also direct you to the production site via email if you wanted.

Yes, the 404 page includes application javascript bundles (it shares a common layout template with the rest of the site).

**Comment by domchristie** [comment]
> I don't really have time at the moment to split this out into a minimal site, but I can provide any configuration files you want.

No problem. I have managed to reproduce this (not just on Chrome) with the following:

```rb
require "sinatra"

def layout(body)
  <<-LAYOUT
  <!DOCTYPE html>
<html>
  <head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/turbolinks/5.2.0/turbolinks.js"></script>
    <script>
      var count = count || 0
      count++
      if (count > 1) console.warn('script in head evaluated ' + count + ' times')
    </script>
  </head>
  <body>
  #{body}
  </body>
</html>
  LAYOUT
end

get "/" do
  body = <<-INDEX
  <h1>Index</h1>
  <a href="/not_found">Broken link</a>
  INDEX
  layout(body)
end

get "/not_found" do
  body = <<-NOT_FOUND
    <h1>Not Found</h1>
    <a href="/another_page">Go to another page</a>
  NOT_FOUND
  status 404
  layout(body)
end

get "/another_page" do
  body = <<-ANOTHER_PAGE
  <h1>Another Page</h1>
  <p>Now go back</p>
  ANOTHER_PAGE
  layout(body)
end
```

Error responses are handled differently to successful ones. Rather then merging assets in the `head`, on error responses, the `head` is simply replaced, and therefore the scripts are re-evaluated. (This also explains why error pages sometimes display a flash of unstyled content.) I'm not quite sure why this is. Perhaps there is an assumption that error pages won't include application JavaScript?

Anyway, I have just found https://github.com/turbolinks/turbolinks/issues/179 which also includes a couple of patches, so closing this as a duplicate.

Thanks!
