### ISSUE TITLE
Enable instant.page to work with Turbolinks

### ISSUE THREAD

**Issue by david-a-wheeler** [turbolinks/turbolinks#443]
Enable instant.page to work with TurboLinks, or build in the same functionality.  This is similar to https://github.com/turbolinks/turbolinks/issues/313 , but the way it works is slightly different.

[Instant.page website explains](https://instant.page/):

> Before a user clicks on a link, they hover their mouse over that link. When a user has hovered for 65 ms there is one chance out of two that they will click on that link, so instant.page starts preloading at this moment, leaving on average over 300 ms for the page to preload.
> On mobile, a user starts touching their display before releasing it, leaving on average 90 ms to preload the page.

instant.page is MIT licensed.

**Comment by domchristie** [comment]
@david-a-wheeler thanks for highlighting instant.page. #313 contains alternatives for instantclick, e.g. hoverintent, so to keep that issue as the central place for discussing preloading solutions, I'll close this for now. Thanks again.
