### ISSUE TITLE
Turbolinks 5 and setInterval issue

### ISSUE THREAD

**Issue by Backoo** [turbolinks/turbolinks#448]
I'm using [Turbolinks 5][1] with [Rails 5][2] and I'm setting a JS interval in order to refresh page content each 10 seconds through AJAX:

    <script type="text/javascript">
      $(document).ready(function() {
        function fetchContent() {
          // some AJAX request
        }

        setInterval(fetchContent, 10000);
      });
    </script>

When I first load the page containing the above code, it works: the `fetchContent` is fired every 10 seconds.

However, when I navigate to another page, the `fetchContent` keeps firing. Moreover, when I go back to the page (using the browser back button), the `fetchContent` fires unpredictably multiple times. Obviously, this is not the wanted behaviour.

How to fix this?

----------

*Note*: To fix this, I know I could need a `clearInterval` call of some sort, but how should I make it using Turbolinks 5 e.g. what event should I bind? Since Turbolinks 5, [API has changed][3]. In particular, all of the Turbolinks Classic events have been renamed, and several—including `page:update`—have been removed, so I cannot use solutions like [this][4], [this][5] or [this][6].

  [1]: https://github.com/turbolinks/turbolinks
  [2]: https://github.com/rails/rails
  [3]: https://github.com/turbolinks/turbolinks/wiki/Turbolinks-5-FAQ#should-i-use-turbolinks-5-or-turbolinks-classic
  [4]: https://product.reverb.com/fun-with-setinterval-and-turbolinks-66f5fcb1bbcd
  [5]: https://gist.github.com/dv/fc51f798d825bff5a371
  [6]: https://github.com/turbolinks/turbolinks-classic/issues/373

**Comment by Backoo** [comment]
A possible solution [here](https://github.com/turbolinks/turbolinks/issues/448).

**Comment by domchristie** [comment]
> when I navigate to another page, the `fetchContent` keeps firing.

When working with Turbolinks apps it's important to remember that function schedulers like `setTimeout` and `setInterval` are not torn down between page loads (as they are in "traditional " page loads). So even though it might seem like an inline `<script>` should only execute on the page it's present on, it will still be running on subsequent page loads unless it is manually torn down.

> when I go back to the page (using the browser back button), the `fetchContent` fires unpredictably multiple times.

It sounds like you are including the script inline (in the `<body>`). These are evaluated and executed every time a page loads. So in your case:

1. Load page
2. Script executes for the first time and `setInterval` schedules `fetchContent` to be called
3. Navigate to another page (`setInterval` continues scheduling as it has not been cleared)
4. Navigate back to first page
5. Script executes a second time _in addition_ to the first execution, and so `fetchContent` is scheduled by more than one `setInterval`

It looks like you have found a solution for your case 👍 
As a general rule, I'd aim to keep as much of your JS in your application.js bundle, and avoid running asynchronous code (`setInterval`, `setTimeout`, event listeners etc) in inline scripts as much as possible, to help avoid this kind of confusion.

Hope that helps.
