### ISSUE TITLE
Cache just the raw HTML from server

### ISSUE THREAD

**Issue by garygreen** [turbolinks/turbolinks#449]
I understand that it's recommended to use the `turbolinks:before-cache` event to destroy any previous handlers / events bound to elements which have potentially mutated the DOM structure. However, this is pretty troublesome and means you need to micro manage the state in your app.

Would it not be better to cache just the raw dom structure/HTML returned from the server? Maybe there could be a function where you tell turbolinks to `.attemptCache()` BEFORE you initialise your main javascript stuff (which will mutate the DOM).. that way you always have a fresh DOM state in your cache and don't need to always unbind/destroy stuff?

**Comment by kat0d** [comment]
does this solution make sense ?
```html
<head>
  ...
  <meta name="turbolinks-cache-control" content="no-cache">
</head>
```

**Comment by domchristie** [comment]
One of the benefits of Turbolinks caching strategy is that upon returning to a page, a visitor will see the page just as they left it. For example, consider a blog with comments rendered via AJAX:

1. Page loads
2. User adds comment
3. User navigates away (and page is cached)
4. User navigates back to the page, and is shown the page as they left it
(5. Turbolinks may load/render a fresh copy, seamlessly replacing the preview)

Caching the server response leads to the following:

1. Page loads (and HTML is cached)
2. User adds comment
3. User navigates away 
4. User navigates back to the page, but their comment is missing
(5. Turbolinks may load/render a fresh copy, replacing the preview, but the page may "jump" as the HTML will differ)

Having to teardown handlers and DOM manipulation may seem a little troublesome, but with some structured JavaScript this can be minimised. For example, by structuring your JavaScript behaviours with objects that include a `destroy` method, tearing down can be achieved in a single place: put your teardown code for each behaviour in the `destroy` method, then on `turbolinks:before-cache`, cycle through each behaviour and call `destroy`. Frameworks will often help with this. [Stimulus](https://stimulusjs.org/) is one example with its `disconnect` hook.

Hope that helps.
