### ISSUE TITLE
Remove dynamically injected CSS

### ISSUE THREAD

**Issue by xire28** [turbolinks/turbolinks#45]
I don't think the current way of injecting the style for the progressbar follows the css/javascript/rails guidelines. 

Wouldn't it be better to create a sass file using an `$animation-duration` variable with a default value so that it can be overriden easily ?

Then change the rails `new` generator to insert a line in the `application.scss` file for the turbolink-rails engine like the javascript part in the `application.js`

Is there any reason to use the current hackish technique I am not seeing ?

**Comment by packagethief** [comment]
Including CSS with a `<style>` element is perfectly legit. In this case it's also much more practical than linking an external stylesheet or depending on SASS.

**Comment by xire28** [comment]
So

```
 @defaultCSS: """
    .turbolinks-progress-bar {
      position: fixed;
      display: block;
      top: 0;
      left: 0;
      height: 3px;
      background: #0076ff;
      z-index: 9999;
      transition: width #{ANIMATION_DURATION}ms ease-out, opacity #{ANIMATION_DURATION / 2}ms #{ANIMATION_DURATION / 2}ms ease-in;
      transform: translate3d(0, 0, 0);
    }
  """
```

```
element = document.createElement("style")
element.type = "text/css"
element.textContent = @constructor.defaultCSS
...
document.documentElement.insertBefore(@progressElement, document.body)
```

is better for you than

`<link rel="stylesheet" type="text/css" href="turbolink.css">`

To sum my point, your technique :

- Add unnessessary complexity in the codebase for no reason
- Add redundancy in the page if you override the style
- Use javascript (dynamic) to create the same static content every time so unnecessarily slows down the page
- Doesn't follow the principle of separation of concerns and of least astonishment

Let's ask @dhh about this

**Comment by nateberkopec** [comment]
Isn't there a way to override `@defaultCSS`? Not a CoffeeScript guy so I'm not sure of the syntax for doing that. So I don't think this adds redundancy.

Injecting an inline stylesheet isn't really that complex (the progressbar element is, necessarily, injected too). Requiring that developers style the element themselves (by including styles in an external stylesheet or in their `application.css`) isn't practical from a usability standpoint either, far better that Turbolinks "Just Works" here.

> Use javascript (dynamic) to create the same static content every time so unnecessarily slows down the page. 

Would love to see a benchmark, but external stylesheets are not free either. The performance tradeoff is unclear.

**Comment by xire28** [comment]
Rails 5 with the new turbolinks 5 that doesn't support the asset pipeline, nice

**Comment by jeremy** [comment]
Encapsulation is the benefit, @xire28.

This is similar to what you'd see with a custom element neatly bundling its DOM and default style in an HTML template. External users can then *separately* style the custom element, as they expect, and there's no dangling internal dependency on an external asset—which is slow to load, introduces new ways for asset packaging and delivery to fail, and, by breaking encapsulation in an puzzling spot, sows confusion about how to properly interact with and customize the element.

Take a look at custom elements and shadow DOM to review why such a technique is desirable and why you're seeing a similar pattern here.

(Explicit Social Cue: You're communicating your disagreement with a technical decision, but you're also transmitting dismissiveness and contempt. These may be what you're feeling but not what you intend to share with others.)

**Comment by xire28** [comment]
> (Explicit Social Cue: You're communicating your disagreement with a technical decision, but you're also transmitting dismissiveness and contempt. These may be what you're feeling but not what you intend to share with others.)

I agree, I will be careful from now on

Thanks for our anwers

**Comment by merqlove** [comment]
You can simply drop ProgressBar:
```js
Turbolinks.removeProgressBar = (function(stub) {
    Turbolinks.BrowserAdapter.prototype.showProgressBarAfterDelay = stub;
    Turbolinks.BrowserAdapter.prototype.showProgressBar = stub;
    Turbolinks.BrowserAdapter.prototype.hideProgressBar = stub;
    Turbolinks.ProgressBar.prototype.show = stub;
    Turbolinks.ProgressBar.prototype.hide = stub;
    Turbolinks.ProgressBar.prototype.createStylesheetElement = stub;
    Turbolinks.ProgressBar.prototype.createProgressElement = stub;
    Turbolinks.ProgressBar.prototype.setValue = stub;
})(function(){});

Turbolinks.removeProgressBar();
```
