### ISSUE TITLE
So… which script should I load?

### ISSUE THREAD

**Issue by Lohoris** [turbolinks/turbolinks#450]
Now… I'm feeling stupid, but I can't find out which script I'm supposed to load.

There's only a single `.js`: `rollup.config.js`, and it throws an error on the very first line.

Is there an old fashoned `<script src="">` way to load it? Should I somehow compile it first? Really, this feels very very stupid, I'm missing something obvious, but…

**Comment by sstephenson** [comment]
Hey there!

If you're looking for the [latest release (5.2.0)](https://github.com/turbolinks/turbolinks/releases/tag/v5.2.0), you can download the `dist/turbolinks.js` file here: https://raw.githubusercontent.com/turbolinks/turbolinks/v5.2.0/dist/turbolinks.js

As of 866a29c, we have fully switched over to npm for distribution, and are no longer and checking the distributable file in to the source repository itself. So you'll either need to:
* install the `turbolinks` package using `npm` or `yarn`,
* follow the instructions for [Building From Source](https://github.com/turbolinks/turbolinks#building-from-source), or
* grab the pre-built distributable file from unpkg: https://unpkg.com/turbolinks@5.3.0-beta.0/dist/turbolinks.js
