### ISSUE TITLE
Turbolinks crashes when elements in head change.

### ISSUE THREAD

**Issue by mfittko** [turbolinks/turbolinks#458]
We at [sofatutor.com](https://www.sofatutor.com) just discovered a bug in turbolinks (as we currently think), which makes our page crash once a DOM element in the head section of the page changes slightly.

We discovered this due to an external script which was adding data attributes to every DOM element in the head. So now when we add for example an `async='true'` attribute (or some data attribute) to an arbitrary script tag in the head, the whole page crashes when opening the next turbolinks enabled page. I would at least have expected a DOM change in the head triggering a full turbolinks reload. Unfortunately it is first reloading the body js and then the scripts in the head which leads to a lot of `Uncaught TypeError: Cannot read property '...' of undefined` errors.

Feel free to point me to a solution if the error is actually on our side. Thanks for you help!

**Comment by domchristie** [comment]
Hi @mfittko, which version of Turbolinks are you using? and are you able to create a minimal demo of this?

**Comment by mfittko** [comment]
@domchristie It's turbolinks 5.1.1. I tried to dive into the internals and I saw that elements in the head are stored in a key value store where the html of the tags are the keys. So it's kinda clear why turbolinks decides to re-add these dom elements when their signature changes. try to do the demo later when I'm on a mac :)
