### ISSUE TITLE
turbolinks:load for 1 time

### ISSUE THREAD

**Issue by u007** [turbolinks/turbolinks#46]
Hi 
is there a way to call turbolink for 1time when the page matches the current action?
it seems that when ive this added, it will always call this method no matter which page it is loading..

```
jQuery(document).on('turbolinks:load', function() {
//do something
});
```

thank you

**Comment by nateberkopec** [comment]
If I understand your question correctly, there are a lot of ways to solve that problem. Here's one idea.

In your layout:

```html
<body id="<%= [ controller_name, action_name ].join('_') %>">
```

Then in your Javascript:

```javascript
jQuery(document).on('turbolinks:load', function() {
  if($("#posts_index")) {
    // do something
  }
});
```

**Comment by u007** [comment]
This may sound good, but for same reason, I may recalling this when that
page is loaded.
Then it will be called twice

**Comment by gbuesing** [comment]
How about storing state in data attributes, e.g.:

```javascript
jQuery(document).on('turbolinks:load', function() {
  if($("#posts_index:not([data-foo-applied])").length > 0) {
    foo()
    $("#posts_index").attr('data-foo-applied', true) 
  }
});
```

**Comment by u007** [comment]
hi,
thanks everyone for your recommendations,
i found out thay i dont need to put into turbolinks if its executed after on load of the document.
ive put back my jQuery(document).on('ready' instead..
