### ISSUE TITLE
Turbolinks hyperlink event firing twice

### ISSUE THREAD

**Issue by Tectract** [turbolinks/turbolinks#461]
This issue is for posterity in case anyone ever runs into this issue:

The issue for me was that link_to hyperlinks would fire the get event twice when you clicked on the link within my ruby on rails app.

I discovered I had these lines included twice in my application.html.erb file header:

``
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
``

Making sure these lines were only included ONCE in the application.html.erb header solved the issue for me :)

**Comment by domchristie** [comment]
Yes, if you include Turbolinks twice, then clicks will be handled twice, which will result in duplicate requests :/
Glad you found a solution :)
