### ISSUE TITLE
Sidebar menu doesn't work on mobile screens

### ISSUE THREAD

**Issue by pututbawono** [turbolinks/turbolinks#467]
I've searched this Issues page for the problem I'm facing and actually I've found 2 posts that have similar problem as I have, but unfortunately not answered yet.

So, this is my condition : 
1.  I'm using Turbolinks 5.
2. I'm also using Core UI as a admin template, which is based on Bootstrap 4.

In desktop view, all of sidebar items (menu links and menu dropdowns) are working normally, but they dont't work (won't open) in mobile view. After a bit of investigation, I think it's caused by the sidebar is automatically hidden in mobile view (as would normally any sidebars in most admin templates are). If I force the sidebar to always open, even in mobile view, all of sidebar items would work normally, but once I hide the sidebar using a toggler, they won't work anymore.

If anybody has experienced this kind of problem and found the solution, please point me to the right direction. This web programming is very new to me and I've tried to look anywhere for the solution.
Thanks.

**Comment by domchristie** [comment]
Hi @pututbawono, some third party libraries don't play nicely with Turbolinks,, particularly those that rely on the `DOMContentLoaded` event to initialise their components e.g. when using Bootstrap with the `data-` API. Here's some advice taken from: https://github.com/turbolinks/turbolinks/issues/508

> When using third-party libraries such as Bootstrap (or bootstrap-native) it is often best to manually call the JavaScript functions rather than relying on the library to do the work automatically (e.g. via data- attributes). Many libraries will listen out for the DOMContentLoaded event to initialise their components. For Turbolinks applications, this is only called on the first page load, so subsequent page loads won't behave in the same way. It's also good practice to tear down the effects of libraries on turbolinks:before-cache. This can often prevent components from being initialised more than once.

I hope that helps.
