### ISSUE TITLE
How to listen on load event?

### ISSUE THREAD

**Issue by mabras** [turbolinks/turbolinks#469]
I have a Rails 5.1 app with turbolinks 5.0.1 enabled . I want to trigger some script on `load` page event. The problem is that TL does not fire this event on page navigation. This log does not happen on page navigation:

```
window.addEventListener('load', (event) => {
  console.log('load');
});
```

the `load` event gets fire on full page refresh (or page init request). But that does not help me.

My goal is to scroll on certain #id (using anchor at the end of link) after all content of the page loads (mainly images). Without this event images change scroll positions after fully images loaded. This just like github comments link

Is there away to achieve this?
I have already tried to add:
```
<meta name="turbolinks-cache-control" content="no-cache">
# Or
<meta name="turbolinks-visit-control" content="reload">
```

**Comment by domchristie** [comment]
I'm afraid there currently aren't any Turbolinks events like `window.onload`. You may find the [imagesLoaded](https://imagesloaded.desandro.com/) library useful to achieve what you're after.
Hope that helps.
