### ISSUE TITLE
fixed navigation menu

### ISSUE THREAD

**Issue by u007** [turbolinks/turbolinks#47]
Hi,

im thinking to render side menu and top bar menu as fix.
am i suppose to use it with data-turbolinks-permanent ?

im thinking to highlight active menu after a page is loaded via javascript.
can anyone suggest a good solution to this?

and is there any header indication that this page is being load via turbolinks?
because if the page is loaded via turbolinks, i will output without the side menu and top menu, making it as content only. 
im thinking to also trigger turbolink to replace header title and meta tag after loading.

Sorry im still new with turbolinks 5..'

thank you :)

**Comment by sstephenson** [comment]
> im thinking to render side menu and top bar menu as fix.
> am i suppose to use it with data-turbolinks-permanent ?

If the state of those elements changes dynamically with JavaScript after the page loads, you should annotate them with `data-turbolinks-permanent`. If the state of those elements should change with each page requested from the server, marking them as permanent is probably not necessary.

> im thinking to highlight active menu after a page is loaded via javascript.
> can anyone suggest a good solution to this?

This doesn't sound like a Turbolinks question. Let's please reserve the issue tracker for Turbolinks-specific questions. Thanks!
