### ISSUE TITLE
Is it possible to override request URL?

### ISSUE THREAD

**Issue by nesterow** [turbolinks/turbolinks#471]
I have an idea to create a static builder for a site which uses Turbolinks. 
I figured that the simplest way would be to override URLs without extensions to lead them on `*.html` pages.
 
Is it possible to override URLs before Turbolinks makes a visit?

**Comment by domchristie** [comment]
Hi @nesterow. I'm not sure I understand the use case, but if you need to change the request URLs, you could either: query the DOM and change every the link `href`s on `turbolinks:load`, or alternatively do something like the following:

```js
document.addEventListener('turbolinks:click', function (event) {
  event.preventDefault()
  Turbolinks.visit(event.data.url + '.html')
})
```

I hope that gives you some ideas.

**Comment by nesterow** [comment]
@domchristie Thank you. Not exactly what I am looking for. `Turbolinks.visit` will change url in the address bar. I want to make Turbolinks load markup from modified location, but save original location to the browser history
