### ISSUE TITLE
Tearing down third party async widget

### ISSUE THREAD

**Issue by Shriken** [turbolinks/turbolinks#475]
Hey!
I am using FreshChat widget and I'm losing it when performing cached visit. The this is that the destroy() function of the widget is async, so while I execute it on any event such as 'click' or 'before-visit', the widget is still not deleting when the caching operation executes. So what I get is a cached page with an initialized widget, this breaks the widget and I can't re-initiate it. 
If I manually destroy it in console, then everything is fine.

The question is - how can I make sure that once I make a visit, the widget is destroyed BEFORE the current page is cached?

**Comment by Shriken** [comment]
Found a solution:

`function beforeVisit( event ) {
  if (!window.turbolinksVisitFlag) {
    event.preventDefault();
    if (window.fcWidget ) {
    window.fcWidget.destroy();
  }
  window.turbolinksVisitFlag = true;
  setTimeout(function(){Turbolinks.visit(event.data.url);}, 500);
}`

So now I just intercept the visit and call it manually with delay.

**Comment by domchristie** [comment]
> how can I make sure that once I make a visit, the widget is destroyed BEFORE the current page is cached?

Have you tried tearing down on the `turbolinks:before-cache` event? Something like:

```js
addEventListener('turbolinks:before-cache', function () {
  if (window.fcWidget) window.fcWidget.destroy()
})
```

**Comment by Shriken** [comment]
> > how can I make sure that once I make a visit, the widget is destroyed BEFORE the current page is cached?
> 
> Have you tried tearing down on the `turbolinks:before-cache` event? Something like:
> 
> ```js
> addEventListener('turbolinks:before-cache', function () {
>   if (window.fcWidget) window.fcWidget.destroy()
> })
> ```
> 
> See: https://github.com/turbolinks/turbolinks#preparing-the-page-to-be-cached

Yeah but as I mentioned above, the destroy() method is async, so the page get cached before the operation completes.

**Comment by domchristie** [comment]
Ah, I see what you mean now.

**Comment by Shriken** [comment]
But thanks anyway, I posted my solution and it fixed the issue.

**Comment by sarah-mostafa-mostafa** [comment]
I checked if the widget is still initialized, then I would destroy it using the below flush_freshchat method and reload the script to initialize window.fcWidget again
`
  function initFreshChat() {
    window.fcWidget.init({
      token: "<%= Settings::FRESHCHAT_TOKEN %>",
      host: "<%= Settings::FRESHCHAT_HOST %>"
  }); 

  function flush_freshchat(){
    delete window.fcWidget;
    delete window.history.pushState_fc_observer;
    delete window.history.replaceState_fc_observer;
    delete window.history.pushState;
    delete window.history.replaceState;
  }

(function(d, id) {
    var fcJS;
  freshchat_sdk = d.getElementById(id);
    if (freshchat_sdk) {
      freshchat_sdk.remove();
      if(window.fcWidget.isInitialized()){
        flush_freshchat();
      }
    }
    fcJS = d.createElement('script');
    fcJS.id = id;
    fcJS.async = true;
    fcJS.src = 'https://wchat.freshchat.com/js/widget.js';
    fcJS.onload = initFreshChat;
    d.head.appendChild(fcJS);
}(document, 'freshchat-js-sdk'));

`

**Comment by descovi** [comment]
Hi! I expanded the solution of @sarah-mostafa-mostafa (thanks a lot!) because inside my firefox, the expression `delete window.fcWidget` does not work. And I've used turbolinks listener so I hope the this sound more comfortable to people.

```
function initFreshChat() {
  window.fcWidget.init({
    token: "TOKEN",
    host: "HOST"
  })
}

function initialize(document, tag){
  var element;
  element = document.createElement("script")
  element.id=tag
  element.async = false
  element.src="https://wchat.freshchat.com/js/widget.js"
  element.onload=initFreshChat
  document.body.appendChild(element)
}

document.addEventListener("turbolinks:load", function() {
  if(window.fcWidget){ flush_freshchat() }
  initialize(document, "freshchat-js-sdk")
})

function flush_freshchat(){
  window.fcWidget = null
  delete window.history.pushState_fc_observer
  delete window.history.replaceState_fc_observer
  delete window.history.pushState
  delete window.history.replaceState
}

```
