### ISSUE TITLE
old video source requested again in the new page

### ISSUE THREAD

**Issue by levi0214** [turbolinks/turbolinks#476]
I have a video player in every page, which is very common video tag like 
```html
<video controls poster="...">
    <source src="..." type="video/mp4">
</video>
```
but when I click from video-1 page to video-2 page, two things happened:

1. firstly video-1 was requested
2. then video-2 was requested 

Why would it be like this? Is there any suggestion to fix it?

**Comment by domchristie** [comment]
It could be making an additional request when it is cached. Could you try [opting out of caching](https://github.com/turbolinks/turbolinks#opting-out-of-caching), to see if that fixes things?
