### ISSUE TITLE
turbolinks:load event not fired at first page load when we use rails 6.0.0 with webpacker

### ISSUE THREAD

**Issue by windy** [turbolinks/turbolinks#477]
https://github.com/rails/webpacker/issues/354

the same problem with this issue above.

**Comment by driedjack** [comment]
Yeah, the same for me. I must reload pages for javascript to run. 💆🏼‍♂️

**Comment by windy** [comment]
I have found the problem.

I use `import('turbolinks').then( t => t.start() )` instead of `require('turbolinks').start()`.

This change cause `Turbolinks` can't fire `turbolinks:load` event at the first page load.

The differcence is here: https://2ality.com/2017/01/import-operator.html
