### ISSUE TITLE
Replace a dom element other than body?

### ISSUE THREAD

**Issue by pioz** [turbolinks/turbolinks#478]
I have a page with video background and every time Turbolinks replace the body the video restart from the beginning.

Is possible tell to Turbolinks to replace another dom element other than body? Something like `<meta name="turbolinks-container" content="#my-container">`. So the video is not replaced and does not start again from the beginning.

Or there is another way to achieve this result?

**Comment by anatoliyarkhipov** [comment]
Isn't this what you're looking for? 🤔 

https://github.com/turbolinks/turbolinks#persisting-elements-across-page-loads

**Comment by domchristie** [comment]
Hi @pioz, this has been raised a few times (#43, #400, #401, #457), so you may want to check those out, and perhaps try some of the proposed solutions.

An alternative might be to track the video's play position when leaving the page, then set the play position on `turbolinks:load`.

Hope that helps.

**Comment by pioz** [comment]
> Isn't this what you're looking for? 🤔
> 
> https://github.com/turbolinks/turbolinks#persisting-elements-across-page-loads

Oh yeah. I've tried without the `id` and it didn't work. With `id` it works!
