### ISSUE TITLE
Trying to use Emojics with Turbolinks but it isn't executing returned script

### ISSUE THREAD

**Issue by kostadriano** [turbolinks/turbolinks#479]
Hello, I'm having a problem to use [emojics](https://www.emojics.com/), I was using this with Google Tag Management, but since it wasn't working I tried a direct approach. The problem now is, it just loads when I go directly to the target page, it doesn't load if I change from a page to another one using turbo links.

When I go direct to the page that emojics are on: 
![image](https://user-images.githubusercontent.com/15300776/62217380-e9ba5780-b380-11e9-819d-079cd192c43f.png)

When I go from another page:
![image](https://user-images.githubusercontent.com/15300776/62217444-0191db80-b381-11e9-971b-d02a0d98ef3b.png)

This is the Emojics code that goes on the body of the `erb` page.

```ruby
<!-- Start of Emojics Code -->
<div id="emojics-root"></div>
<script>
  window.emojicsOpts = {
    widget: 'xxxxxxxxxxxxxxxx',
    metadata: {
      email: window.user_email,
      name:  window.user_name,
    } 
  };

  (function(d, s, id) {
	var js, fjs = d.getElementsByTagName(s)[0];
	js = d.createElement(s);
	js.id = id;
	js.src = "//connect.emojics.com/dist/sdk.js";
	fjs.parentNode.insertBefore(js, fjs);
  })(document, "script", "emojics-js");
</script>
<!-- End of Emojics Code -->
```

So, this code inserts a `script` tag with the emojics source, this script will make a request, the return of this will be a script that will execute using my "widget" and get the images, emojis and will put this on my page.

I already tried to use turbolinks events and other things. I think what is happening is **the return of the emojics scripts is not being executed?**. Also, I think that the same problem was happening with GTM.

I don't know if this is the case but I tried to do a direct request and got this error: 
![image](https://user-images.githubusercontent.com/15300776/62218461-e1fbb280-b382-11e9-9a53-6fa41d411e6a.png)

**Comment by domchristie** [comment]
Hello @kostadriano 

Integrating third-party libraries and widgets can pose some problems, particularly when the installation only involves adding a script tag and some markup. With this set up, it can be difficult to figure out how it works and what's going wrong.

If there is a way to manually initialise the library (on `turbolinks:load` and perhaps tear it down on `turbolinks:before-cache`), then I'd recommend that route if possible.
