### ISSUE TITLE
Webpack integration issue

### ISSUE THREAD

**Issue by jpic** [turbolinks/turbolinks#487]
Hi all! 

Not sure why but getting this error from IE11:

![2019-09-02-223824_588x128_scrot](https://user-images.githubusercontent.com/94636/64132797-89309700-cdd2-11e9-8e3a-0f685cb9f797.png)

Is this a bug ?

Any suggestion welcome

**Comment by javan** [comment]
Same issue as https://github.com/turbolinks/turbolinks/issues/379, perhaps?

**Comment by jpic** [comment]
Sorry I had completely forgotten about it.

I will re-open with a reproductible test case !

Sorry again
