### ISSUE TITLE
Specific page script in head doesn't get called first time I navigate on page. Code organization doubts.

### ISSUE THREAD

**Issue by frederikhors** [turbolinks/turbolinks#489]
I'm using Turbolinks for the first time and not with Rails (I'm using Django).

## SOURCE CODE

1. `index.html`:

    ```html
    <html>
    <head>
      <script defer src="/js/index.js"></script>
    </head>
    <body>
      Text and NO <script></script>!
    </body>
    </html>
    ```

1. `about.html`:

    ```html
    <html>
    <head>
      <script defer src="/js/index.js"></script>
      <script defer src="/js/about.js"></script>
    </head>
    <body>
      Text and NO <script></script>!
    </body>
    </html>
    ```

1. `index.js`:

    ```js
    import Turbolinks from 'turbolinks'

    Turbolinks.start()
    ```

1. `about.js`:

    ```js
    function drawChart() {
      console.log("I will drawChart() here")
    }

    // drawChart() <--- this is commented on purpose here, with this it works!

    document.addEventListener('turbolinks:load', drawChart)
    ```

## THE PROBLEM

If I start from page `/index` and then navigate by link to `/about` nothing happens!

If I now go back to `/index` I can see in console the log: `I will drawChart() here`. So the listener is working.

If I start (refresh on) from `/about` instead it print in console the message so the listener `turbolinks:load` is running the function `drawChart()` on refresh.

## WHAT I EXPECT AND WHAT I DID

I need the call to the function `drawChart()` happens in the first navigation to `/about` too.

So I thought of using a direct call in the file (`drawChart()`, commented in the source code on this issue as you can see) and it works.

But I think this is not the good way to go, especially because if I go on `/about` and refresh the page it's called two times!

It seems to me too hacky.

Isn't?

## WAHT DO OTHER PEOPLE DO

1. Same problem but his solution doesn't work for me: https://candland.net/rails/2019/03/13/rails-turbolinks-not-firing-js-on-load.html

### THANKS FOR YOUR WORK!

**Comment by domchristie** [comment]
Hi @frederikhors 

I have answered this on StackOverflow: https://stackoverflow.com/a/57849993/783009

Hope that helps.

**Comment by frederikhors** [comment]
Please re-open this issue because when I will understand how to do I can write a wiki for newbies like me.

Believe me, I read all the issues looking for an answer to this!

I paste my answer from SO (the answer is good to read here).

---

### First of all thanks for your answer.

Now I tried:

1. **Removing `defer` in head `<script>`**:

    From:
    
    ```html
    <script defer type="module" src="/js/index.js"></script>
    ```
    
    to:
    
    ```html
    <script type="module" src="/js/index.js"></script>
    ```

    It's the same (I tried for all files).

1. **Including `about.js` in body bottom in `about.html`**:

    From:

    ```html
    <html>
    <head>
        <script type="module" src="/js/index.js"></script>
        <script type="module" src="/js/about.js"></script>
    </head>
    <body>
        About
    </body>
    </html>
    ```
    
    to:
    
    ```html
    <html>
    <head>
        <script type="module" src="/js/index.js"></script>
    </head>
    <body>
        About
        <script type="module" src="/js/about.js"></script>
    </body>
    </html>
    ```

    It works the first time I go on `/about` page and no more.
    
    If I go back to `/index` and return to `/about` again, nothing happens.

1. Your hint to include all js files in a big one is a path I can't take for several reasons (big team, many teams, many many js, big js, big website).

---

_I think I'm loosing my mind. :)_

I think I'm very unlucky to run into this problem after years of Turbolinks in production in the world.

**What do you think?**

**Comment by frederikhors** [comment]
@domchristie I forgot to tag you.

**Comment by domchristie** [comment]
Using `type="module"` changes the behaviour of `script` loading so that it is only run once. I'm not experienced in loading scripts in this way, so I can't offer much guidance on this. If you must load scripts in this way, then you may want to try loading all your scripts at the same time, and use the content of the page to determine when to call certain functions:

```html
<!-- index.html -->
<html>
<head>
    <script type="module" src="/js/index.js"></script>
    <script type="module" src="/js/about.js"></script>
</head>
<body>
    …
</body>
</html>
```

```html
<!-- about.html -->
<html>
<head>
    <script type="module" src="/js/index.js"></script>
    <script type="module" src="/js/about.js"></script>
</head>
<body>
    …
</body>
</html>
```

```js
// about.js
document.addEventListener('turbolinks:load', function () {
  var chart = document.getElementById('chart')
  if (chart) drawChart()
})
```
---

It's worth pointing out that if you are trying to load another script when a new page loads via Turbolinks, be aware that it will be loaded _asynchronously_. If you add a `turbolinks:load` event listener in that script, it won't be called until the next page load, because `turbolinks:load` will be triggered _before_ the script loads and runs.

---

> Your hint to include all js files in a big one is a path I can't take for several reasons (big team, many teams, many many js, big js, big website).

To clarify: I'm suggesting that you bundle your JavaScript files into a single file. This will allow you and your team to work on the files independently before compiling them all for loading in the browser. This is a common approach and works well with Turbolinks. If your JS bundle becomes very large then you may want to consider splitting it up into smaller ones.

**Comment by frederikhors** [comment]
I also tried without `type="module"`, it's the same.

Anyway thanks for your effort.

**Comment by frederikhors** [comment]
People with problem like this:

1. https://stackoverflow.com/questions/51751909/turbolinks-invokes-load-scripts-just-before-load-content-of-next-page

1. https://github.com/turbolinks/turbolinks/issues/107

1. 
https://github.com/turbolinks/turbolinks/issues/212

1. https://github.com/turbolinks/turbolinks/issues/28

**Comment by LucasArruda** [comment]
@frederikhors did you try this approach https://github.com/turbolinks/turbolinks/issues/212#issuecomment-376399218 ?

For me, removing async (or defer in your can) might solve the issue.

Couple other approaches you could follow:

Call `drawChart()`. If your function cannot be called twice – because that might happen when you move from pages (not first time you visit) – then you can check if chart is already draw.

**Comment by frederikhors** [comment]
@LucasArruda first of all thanks for your help.

Believe me I tried everything, also the code you linked (https://github.com/turbolinks/turbolinks/issues/212#issuecomment-376399218):

```js
Turbolinks.dispatch("turbolinks:load")
```

is the same if I use directly

```js
drawChart()
```

the same behaviour:

1. if I go from "Index" to "About" it calls `drawChart()`,
1. if I refresh the site from page "About" it call two times `drawChart()` as you can imagine:

so it's the same.

I also tried with `async`, without `async`, with `defer`, without `defer`, with nothing too.

> Call drawChart(). If your function cannot be called twice – because that might happen when you move from pages (not first time you visit) – then you can check if chart is already draw.

It is what I'm using right now.

**Comment by frederikhors** [comment]
@domchristie please, can you re-open this issue?

I have a **reproduction** of the problem here: https://glitch.com/edit/#!/join/dc628a17-3ccd-47b4-9921-8fb332aaebb1

@LucasArruda

**Comment by domchristie** [comment]
Thanks for the demonstration; it's really helpful. As is advised in #107 (https://github.com/turbolinks/turbolinks/issues/107#issuecomment-236436760), the official advice is: _: don’t load scripts this way_.

I think your best option is to include the `about.js` in both the `<head>` of `index.html` and `about.html` (or bundle it into a single file), then conditionally call `drawChart`.

Here is a remix of your example demonstrating that: https://glitch.com/edit/#!/join/0d5c83f7-6de0-4f21-ae23-2c1696b91f62

**Comment by frederikhors** [comment]
Ok. The problem is I have many pages (many and very different each other) and I wanna use different .js per page for speed and lightweight navigation (mobile). I think it's best to have chunks of about 200kb each to load when it needs...

And also conditionally calls are evaluated and called all together for a navigation of just a page or two. I don't like it too much.

Maybe Stimulus with conditional import() can help?

**Comment by LucasArruda** [comment]
@frederikhors as @domchrisite explained, what I did and told you to do will only work for you if you load everything in head and in all pages.

**Comment by domchristie** [comment]
I suppose it depends on how much JavaScript you're planning on loading. For the app I work on, we bundle about 60 JavaScript files (including jQuery, Turbolinks, rails-ujs, and about 50 components) into a single file, which comes to about 80kB gzipped. On each page load, a function loops through the array of component names, queries the DOM for elements that match, then initialises the component. It's a more generalised pattern to the demo of conditionally calling `drawChart`, but the principles are the same. 

The key benefit of using Turbolinks is that assets do not need to be reloaded or re-evaluated when the user clicks a link, so you might be missing out on this if you split up your JavaScript into lots of different bundles. You also need to be aware that once a script is loaded it will still be "active" on subsequent Turbolinks page loads, and so to avoid duplicate or "ghost" events generated by page-specific scripts, you'll need to tear them down. For these reasons, I'd generally avoid loading lots of scripts to handle page-specific behaviour. It can get messy and confusing.

Regarding Stimulus: Requiring Stimulus controllers on a per-page basis seems to work 🎉  (see: https://glitch.com/edit/#!/join/720b3cf1-e8ce-4fb1-9c45-49f2e06dc167) so you may want to experiment with that. The [Stimulus Discourse](https://discourse.stimulusjs.org/) might be able to help with issues you face going down that route.
