### ISSUE TITLE
Turbolinks.visit(url, { keep: 'flash' }); seems not to be working

### ISSUE THREAD

**Issue by matissg** [turbolinks/turbolinks#490]
In my `application.html.erb`
```
<body>
  <div class="row" id="flash" data-turbolinks-temporary></div>
</body>
```
I have `remote: true` form and in my `update.js.erb` there is this:
```
$('#flash').html('User is updated!');
Turbolinks.visit("<%= users_path %>", { keep: 'flash' });
```
At the moment I see my text is added to `flash`, however after Turbolinks does visit to `users_path` text is lost.

**I'm wondering if I'm doing something wrong or [this feature](https://www.rubydoc.info/github/rails/turbolinks) is not available in Turbolinks 5.2?** 
My stack: Rails 6, Ruby 2.6.3

**Comment by domchristie** [comment]
Hi @matissg. I spotted [your question on StackOverflow](https://stackoverflow.com/questions/57935148/rails-6-form-with-remote-true-and-turbolinks-not-showing-flash-after-redirect) and I have answered there (https://stackoverflow.com/a/57953502/783009).
