### ISSUE TITLE
Updating history independent of turbolinks

### ISSUE THREAD

**Issue by joker-777** [turbolinks/turbolinks#491]
Hi,

First of all, thanks for this amazing library. I have a question though. How would you recommend updating the history manually (without turbolinks) but then make it play nicely with the rest of the navigation via turbolinks.

What happens right now is, that when you continue navigating after doing some `history.pushState` operations and then go back with the browser back button, the page stays the same but the URL changes. I understand also why, because my `pushState` calls didn't have the `turbolinks` key but when I add this information to the state when using `pushState`, it triggers page loads, where I don't want them.

I'm confused that there isn't any documentation for this case. I can imagine that this use case is quite frequent.

Thanks!

**Comment by domchristie** [comment]
Hi @joker-777 

Thanks for raising this. Yes, this has come up once or twice (#61, #219). 

There is currently no _official_ way to push or replace state. As I mention in https://github.com/turbolinks/turbolinks/issues/219#issuecomment-424817249, there are a couple of public methods that you may wish to try, although as they are not documented, they may not be available in future versions. (e.g. `Turbolinks.uuid()` is no longer public as of v5.3.0-beta.1, so you may need to implement your own UUID.)

Given that there is already an open issue and an open pull request, I'll close this for now.

**Comment by joker-777** [comment]
Thanks a lot for your quick response. As far as I can see using

```js
Turbolinks.controller.pushHistoryWithLocationAndRestorationIdentifier(location, Turbolinks.uuid())
```

has the same effect as 

```js
window.history.pushState({custom: turbolinks_state}, null, create_url(content_tags))
```

It kind of works but it has this very ugly loading and slow loading effect when using the browser back/forward buttons.
