### ISSUE TITLE
5.2.1 is on rubygems but no tag/changelog here

### ISSUE THREAD

**Issue by AleksandrKudashkin** [turbolinks/turbolinks#493]
It is a little bit confusing that there is a patch version of the gem (5.2.1) on the rubygems from September 18 but there is nothing here (checked tags, releases, changelog...), so I couldn't check the changes. Would it be possible to update `Releases`?

**Comment by domchristie** [comment]
The change in gem version refers to [turbolinks-rails](https://github.com/turbolinks/turbolinks-rails). The diff from v5.2.0 to v5.2.1 can be see here: https://github.com/turbolinks/turbolinks-rails/compare/v5.2.0%E2%80%A6v5.2.1.

**Comment by AleksandrKudashkin** [comment]
Thank you
