### ISSUE TITLE
Cache causes image flickering in Chrome on Mac OS

### ISSUE THREAD

**Issue by gregblass** [turbolinks/turbolinks#494]
For pages that have images on them, if I leave the cache enabled, images will 'flicker' when the page is loaded (and replaces the cached version).

FWIW, this does not happen in Safari - but I'm still throwing this out there in hopes that there is something else that can be done. I feel like it'd be a shame to disable caching on any page that uses an image.

I wonder if Basecamp has experienced this and/or dealt with it in some way? @dhh @javan @sstephenson 

https://giphy.com/gifs/jqZeD2l1msxGEeK7W4

**Comment by javan** [comment]
Re-posting [my twitter reply](https://twitter.com/javan/status/1179013399327449088):
> Are your images HTTP-cached? They might be reloading if not. Check the Network inspector.

**Comment by gregblass** [comment]
Thank you @javan. I think the issue here might have to do with Active Storage. These images are uploaded by the user and going through Active Storage's http requests. I can't seem to find any information about caching images uploaded with Active Storage though.

**Comment by gregblass** [comment]
Oh my f-ing god. This was the culprit. I'm so sorry to waste your time!

![image](https://user-images.githubusercontent.com/279927/65968349-06cadf80-e431-11e9-9c83-5b2d2a48491f.png)

**Comment by Petercopter** [comment]
@gregblass Aaaaaaaaaargh! I was doing the same thing! dev tools was open to look at network on staging and debug something else. I saw the logo in the header flickering, and I was like *eww shiny* and luckily you saved me an hour or two 🎉
