### ISSUE TITLE
Only use cached snapshot for browser buttons

### ISSUE THREAD

**Issue by joker-777** [turbolinks/turbolinks#496]
Hello,

We want turbolinks to only use the cached snapshot when using the browser button (history) but not when navigating normally e.g. mouse click on links. Do you have any recommendations on how to configure Turbolinks to accomplish this?

Thanks!

**Comment by domchristie** [comment]
Hello, have you tried the `no-preview` cache directive?

```html
<head>
  ...
  <meta name="turbolinks-cache-control" content="no-preview">
</head>
```
(See https://github.com/turbolinks/turbolinks#opting-out-of-caching)

**Comment by joker-777** [comment]
Oh, wow, I completely missed this. This might be the solution. Thanks a lot. I will it immediately.

**Comment by joker-777** [comment]
@domchristie Thanks you so much for answering so quickly. It is exactly what we were looking for. No idea how I missed this when reading the documentation.
