### ISSUE TITLE
Going forward quickly after going back can break the history

### ISSUE THREAD

**Issue by joker-777** [turbolinks/turbolinks#498]
Hi,

We use turbolinks with `turbolinks-cache-control=no-preview`. The error only happens when you have more javascript to be executed when going to a page. When you go back in history and then very quickly go forward with the browser button while the javascript is still executed, then you stay on the page but the url changes correctly.

**Comment by domchristie** [comment]
Hi @joker-777 are you able to provide a demo of this behaviour? Thanks.

**Comment by domchristie** [comment]
Closing as inactive.
