### ISSUE TITLE
Permanent element on multiple browser tabs

### ISSUE THREAD

**Issue by xronos-i-am** [turbolinks/turbolinks#499]
We have permanent header block (shows signed user's related data). Our users usually open the site in multiple tabs. If user signs in on one tab when the header block changes on that tab. But other tabs stays the same while the user continue browsing until page refresh

That happens because permanent element migrates from current page to new one. Possible solution is to take permanent element loaded from server instead of cached one (if user visits page that loaded from server, not from history)

https://github.com/turbolinks/turbolinks/blob/master/src/snapshot_renderer.ts#L102-L103

**Comment by domchristie** [comment]
The permanent element feature is designed to work with existing elements. There is currently no way to request a specific permanent element for replacement.

You may wish to avoid using `data-turbolinks-permanent` when the user is not signed in. Alternatively, have you considered using WebSockets? You could notify all non-active tabs that the user has logged in. Each tab could then reload itself when notified.

**Comment by xronos-i-am** [comment]
Little hack for anyone who wants the same :
```html
  <div id="user-related-content" data-turbolinks-permanent-delay="">
  </div>
```
```javascript
document.addEventListener("turbolinks:load", () => {
  document.querySelectorAll("[data-turbolinks-permanent-delay]").forEach(el => {
    el.setAttribute("data-turbolinks-permanent", "")
    el.removeAttribute("data-turbolinks-permanent-delay")
  })
})
```

**Comment by domchristie** [comment]
Good to hear you've found a solution 👍
