### ISSUE TITLE
Make `turbolinks:request-end` event cancelable

### ISSUE THREAD

**Issue by wimleers** [turbolinks/turbolinks#50]
(Forgive me if I don't use Rails terminology. I'm coming at this from a Drupal background.)

Some sites want to have multiple themes (different layout + CSS) — e.g. when switching from "the front end" to "the back end". Whenever this happens, you don't want a Turbolinks page load, you want a full page load.

The obvious answer: `data-turbolinks="false"` should be sufficient.

But it's not always so simple. Sometimes, the theme may be selected/negotiated based on complex conditions. Not just based on the path prefix (`/admin/foo` -> the `admin/` prefix) or some similarly simple condition. But perhaps it's based on permissions, or even time of day (think e-commerce site with time-limited promotions).

In this case, it'd be helpful if the `turbolinks:request-end` event was cancelable. Upon detecting a theme change (through some header, or the presence of some HTML) in a listener for that event, the event could be canceled and Turbolinks would perform a full page load.

Thanks for considering to support this.

**Comment by sstephenson** [comment]
I don’t think we want to make `request-end` cancelable, nor do I think it’d be the right place to do what you want. However, you ought to be able to use Turbolinks’ [asset tracking feature](https://github.com/turbolinks/turbolinks#reloading-when-assets-change) to reload when the theme changes.

The documentation shows how to use `data-turbolinks-track=reload` for `<script>` and `<link>` tags, but it works for `<meta>` tags, too:

```html
<meta name="drupal-theme" content="..." data-turbolinks-track="reload">
```

Ensure each page has this in its `<head>`. When the content value changes, Turbolinks will perform a full reload.
