### ISSUE TITLE
Turbolinks and Stimulus still alive?

### ISSUE THREAD

**Issue by thelucid** [turbolinks/turbolinks#500]
Apologies if this is not the right place to ask. Are Turbolinks and Stimulus still alive and kicking i.e. are Basecamp still focussing on them or using some other solution now? There doesn't appear to be much activity on the repos. Just starting a new Rails 6 project and don't want to head down the wrong path.

**Comment by panoply** [comment]
I wouldn't worry so much about this. Turbolinks and Stimulus are still active. I noticed Sam rolled out a project the other day which included Stimulus. Stimulus and Turbolinks are the perfect solution to statically generated PWA's and they have steady community growth. Moving the codebase to Typescript is clear indication that the future of Turbolinks is safe.

**Comment by kaspth** [comment]
They’re still very much alive at Basecamp, there’s not anything ready to announce just yet though. Besides the Classes and Values PR on Stimulus or the Remote Ruby episode with Sam and Javan from earlier this year.

**Comment by dwightwatson** [comment]
Is there any chance of getting a more recently tagged release of Turbolinks then?

There's a bugfix on master that fixes redirect tests with Rails 6.0.0 (see rails/rails#36989).

**Comment by javan** [comment]
Confirmed! Both are alive and well.
