### ISSUE TITLE
Blank page the first time the page is loaded

### ISSUE THREAD

**Issue by GiacomoK** [turbolinks/turbolinks#502]
Hi,
I am trying to use turbolinks (installed with tag script instead of npm) but I get a blank page when I first load the page (even if the html code of the page is there).

If I reload the page it loads itself well.

I do not know where start to look for solving this behaviour.

**Comment by domchristie** [comment]
Hi @GiacomoK,
Were you able to solve your problem? If not, could you post an example that demonstrates the issue? Thanks.

**Comment by domchristie** [comment]
Closing as inactive
