### ISSUE TITLE
Preventing document merging when the file extension(other than .html) is not present in URL 

### ISSUE THREAD

**Issue by MLiapkalo** [turbolinks/turbolinks#503]
Given the basic html page with link which leads to the PDF document. After visiting this link with Turbolinks (which is like `/some-link-to-pdf`) the result would be like on the screenshot below

![image](https://user-images.githubusercontent.com/43294318/68595594-6d1c3680-04a2-11ea-81db-aaaa2b9f3a9a.png)

This is the result of Turbolinks trying to merge pdf as a regular html.
In case of file extension being present in url( like `/some-document.pdf`) everything works as expected.

**Comment by domchristie** [comment]
What is the `content-type` of the response header when requesting the PDF? When it's not ["HTML-like"](https://github.com/turbolinks/turbolinks/blob/b85b343f554371bea9aee4d2165b99a2b0522211/src/http_request.ts#L150-L152), [Turbolinks reloads the location](https://github.com/turbolinks/turbolinks/blob/b85b343f554371bea9aee4d2165b99a2b0522211/src/browser_adapter.ts#L52-L53). This effectively performs a fresh visit to the link destination.

As you have discovered, the best way handle this situation is to ensure non-HTML links have extensions (e.g. `.pdf`).

**Comment by domchristie** [comment]
Closing as solved/inactive
