### ISSUE TITLE
Update lang attribute in html to make site more accessible

### ISSUE THREAD

**Issue by sophieheb** [turbolinks/turbolinks#504]
We have a site which functions in multiple languages. We haven't included a lang attribute in our HTML so far and are using a different system to handle change of language throughout the site.

However we had a accessibility review done and a big problem was this lack of lang attribute in the html tag for screenreaders: https://accessibility.psu.edu/foreignlanguages/langtaghtml/

We need some way to conditionally re-render this lang attribute in the html tag only when the language has been changed to ensure that all of our users are able to access the site in all languages.

**Comment by domchristie** [comment]
Turbolinks merges the contents of the `head`, which provides an opportunity to render metadata on each page load. You may wish to try adding a custom `meta` tag containing the language, then updating the `html` `lang` attribute on `turbolinks:load`.

For example, given this HTML:

```html
<html lang="en">
  <head>
    <meta name="language" content="es">
```

and including this snippet in your main application JavaScript:

```js
document.addEventListener('turbolinks:load', function () {
  var meta = document.querySelector('meta[name=language]')
  var language = meta.getAttribute('content')
  document.documentElement.setAttribute('lang', language)
})
```

the resultant HTML should be:

```html
<html lang="es">
  <head>
    <meta name="language" content="es">
```

I'm not sure how well screenreaders handle dynamically updated `lang` attributes, but it might be worth a try.

Alternatively, you could force a full reload when the `language` meta tag changes:

```html
<html lang="en">
  <head>
    <meta name="language" content="en" data-turbolinks-track="reload">
```

(no additional JS required)

**Comment by domchristie** [comment]
Closing as fixed by https://github.com/turbolinks/turbolinks/issues/504#issuecomment-564785786. Feel free to reopen if the proposed solutions do not work.
