### ISSUE TITLE
Clear previous loaded data

### ISSUE THREAD

**Issue by willyarisky** [turbolinks/turbolinks#505]
Previous data loaded by fetch from API not cleared when access another page, how to clear the loaded data from js request before access another page?
For example on page list.html I load a JSON data list of the task when I move to home the data still accessible and not cleared.

**Comment by domchristie** [comment]
Hi @willyarisky, you may find the following sections of the readme useful:

- [Building Your Turbolinks Application](https://github.com/turbolinks/turbolinks#building-your-turbolinks-application) - particularly the first few paragraphs
- [Preparing the Page to be Cached](https://github.com/turbolinks/turbolinks#preparing-the-page-to-be-cached)
