### ISSUE TITLE
Refresh page using F5 or CTRL + R is not requesting with complete params

### ISSUE THREAD

**Issue by kumaranubhaw** [turbolinks/turbolinks#506]
My controller method needs id to fetch data from database table which will be sent in params. When using turbolinks, when refresh page using the key F5 and CTRL + R the params to the controller contains only action and controller name only not the id.

Note: Without using turbolinks when refreshing page using  the key F5 and CTRL + R, I was getting prompt as "The page you are searching for uses the information you entered. If you return to this page, you may have to try again. Do you want to continue?". After confirming, the request to server is with the complete params.

**Comment by domchristie** [comment]
> My controller method needs id to fetch data from database table which will be sent in params.

Is this a `POST`? If so, you might be experiencing the bug described in #495

**Comment by kumaranubhaw** [comment]
@domchristie  Yes, It is a POST request. I have the updated turbolinks with the fix but doesnot work for me.

**Comment by kumaranubhaw** [comment]
@domchristie No its a GET request.

**Comment by domchristie** [comment]
Are you able to share an example which demonstrates the problem? Thanks

**Comment by kumaranubhaw** [comment]
Here is the demontration code for that error
https://github.com/kumaranubhaw/default_refresh_page_error 

For setup please read the README Note.
Thank you

**Comment by domchristie** [comment]
Thanks for taking the time to create an example. The form you are using does perform a `POST` request, so you are seeing the issue described in #495 

By default the Rails `form_tag` helper creates a `form` with `method="post"`. To make this a `GET`, change your view template to look something like:

```erb
<%= form_tag({ :action => 'get_detail' }, :method => :get) do %>
…
<% end %>
```

This will put the form parameters in the browser's address bar, so when refreshing, the parameters are sent as expected. I hope that helps.

**Comment by kumaranubhaw** [comment]
Thank you for the help, It worked fine after using the get method in form_tag.
