### ISSUE TITLE
Trubolinks.visit not triggering on the same page

### ISSUE THREAD

**Issue by aksharj** [turbolinks/turbolinks#507]
Hi,

Thanks for a great gem. 

In our application, we have integrated Tableau JS API, using which we integrate tableau dashboards into our rails application.

We have a dropdown on a page which calls `Turbolinks.visit(url, {action: 'replace'})`, this opens different dashboards for the user to be viewed. 

The user opens a dashboard by clicking the dropdown, applies different filters which changes the page view but **does not change the page URL**. 

when the user tries to click the same dropdown option again (`Turbolinks.visit(url, {action: 'replace'})`) to go back to the old view before applying filters, the dropdown click does not reload / open the URL.

I there a way I can force Turbolink.visit(url, {action: replace}) to always visit the page even if its on the same page?

Any work around as to how to do this would be great.

**Comment by domchristie** [comment]
Hi @aksharj 
I've not been able to reproduce this. Are you able to post an example which demonstrates the problem? Thanks.

**Comment by domchristie** [comment]
Closing as inactive.

**Comment by aksharj** [comment]
hi @domchristie,

sorry for a really late reply on this. 

If you are on a page and try to use Turbolinks.visit(window.location.url) // url of the current page. 
nothing happens, probably because we are trying to visit the page on which we are already on.

If there a way to achieve window.location.reload() using turbolinks i.e. to visit the same page

Looking forward to your reply, Thanks.

**Comment by aksharj** [comment]
@domchristie,

my apologies, its working as expected, I had the below code which was preventing the page reload on the same page

```
$(document).on('turbolinks:before-visit', function(event) {
            if (event.originalEvent.data.url == window.location.href) {
                event.preventDefault();
            }
        });
```
