### ISSUE TITLE
Olark chat with Turbolinks

### ISSUE THREAD

**Issue by maguri** [turbolinks/turbolinks#509]
Hello,

I'm using the [Olark](https://www.olark.com/api) chat with turbolinks into a Rails application, and the issue is that turbolinks does not take into account the chat inserted with JS into an iframe after render the page.

how could tell turbolinks to start caching after load the chat?

- Olark has this event [api_chat_onready](https://www.olark.com/api#api_chat_onready) to detect when the Olark chatbox has loaded.

I was thinking about store the chat into the turbolinks cache, but it is not working.

Any idea?

**Comment by markets** [comment]
This would be easier with #457 :)

**Comment by adrienpoly** [comment]
@maguri I am not familiar with Olark but for Drift I used a permanent Turbolinks tag and it works well

https://gethelp.drift.com/hc/en-us/articles/360019349734-Install-Drift-on-a-Turbolinks-site

**Comment by tridnguyen** [comment]
Using a permanent Turbolinks tag won't work for Olark because it appends an iframe and a div directly to the body tag.  Olark actually injects a script tag and multiple style tags into the head, as well as the previously mentioned iframe and div elements in the body.

What I did to make it work with Turbolinks is to create two functions, one executes on turbolinks:load and one executes on turbolinks:before-cache.  The load event contains a line to delete the window.olark object and the script block that olark provides to install it.  The second function basically removes the elements that were injected by Olark:

```JavaScript
export default class Olark {
  static init() {
    delete window.olark;

    // olark snippet, be sure to update your site ID
    ;(function(o,l,a,r,k,y){if(o.olark)return;        
        r="script";y=l.createElement(r);r=l.getElementsByTagName(r)[0];        
        y.async=1;y.src="//"+a;r.parentNode.insertBefore(y,r);        
        y=o.olark=function(){k.s.push(arguments);k.t.push(+new Date)};        
        y.extend=function(i,j){y("extend",i,j)};        
        y.identify=function(i){y("identify",k.i=i)};        
        y.configure=function(i,j){y("configure",i,j);k.c[i]=j};        
        k=y._={s:[],t:[+new Date],c:{},l:a};        
        })(window,document,"static.olark.com/jsclient/loader.js");        
        /* Add configuration calls below this comment */        
        olark.identify('YOUR_SITE_ID');
  }

  static cleanUp() {
    document.querySelectorAll('script[src*="olark"], [data-olark]').forEach(element => {
      element.parentNode.removeChild(element);
    });
  }
}

document.addEventListener('turbolinks:load', Olark.init);
document.addEventListener('turbolinks:load', Olark.init);
```

**Comment by domchristie** [comment]
Thanks for digging into this @tridnguyen!

**Comment by markets** [comment]
Thanks @tridnguyen! just for future readers, I think the listeners should be defined this way:

```js
document.addEventListener('turbolinks:load', Olark.init);
document.addEventListener('turbolinks:before-cache', Olark.cleanUp);
```

**Comment by tridnguyen** [comment]
> Thanks @tridnguyen! just for future readers, I think the listeners should be defined this way:
> 
> ```js
> document.addEventListener('turbolinks:load', Olark.init);
> document.addEventListener('turbolinks:before-cache', Olark.cleanUp);
> ```

That's correct, thanks for catching that.  My original post has been updated.
