### ISSUE TITLE
Event naming is inconsistent

### ISSUE THREAD

**Issue by wimleers** [turbolinks/turbolinks#51]
The events are:

- `click`
- `before-visit`
- `visit`
- `request-start`
- `request-end`
- `before-cache`
- `before-render`
- `render`
- `load`

The pattern here is:
- `<action>`
- `before-<action>`

The only exceptions are `request-start` and `request-end`. This is the inconsistency.

Wouldn't it be better if they were named `before-request` and `after-request`? Or, alternatively, `request` and `receive`.

**Comment by sstephenson** [comment]
I agree that `request-start` and `request-end` are misfits. I don’t think your proposed event names are quite right either, though. I’ll leave this open for discussion and we’ll plan on addressing it before the final 5.0.0 release.

**Comment by sstephenson** [comment]
Leaning towards `before-request` and `response`, btw.

**Comment by wimleers** [comment]
Sounds great!

**Comment by BrokenChair** [comment]
Shouldn't it be `after-response` if we're being pedantic?

**Comment by sstephenson** [comment]
After letting this sit for a few months, I think `request-start` and `request-end` are the best names for these specific events. Let’s address each alternative proposal individually:

* `before-request` and `after-request`: `before-request` would be conventional, but we don’t have any events named `after-`.
* `before-request` and `request`: It doesn’t feel right to listen for a `request` event to determine when a request has _completed_.
* `request` and `receive`: The two events we fire should be enough to implement a progress indicator. If a network request fails, you never _receive_ anything. If we rename and restrict the second event to only fire on successful responses, we need to introduce a third event so you can tell when a request ends unsuccessfully. And what would we call it? `request-end`? :)
* `before-request` and `response`, or `after-response`: See above.
