### ISSUE TITLE
Disable progress bar on restoration visit

### ISSUE THREAD

**Issue by rept** [turbolinks/turbolinks#511]
Turbolinks is working great.  Thanks for the library.

I'm using the progress bar, but I notice that on restoration visits (from cache): 

1. the user presses back
2. page displays instantly
3. progress bar appears
4. progress bar disappears
5. page looks exactly as in step 2

So for the user it's confusing since it looks like the page is ready, and then the bar appears.

Is this the intended way it should behave?  Is there a way to not show the progress bar on restoration visits?

**Comment by domchristie** [comment]
Hi @rept 
I'm not seeing this behaviour on the [minimal demo](https://turbolinks-demo.glitch.me/) (using Safari/Firefox/Chrome on Mac OS). Are you able to post a reproduction of this?

**Comment by domchristie** [comment]
Closing as inactive.
