### ISSUE TITLE
Turbolinks interfering with links my Rails 6 app

### ISSUE THREAD

**Issue by zx1301** [turbolinks/turbolinks#513]
I already posted this as a [question](https://stackoverflow.com/questions/59763878/rails-6-app-links-not-working-until-refresh) on stackoverflow, but I thought maybe I could get help here.
I was trying to follow [this tutorial](https://www.youtube.com/watch?time_continue=62&v=ibxlNN73UTY&feature=emb_logol) by GoRails. to add an autocomplete feature to my Rails 6 app. After following the tutorial I got the search bar to work as he demonstrates in the video, but now whenever I click on a link in my app, my url changes accordingly but I see this page:
![image](https://user-images.githubusercontent.com/35082619/72589873-7377c600-38ca-11ea-91f4-2e5bf64959ae.png)
If I refresh the page, the app directs me to the page that the url shows. Even if I comment out the js files for easyautocomplete and I leave these lines in the head of my application.html.erb in layouts, I still see the problem
```
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'  %>
<%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'  %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
```

If I get rid of the "require("turbolinks").start()" in my application.js, then the problem goes away but I still want to use turbolinks:
```
require('@rails/ujs').start()
require('turbolinks').start()
require('@rails/activestorage').start()
require('channels')
require('jquery')

//= require jquery
//= require popper
//= require bootstrap-sprockets
//= require jquery.easy-autocomplete
```
Also, I see this error in my browser console:
![image](https://user-images.githubusercontent.com/35082619/72590457-b5edd280-38cb-11ea-8c98-e90e7091c0af.png)

I also created a sample app that also has the same problem in this repository: https://github.com/zx1301/sampleAppTurbolinksError I'm using ruby 2.6.2 and rails 6.0.2. In its current state I commented out the lines linking the css and js files to easyAutocomplete and the problem persists unless I disable turbolinks by commenting out turbolinks in application.js.

**Comment by domchristie** [comment]
Your Colorlib template calls [`document.write(new Date().getFullYear())`](https://github.com/zx1301/sampleAppTurbolinksError/blob/28303941b2ee99ec0166b7cfba672adabab8cce5/app/views/pages/index.html.erb#L1369), causing "2020" to render. If you replace this with a hard-coded "2020", this problem should be solved.

---

Your template uses quite a few third-party libraries placed in the `<body>`. Turbolinks works best when scripts are compiled and loaded in the `<head>`. Also, some third-party libraries also don't play nicely with the Turbolinks approach, so you may want to consider whether Turbolinks is the right fit for this.

I hope that helps.
