### ISSUE TITLE
Built in support for route specific events

### ISSUE THREAD

**Issue by lukechu10** [turbolinks/turbolinks#514]
**Is your feature request related to a problem? Please describe.**
It would be great if there was a way to the `turbolinks:load` event but that only triggers on specific pages. For example, something like this would be great:
```js
document.attachEventHandlers("turbolinks:load-unique", () => {
    // only executes on page loads where the page is the same as the one the code is on
});
```

**Describe alternatives you've considered**
The current way I am doing this is by adding an id to the `<body>` tag describing which page this is on and than having a `switch` statement inside the event handler. This is not very convenient and there should be a better method of doing this.

One way I can immediately think of for implementing this is by adding a `url` parameter together with the handler and only invoke it if the `url` matches `location.href`

**Comment by domchristie** [comment]
Hi @lukechu10, there are a few ways to handle this. [Turbolinks up high, Stimulus down low](https://stimulusjs.org/handbook/origin#turbolinks-up-high-stimulus-down-low) describes Basecamp's approach. Basically, Turbolinks is responsible for handling clicks, rendering, and caching; whereas [Stimulus](https://stimulusjs.org/) handles component behaviours.

Other ideas are mentioned in #305, #310, and #364.
Hope that helps.
