### ISSUE TITLE
Page loads twice along with scripts when visiting cached page 

### ISSUE THREAD

**Issue by masudhossain** [turbolinks/turbolinks#515]
I've noticed that the pages that takes a little extra length of time and is cached, it loads the page twice. Is there any work around for this?

**Comment by domchristie** [comment]
Hi @masudhossain, it sounds like you're seeing Turbolinks previews. When revisiting a page, Turbolinks displays a cached version of the page, providing immediate feedback and the impression of instantaneous loads. Once the fresh version has loaded, the preview is replaced. You can read more about this in [Understanding Caching](https://github.com/turbolinks/turbolinks#understanding-caching) section of the readme.

If the preview behaviour is undesirable, you can disabled previews using the "no-preview" cache directive:

```html
<head>
  ...
  <meta name="turbolinks-cache-control" content="no-preview">
</head>
```
Hope that helps.
