### ISSUE TITLE
Support scroll-padding + anchor links

### ISSUE THREAD

**Issue by robacarp** [turbolinks/turbolinks#518]
When I add a `display: fixed; top: 0;` element to my document, such as a floating toolbar, it would be nice for the scrollToAnchor to work so that the content can be shown. For browser-handled anchor links, I can add `scroll-padding-top: NNpx;` to the body and that works well. For turbolinks-handled-anchors, that doesn't work.

Clicking on a turbolinks handled anchor has the strange effect of taking you to juuuust the wrong place in the scroll, but then refreshing the page corrects it, which is a confusing user interaction.

One alternative is to disable turbolinks on the anchor links within a page. This works, except when linking to a page from another page and is an acceptable workaround for now.

**Comment by domchristie** [comment]
Hi @robacarp, `scroll-padding` looks _really_ useful! I've not been able to reproduce this issue across all browsers: Firefox and Chrome appear to behave as expected, observing `scroll-padding` values, but Safari (macOS) ignores them.

It seems like this is an issue with Safari's implementation of the [CSS Scroll Snap Module](https://drafts.csswg.org/css-scroll-snap-1/). A [recent update to the recommendation](https://drafts.csswg.org/css-scroll-snap-1/#change-2019-clarify-nonsnapping) suggests that `scroll-padding` should be observed when navigating to anchors (even if scroll snapping is disabled).

To demonstrate the issue, check out [this example](https://entertaining-flashy-order.glitch.me/). It doesn't use Turbolinks, but the JavaScript handling the `<button>` mirrors its implementation.
