### ISSUE TITLE
Scroll to top on restoration visits when scrollPosition is empty is bad for UX

### ISSUE THREAD

**Issue by berndartmueller** [turbolinks/turbolinks#519]
Hello,

I was experiencing scroll to top jumps on iOS devices whenever I use swipe back gesture. More concrete, I had turbolinks for certain pages disabled, therefore no scroll position was stored. Navigating back it tried to restore scroll position with `Visit.performScroll()`, but because of the missing scroll position, it simply jumps to the top. This is a little bit annoying when you have a long list of items, you want to go back from a detail page and you have to scroll back to the previous scroll position manually.

Is there any particular reason to hard code this behaviour and let it jump to the top? Why not only jump to a scroll position whenever previous scroll position was stored and is available? For testing purposes I removed this function call to `scrollToTop()` and had no issues at all. Maybe I'm missing something.

Thanks a lot!

**Comment by domchristie** [comment]
> More concrete, I had turbolinks for certain pages disabled, therefore no scroll position was stored.

Hi @berndartmueller, would you be able to demonstrate this with an example? https://turbolinks-demo.glitch.me/ might be useful as a starting point. Thanks!

**Comment by domchristie** [comment]
Closing as inactive.
