### ISSUE TITLE
Navigation performance api

### ISSUE THREAD

**Issue by aksharj** [turbolinks/turbolinks#520]
Hi All,
I am trying to monitor the load times of our application which uses turbolinks. However, when I am using the navigation performance API, the `requestStart` seems to be always the same.

In our application we also embed tableau dashboards, I am trying to measure how much time the dashboard is taking to load, tableau provides a event called `onFirstInteractive` which is fired when a embedded dashboard is loaded.

The page that has a embedded dashboard can be opened by clicking a link or directly copy / pasting a link in the browser.

I am trying to access the time when a link was clicked to open a dashboard by accessing `window.performance.timing.requestStart`, however it always is the same.

Can you please guide me in accessing the actual start time of when a request was started using navigation performance API?

**Comment by domchristie** [comment]
Hi @aksharj, timing information for Turbolinks loads is available in the `event.data.timing` event object on `turbolinks:load`. e.g.

```js
document.addEventListener('turbolinks:load', function (event) {
  // event.data.timing === { requestEnd: …, requestStart: …, visitEnd: … visitStart: … }
})
```

Hope that helps.
