### ISSUE TITLE
Turbolinks caching CORS error on video tag poster attribute

### ISSUE THREAD

**Issue by 127** [turbolinks/turbolinks#527]
Got a problem with turbolinks cache on video poster attribute — images fail to load from another domain because of CORS error. CORS is correct, doublechecked that.
And disabling cache with ```<meta name="turbolinks-cache-control" content="no-cache">``` works like a charm.
Are there any other ways to exclude this cache without decaching all page?

**Comment by domchristie** [comment]
Hi @127, are you able to post a demonstration of this? Thanks!

**Comment by 127** [comment]
Removed turbolinks from project
