### ISSUE TITLE
rack-mini-profiler doesn't display on Turbolinks page loads

### ISSUE THREAD

**Issue by cannikin** [turbolinks/turbolinks#53]
I just added the `rack-mini-profiler` gem and everything displays fine on full page loads (hitting ENTER in the URL bar, or reloading) but on Turbolinks-loaded pages the profiler never shows.

If you navigate a few pages, then do a full page load, the profiler will show an "x 4" or similar letting you know there were four total pages that were captured since the last time you saw it:

![image](https://cloud.githubusercontent.com/assets/300/14002002/5dea5c68-f106-11e5-8817-593eb44ca383.png)

And then you can expand it to see details for each page:

![image](https://cloud.githubusercontent.com/assets/300/14002011/6b7e0bcc-f106-11e5-9a9b-8a4a7a007d97.png)

But ideally it should show the profiler on every load.

Is there maybe a combination of `data-turbolinks` attributes I can drop into my page that'll allow the profiler to show every time? If so I'd happily pull-request some changes to the README to let others know how to do the same.

**EDIT**

Here's the script include that's appended by `rack-mini-profiler` before the closing body tag:

    <script async type="text/javascript" id="mini-profiler"
      src="/mini-profiler-resources/includes.js?v=12b4b45a3c42e6e15503d7a03810ff33" 
      data-version="12b4b45a3c42e6e15503d7a03810ff33" data-path="/mini-profiler-resources/" 
      data-current-id="v83213qtk53ogdtcmqkt" data-ids="v83213qtk53ogdtcmqkt" 
      data-position="left" data-trivial="false" data-children="false" data-max-traces="10" 
      data-controls="false" data-authorized="true" data-toggle-shortcut="Alt+P" 
      data-start-hidden="false" data-collapse-results="true">
    </script>

**Comment by cannikin** [comment]
Over at rack-mini-profiler someone pointed out this is probably due to #9. Nevermind!

**Comment by packagethief** [comment]
Somewhat related, I noticed that rack-mini-profiler's JavaScript is [listening for Turbolinks Classic events](https://github.com/MiniProfiler/rack-mini-profiler/blob/master/lib/html/includes.js#L406-L410).
