### ISSUE TITLE
Permanent not working with custom elements

### ISSUE THREAD

**Issue by lukechu10** [turbolinks/turbolinks#531]
**Describe the bug**
I have an element with `data-turbolinks-permanent` that is also a custom element. When I navigate, the element is reset.

**To Reproduce**
https://glitch.com/~tender-tasteful-guavaberry

1. Wait for the page to load. There should be an element that says "Test".
2. After one second, it should change to "Test 2".
3. Navigate to another page, notice that it changes back to "Test". Notice also that the element is marked with `data-turbolinks-permanent`

**Expected behavior**
The text should remain "Test 2" on navigation.

**Details (please complete the following information):**
 - Operating System: Windows and MacOS
 - Browser Chrome and Electron
 - Turbolinks Version: 5.2.0

**Screenshots**

**Additional context**

**Comment by javan** [comment]
Custom element `connectedCallback()` [lifecycle methods](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements#Using_the_lifecycle_callbacks) are:

> Invoked each time the custom element is appended into a document-connected element. This will happen each time the node is moved, and may happen before the element's contents have been fully parsed. 

So, your element is resetting itself when moved from page one to page two by Turbolinks. You can fix that by moving the implementation to the constructor so it only runs once, e.g.:
```js
class Test extends HTMLDivElement {
  constructor() {
    super();
    this.innerHTML = "<p>Test</p>"
    setTimeout(() => {
      this.innerHTML = "<p>Test 2</p>"
    }, 1000);
  }
}
```
Example: https://glitch.com/~stump-subdued-newt
