### ISSUE TITLE
Images cached by Turbolinks

### ISSUE THREAD

**Issue by lepieru** [turbolinks/turbolinks#532]
I just add Turbolinks to an empty project (created with Phoenix with the `mix phx.new app_name` command). It works as expected but I perceive a flickering with the header logo image on page changes as you can see on [this Turbolinks app example](https://d33wubrfki0l68.cloudfront.net/90a69695f840fccfcd9bbd559a9af9665ab509e3/29654/public/images/turbolinks_transition.gif) where we can note the same behavior. However, it's a kind of image the browser require on mostly all pages.

Do a Turbolinks image caching feature could fix this flickering?

Moreover, this feature could lower the bandwidth usage and speed up the full page load IMHO.

**Comment by javan** [comment]
Possibly related: https://github.com/turbolinks/turbolinks/issues/494. Are your images HTTP-cached? Do you have caching disabled in the web inspector?

**Comment by lepieru** [comment]
You right. Caching was disabled in my Chromium Web inspector, I don't know why.

Thank you :)
