### ISSUE TITLE
Turbolinks not firing load event on Rails 6 with Webpacker

### ISSUE THREAD

**Issue by woniesong92** [turbolinks/turbolinks#534]
**Describe the bug**
The event `turbolinks:load` doesn't get fired when I navigate to a new page.

**To Reproduce**

I created a fresh [Rails app](https://github.com/woniesong92/turbolinks-bug-with-webpack) so it's easy to reproduce the bug. You can also follow along the steps below.

```html
// index.html.erb
<div id="some-id"></div>
<%= javascript_pack_tag 'SomeComponent', 'data-turbolinks-track': 'reload' %>
```

```js
// SomeComponent.js
const renderComponent = () => {
  const node = document.getElementById("some-id");
  const data = JSON.parse(node.getAttribute("data"));

  ReactDOM.render(<SomeComponent {...data} />, node);
};

// Listen to `turbolinks:load` event
document.addEventListener("turbolinks:load", renderComponent);
```

1. Start from some other page than `index.html.erb`
2. Navigate to `index.html.erb`
3. Notice that `SomeComponent` isn't rendered because `turbolinks:load` isn't fired
4. Refresh the page
5. Notice that `SomeComponent` is rendered because `turbolinks:load` is fired

**Expected behavior**
1. Start from some other page than `index.html.erb`
2. Go to the page that renders `index.html.erb`
3. `SomeComponent` is rendered because `turbolinks:load` is fired

**Details (please complete the following information):**
 - MacOS Catalina
 - Chrome Version 80.0
 - Rails 6.0.2.2
 - ruby 2.7.1p83
 - turbolinks 5.2.1
 - webpacker 4.2.2

**Additional context**
I was able to reproduce this problem in a clean project that uses the latest Rails, Webpacker, Turbolinks packages. The following links might be related but none of them seemed to solve the problem but only worked around it by disabling turbolinks.

- https://github.com/rails/webpacker/issues/354
- https://github.com/turbolinks/turbolinks/issues/477

I also posted this issue on https://github.com/rails/webpacker/issues/2527.

**Comment by domchristie** [comment]
`turbolinks:load` is always fired when Turbolinks loads a page via AJAX, but it does not wait for scripts to load. In your example, `turbolinks:load` is being fired _before_ `SomeComponent.js` is loaded and executed. When a page is "fully" loaded e.g. via a refresh, Turbolinks fires `turbolinks:load` on `DOMContentLoaded`, so in this case it _will_ wait for scripts to load.

If you're loading some scripts at the end of the `<body>` element, you may not need to listen out for `turbolinks:load`; the DOM should be accessible without having to wait for the load event.

Hope that helps.

**Comment by ykamin-booth** [comment]
Having the same issue here and it seems pretty unintuitive that turbolinks:load is fired before the javascript_pack_tag is loaded. Got it to work by adding the following to my packs based on Issue #354 referenced above, but not a huge fan of the workaround: 

if (!Turbolinks) {
    location.reload();
}

Turbolinks.dispatch("turbolinks:load");
