### ISSUE TITLE
Firefox appears to set autocomplete form fields to incorrect values after page render

### ISSUE THREAD

**Issue by jonknapp** [turbolinks/turbolinks#536]
Logging an issue in case it's helpful to others through the magic of SEO. I'm not convinced this is a Turbolinks bug and only recently started occurring in specific browsers. I'm completely fine if this is closed quickly; just looking to save others from a time vacuum if they run into a similar issue.

**Describe the bug**
In latest Firefox (v75), the browser appears to more aggressively use prior form field values regardless of the url being different. The fields in question used [bootstrap-select](https://developer.snapappointments.com/bootstrap-select/) to hijack the `<select>` fields on render.

If I disable TurboLinks the issue goes away. If I keep TurboLinks enabled and change the field or form to use `autocomplete="off"` then the issue also goes away. My guess is that the browser is doing a final pass at trying to be helpful and auto-selecting a prior field value using a new heuristic that isn't dependent on the url being exact.

**To Reproduce**
Guessing this is very specific to my app, but briefly:

1. Visit url with dropdowns that are managed by `bootstrap-select`; ex: `users/1/edit`
2. Visit another url; ex: `users/`
3. Visit a different url with similar dropdowns managed by `bootstrap-select`; ex: `users/2/edit`
4. Dropdowns show the selected options from step 1, not the ones in the server returned html response

**Expected behavior**
I'd expect the selected option in the `bootstrap-select` dropdown to mirror what the server returned as html. This has worked properly for quite awhile and was only recently found as an issue.

**Details (please complete the following information):**
 - Operating System: macOS
 - Browser: Firefox v75
 - Turbolinks Version: v5.2.0

**Comment by domchristie** [comment]
Hi @jonknapp I've not been able to reproduce this with the steps outlined above. Are you able to remix [this example](https://glitch.com/edit/#!/join/4b2f91c1-4e5f-4b20-97b4-7d53cd991706) to demonstrate? Thanks.

**Comment by jonknapp** [comment]
Excellent way to set that up! Thanks!

I was able to get a semi-recreation of the issue at https://lavish-jeweled-dish.glitch.me with the code at https://glitch.com/edit/#!/lavish-jeweled-dish

I changed library versions and sources a bit, added some `<form>` stuff and can see the autocomplete issue by performing the following:

1. view [index.html](https://lavish-jeweled-dish.glitch.me/index.html)
2. select a value from the dropdown
3. refresh the page; prior value is filled in
4. go to [one.html](https://lavish-jeweled-dish.glitch.me/one.html)
5. refresh the page; prior value from index is filled in

**Comment by jonknapp** [comment]
Tweaked it just a bit so that [two.html](https://lavish-jeweled-dish.glitch.me/two.html) starts with the `Barbecue` pre-selected via html attributes. It did show the correct value at first, but if I refresh the page it shows the original value selected in step 2 above.

**Comment by domchristie** [comment]
👍  Great, thanks for clarifying. I can see this issue now, even without jQuery/Bootstrap/bootstrap-select (see: https://horse-eastern-coral.glitch.me/)

Given that this is occurring after full page refreshes, and that Turbolinks doesn't really do much until a link is clicked, I suppose this is a bug/quirk with Firefox's caching behaviour. It appears that Firefox clears this cache once a new page is fully loaded (i.e. without Turbolinks and not a refresh), whereas perhaps it should be cleared when the history state is pushed/replaced?

It might be worth raising this as a Firefox bug. In the meantime, I reckon `autocomplete="off"` is your best option.

Thanks for raising this!

**Comment by jonknapp** [comment]
Thanks for walking through this with me, bug filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1630942
