### ISSUE TITLE
Back button for page with hash #, turbolinks reload page.

### ISSUE THREAD

**Issue by hortigado** [turbolinks/turbolinks#537]
**Describe the bug**
Hello, I am using a photoswipe library that when clicking on an image places in the url #&gid=1 to zoom it. With the back button of the browser the anchor is removed and the zoom is removed. The problem with turbolinks is that it reloads the page by clicking back, how could I fix it so that turbolinks popstate does not work with url hash. Thank you

**Comment by domchristie** [comment]
Hi @hortigado, it sounds like your photoswipe library is changing the url via `history.pushState` or `history.replaceState`, and therefore may not be compatible with the way Turbolinks handles Back navigations.

When changing the history via `pushState`/`replaceState`, Turbolinks requires that the state includes a `restorationIdentifier`, which is internally generated for each visit. If this is absent (for example when your photoswipe library changes the url), then Back navigations won't work as expected.

I'm afraid there is no easy fix for this, other than removing Turbolinks for that page.

**Comment by hortigado** [comment]
Thanks friend a answer, turbolinks work with window.location.hash ?

**Comment by hortigado** [comment]
```
 var misma=null;
                e.History = function() {
                    var loc = window.location.href; 
                    function r(e) {
                        this.delegate = e, this.onPageLoad = t(this.onPageLoad, this), this.onPopState = t(this.onPopState, this)
                    }
                    return r.prototype.start = function() {
                        var urlactual= null;
                        return this.started ? void 0 : (addEventListener("popstate", this.onPopState, !1), addEventListener("load", this.onPageLoad, !1), this.started = !0)
                    }, r.prototype.stop = function() {
                        return this.started ? (removeEventListener("popstate", this.onPopState, !1), removeEventListener("load", this.onPageLoad, !1), this.started = !1) : void 0
                    }, r.prototype.push = function(t, r) {
                        urlactual= t.requestURL;

                        console.log(urlactual);
                        return t = e.Location.wrap(t), this.update("push", t, r)
                    }, r.prototype.replace = function(t, r) {
                         urlactual= t.requestURL;
                         loc=window.location.href;
                            console.log(urlactual);
                        return t = e.Location.wrap(t), this.update("replace", t, r)
                    }, r.prototype.onPopState = function(t) {
                        var r, n, o, i;
                        var openphoto=false
                        if(t.location.hash){
                            var openphoto=true

                        }
if (loc != urlactual && !openphoto) return this.shouldHandlePopState() && (i = null != (n = t.state) ? n.turbolinks : void 0) ? (r = e.Location.wrap(window.location), o = i.restorationIdentifier, this.delegate.historyPoppedToLocationWithRestorationIdentifier(r, o)) : void 0
              
```

**Comment by hortigado** [comment]
I made this modification for my need. It works for me. I need to detect when the image opens, I try to retrieve the url before the onPopState, which would be the one with #, but I can't. Any ideas? Thanks
```
  if(t.location.hash){
                            var openphoto=true
                        }
```
This does not work

**Comment by hortigado** [comment]
I managed to solve it by putting a global variable and setting it to true every time a modal or image is opened that changes the url. Now my site works properly with turbolinks :). They should implement it to turbolinks because many people see that they have the same problem. Regards
