### ISSUE TITLE
how to disable data-turbolinks-permanent?

### ISSUE THREAD

**Issue by hortigado** [turbolinks/turbolinks#539]
Is there a way to disable data-turbolinks-permanent from div inside a div data-turbolinks-permanent? with data-turbolinks-permanent = "false" does not work. Thanks
```
<div data-turbolinks-permanent>
<div></div>
<div data-turbolinks-permanent="false"></div>
</div>
```

**Comment by hortigado** [comment]
Solution 

> <div data-turbolinks-permanent>
> <div></div>
> <div data-turbolinks-track></div>
> </div>

**Comment by domchristie** [comment]
Hi @hortigado. There's no way to exclude elements within a `data-turbolinks-permanent` element. You may wish to be more selective with the elements you mark as permanent.
