### ISSUE TITLE
Touch event passes through to the next page and triggers a focus/active event in iOS 9.3

### ISSUE THREAD

**Issue by gregblass** [turbolinks/turbolinks#54]
This was similar to something that was happening to me in Turbolinks Classic, where links would actually get triggered on the next page. This is at least not a showstopper like that, but similar: If I tap a link in iOS 9.3 in safari, if there is another element with a focus/active CSS class (common for mobile) in the same location on the screen on the next page, it will get that style applied to it.

**Comment by sstephenson** [comment]
Hey @gregblass—I’m afraid we don’t have the resources to debug this unless you can provide a minimal test case to reproduce the issue.

**Comment by gregblass** [comment]
OK, I'll see if I can spin one up.

**Comment by gregblass** [comment]
What would be your recommended way of doing this? Create a github repository with a project that illustrates the problem? Then you can download and run it on your machine?

**Comment by nateberkopec** [comment]
@gregblass Yup, that would work.

**Comment by sstephenson** [comment]
Preferably you’d just provide a URL to a static site demonstrating the issue, but a repo works if that’s not feasible.

**Comment by gregblass** [comment]
So when it comes down to it, using :active for a background color on mobile isn't all that great of a solution, because it will be triggered on scroll.

To truly get that native style tap background highlighting (but not on scrolling), a little javascript is needed to implement a delay in case the user is scrolling. I accomplished it here if anyone cares: http://stackoverflow.com/questions/36224862/

I'm closing this because the whole thing was based on that active class giving elements a background color, and as far as I can tell, thats not really the best practice in the first place.

**Comment by gregblass** [comment]
This is really a problem with iOS. Android has fixed this...you can use :active to highlight an element, and there is a small delay to prevent activation on scrolling. Wish iOS 9.3, I rolled my own solution...see my stackoverflow question and my answer to it above.
