### ISSUE TITLE
Open bootstrap tab programmatically after load

### ISSUE THREAD

**Issue by ArtemisGraphic** [turbolinks/turbolinks#543]
I'm tryng to open a Bootstrap 4 tab after page load. It does work if I refresh the page, but if I navigate within the site, I get a query selector empty error.

This is my code, that's basically a port I did of this [https://webdesign.tutsplus.com/tutorials/how-to-add-deep-linking-to-the-bootstrap-4-tabs-component--cms-31180](url)

      document.addEventListener("turbolinks:load", function() {
        let url = location.href.replace(/\/$/, "");
        if (location.hash) {
          const hash = url.split("#");
          document.querySelector('#nav-tab a[href="#'+hash[1]+'"]').Tab.show();
          url = location.href.replace(/\/#/, "#");
          history.replaceState(null, null, url);
          setTimeout(() => {
            window.scrollTo(0,0);
          }, 400);
        }
      });

I placed it just before the closing body tag. If I write `http://www.myURL#mytab` and click refresh, the page refresh and the tab is changed, but if I get there from a (turbo)link, it does not find the tab to query select. I'm afraid the problem is with the "load" event, I tried different methods but I can't get it to work.
If I place the setTimeout just below the `if (location.hash)` and increasing the time like so:

        if (location.hash) {
          setTimeout(() => {
          const hash = url.split("#");
          document.querySelector('#nav-tab a[href="#'+hash[1]+'"]').Tab.show();
          url = location.href.replace(/\/#/, "#");
          history.replaceState(null, null, url);
            window.scrollTo(0,0);
          }, 600);

It does work, except it waits too much and sometime the tab is completely empty...

**Comment by domchristie** [comment]
@ArtemisGraphic [I've answered your question on StackOverflow here](https://stackoverflow.com/a/61878088/783009). I hope that helps.
