### ISSUE TITLE
Anchors not working on page refresh

### ISSUE THREAD

**Issue by estani** [turbolinks/turbolinks#544]
When refreshing a page with an anchor, it is not followed. The last seen location seems to be retained

Reproducing is fairly easy, put this in some page:
```
<a href="#a">go</a><br>
<div style="height:500px">some space</div>
<h2 id="a" >Target</h2>
```

clicking once on "go" should work properly as expected. No scroll back up and reload the page.

The expectation is to honor the url anchor and go back to the anchor. This does not happen.

Actually if you stop the debugger on a scroll event, and go step by step, you can watch the page jumping forth to the anchor and back.

1) In chrome's debugger look for the "Event Listener Breakpoints"->Control->scroll
2) reload the page with the anchor in the url and a different position
3) wait in the debugger until the page disappears (there's a timeout in turbolinks apparently doing this).
4) Now go step by step to watch the page being rendered at the expected position and then jump back.

Because of minification I cannot exactly tell where this is happening, is in some function inside a timeout. somewhere in the pageLoaded handler I think...

Breakpoint found before jump (rails-ujs.js):
![image](https://user-images.githubusercontent.com/1331850/82556487-16d33300-9b6a-11ea-9f24-8493c9edf3b2.png)

Breakpoint found after jump (turbolinks.js):
![image](https://user-images.githubusercontent.com/1331850/82556427-f86d3780-9b69-11ea-8980-33ff0622eb8c.png)

**Comment by domchristie** [comment]
> scroll back up and reload the page.
> The expectation is to honor the url anchor and go back to the anchor. This does not happen.

Hi @estani 
Turbolinks currently doesn't perform any scrolling on a full page load or refresh. Returning to the most recent scroll position (rather than the anchor) is expected and is the default browser behaviour. You can try this out by removing all your JavaScript from your page and perform the same steps as before.

**Comment by estani** [comment]
sorry! My bad. This indeed worked as expected (if a new tab or page is opened, the anchor is honored). The logic that a refresh works differently that loading the page for the first time, at least in chrome, was new to me.
