### ISSUE TITLE
Pages not scrolling back to top after Turbolinks visit on Firefox. Works in Chrome.

### ISSUE THREAD

**Issue by boboldehampsink** [turbolinks/turbolinks#547]
**Describe the bug**
Pages are not scrolling back to top after a Turbolinks visit with latest Firefox. This is working in Chrome. In Firefox, the scroll position is retained.

**To Reproduce**
Click on a Turbolinks link on the bottom of a page with Firefox. It navigates to the second page but it will still be on the bottom. 

**Expected behavior**
In Chrome, it correctly starts at the top again.

**Details (please complete the following information):**
 - Operating System: macOS
 - Browser: Firefox 76
 - Turbolinks Version: 5.2.0 (also on 5.3.1-beta.1)

**Additional context**
Using the following setup:

`<meta name="turbolinks-cache-control" content="no-preview">` in `<head/>`.

Scripts loaded with:

`<script src="{{ js }}" data-turbolinks-track="reload" defer></script>` in `<head/>`.

Styles loaded with:

`<link rel="stylesheet" href="{{ css }}" data-turbolinks-track="reload">` in `<head/>`

**Comment by domchristie** [comment]
I'm unable to reproduce this (see [demo](https://tender-fog-bun.glitch.me/)). It sounds like you might be experiencing this issue: https://github.com/turbolinks/turbolinks/issues/181. Perhaps your JS or CSS asset paths are changing, causing a reload? (This wouldn't explain the Chrome/Firefox differences though.) If you could provide a demonstration that'd really help.

**Comment by boboldehampsink** [comment]
@domchristie here is the link of a project of mine that has items and pagination on the bottom: https://salta-trampolines-dev.herokuapp.com/search?q=comfort+edition

When clicking the pagination on the bottom, Chrome correctly renders the next page from the top, while Firefox stays at the pagination position.

**Comment by boboldehampsink** [comment]
It is actually exactly this problem: https://github.com/turbolinks/turbolinks/issues/181#issuecomment-545084567

**Comment by domchristie** [comment]
I've added the scroll-behaviour CSS to the [demo](https://tender-fog-bun.glitch.me/) and can't reproduce this. Are you able to pinpoint the issue?

**Comment by boboldehampsink** [comment]
@domchristie I tried many things on glitch.me and I can't reproduce it... Must've been something else interfering then. Thanks a lot for taking the time to help me debug this.
