### ISSUE TITLE
Capybara testing inline javascript / Is the use of inline javascript recommended?

### ISSUE THREAD

**Issue by gregblass** [turbolinks/turbolinks#55]
I have inline javascript in my view that I'm loading with

    document.addEventListener("turbolinks:load", function() {});

When I try to write an integration test using capybara (with javascript enabled), this code isn't running for some reason. It is running correctly in if I test it manually, not in an automated test.

Should I really be registering ALL the javascript of my entire app once using $(document).on? Wouldn't this potentially decrease performance with all of the javascript loaded at once, even if its only needed for one page/small use case? I can see the js is being used in multiple places or used commonly, but if I have page specific javascript that a user might not hit very often, I thought that it would make more sense to keep that inline.

But as of now I can't seem to write a feature test that is able to test inline js.

**Comment by gregblass** [comment]
If the answer is "We don't recommend writing inline javascript for any reason," I'm more than OK with that. I could refactor this into the asset pipeline and am doing so until hopefully someone drops some insight here.

**Comment by nateberkopec** [comment]
Hey @gregblass - TL5 doesn't evaluate inline script tags *yet*, but will before 5.0 is released. See #9.

**Comment by gregblass** [comment]
Awesome, thanks for the info!
