### ISSUE TITLE
ProgressBar element rendered outside body tag

### ISSUE THREAD

**Issue by Tylerian** [turbolinks/turbolinks#550]
**Describe the bug**
The progress-bar is rendered outside the document body. Is it intended behaviour?

**To Reproduce**
[reproducible demo](https://turbolinks-demo.glitch.me/)

1. Go to the demo
2. Open navigator devtools
3. Click the network tab and throttle the connection
4. On the demo, click a turbolink
5. See bug

**Expected behavior**
The progress-bar should be rendered inside the document body tag.

**Details (please complete the following information):**
 - Operating System: macOS Catalina 10.15.4
 - Browser: Chrome 83.0.4103.61 (64 bits)
 - Turbolinks Version: v5.2.0

**Additional context**
The reason I ask this is because I'm trying to implement an alternative loading status (the placeholder/glimmer pattern) and I see weird issues when adding the placeholder event on body between turbolink requests.

**Comment by bgold0** [comment]
Why was this closed? My progress bar is rendering above the body as well and is limiting my ability to style it.
