### ISSUE TITLE
Chrome translation prompt does not appear when using Turbolinks

### ISSUE THREAD

**Issue by collimarco** [turbolinks/turbolinks#553]
Let's say that you have a page X in Italian and the browser language is English.

When you open the page X directly, Chrome asks you if you want to translate the page to English

However if the website uses Turbolinks and you surf from page A (in English) to page X (in Italian), then Chrome does not show the prompt.

This is probably because Turbolinks does not refresh the page and Chrome doesn't notice the change of the page language.

Is there any solution?

**Comment by domchristie** [comment]
Closing as inactive
