### ISSUE TITLE
`link_to :back` does not work

### ISSUE THREAD

**Issue by jastkand** [turbolinks/turbolinks#56]
I'm using Turbolinks 5.0.0.beta3 and `= link_to 'Back', :back: ` does not work for me. It generates a link to the current page instead of the previous one.

**Comment by 1989medium** [comment]
@jastkand,  

> = link_to 'Back', :back

, work! update Turbolinks 5.0.0.beta4 :+1:

**Comment by jastkand** [comment]
@1989medium Great, it works, thanks!

**Comment by packagethief** [comment]
For posterity, this was (unintentionally) fixed by #48, by starting the request before changing history.
