### ISSUE TITLE
Ajax PUT call returning Turbolink.clearCache() in response. See the below description for details

### ISSUE THREAD

**Issue by SK-CSE** [turbolinks/turbolinks#562]
I have enabled turbolink in my ROR app. now if i open `http://localhost:3000/about` two times in different tab  by copy pasting the URL, then Ajax call which i put on the button inside about page is giving me 
```
Turbolinks.clearCache()
Turbolinks.visit("http://localhost:3000/about", {"action":"replace"})
```
instead of proper response, because of which my flow is breaking.
can anyone help me with it..?

**Comment by welearnednothing** [comment]
Hey @SK-CSE,

That behavior is expected if your controller action is returning a redirect and is explained [here](https://github.com/turbolinks/turbolinks#redirecting-after-a-form-submission). Is it safe to say that the controller action for your PUT request is redirecting (via `redirect_to` or `redirect_back`, most likely) back to the about page?

**Comment by SK-CSE** [comment]
@welearnednothing  in the response of PUT request i am sending `render json: { data: @data, current_time: Time.zone.now }`
let's suppose i opened same link in 4 times in different tabs, let's say : tab1, tab2, tab3, tab4 then all even number tabs like tab2, tab4 is sending desired response but all odd tabs like tab1 and tab3 is sending 
`Turbolinks.clearCache()
Turbolinks.visit("http://localhost:3000/about", {"action":"replace"})`

**Comment by welearnednothing** [comment]
@SK-CSE When you say the even numbered tabs would work and the odd ones wouldn't, I'm missing something. Why would some tabs return different responses? Since these requests are in response to a `PUT` request, it sounds like, per the link above, that Rails and Turbolinks are doing what they're supposed to do.

In your original post, you say "my flow is breaking". Can you clarify what you're expecting to happen form a user perspective and what is actually happening? And/or any other info you provide that would help me understand the problem you're having. Thanks!

**Comment by SK-CSE** [comment]
@welearnednothing when i say "my flow is breaking" means I am using the response sent by the server and based on that I am showing and hiding few elements, but since i am getting `Turbolinks.clearCache() Turbolinks.visit("http://localhost:3000/about", {"action":"replace"})` on odd number tab let's say tab1 tab3, on those tabs if I make PUT requests then i am unable to show or hide elements which i am doing based on my server response. while my tab2 tab4 which I opened by copy-pasting the same URL work fine as i am getting my server response on those tabs

**Comment by welearnednothing** [comment]
@SK-CSE Copying/pasting a URL into your browser is a `GET` request - so you're comparing the results of a GET (read) versus that of a PUT request (write). By default in Rails, these won't even hit the same controller actions. So we may be comparing apples and oranges, here.

That said, the response you're getting only makes sense if you're using `redirect_to` in your controller, but is not what you should be getting if you're not redirecting and only rendering. Are you certain the correct controller action is being called and are you certain you're not calling `redirect_to` anywhere in the controller action being called?

**Comment by SK-CSE** [comment]
@welearnednothing `PUT` request is triggered when clicking a button which we get when we render the web page, so i don't think copy pasting urls will not affect it. in the response of PUT request i am sending `render json: { data: @data, current_time: Time.zone.now }` from backend but on all odd tabs like tab1 tab3 I'm getting `Turbolinks.clearCache() Turbolinks.visit("http://localhost:3000/about", {"action":"replace"})`

**Comment by domchristie** [comment]
@SK-CSE are you able to post a minimal reproduction app? It really helps when trying to debug issues like this.

**Comment by domchristie** [comment]
Closing as inactive
