### ISSUE TITLE
Images do not cache

### ISSUE THREAD

**Issue by ArtemisGraphic** [turbolinks/turbolinks#564]
I've made a web application using node.js and turbolinks: [necronomicon.app](https://necronomicon.app), If I go back and forth in the app, you can see the icons reloading all the time and reflowing the content. Is there a way to cache them so to avoid re-downloading?

**Comment by domchristie** [comment]
Hey @ArtemisGraphic Be sure you're not browsing with the developer tools open with the cache disabled. (see https://github.com/turbolinks/turbolinks/issues/494)

**Comment by ArtemisGraphic** [comment]
Hi dom, thank you for your reply. Unfortunately this is not a dev tools setting, I have this issue in every browser and it has been pointed out by others to me. You can check the link in your mobile browser and it will do the same.

**Comment by tleish** [comment]
Hi @ArtemisGraphic - Browsing through necronomicon.app testing with both Google Chrome and Firefox on MacOS and using the network tab in developer tools with "Disable Cache" unchecked, I do not see images re-downloaded when I revisiting a cached page.

Are you seeing images re-downloaded from the network tools, or are you seeing what appears to be a re-download from caching/rendering artifacts?  Can you give a specific click through scenario and describe a bit more what you are seeing?

FYI, I noticed the application loads `turbolinks.js` twice, 

```html
<script src="/scripts/turbolinks/dist/turbolinks.js" type="text/javascript"></script>
<script src="/scripts/howler/dist/howler.core.min.js" type="text/javascript"></script>
<script src="/scripts/turbolinks/dist/turbolinks.js" type="text/javascript"></script>
```

**Comment by ArtemisGraphic** [comment]
Hi @tleish, thank you very much for helping me. You're right, on chrome and firefox it does behave correctly, I was sure I've seen this problem on those browsers too, but apparently I was wrong. The problem occurs if you add the web app in the home screen, on iOS.
I've made a small video to show the problem. [https://i.imgur.com/fi6uAWY.mp4](https://i.imgur.com/fi6uAWY.mp4)

Thank you for the double script error, this is a recent edit that escaped me.

**Comment by tleish** [comment]
@ArtemisGraphic - is this an iOS mobile app with a web view?

**Comment by ArtemisGraphic** [comment]
@tleish - no, this is just a website (web app) added to the home screen from Safari. It's the <meta name="mobile-web-app-capable" content="yes"> that removes address bar and it makes it look like a webview app.

**Comment by tleish** [comment]
@ArtemisGraphic - I just tested Safari on iOS 13.x, and image caching works just like the desktop.  The only items that are not cached are *.mp4 (this same behavior exists on desktop).

Here's a screenshot of the network activity of my mobile iOS Safari 13 (see: https://appletoolbox.com/use-web-inspector-debug-mobile-safari/)

![image](https://user-images.githubusercontent.com/1099993/89180857-d7549a00-d54f-11ea-9bc9-e09fb1eb43fd.png)

If you are having problems with iOS Safari caching, I suggest you google for iOS Safari solutions.

This is not a turbolinks bug and this issue should be closed.

**Comment by ArtemisGraphic** [comment]
@tleish – The problem then may be relative to how safari handle caching on installed web apps. I thought it was some sort of incompatibility of turbolinks or a wrong configuration (hence the "Question" tag).
Thank you

**Comment by domchristie** [comment]
I'm not seeing this on iOS Safari or [installed as a homescreen webapp](https://youtu.be/cXn7viuh8s4) (running iOS 13.5.1). Feel free to post a solution if/when you find the cause of this.
