### ISSUE TITLE
document.write broken the Turbolinks

### ISSUE THREAD

**Issue by askareija** [turbolinks/turbolinks#566]
**Describe the bug**
I've implemented divisima html template from colorlib, and in the footer there's script like this
`<script>document.write(new Date().getFullYear());</script>`, after i run it whenever i click on a link helper 
`<%= link_to ... %>` it will return blank page, head is empty and body is only have 2020 text.

**To Reproduce**
Implement divisima template from colorlib on your app, take the footer section.

1. click on any link helper `<%= link_to ... %>`
2. It will return blank page with 2020 text

**Details (please complete the following information):**
 - Operating System: MacOS Catalina 10.15
 - Browser: Edge Version 84.0.522.44
 - Turbolinks Version 5.2.1

**Screenshots**
![Jepretan Layar 2020-08-10 pukul 10 21 31](https://user-images.githubusercontent.com/21377617/89749806-7ac72100-daf3-11ea-83e9-a251be760799.png)

**Comment by tleish** [comment]
See: #267 and #513
