### ISSUE TITLE
TurboLinks and caching form inputs

### ISSUE THREAD

**Issue by tleish** [turbolinks/turbolinks#574]
I would like TurboLinks to preserve bfcache (back-forward cache) for form inputs?

### BACKGROUND
Browsers today have bfcache (back-forward cache).  Turbolinks essentially replaces this bfcache functionality and seems to behave similar to browsers except when it comes to form inputs (text, select, checkboxes, etc).

### STEPS TO REPRODUCE:
1. Fill in form field(s) on page
2. Leave page (e.g. submit form or click other link)
3. Press browser back button

### BROWSERS BFCACHE:
After pressing the back button, users input is cached and the user can see/modify one (or more) of their inputs (accept for input type="password").

### TURBOLINKS BFCACHE:
After pressing the back button, users input is NOT cached.  The form is reset to it's original default state.

## Summary

Is there a flag or functionality in TurboLinks that would allow me to preserve the input fields in the cache?

**Comment by arielkirkwood** [comment]
TIL about the bfcache! I’ve noticed this behavior outside of Turbolinks, but I didn’t know its name. Thank you!

**Comment by tleish** [comment]
BTW, I'm assuming the answer to my original question is "not at the moment" (because of how TurboLinks caches pages), but wanted to confirm.

My understanding is, when a user changes values in form fields, these changes are preserved in memory and not in the DOM.  In other words, lets say you have the following input:

Original DOM:
```html
<input type="text" id="first_name" name="first_name" value="" />
```

Original JavaScript:
```javascript
document.getElementById("first_name").value //=> ""
document.getElementById("first_name").defaultValue //=> ""
```    

#### UPDATE THE FORM:
Update the form with user input or javascript
```javascript
document.getElementById("first_name").value = "Suzy"
```

After entering in a first name "Suzy", you now have the following:

Updated DOM: (no change)
```html
<input type="text" id="first_name" name="first_name" value="" />
```

Updated JavaScript:
```javascript
document.getElementById("first_name").value //=> "Suzy"
document.getElementById("first_name").defaultValue //=> ""
```

Even though the "value" has changed, the DOM reflects the inputs "defaultValue".  Preserving the original defaultValue in the DOM, The browser uses this defaultValue in the DOM to reset all the fields to their defaultValue if using a form "reset" functionality.

Since Turbolinks caches DOM changes (and not memory changes), it only caches the defaultValue and not the users input.  In some cases, this is desired (there are forums with developers asking how to prevent browsers from apply bfcache to their forms).  However, some users (like me) often want this functionality on some forms to make it easier for users after they press back/forward buttons on pages where they've spent time filling out forms.  This is especially important if the form was long.

#### WORKAROUND 1: defaultValue
If I update using `defaultValue`, then the DOM is in fact updated:

```javascript
document.getElementById("first_name").defaultValue = "Suzy"
```

Then the DOM is updated.

Updated DOM:
```html
<input type="text" id="first_name" name="first_name" value="Suzy" />
```

Updated JavaScript:
```javascript
document.getElementById("first_name").value //=> "Suzy"
document.getElementById("first_name").defaultValue //=> "Suzy"
```
This updates the DOM and is therefore cached by TurboLinks, but it also breaks another common browser feature of `form.reset()` which uses the defaultValue attribute.

#### WORKAROUND 2: custom attribute

Another possible solution would be to:

1. Write form input values to a custom attributes on form fields during `turbolinks:before-cache`
2. Restore form inputs using custom form field attributes on `turbolinks:load` (and remove the custom form field attribute)

**Comment by stefanpenner** [comment]
IMHO BFCache may need to emit change events if it mutates form elements values, otherwise the UI get's out of sync, i've done some investigation + opened a crbug. I wouldn't mind input from you fine folks.

Issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1143298

**Comment by tleish** [comment]
FYI, I created a library to provide a solution to this issue with Turbolinks.

https://github.com/tleish/turbolinks-bfcache-form
