### ISSUE TITLE
Smooth Progress Bar

### ISSUE THREAD

**Issue by onur-km** [turbolinks/turbolinks#575]
I need a progress bar that is triggered on each request.
For this I made the following setting:

`Turbolinks.setProgressBarDelay(0);`				
https://github.com/turbolinks/turbolinks#turbolinkssetprogressbardelay

But when the page is loaded, the "**Progress bar**" suddenly disappears regardless of the position it is in.

I dont want this. Even when the page loads and the "body" is changed, I want it to complete itself wherever it is left. Instead of disappearing suddenly, let it run to the "**100%**" position quickly and then disappear. Is this possible?

**Comment by tleish** [comment]
Not out of the box.  When the page loads, the library just hides the progressbar. 

```javascript
export class BrowserAdapter implements Adapter {
  //...
  visitRequestFinished(visit) {
    this.hideProgressBar()
  }
  //...
}
```

I haven't tested it, but perhaps you could try to monkeypatch visitRequestFinished do the behavior your looking for.  Something like:

```javascript
window.Turbolinks.controller.adapter.visitRequestFinished = function(visit) {
  this.progressBar.setValue(1);
  this.hideProgressBar();
}
```
