### ISSUE TITLE
document.referrer should be updated by Turbolinks

### ISSUE THREAD

**Issue by collimarco** [turbolinks/turbolinks#577]
Currently  `document.referrer` is not updated properly by Turbolinks.

We have a page where we would like to have a different navigation based on the referrer. For several reasons (enable public caching, seo, etc.) we don't want want to serve different html from the server, instead we want to have the logic in Javascript.

The problem is that Javascript can't use the `document.referrer` when using Turbolinks.

I thinks that Turbolinks should update that variable or at least provide an alternative variable that can be read from Javascript.

**Comment by tleish** [comment]
You could try the following.

```javascript
Turbolinks.controller.currentVisit.referrer.absoluteURL
```
or
```javascript
Turbolinks.controller.currentVisit.referrer.requestURL
```

Be sure to check if `Turbolinks.controller.currentVisit` exists, as it will be `undefined` when the page has not be loaded via TurboLinks.  Perhaps something like.

```javascript
if(Turbolinks.controller.currentVisit === undefined){
   return location.referrer
}
return Turbolinks.controller.currentVisit.referrer.absoluteURL
```

Be careful with this, as this is likely to break with the new release.

Note: I do not understand the difference between `absoluteURL` and `requestURL` as they appear to be the same in my environment.

**Comment by domchristie** [comment]
`document.referrer` is immutable and so cannot be updated by Turbolinks. Given that Turbolinks maintains state between visits, it's possible to implement this variable yourself:

```js
var referrer = document.referrer
document.addEventListener('turbolinks:before-visit', function () {
  referrer = window.location.href
})
```

Edit: Bear in mind that if the `turbolinks:before-visit` event is cancelled by another event handler, the referrer might be inaccurate.

**Comment by domchristie** [comment]
> Note: I do not understand the difference between absoluteURL and requestURL as they appear to be the same in my environment.

If I recall correctly, `absoluteURL` includes the anchor/fragment part, whereas `requestURL` does not.

**Comment by collimarco** [comment]
@domchristie I have just tested your code and it doesn't work. If I read the `referrer` variable it returns the current page URL, not the referrer.

**Comment by domchristie** [comment]
@collimarco ah, `turbolinks:visit` is called after the `Visit` has started and therefore after the history has changed. I've updated the code example above to use `turbolinks:before-visit` but bear in mind the note at the bottom.
