### ISSUE TITLE
5.2.1 release on rubygems but not on Changelog or Releases page

### ISSUE THREAD

**Issue by woodhull** [turbolinks/turbolinks#578]
We're curious if there are release notes for this release, and would like to know what is included exactly. 

 https://rubygems.org/gems/turbolinks/versions/5.2.1

Was a tiny bit worried this might be someone publishing a non-genuine gem package.

**Comment by georgeclaghorn** [comment]
The `turbolinks` gem is at [turbolinks/turbolinks-rails](https://github.com/turbolinks/turbolinks-rails). 5.2.1 is tagged there.

**Comment by woodhull** [comment]
Ah! Thanks!
