### ISSUE TITLE
Same page hashs trigger the turbolinks visit action

### ISSUE THREAD

**Issue by onur-km** [turbolinks/turbolinks#579]
Same page hashs trigger the turbolinks visit action. How do i disable it?

**Comment by Hrishikesh-K** [comment]
It's clearly mentioned in documentation, use `data-turbolinks = "false"` on the anchor or any of its parent element.

**Comment by domchristie** [comment]
This is a known issue (https://github.com/turbolinks/turbolinks/issues/75, with corresponding PR: #285). You might find this workaround useful: https://github.com/turbolinks/turbolinks/issues/75#issuecomment-445325162
