### ISSUE TITLE
<script> in <head> not loading before executing the one in <body>

### ISSUE THREAD

**Issue by Hrishikesh-K** [turbolinks/turbolinks#581]
Hello! I tried reading the documentation multiple times and read some of the similar issues, but, couldn't get it working in my case.

I'm using Plyr.io as a media player on my website. Currently, I have Plyr's JS in my `<head>` as my entire website's JavaScript bundle. However, I don't need it on pages that don't have any media, so, I thought of removing it from such pages.

So now, on whichever page I need Plyr, I load its script as a separate file in my `<head>` and initialize Plyr in in a `<script>` before my `</body>`. Whenever I reach the page through Turbolinks' navigation, I get error in my console: `Uncaught ReferenceError: Plyr is not defined` pointing to the line in my `<body>`. However, it gives the error only when loading a page with Turbolinks for the first time. If I navigate to any other page and return back to this page, the media loads, probably because by then, the `<script>` has loaded. The error doesn't even come up when reloading the page through the browser or loading the page directly by URL.

By the way, I'm loading Playr like this:

```JS
document.addEventListener('turbolinks:load', function()
  {
    var players = Plyr.setup('.js-player', options)
  }
```

and disabled Turbolinks cache on the entire website by adding `<meta name = "turbolinks-cache-control" content = "no-cache">` to all pages.

This can be checked by visiting my home page: https://quizzical-kare-8c7226.netlify.app/, then opening the project with the name Carry on bot. If you scroll till the end on that one, you can see that the video loads in a weird way and browser's console throws the error I mentioned above. However, if you go back to the home page using internal navigation of the website and then, load another project Windows 10 M, you can see that the video loads fine on that page. Now, if you return home and again visit the Carry on bot page, you'll see the video loads fine.

So, how can I make sure the `<script>` in head is loaded before executing the one in `<body>` when using Turbolinks? I'm using the latest version of Turbolinks by the way.

**Comment by domchristie** [comment]
When Turbolinks loads a page containing new scripts, it loads them asynchronously, so it will be executed after inline scripts in the `<body>`. It does not wait for external scripts to load, which would slow down page transitions.

The key benefit of Turbolinks is that scripts are only loaded and evaluated once, so before separating your scripts out, consider if you _really_ need to do so. It can become a dependency mess when you start splitting things up.

---

The simplest way to fix this would be to bundle up your Plyr JS and your "loading" script into a single file and deliver that when needed. You wouldn't need the `turbolinks:load` event handler for this:

```js
// Plyr script
// …
var players = Plyr.setup('.js-player', options)
// …
```

Alternatively you could trigger a custom event when the Plyr JS has loaded and pick that up in you main application JavaScript. Something lik:

```js
// application.js
document.addEventListener('playr:load', function()
  {
    var players = Plyr.setup('.js-player', options)
  }

// Plyr script
// …
document.dispatchEvent(new Event('playr:load'))
```

I hope that helps.
