### ISSUE TITLE
New Turbolinks version?

### ISSUE THREAD

**Issue by nicl** [turbolinks/turbolinks#582]
Hi, I've heard that there is a new/updated version of Turbolinks, which was developed for Hey. I was interested in some of the features and wondered if there was a timeline for sharing this?

Thanks.

**Comment by kmmbvnr** [comment]
Here is links to couple intriguing dhh  tweets about future plans - https://github.com/turbolinks/turbolinks/issues/576#issuecomment-696166893

**Comment by domchristie** [comment]
Closing as duplicate of https://github.com/turbolinks/turbolinks/issues/576
