### ISSUE TITLE
Turbolinks not intercepting clicks

### ISSUE THREAD

**Issue by msp-matt** [turbolinks/turbolinks#583]
I'm trying to add Turbolinks to a large and somewhat complex PHP web app (in particular, we're not using Rails), but Turbolinks is not intercepting the clicks at all. I've added event listeners on the document object for all Turbolinks events, and the only one that ever fires is `turbolinks:load`. In the browser's dev tools, I'd expect to see that the requests have type `xhr`, but I'm not seeing that.

We have not used `data-turbolinks="false"` to disable Turbolinks anywhere, so it's not that. There are no redirects in place either.

I see this bit in the documentation:
> Turbolinks intercepts all clicks on `<a href>` links to the same domain. When you click an eligible link, Turbolinks prevents the browser from following it. Instead, Turbolinks changes the browser’s URL using the History API, requests the new page using XMLHttpRequest, and then renders the HTML response.

This makes me think that for some reason Turbolinks thinks our links are going to a different domain, or are otherwise ineligible. Any ideas what might cause that, or anything I can test to get any useful information?

**Comment by msp-matt** [comment]
The source of the problem is `Location.isHTML`, which makes `.php` links ineligible. The problem is solved by overriding the method, as shown in this comment: https://github.com/turbolinks/turbolinks/issues/15#issuecomment-186639159

I think it would be really nice to put this fact in the main documentation. It's not that hard to dig through the code to find it, but it would have saved me and apparently some others some time if it were mentioned up front. Ultimately, a way to configure this would be nice, but at least mentioning the workaround would be a good step.

**Comment by msp-matt** [comment]
If it helps others, here's the explicit solution I used:
```
Turbolinks.Location.prototype.isHTML = (() => {
  const isHTML = Turbolinks.Location.prototype.isHTML
  return function() { return isHTML.call(this) || this.getExtension() === '.php' }
})()

```

**Comment by domchristie** [comment]
Thanks for sharing your solution.
There's an open issue for this here: https://github.com/turbolinks/turbolinks/issues/301 so closing as a duplicate.
