### ISSUE TITLE
Save scroll when navigate to other page

### ISSUE THREAD

**Issue by pemudakoding** [turbolinks/turbolinks#591]
Hello, i want ask something. 

how to save my scroll when navigate to other page, just some link  not all. 
i want if i click link that, i will go to other page but the same scroll, but turbolinks alway scroll to top.
maybe anyone can help me please

thanks.

**Comment by sudhirj** [comment]
Here's what I'm doing right now (add this monkey patch after you load turbolinks, in the `application.js`): 

```
// monkey-patch the turbolinks loader to shift scroll to the top only when the page actually changes.
Turbolinks.Visit.prototype.loadResponse = function () {
    return null != this.response ? this.render(function () {
        var t, e;
        console.log(this.request);
        var scroller = this.performScroll;
        if (this.request.url === this.request.referrer) {
            scroller = function () {
            }
        }
        return this.cacheSnapshot(), this.request.failed ? (this.controller.render({
            error: this.response
        }, scroller), "function" == typeof (t = this.adapter).visitRendered && t.visitRendered(this), this.fail()) : (this.controller.render({
            snapshot: this.response
        }, scroller), "function" == typeof (e = this.adapter).visitRendered && e.visitRendered(this), this.complete());
    }) : void 0;
};
```

You can modify the `this.request.url === this.request.referrer` condition to whatever your logic is. I've done it so scrolling to the top is switched off if the same page is loaded again, so I get a single-page-app effect. You can do anything else, of course.

**Comment by pemudakoding** [comment]
> Here's what I'm doing right now (add this monkey patch after you load turbolinks, in the `application.js`):
> 
> ```js
> // monkey-patch the turbolinks loader to shift scroll to the top only when the page actually changes.
> Turbolinks.Visit.prototype.loadResponse = function () {
>     return null != this.response ? this.render(function () {
>         var t, e;
>         var scroller = this.performScroll;
>         if (this.request.url === this.request.referrer) {
>             scroller = function () {
>             }
>         }
>         return this.cacheSnapshot(), this.request.failed ? (this.controller.render({
>             error: this.response
>         }, scroller), "function" == typeof (t = this.adapter).visitRendered && t.visitRendered(this), this.fail()) : (this.controller.render({
>             snapshot: this.response
>         }, scroller), "function" == typeof (e = this.adapter).visitRendered && e.visitRendered(this), this.complete());
>     }) : void 0;
> };
> ```
> 
> You can modify the `this.request.url === this.request.referrer` condition to whatever your logic is. I've done it so scrolling to the top is switched off if the same page is loaded again, so I get a single-page-app effect. You can do anything else, of course.
> 
> See #588

Thanks for the reply, it's help full me and the issues is closed thanks a lot bro..
