### ISSUE TITLE
Turbolinks populating values from the last form I visited, rather than the one I'm on

### ISSUE THREAD

**Issue by jhackett1** [turbolinks/turbolinks#592]
**Describe the bug**
I'm having a strange bug with Rails where Turbolinks seems to be intermittently populating my form with values from the last form I visited, rather than the one I'm looking at, even if the URLs are different.

If I turn javascript off, everything works as expected.

My form looks like this:

```
    <%= form_for(@service, as: :service, url: admin_service_path(@service), method: :put, data: {warn_unsaved_changes: true}) do |s| %>

        <%= s.label :organisation_id, "Parent organisation", class: "field__label" %>
        <%= s.collection_select( 
            :organisation_id, 
            Organisation.all, 
            :id, 
            :display_name, 
            { include_blank: "" }, 
            class: "field__input" )
        %>

<% end %>
```

The issue occurs between different forms on a fairly standard resourceful route:

```
resources :services, except: :edit
```

I'm not _certain_ this is specifically a turbolinks problem, but I've eliminated everything else. Any thoughts?

**To Reproduce**

1. Go to a URL with a form (for me, this could be: `/services/123`)
2. Go to the URL of a different resource, same form (for me, could be: `/services/abc`)
3. I see a quick flash of the correct value, but then it gets replaced with the value from (1)

**Expected behavior**
I see the values for the form and resource I'm on, rather than the last one I saw.

**Details:**

Issue seen in Firefox and Chrome

```
ruby '~> 2.6.0'

gem 'rails', '~> 6.0.2', '>= 6.0.2.1'
gem 'webpacker', '~> 4.0'
gem 'turbolinks', '~> 5'
```

**Screenshots**

In this screenshot I'm printing the correct value from the view. You can see the value the select box chooses is different.

![Screenshot](https://i.imgur.com/prXb7Iz.png)

**Comment by preetpalS** [comment]
I had this issue once in Firefox, I am not sure if it is related to Turbolinks though.

Try the following  [monkey patch](https://gist.github.com/preetpalS/46a2579b2c6cb4e2787b809061b0556d):

```ruby
# frozen_string_literal: true

# Firefox form fix
module ActionView::Helpers::FormHelper
  alias original_form_for form_for
  def form_for(record, options = {}, &block)
    options[:html] = { autocomplete: 'off' } unless options[:html]
    options[:html][:autocomplete] = 'off' unless options[:html][:autocomplete]

    original_form_for(record, options, &block)
  end

  alias original_form_with form_with
  def form_with(model: nil, scope: nil, url: nil, format: nil, **options, &block)
    options[:html] = { autocomplete: 'off' } unless options[:html]
    options[:html][:autocomplete] = 'off' unless options[:html][:autocomplete]

    original_form_with(options.merge(model: model, scope: scope, url: url, format: format), &block)
  end
end
```

**Comment by jhackett1** [comment]
that solved it!

**Comment by preetpalS** [comment]
Update for Ruby 3.0+ (works on Ruby 2.7 as well).

```ruby
# frozen_string_literal: true

# Firefox form fix
module ActionView::Helpers::FormHelper
  alias original_form_for form_for
  def form_for(record, options = {}, &block)
    options[:html] = { autocomplete: 'off' } unless options[:html]
    options[:html][:autocomplete] = 'off' unless options[:html][:autocomplete]

    original_form_for(record, options, &block)
  end

  alias original_form_with form_with
  def form_with(model: nil, scope: nil, url: nil, format: nil, **options, &block)
    options[:html] = { autocomplete: 'off' } unless options[:html]
    options[:html][:autocomplete] = 'off' unless options[:html][:autocomplete]

    original_form_with(**options.merge({model: model, scope: scope, url: url, format: format}), &block)
  end
end
```
