### ISSUE TITLE
Is this package now deprecated in favor of @hotwired/turbo?

### ISSUE THREAD

**Issue by guillaumebriday** [turbolinks/turbolinks#594]
See: https://turbo.hotwire.dev/handbook/drive

**Comment by gueorgui** [comment]
[According to the Turbo handbook](https://turbo.hotwire.dev/handbook/drive), Turbo Drive is replacing Turbolinks:

> Turbo Drive is the part of Turbo that enhances page-level navigation. It watches for link clicks and form submissions, performs them in the background, and udpates the page without doing a full reload. It’s the evolution of a library previously known as Turbolinks.

So I'm guessing the answer is yes, but I'd also be curious to hear from a maintainer.

**Comment by guillaumebriday** [comment]
Yes I would like to hear an "official" statement 👍

**Comment by MihaiVoinea** [comment]
Would it be possible to get some documentation on how to upgrade from Turbolinks to Turbo Drive the right way?

**Comment by JoseFarias** [comment]
> Would it be possible to get some documentation on how to upgrade from Turbolinks to Turbo Drive the right way?

@MihaiVoinea See https://discuss.hotwire.dev/t/upgrade-from-turbolinks-to-turbo-drive/1546

This might help in the meantime. If it's not enough I would recommend opening a different issue in the new repo so maintainers can give your question proper attention.

**Comment by MihaiVoinea** [comment]
Thanks a lot! That thread should do it.

**Comment by feute** [comment]
> Yes I would like to hear an "official" statement +1

It is official now. From the most recent commit:

> Please note that Turbolinks is no longer under active development. It has been superseeded by a new framework called Turbo, which is part of the Hotwire umbrella.

I hope we get a final/stable release of Turbo soon!

**Comment by guillaumebriday** [comment]
The answer is yes: https://github.com/turbolinks/turbolinks/commit/902645195d486f7e49b5944488d9944c0182472f
