### ISSUE TITLE
How to use Turbolinks with IE?

### ISSUE THREAD

**Issue by adaamz** [turbolinks/turbolinks#608]
Hi,
when I add turbolinks init scripts in <head> then IE errors because it doesn't have document.body.
When I add turbolinks init scripts after </body> then IE works, but site is reliable too late (and turbolinks complains about script is not in <head>).
When I add turbolinks init scripts in <body> then Turbolinks complains (but probably works?) and IE works.

Which way should I go? Which way do you go?

**Comment by le0pard** [comment]
@adaamz did you use https://github.com/turbolinks/turbolinks#turbolinkssupported to check, that browser can use turbolink? It can be like:

```js
if (Turbolinks.supported) {
  Turbolinks.start()
}
```

**Comment by adaamz** [comment]
ok, thx :)
