### ISSUE TITLE
Turbolinks:load not fired after first page load

### ISSUE THREAD

**Issue by Bramjetten** [turbolinks/turbolinks#62]
In Chrome and Firefox (not Safari) the turbolinks:load event isn't fired when running in production on the first page load. 

![schermafbeelding 2016-03-30 om 13 50 21](https://cloud.githubusercontent.com/assets/423116/14141259/5f7898f6-f67e-11e5-9525-bc3cf02e000c.png)

Turbolinks.controller exists and seems to have started, but only after manually running the pageLoaded() function does it trigger my JavaScript. When doing it manually, JavaScript execution is awfully slow in Chrome.

Turbolinks 5.0.0.beta3 and Rails 4.2.6

**Comment by javan** [comment]
Can you share your logging code? I created a little test page and see `turbolinks:load` consistently fired in all browsers. http://codepen.io/javan/pen/YqxYBK
![screen shot 2016-03-30 at 9 06 33 am](https://cloud.githubusercontent.com/assets/5355/14142975/b7686d16-f656-11e5-9fa6-9a45a843dc99.png)
> When doing it manually, JavaScript execution is awfully slow in Chrome.

What exactly is slow and how are you measuring it?

**Comment by Bramjetten** [comment]
I'm sorry! Apparently Cloudflare's Rocket Loader was messing with our JavaScript! Turning it off fixed it.

**Comment by obromios** [comment]
I am getting the same issue.   This problem does not happen on my local production server, but does happen on my heroku staging server which does not user cloudflare.  Any other ideas as to what could cause this?

 I developed a workaround with this [SO question](http://stackoverflow.com/questions/41421496/turbolinks-load-event-not-working-on-with-page-refresh). However this workaround is undesirable as it can cause the javascript to load twice.

**Comment by julianguyen** [comment]
@obromios Did you ever find a better solution than your workaround? I'm also in the situation as you.

**Comment by fedegos** [comment]
Any solution to this problem?

**Comment by obromios** [comment]
No, only the work around I posted.

regards

Chris

**Comment by sandipsubedi** [comment]
I am also facing this issue. Not quite sure how to fix it.

**Comment by NuclearMachine** [comment]
same here.

**Comment by kamal-kambe** [comment]
Same here. Any solution to this?

**Comment by Tylerian** [comment]
Same for me, is there any workaround for this?

**Comment by Tylerian** [comment]
After digging in Turbolinks source-code I found the issue. Turbolinks implementation of `DOMContentLoaded` event handling is faulty. It doesn't check the fact that the event may already have been fired before the script is loaded.


I'll make a push request to fix this issue. As a simple workaround while it gets accepted and merged, you can simply check if your `document.readyState` equals `interactive`, and if it does, fire the `turbolinks:load` event yourself as shown in the snippet below.

```javascript
if (document.readyState === "interactive") {
  const event = document.createEvent("Event");
  event.initEvent("turbolinks:load", true, true);
  document.dispatchEvent(event);
}
```
