### ISSUE TITLE
Re-evaling Javascript..

### ISSUE THREAD

**Issue by sblackstone** [turbolinks/turbolinks#64]
Is there a way in TL 5.0 to ensure that a block of javascript is re-evaluated at each load?

I'm using gon in my application to write data from the controller to an object in javascript and pages that depend on it throw an error if another page is loaded first which doesn't include the same data.

It seems that classic has a feature data-turbolinks-eval that I don't see in the 5.0 codebase.

Thanks,
Stephen

**Comment by nateberkopec** [comment]
It's coming soon and should be included in the TL5 final release. See #9.

**Comment by sblackstone** [comment]
gracias!
