### ISSUE TITLE
turbolinks not working with jQuery(document).on('ready', ...)

### ISSUE THREAD

**Issue by u007** [turbolinks/turbolinks#66]
hi,

the new turbolinks works perfectly with jquery(document).ready() :)

but i realize .on('ready', ...) wont work...
maybe we missed this?

thanks

**Comment by nateberkopec** [comment]
` $(document).on( "ready", handler )` was deprecated in JQuery 1.8. What version of JQuery are you using? I don't think this is a Turbolinks issue.
