### ISSUE TITLE
Turbolinks beta 4 shows [object Object] in between page loads

### ISSUE THREAD

**Issue by matiaskorhonen** [turbolinks/turbolinks#67]
After upgrading my Rails 5 app to use turbolinks-source 5.0.0.beta4, `[object Object]` flashes on the page in between page loads:

![turbolinks [object Object]](https://cloud.githubusercontent.com/assets/43314/14232303/78aeba7e-f9af-11e5-83eb-4d14872e2178.gif "[object Object]")

I've confirmed that this does not occur after downgrading back to turbolinks-source 5.0.0.beta3. No errors show up in the browser console and the issue occurs on both Google Chrome and Firefox (the latest versions).

**Comment by waits** [comment]
I can't reproduce this on another Rails 5 app with turbolinks-source 5.0.0.beta4, in any browser. Can you reproduce it on a minimal (empty) app?

**Comment by matiaskorhonen** [comment]
I tried to produce a minimal test case, but failed at it.

Switching from `"data-turbolinks-track" => true` to `"data-turbolinks-track" => "reload"` on the stylesheet links and javascript include tags seems to fix the issue, though. I'm not really sure what's going on there…

I'll close this issue since I can't reproduce it in a minimal Rails app.

By the way, is there changelog somewhere for Turbolinks 5? I couldn't find one…

**Comment by nateberkopec** [comment]
> Switching from "data-turbolinks-track" => true to "data-turbolinks-track" => "reload" on the stylesheet links and javascript include tags seems to fix the issue, though. I'm not really sure what's going on there…

The value of the data-turbolinks-track attribute needs to be `reload` in Turbolinks 5. :+1:

**Comment by matiaskorhonen** [comment]
Yeah, this project was generated with the old Rails 5 beta which was still using Turbolinks 2.x and it worked fine until Turbolinks 5 beta 4, so I never even noticed.

I hope there's an upgrade guide coming :)

**Comment by demiurgosoft** [comment]
This issue happened with Turbolinks 5.0.0.beta4 standalone on a nodejs application (loading the dist file in the client)

Turbolinks seems to be working, but sometimes this exact issue happens, please, 

Please give more details on the fix of possible

**Comment by demiurgosoft** [comment]
Using `data-turbolinks-track" => "reload` seems to fix the problem, but some pages stay hung for a while (I suspect is a problem with cached pages), only disabling the cache seems to fix both problems (no more [object Object])
