### ISSUE TITLE
rendering twice via cache + reloaded

### ISSUE THREAD

**Issue by u007** [turbolinks/turbolinks#7]
Hi,
is there a way to off the render from cache?
because the cached version is rendered while its trying to load the latest version.
its not good when we have a form in place, whereby user may started to type in some input in the text field and the server seems to take sometime to load, and causes the form to entirely rerendered.

yes. im using git version of turbolinks 5
thanks

**Comment by sebastianpicklum** [comment]
Wouldn’t that be solved by using `data-turbolinks-permanent`?

**Comment by packagethief** [comment]
Hi James --

Turbolinks Classic calls this the "transition cache" and allows it to be disabled both globally and on a per-page basis, neither of which are possible, currently, in Turbolinks 5. There's no philosophical reason for this. It just hasn't yet come up in our usage at Basecamp.

Ideally your replacement page will load quickly enough that there's hardly time to begin interacting with the temporary, preview DOM. When that's not the case you can detect whether a preview is being displayed and prevent interaction.

Since this isn't yet documented, I'll explain a bit about Turbolinks’ "preview DOM" here.

Turbolinks shows a cached preview DOM, if possible, when performing an `advance` visit (e.g., clicking a link). As its name suggests, this DOM is temporary -- it's a preview of the DOM we're waiting on from the server. While the same cached snapshot might be shown during a `restore` (e.g., clicking “back” or “forward”), it’s not a preview -- it's the final version and won't be replaced.

It can be useful to detect the preview state so you can avoid doing unnecessary work on a temporary DOM. To make this possible, Turbolinks annotates the `<html>` element with `data-turbolinks-preview` when a preview is being displayed.

So, one solution to your problem would be to listen for `focusin` on form fields and prevent them from accepting focus during a preview. For example:

```javascript
$(document).on("focusin", "input, button, textarea, [contenteditable]", function() {
  if (document.documentElement.hasAttribute("data-turbolinks-preview")) {
    this.blur();
  }
})
```

**Comment by u007** [comment]
thank you, okay i will take note, and wait for the good news :+1: 

btw, ive another question, does event $(document).on('ready page:load') still work?

i found that page:load and page:change does not work.
how do i rerun my js?

**Comment by gbuesing** [comment]
@u007 TL5 events have new names and new behaviors, see here for basic documentation: https://github.com/turbolinks/turbolinks/tree/docs#observing-navigation-events

Also, see here for a discussion of updating existing ```$(document).on('ready page:load')``` for TL5: https://github.com/turbolinks/turbolinks/issues/4

**Comment by jmbejar** [comment]
@u007 @packagethief 
As I commented in https://github.com/turbolinks/turbolinks/pull/8, I'm currently trying TL5 in a existing application that was working with TL3.

Rendering the cached version before loading a fresh copy of the page is introducing important issues to our application.

For instance, we have a sidebar in our application where some numbers are shown. This sidebar is always present, even in the home page.
Let's say we navigate from the home page to a section where we can add/modify/delete some items that affect the numbers in the sidebar. Being in this specific section of the app, the whole page is updated after each modification to those items (using turbolinks API, of course).

The problem appears when the user decides to leave this section browsing back to the home section. The sidebar **is showing correct (and fresh) numbers right before leaving the section** but it will render a cached version of the sidebar while the home page is loading, and then finally "restore" the correct values. In brief, it's causing a visual glitch that could confuse users.

Apart from this issue and the others described in https://github.com/turbolinks/turbolinks/pull/8, that are specific to our app, I feel like having some way to disable this behavior will be necessary (it could be a new option for links as I've implemented in the PR, or maybe a global option?).

**Comment by fernandes** [comment]
hi @jmbejar 

for forms I got a problem similar to yours, I solved with a JS removing all the notifications on `turbolinks:click`, so a fresh new view is cached.

but we got a problem like yours with a shopping cart badge, the use case:

1. user is seeing 0 items on cart
2. adds a item, items on cart is 1
3. back to a previously cached page, cart is empty

The idea of rendering a cached view is amazing for websites, where we have "stateless" views, but when we are on an admin, page it's more a problem then a solution.

I tried the `data-permanent`, but I don't know, its easier to handle the whole view server side and show on body then juggling between permanent/non-permanent divs

I'm +1 for a cache opt out

**Comment by packagethief** [comment]
Hi Jorge --

I agree with you on the need for an annotation to opt out of the preview cache. Thanks for exploring that in your PR. I have some thoughts on it that I'll share over there.

> Let's say we navigate from the home page to a section where we can add/modify/delete some items that affect the numbers in the sidebar... The problem appears when the user decides to leave this section. ... The sidebar is showing correct numbers right before leaving ... but it will render a cached version of the sidebar while the home page is loading, and finally "restore" the correct values. In brief, it's causing a visual glitch that could confuse users.

Your sidebar sounds like it would be good candidate for `data-turbolinks-permanent`, provided you have some way to maintain its state outside of a full render.

That's what we do with our top navigation menu in Basecamp 3, which shows live badge counts. It's rendered once with current counts on each full load, but ever after it's updated dynamically. Thus, we keep it from page-to-page by annotating it with `data-turbolinks-permanent` and giving it an HTML `id`. Permanent elements are moved from page-to-page, including their data and bound event listeners.

If your sidebar counts are only accurate after a full render, I think you'll have the staleness problem when navigating by history as well (i.e., "back" and "forward" buttons). If someone makes a change that affects the sidebar, and then clicks the "back" button, they'll see a stale version. The difference is that it won't be replaced by a fresh version from the network. (To be fair, you'd have this problem with standard browser navigation too. It's not unique to Turbolinks.)

In lieu of maintaing your sidebar's state out-of-band, you could consider clearing the page cache after any server-side state changes that affect it. This would ensure the next render is fresh, even when navigating by history. You can clear the cache at any time using `Turbolinks.clearCache()`.

**Comment by packagethief** [comment]
Hi @jmbejar --

> for forms I got a problem similar to yours, I solved with a JS removing all the notifications on turbolinks:click, so a fresh new view is cached.

A more appropriate place to do this is on the `turbolinks:before-cache` event. This is fired on `document` just before the current page is saved to the snapshot cache. It's the ideal place to prepare your DOM for storage: reset form fields, close expandable sections, uninstall non-idempotent behavior, and clean up state.

```js
$(document).on("turbolinks:before-cache", function() {
  // Prepare your DOM for cache storage
})
```

**Comment by u007** [comment]
awesome, i got onload working properly :+1:

**Comment by fernandes** [comment]
@packagethief thank you for the tip on `before-cache`, really is much better then on click
