### ISSUE TITLE
Transition page, tinming for transition out.

### ISSUE THREAD

**Issue by sutter** [turbolinks/turbolinks#70]
Hello,
I would like to know if it is possible to add animation with timing before loading the new page in order to have more fluid page transitions.

This is my code, but I do not know where to put the timer .

```
$(document).on('turbolinks:load', function() {
    $('body').addClass('loaded');
});

$(document).on('turbolinks:fetch', function() {
   $('body').addClass('loading');
});
```

Thanks

**Comment by sstephenson** [comment]
No, I’m afraid it’s not currently possible to animate the body transition.

Making this work would require careful coordination between [Turbolinks.BrowserAdapter](https://github.com/turbolinks/turbolinks/blob/master/src/turbolinks/browser_adapter.coffee) and [Turbolinks.Visit](https://github.com/turbolinks/turbolinks/blob/master/src/turbolinks/visit.coffee). The iOS and Android adapters use native view controller transitions.

**Comment by PascalPixel** [comment]
This is a sad moment
