### ISSUE TITLE
Angular

### ISSUE THREAD

**Issue by tibastral** [turbolinks/turbolinks#71]
Hello everyone,
First thank you for this amazing project.

I had an old turbolinks project with some angularjs.

When I migrated to turbolinks 5, the angular code runs when I load a page from http, but when I click on a link inside my project, the ng-app and ng-controller doesn't do anything.

Thank you for your help.

**Comment by packagethief** [comment]
My guess is that your previous code was bootstrapping Angular in response to Turbolinks Classic's `page:load` or `page:change`. Those events don't exist in Turbolinks 5. I suggest bootstrapping Angular in response to `turbolinks:load`, which fires both on the initial page load and after every Turbolinks visit.

That's just a guess, though. Did you end up figuring it out?

**Comment by tibastral** [comment]
That’s what I did at the end :

  document.addEventListener("turbolinks:load", function () {
    angular.bootstrap("body", [‘myControllerName']);
  })

—
Thibaut

On 17 mai 2016 at 20:11:35, Jeffrey Hardy (notifications@github.com) wrote:

My guess is that your previous code was bootstrapping Angular in response to Turbolinks Classic's page:load or page:change. Those events don't exist in Turbolinks 5. I suggest bootstrapping Angular in response to turbolinks:load, which fires both on the initial page load and after every Turbolinks visit.

That's just a guess, though. Did you end up figuring it out?

**Comment by packagethief** [comment]
Great! Glad you got it figured out.

**Comment by LuisDominguez** [comment]
@tibastral have code example for use angular + turbolinks? please

**Comment by tibastral** [comment]
I don't use neither angular nor turbolinks now, sorry about that !

Have a great day
