### ISSUE TITLE
Wiki is missing links to the now released iOS and Android adapters

### ISSUE THREAD

**Issue by joemasilotti** [turbolinks/turbolinks#72]
The [FAQ page on the Wiki](https://github.com/turbolinks/turbolinks/wiki/Turbolinks-5-FAQ#where-can-i-find-the-ios-and-android-adapters) mentions the iOS/Android adapters as "coming soon." I would edit the Wiki myself but can't seem to find the edit button or the wiki branch.

**Comment by sstephenson** [comment]
Thanks Joe. Feel free to edit it now. We inadvertently had the wiki set to read-only.

**Comment by joemasilotti** [comment]
Done!
