### ISSUE TITLE
Turbolinks reloading page when clicking hash links

### ISSUE THREAD

**Issue by dobrite** [turbolinks/turbolinks#78]
I've got anchor tags with `href="#"` that trigger javascript actions e.g. opens a modal. This seems to trigger a page reload, and thus closes the modal. Seems to be similar to this [Turbolinks classic issue](https://github.com/turbolinks/turbolinks-classic/issues/407). I browsed the issues and didn't see anything. 

Should I be doing something to prevent this?

Thank you so much for your work on Turbolinks!

**Comment by packagethief** [comment]
This is the same issue as #75. There are some workarounds mentioned there, but ultimately I think this needs to be fixed in Turbolinks. Turbolinks should let the browser handle clicks on anchors to the current page.

In the meantime, you should be able to listen for clicks on your anchor elements, present your modal, and call `event.preventDefault()` to prevent the click from bubbling up to Turbolinks's click handler.

**Comment by dobrite** [comment]
Awesome! Thanks for the quick turnaround.

**Comment by vtamara** [comment]
I also had problems with this when I updating turbolinks from 2.5.3 to 5.0.0

**Comment by kadimi** [comment]
@vtamara I'm using 5.0.0 and I fixed it and added scrolling with this:

```javascript
jQuery( document ).on( 'turbolinks:load', function() {

	var $ = jQuery;

	/**
	 * Improve anchors click behaviour:
	 * - Scroll to hash
	 * - Prevent useless refresh
	 */
	$( 'a' ).on( 'click', function( event ) {

		var $this = $( this );

		var current_url_relative = window.location.href.replace( window.location.origin, '' ).split( '#' )[0];
		var href_url_relative = $( this ).attr( 'href' ).replace( window.location.origin, '' ).split( '#' )[0];
		var is_same_page = current_url_relative === href_url_relative;

		if ( is_same_page ) {
			event.preventDefault();

			/**
			 * Position to scroll to.
			 *
			 * - No-hash: 0
			 * - Hash: the position of the referenced element (uses HTML id attribute)
			 * 
			 * @type Integer
			 */
			var to = ( $this.is( '[href*=#]' ) ) ? $( this.hash ).offset().top : 0;
			
			/**
			 * Scroll.
			 */
			$( 'html,body' ).animate( { scrollTop : to } );

			/**
			 * Update address bar and history
			 */
			if ( history.pushState ) {
				history.pushState( null, null, $this.attr( 'href' ) );
			}
		}
	} );
} );
```

**Comment by murb** [comment]
This issue is closed, but hasn't been solved... @packagethief mentions a workaround, as does @kadimi, but that isn't solving what I think is a bug in turbolinks (I believe @packagethief seems to agree). Shouldn't this be reopened? I'm happy to look into this.
