### ISSUE TITLE
Forms are not serializing submit buttons

### ISSUE THREAD

**Issue by pedantic-git** [turbolinks/turbolinks#79]
If I submit a form without `data-turbolinks-form`, the submit button (name and value) is added to the submitted form parameters.

But if I submit it using turbolinks 5 and the `data-turbolinks-form` attribute, it's missing.

I see [there is code in jquery_ujs](https://github.com/rails/jquery-ujs/blob/v1.2.1/src/rails.js#L122) to add it to the parameters but in my app it's not being added.

Any idea what might be causing this? I have two submit buttons and right now I can't see a nice way to determine which of them was pressed.

**Comment by packagethief** [comment]
Hey @pedantic-git,

It doesn't seem like this is a Turbolinks issue. Turbolinks doesn't do anything at all with forms, and has no support for the `data-turbolinks-form` annotation (I've actually never heard of that annotation).

Do you observe the same form behavior when you remove Turbolinks?

**Comment by pedantic-git** [comment]
Oh, of course! How ridiculous of me. I got that from [here](https://github.com/turbolinks/turbolinks-classic/issues/64#issuecomment-102798441) so it's an issue with that code.

Sorry to have bothered you!

**Comment by packagethief** [comment]
No problem!

fwiw, I'd like for Turbolinks to eventually support form submission. It's a bit of a gap right now, requiring that you rely on jquery-ujs or similar.

**Comment by nateberkopec** [comment]
@packagethief I don't mind the jquery-ujs dependency TBH. I wish Rails' UJS behaviors didn't, in turn, require JQuery though 😆
