### ISSUE TITLE
Appropriate event to use when unmounting react components

### ISSUE THREAD

**Issue by dobrite** [turbolinks/turbolinks#80]
Turbolinks classic exposed a `page:before-unload` (`BEFORE_UNLOAD`) that `react-rails` [tapped into](https://github.com/reactjs/react-rails/blob/master/lib/assets/javascripts/react_ujs_turbolinks_classic.js#L7) to unmount components. I hit [an issue](https://github.com/reactjs/react-rails/issues/516) where the react components do not show when the cache is being shown (see linked issue for some gifs). I attempted to tap into the `before-render` event instead, and it seems to fix my issues, but react [is complaining](https://github.com/reactjs/react-rails/pull/517#issuecomment-213043994) in Rails 5.

Is this the most appropriate event to unmount components? It seems like _after_ taking the cache snapshot would be most appropriate, however Turbolinks doesn't expose this as a lifecycle event. Is `before-render` a nice alternative? I'm trying to find where exactly a fix should live.

thanks!

**Comment by sstephenson** [comment]
`turbolinks:before-render` is the right event to observe if you need to do something right before Turbolinks swaps the body.

I’m afraid I can’t help with the React warning, though. Keep in mind that Turbolinks always renders cloned copies of elements from its cache, even when navigating back. I’m guessing React doesn’t handle  that properly.

**Comment by wied03** [comment]
Perhaps there might be a way to combine React's server side rendering compatibility to fix this? I'm not sure if React 15's changes with data-react-id affect this.
