### ISSUE TITLE
remove turbolinks and app events listener after each loading

### ISSUE THREAD

**Issue by snhasani** [turbolinks/turbolinks#81]
Each time the turbolinks is loaded, it add its event listener to window and document object? or I miss something in configuration!
![turbolinks-event](https://cloud.githubusercontent.com/assets/23160/14841887/7a78d046-0c57-11e6-8d1a-3dec8ab9e87e.png)
I just have the turbolinks script in page and I turn off my scripts.
How can I fixed this and remove event listener after each visit?

**Comment by nateberkopec** [comment]
Sounds like a bug, although I can't reproduce it. What Turbolinks version are you using?

**Comment by snhasani** [comment]
latest version @5.0.0-beta4.

**Comment by snhasani** [comment]
I'm sorry for closing issue. I am using latest version @5.0.0-beta4.

**Comment by sstephenson** [comment]
Are you including Turbolinks via a `<script src>` tag in the `<body>`? If so, you’ll want to make sure all scripts are in `<head>` instead.

**Comment by snhasani** [comment]
Thanks. I put turbolinks script tag in `<head>` and working prefect now :smile: :+1:
