### ISSUE TITLE
Prefetch Loading

### ISSUE THREAD

**Issue by glennfu** [turbolinks/turbolinks#84]
Back in 2013 there was this PR and discussion: https://github.com/turbolinks/turbolinks-classic/pull/253

There seemed to be some real interest in making this work back then. In my app, the main index as the app loads has 4 rows. The first row will be clicked 90% of the time. Being able to prefetch this in some way would be awesome.

I have some thoughts about a data attribute triggering a delayed prefetch kind of like this: https://developer.mozilla.org/en-US/docs/Web/HTTP/Link_prefetching_FAQ but I think the most obviously useful thing would be to do it like discussed in the original pull request which involves listening for hover/touchstart to trigger a prefetch.

So just to tinker, you can add this to a page:
```
document.addEventListener("touchstart", function(e) {
  var $link = $(e.target).closest("a");
  if ($link.length == 0) return;
  
  var dest = Turbolinks.Location.wrap($link.attr("href"));
  var delegate = {
    requestCompletedWithResponse: function(response, redirectedToLocation) {
      var snapshot = Turbolinks.Snapshot.wrap(response);
      Turbolinks.controller.cache.put(dest, snapshot);
    }
  };

  var request = new Turbolinks.HttpRequest(delegate, dest, window.location.pathname);
  request.send();
});
```

Now this kind of works, except it doesn't run scripts and also Turbolinks then fetches the page a 2nd time. This is mostly expected since that's the same behavior as clicking the "back" button. The snapshot is loaded, then the page is reloaded overtop of it and scripts are run.

So Turbolinks needs to know this isn't the same kind of "restore" situation. If I add a `data-turbolinks-action='prefetch'` in that touchstart handler above, I can get some places to start adding some custom behavior. I've tinkered a bit with this so I can say "don't reload the page a 2nd time if it's a 'prefetch' action".

I found that if I want turbolinks-ios to play nicely, I should tell `@adapter.visitProposedToLocationWithAction` that the action is "advance" because it shouldn't care about whether or not the page is being prefetched. However if I change it there, the further requests won't know that it should be cached differently. It's here I'm a bit stumped.

Am I totally off track here, or can someone give me some direction? I'd like to make this work, but I'm not intimate enough with the codebase to see where this kind of thing should really fit.

**Comment by nateberkopec** [comment]
Seems out-of-scope or orthogonal to Turbolinks to me. 

I think you're better off with [resource hints](https://w3c.github.io/resource-hints/) (covers your first use case) or [rel=preload](https://w3c.github.io/preload/). I *think* using these solutions will prevent Turbolinks from re-requesting the document. Give them a shot if you haven't already.

**Comment by sstephenson** [comment]
Thanks for opening this issue, @glennfu. Preemptively fetching pages in a predictive manner is an interesting idea with potentially lucrative performance implications.

First, I don’t think a new action is the right way to approach this. Visiting a prefetched URL might seem a lot like visiting a cached page with the `restore` action, but really, actions are about how the browser’s _history_ changes. Whether the page has been prefetched or not is orthogonal to how history is changed. Prefetched pages could apply equally to an `advance` visit, a `replace` visit, or a `restore` visit.

Second, my hope with Turbolinks 5 is that we can lean on the browser as much as possible for these kinds of features, and rely on polyfills or plugins otherwise. So my suggestion for getting this working would be to 1) explore using resource hints or rel=preload as @nateberkopec suggests above, and if that doesn’t work, 2) consider extending Turbolinks with the minimal set of hooks needed to implement this as a plugin.

For the plugin route, we’d probably want to add a way to short-circuit the HTTP request and tell Turbolinks to use our own response body string, perhaps by exposing a “set response body” function on the `turbolinks:visit` or `turbolinks:request-start` event.

**Comment by glennfu** [comment]
@nateberkopec unfortunately those aren't supported by any version of Safari, and I'm primarily building for turbolinks-ios.

@sstephenson I totally agree it doesn't make sense as an action, but I didn't see any more reasonable endpoint to dive into at first. I went the route of leveraging the Cache and Snapshot models since they already existed in Turbolinks. I like your idea of hooking into HTTP requests, though. Next time I get the chance, I'll see if I can do something clever with the HttpRequest model!

**Comment by glennfu** [comment]
Looks like jiagra overrides the onClick of links and adds the prefetched url to the anchor of the current page url when clicked. In both of these ways it definitely steps on the toes of Turbolinks instead of helping out.

This seems to be the most recent conversation I can find on the topic: https://twitter.com/cramforce/status/661315843305836544

I think a plugin into HttpRequest is going to be the best way to go. I'll see if I can give that a try soon.

**Comment by glennfu** [comment]
OK, here's what I have so far: https://gist.github.com/glennfu/936548b58091f284dbb5c1a769130bfc

This seems to work really well for my app, but it's not a full implementation of the "preload" hint, but instead an implementation of the `touchstart` and `mouseover` preload behavior. I think doing it the `rel=prefetch` way would require a lot more conversation about when/how/why. This is a much simpler drop-in plugin to quickly get a solid benefit.

I also chose to store these pages within the Turbolinks.Cache, and delete them as soon as they're used. I kind of like the idea that these would also hold to the limit of your 10 cached pages.

This is my first pass at this. I hope to do some more of my own testing to see if there's any glaring bugs I may have missed, but so far I'm pretty excited at how well it seems to work. I look forward to hearing feedback and suggestions!

**Comment by glennfu** [comment]
For anyone who finds this via Google, the Gist I have there is a drop-in patch that works on top of Turbolinks 5. It's been working well for me this past month in web, turbolinks-ios, and turbolinks-android versions of my app.
