### ISSUE TITLE
Handling form errors with Rails automatically?

### ISSUE THREAD

**Issue by excid3** [turbolinks/turbolinks#85]
When you submit a form that has errors, Rails normally renders the new action again with the form and the errors. With Turbolinks as it is setup right now, the redirects are handled nicely, but this piece requires you to build your own create.js.erb response to render the errors. 

Would it make sense to add something into Turbolinks / turbolinks-rails that if you submitted a non-GET request and it returned an HTML response that it would take the URL of the request and navigate to that but render the HTML that was returned from the server?

**Comment by kevinhughes27** [comment]
I solved this by modifying  `$.rails.ajax` like so:

```coffeescript
$.rails.ajax = (options) ->
  op = $.ajax(options)

  op.done (response) ->
    unless response.substring(0, 10) == 'Turbolinks'
      Turbolinks.clearCache()
      document.documentElement.innerHTML = response
      Turbolinks.dispatch("turbolinks:load")
      window.scroll(0,0)

```

**Comment by fernandes** [comment]
@excid3 

Just improving (and providing an alternative to @kevinhughes27 's answer), this is how I handle form errors in TL

I add a `data-behavior="turbolinks-form"` on forms I want to be handled using my JS, and then add this file under `app/assets/javascripts/support/form_bindings.js`

```javascript
formBindings = function() {
  $('[data-behavior="turbolinks-form"').on("ajax:success", function(e, data, status, xhr) {
    return;
  }).on("ajax:error", function(e, xhr, status, error) {
    form_id = "#" + this.id;
    $(form_id).html($(form_id, xhr.responseText).html());
    return;
  });
};

$(document).on('turbolinks:load', formBindings);
```

the main idea is once its return a HTML rendering a form with the same id that posted, just replaces the HTML. the concept behind was to:

1. use data behaviors to separate code / data
2. bind only specific form
3. replace using id lookups and `html` function

so, here is my suggestion 😉

**Comment by gregblass** [comment]
I think where I lost @sstephenson is here:

"In response to an XHR submit on the server, return JavaScript that performs a Turbolinks.visit to be evaluated by the browser."

An example would help me there, in the case where the record is saved and in the case where there are form validation errors?

**Comment by packagethief** [comment]
> Would it make sense to add something into Turbolinks / turbolinks-rails that if you submitted a non-GET request and it returned an HTML response that it would take the URL of the request and navigate to that but render the HTML that was returned from the server?

We intend to explore expanding Turbolinks to support XHR form submission in the future, so I think this is something we can consider at that time. Until then, I don't think Turbolinks should make (more) assumptions about how you might be responding to non-Turbolinks XHR requests.

Assuming you're using jQuery via Rails' UJS adapter (assumptions!), the following pattern should work well for validation errors. In `create.js.erb`:

```erb
<% if @message.valid? %>
  Turbolinks.clearCache()
  Turbolinks.visit("<%= message_path(@message) %>", { action: "replace" })
<% else %>
  $("form").replaceWith("<%=j render "form" %>")
<% end %>
```

Ensure you [exclude such form-containing pages from Turbolinks' preview cache](https://github.com/turbolinks/turbolinks/blob/master/README.md#opting-out-of-caching) to prevent any validation errors from being displayed during a preview on the next visit.

**Comment by nerdcave** [comment]
Is there a way to just pass an HTML page string to Turbolinks and have it do the processing? I think that would really help in cases like this. I dug through the source and couldn't find a way that worked.
For example:
```coffeescript
ajax.done (response) ->
  Turbolinks.clearCache()
  Turbolinks.render(response) #something like this exist?
```
Similar to @kevinhughes27's suggestion, but I think it would make more sense to pass off the DOM processing to Turbolinks to ensure some consistency in app behavior (events get dispatched properly, etc). Any way to do this?

**Comment by kevinhughes27** [comment]
Turbolinks3 used to have this as `Turbolinks.replace` - maybe its possible to bring back this method but not the partial replace aspects of it?

**Comment by acapro** [comment]
I solved this a bit differently using jquery since kevinhughes27's answer was still causing the page to blink(making it seem like a reload). This is only compatible with simple_form and jquery:

    removeErrors = () ->
      $('.input').each ->
        $(@).removeClass('field_with_errors')
        $(@).find('span.error').remove()

    $(document).on("ajax:success", (e, data, status, xhr) ->
      # Succes code can go here
    ).on("ajax:error", (e, data, status, xhr) ->
      removeErrors()
      errors  = jQuery.parseJSON( data.responseText )
      $.each errors, (key, value) ->
        input_field = $("[id$=#{key}]")
        input_field.parent().addClass('field_with_errors')
        $("<span class='error'>#{value}</span>").insertAfter(input_field)
    )

to make this work, the controller response needs to have something like this:

    format.js { render json: @post.errors, status: :unprocessable_entity }

**Comment by gregblass** [comment]
I have no affiliation with GoRails or @excid3, and I'm not trying to cross any boundaries here on that front, but the screencast he did on this is very helpful and explains the code @kevinhughes27 posted in more detail. IMO its a great solution - I have implemented it myself in production.

**Comment by FloLinn** [comment]
@kevinhughes27 @acapro 
you can also avoid the blinking by only replacing a part of the page.
In my project, I only replace the form object
`$("form").html($("form", response).html())`

**Comment by gregblass** [comment]
One issue I've found with @kevinhughes27 's modifying $rails.ajax is that then it messes up any other ajax request (like when I just want to load a partial via ajax).

So it looks like I may be handling each form on a case by case basis because of that. Unless I can figure out a way to do it the other way around - that is, include something in my one off ajax requests to not fire that code off.

**Comment by gregblass** [comment]
Here's my current solution:

In /partials/_form_errors.js.erb:
```
Turbolinks.clearCache();
$("form").replaceWith("<%= j render 'form' %>");
Turbolinks.dispatch("turbolinks:load");
$(".field_with_errors:first input").focus();
```
Then in new.js.erb and edit.js.erb:
`<%= render "partials/form_errors" %>`

Kinda stinks I have to make new.js.erb and edit.js.erb for every model, but it works just fine.

**Comment by gregblass** [comment]
Here's my current design pattern I've been using in my production apps:

In the controller, on a form error:
```
render partial: "form", status: 422
```
Then I use this app wide:

```
$(document).on("ajax:error", "form", function(e, data, status, xhr) {
  $(this).replaceWith(data.responseText);
  Turbolinks.dispatch("turbolinks:load");
  $(".field_with_errors input:first").focus();
});
```
And of course make all forms remote. This works great for me.

**Comment by woahdae** [comment]
@sstephenson why was this closed without comment? I was quite surprised that turbolinks 5 gets you almost out the gate with 100% CRUD coverage, except this one case you have to figure out yourself. It should still be open for discussion, no? Or (wrongly, IMO) declare "wontfix"?

**Comment by woahdae** [comment]
@gregblass Really nice solution, consider the following a "yes and."

While not good enough yet as a patch to turbolinks (I'm sure the project has its own way of parsing the body already), I think it's more idiomatic overall. The whole point of turbolinks is to just code "normal" Rails, turn on turbolinks, and have everything "just work" but faster. So:

In your controller, nothing changes except currently the 422 status (Turbolinks could do that for you, like they do with the custom redirect_to):

    render "edit", status: 422

Then the javascript becomes something very similar to what Turbolinks does. Again, I'm sure the project authors would do this better, but I don't feel like digging in since it's not clear there'd be any interest.

    $(document).on("ajax:error", 'body', function(e, data, status, xhr) {
      $(this).html(
        data.responseText.match(
          /<body[^>]*>((.|[\n\r])*)<\/body>/im
        )[0]
      );
      Turbolinks.dispatch("turbolinks:load");

      // This is application-dependent, but a nice touch.
      $(".has-error input:first").focus();
    });

Two reasons I like this approach:

1. I had no idea Turbolinks had this issue, and with NO other changes to my code (just the `status: 422` bit and the JS) everything works. Personally, I use the 'form' template for just the form fields, and let 'new' and 'edit' pass in their own form objects and draw their own buttons. I could pull these in to 'form,' but that'd be coupling the organization of your views to a technical gotcha with Turbolinks.
2. It's not just the form that matters, for example I have flash message handling in the layout. With the above technique, the flash messages still work just fine. Sure, I could change the flash messages to be handled with JS too, but same point as before. It's supposed to "just work."

Why does this issue exist, and (again) why was it closed? Is there some edge-case reason why this must break convention over configuration?

**Comment by jondavidchristopher** [comment]
@woahdae nice solution above. I am using it currently. I hit an interesting edge case where errors are only displayed via a flash message (think devise login error "Invalid Email or Password"). When on a mobile device, activating the keyboard causes the page to scroll down. When submitting a form with errors the flash message is displayed but it is above the fold where the user cannot see it. It is standard "Turbolinks" practice to scroll back to the top of the page after loading it. Implemented a simple fix for this below and thought I would share:

`
// This is application-dependent

  if ($("#flash_message").length > 0) {
    scrollTo(0,0);
 } else {
    $(".has-error input, .has-error select").first().focus()
 }
`

**Comment by nerdcave** [comment]
I think a lot of the confusion here is because the Turbolinks gem hijacks the `redirect_to` call in Rails but not the `render` call. This does seem incomplete to me, but I can also see why they tread lightly.

If you wanted to override `render` yourself and keep the solution server-side, you could do something like this:

```ruby
# maybe the Turbolinks gem could do something like this
def render(*args)
  options = args.extract_options!
  return super unless options[:turbolinks]

  html = render_to_string args[0]
  script = <<-SCRIPT
    Turbolinks.clearCache();
    var parser = new DOMParser();
    doc = parser.parseFromString("#{ActionController::Base.helpers.j(html)}", "text/html");
    document.documentElement.replaceChild(doc.body, document.body);
    Turbolinks.dispatch("turbolinks:load");
    window.scroll(0, 0);
  SCRIPT
  self.status = 200
  self.response_body = args.inspect
  response.content_type = "text/javascript"
end

# in your controller:
def update
  if @obj.update(obj_params)
    rendirect_to @obj
  else
    # render entire page, not just the form
    render :edit, turbolinks: true
end
```

**Comment by grosser** [comment]
can we reopen this and get a proper solution ?
... we know the request was xhr ... and that it came from turbolinks ... so do whatever necessary serverside and fix turbolinks js to handle that ...

**Comment by grosser** [comment]
FYI simpler body replacement:
```
$("body").html(response.match(/<body[^>]*>([\s\S]*?)<\/body>/i)[1]);
```

... my complete script to handle get forms and regular forms is now:

```js
$(document).on('submit', 'form[method=get][data-remote=true]', function(e) {
  e.preventDefault(); // do not perform regular sumbit
  e.stopPropagation(); // do not let regular remote handler see this
  var form = $(this);
  Turbolinks.visit(form.attr("action") + form.serialize());
});

$(document).on('ajax:success', 'form[method!=get][data-remote=true]', function(e, response) {
  if(response.substring(0, 10) == 'Turbolinks'){ return; }
  Turbolinks.clearCache();
  $("body").html(response.match(/<body[^>]*>([\s\S]*?)<\/body>/i)[1]);
  Turbolinks.dispatch("turbolinks:load");
  $(".has-danger input, .has-danger select").first().focus();
});
```

**Comment by danieldraper** [comment]
Rails 5 introduced `form_with` which by default treats all forms as AJAX unless you pass the `:local` option. The solution for Turbolinks should probably be applied to Rails to work with `form_with` also. See https://github.com/rails/rails/blob/master/guides/source/working_with_javascript_in_rails.md

**Comment by minimul** [comment]
@nerdcave Just what I needed when doing an upgrade to TL5. 

Submitted as a PR as well. 

https://github.com/turbolinks/turbolinks-rails/pull/20

Thanks.

**Comment by jondavidchristopher** [comment]
Another issue I just ran into with wholesale replacing the body on an error is that inline page scripts are not executed. Below is a simple snippet of CoffeeScript that handles this via Turbolinks.


```
    renderer = new Turbolinks.Renderer
    for inline_script in document.body.getElementsByTagName "script"
      element = renderer.createScriptElement inline_script
      inline_script.parentNode.replaceChild element, inline_script
```

**Comment by codyrobbins** [comment]
I’m just going to pile on and say that this seems like a glaring hole in Turbolinks and it makes no sense to me that you have to roll your own form submissions instead of having them “just work” out of the box. It seems inconsistent with the way Turbolinks handles responses to GET requests and redirects and the documentation doesn’t make it clear that Turbolinks doesn’t work in this respect—it took me quite a while to figure out that I wasn’t doing something wrong but rather that Turbolinks just doesn’t do what you’d expect it to do here.

**Comment by tomrossi7** [comment]
@woahdae I really like your approach. I'm not sure if it is related to `jquery-rails 4.3.1` and `rails 5.1.1`, but I'm unable to get it to work. The "ajax:error" event is triggered, but I can't access the data. Logging appeared to show that of the variables passed (e, data, status, xhr), only e was being passed from ujs? Am I missing something obvious?

**Comment by johnclittle** [comment]
Is it possible with any of the above solutions to respect the data-turbolinks-permanent designations?

**Comment by hansondr** [comment]
@tomrossi7

There were a number of changes that came with `rails-ujs`.  The current callback format is:

```
$(document).on("ajax:error", 'body', function(event) {
  var data = event.detail[0];
  var status = event.detail[1];
  var xhr = event.detail[2];
  var responseText = xhr.responseText;
  // ....
}
```

**Comment by stefan694** [comment]
Is there a solution in ES6 ? I dropped jQuery in my project.

**Comment by mvanduijker** [comment]
I dropped jquery as well. I am doing something like.

```javascript
document.body.addEventListener("ajax:error", function (e) {
      if (e.detail[2].status !== 422) {
        return
      }
      document.body = e.detail[0].body
      Turbolinks.dispatch("turbolinks:load")
      scrollTo(0, 0)
    })
```

**Comment by stefan694** [comment]
Thanks mvanduijker I add a little change to your code. WIthout it will only catch ajax error the first time.

document.addEventListener("turbolinks:load", () => {
  document.body.addEventListener("ajax:error", (e) => {
    if (e.detail[2].status !== 422) {
      return
    }
    document.body = e.detail[0].body
    Turbolinks.dispatch("turbolinks:load")
    scrollTo(0, 0)
  })
})

**Comment by dustMason** [comment]
@stefan694 and @mvanduijker You can also create a persistent event listener without re-attaching every time Turbolinks loads the page:

```js
document.addEventListener("ajax:error", (e) => {
  if (e.detail[2].status !== 422) { return }
  document.body = e.detail[0].body
  Turbolinks.dispatch("turbolinks:load")
  scrollTo(0, 0)
})
```

**Comment by mvanduijker** [comment]
Nice catch @dustMason!

**Comment by dvcolgan** [comment]
While spelunking in the sourcecode for changelog.com (not Rails but uses Turbolinks), I found them using this technique:

```javascript
// submit all other forms with Turbolinks                                                   
u(document).on("submit", "form:not(.js-cm)", function(event) {                              
  event.preventDefault();                                                                   
                                                                                            
  const form = u(this);                                                                     
  const action = form.attr("action");                                                       
  const method = form.attr("method");                                                       
  const data = form.serialize();                                                            
  const referrer = location.href;                                                           
                                                                                            
  if (method == "get") {                                                                    
    return Turbolinks.visit(`${action}?${data}`);                                           
  }                                                                                         
                                                                                            
  const options = {method: method, body: data, headers: {"Turbolinks-Referrer": referrer}}; 
  const andThen = function(err, resp, req) {                                                
    if (req.getResponseHeader("content-type").match(/javascript/)) {                        
      eval(resp);                                                                           
    } else {                                                                                
      const snapshot = Turbolinks.Snapshot.wrap(resp);                                      
      Turbolinks.controller.cache.put(referrer, snapshot);                                  
      Turbolinks.visit(referrer, {action: "restore"});                                      
    }                                                                                       
  }                                                                                         
                                                                                            
  ajax(action, options, andThen);                                                           
});                                                                                         
```
from https://github.com/thechangelog/changelog.com/blob/master/assets/app/app.js#L121

In summary, for forms marked to be submitted with Turbolinks, submit the request, and check if the response has content-type Javascript.  If it does eval it, otherwise take the response (which would be the html for the whole page of an invalid form), _manually add it to the Turbolinks cache, and then visit that newly added page._

I don't think adding pages manually to the cache is documented anywhere but it does appear to work pretty well for me, and you don't have to mess with anything server-side other than not returning a JS response if there is a problem.

**Comment by hsgubert** [comment]
I solved this problem in my application by capturing the rendered HTML after a form submit, and replicating the behavior of Turbolinks, namely:

1. The body of the page is replaced by the new body
2. Inline `<script>` tags on the new body are run
3. The correct turbolinks events are triggered (e.g. request-start, request-end, before-render, render, load)

I've packaged my solution to a gem [turbolinks-form](https://github.com/hsgubert/turbolinks-form) and using it is as simple as adding an option to your form_tag/form_for and rendering something with an error code in your controller.

I'm glad to receive any comments

**Comment by domchristie** [comment]
The [changelog.com code](https://github.com/turbolinks/turbolinks/issues/85#issuecomment-328366836) that @davidscolgan shared is great, since it uses Turbolinks to render the response, run inline scripts, handle scrolling, and fire the load event, all with just a few built-in methods. Clever.

For those using Rails, the form serialization code is not necessary as it is built-in to rails-ujs. To combine some of the other solutions with the changelog code:

```js
$.rails.ajax = function(options) {
  return $.ajax(options).done(function(response, status, $xhr) {
    if (response && ($xhr.getResponseHeader('Content-Type') || '').substring(0, 9) === 'text/html') {
      var referrer = window.location.href
      Turbolinks.controller.cache.put(referrer, Turbolinks.Snapshot.wrap(xhr.response))
      Turbolinks.visit(referrer, { action: 'restore' })
    }
  });
};
```

or for rails-ujs (i.e. without jQuery):

```js
document.addEventListener('ajax:complete',function (event) {
  var xhr = event.detail[0]
  if ((xhr.getResponseHeader('Content-Type') || '').substring(0, 9) === 'text/html') {
    var referrer = window.location.href
    var snapshot = Turbolinks.Snapshot.wrap(xhr.response)
    Turbolinks.controller.cache.put(referrer, snapshot)
    Turbolinks.visit(referrer, { action: 'restore' })
  }
})
```

**Comment by pioz** [comment]
My solution is this based on @kevinhughes27 post

```
$.rails.ajax = function(options) {
  var op = $.ajax(options);
  op.done(function(response) {
    if (response.substring(0, 10) != 'Turbolinks') {
      Turbolinks.clearCache();
      document.body.innerHTML = /<body.*?>([\s\S]*)<\/body>/.exec(response)[1];
      Turbolinks.dispatch("turbolinks:load");
      window.scroll(0,0);
    }
  });
}

```

**Comment by kmmbvnr** [comment]
I extended a bit @domchristie solution

After a successful form submission, the location should be changed to the redirected.

```javacript
performPostRequest() {
    // disable form buttons
    this.root_.querySelectorAll('button').forEach(
      (button) => button.disabled=true
    );

    let xhr = new XMLHttpRequest();
    xhr.open('POST', window.location.search, true);
    xhr.setRequestHeader('Turbolinks-Referrer', window.location);

    xhr.onload = (event) => {
      let location = xhr.getResponseHeader('turbolinks-location');
      let snapshot = window.Turbolinks.Snapshot.wrap(xhr.response);

      if (!location) {
        location = window.location.href;
      }

      window.Turbolinks.controller.adapter.hideProgressBar();
      window.Turbolinks.controller.cache.put(location, snapshot);
      window.Turbolinks.visit(location, {action: 'restore'});

      if (xhr.status > 299) {
        Turbolinks.controller.disable();
      }
    };

    window.Turbolinks.controller.adapter.showProgressBarAfterDelay();
    xhr.send(new FormData(this.root_));
  }
```

**Comment by pioz** [comment]
My solution is this:

```
$.rails.ajax = function(options) {
  return $.ajax(options).done(function(response, status, xhr) {
    if (response && (xhr.getResponseHeader('Content-Type') || '').substring(0, 9) === 'text/html') {
      var referrer = window.location.href;
      Turbolinks.controller.cache.put(referrer, Turbolinks.Snapshot.wrap(response));
      Turbolinks.visit(referrer, { action: 'restore' });
    }
  });
};
```

**Comment by acapro** [comment]
i've modified @dustMason's code so that only the forms get replaced instead of the whole body.  This way the rest of the JS stuff on the page still works fine.

```js
document.addEventListener("ajax:error", (e) => {
  if (e.detail[2].status !== 422) { return }

  for(let i=0; i < document.forms.length; i++) {
    document.forms[i].innerHTML = e.detail[0].forms[i].innerHTML
  }

  Turbolinks.dispatch("turbolinks:load")
  scrollTo(0, 0)
})
```

**Comment by jorgemanrubia** [comment]
I published a [gem to support handling `render` with Turbolinks](https://github.com/jorgemanrubia/turbolinks_render). It is based on the idea shared by @nerdcave in [this comment](https://github.com/turbolinks/turbolinks/issues/85#issuecomment-298347900):

- By default, it handles render with Turbolinks for Ajax requests that are not `GET` (and that are not rendering json).
- There is a global config flag to change the default behavior
- It supports passing a `turbolinks` option to `render` to enable/disable turbolinks on a per-request basis.

I think the situation right now is inconsistent and can be really confusing:

- Rails 5 adds Turbolinks by default
- Forms are remote by default
- `render` won't work with the defaults mentioned above. 

The fact that forms in scaffolds are generated with `local: true` in Rails 5.2 looks like an smell to me. The vanilla code generated by Rails won't use its own defaults!

**Comment by besrabasant** [comment]
Here is my solution that works with Laravel

https://gist.github.com/besrabasant/4ea3c6503a1896e50b5c6973bc48395f

**Comment by kmmbvnr** [comment]
Anyone has solution for Turbolinks 5.3.0-beta.1 ? Turbolinks.Snapshot became undefined
