### ISSUE TITLE
Redirection as part of Authentication...

### ISSUE THREAD

**Issue by sblackstone** [turbolinks/turbolinks#86]
We are using Turoblinks 5.

In our app, if a user isn't logged in, we redirect them to a sign-in page that uses a separate layout..

However, If a user's session has timed out and they click on any link, turbolinks ends up showing our login screen with the styling of the main site - I'm not sure how to say "redirect the user with a reload"

Couldn't find anything in the docs that covers this case..

Thanks,
Stephen

**Comment by packagethief** [comment]
Hey Stephen. I saw you closed this issue but I wanted to reply anyway. Sorry for not replying sooner!

I suggest returning responding to Turbolinks requests with "401 Unauthorized" when you require a signed-in user. Include the URL of your sign in page in the "WWW-Authenticate" header. Then, listen for `turbolinks:request-end` and handle a 401 by setting `window.location` to the URL in "WWW-Authenticate".

Here's how that might look.

```ruby
head :unauthorized, "WWW-Authenticate" => sign_in_url
```

```js
document.addEventListener("turbolinks:request-end", function(event) {
  if (event.data.xhr.status == 401) {
    window.location = event.data.xhr.getResponseHeader("WWW-Authenticate")
  }
})
```

What did you end up doing in your application?

**Comment by sblackstone** [comment]
Thanks!  I haven't done anything yet, but I like this - its clean.

I realized that it was devise that was doing the re-direct and I suspect its not using standard rails redirect_to - I was just going to look for the Turbolinks header in the response and see if the redirect location was /users/sign_in but I wasn't being set.
