### ISSUE TITLE
Turbolinks.clearCache() not working as expected?

### ISSUE THREAD

**Issue by gregblass** [turbolinks/turbolinks#87]
I have a remote form submission that will render the form back with error classes if validation fails. Then, on a successful submission, I have in my create.js.erb or update.js.erb:

    Turbolinks.visit("<%= path %>", { action: "replace" });
    Turbolinks.clearCache();

I would expect that to clear the cache. However, if I click again to return to that form, the form error classes are still there for a split second before the cache replaces it, resulting in a jarring effect on the user.

What am I missing here, or could this be a bug? Using 5.0.0.beta4.

**Comment by nateberkopec** [comment]
Sounds like the [preview being loaded](https://github.com/turbolinks/turbolinks#understanding-caching).

On the page with the form, [try adding a `no-preview` meta tag](https://github.com/turbolinks/turbolinks#opting-out-of-caching) and see if that helps.

Also, clearing cache *before* calling `visit` may work for you.

**Comment by nateberkopec** [comment]
One other idea. Use `data-turbolinks-preview` to hide error-related CSS/HTML when previewing.

```javascript
if (document.documentElement.hasAttribute("data-turbolinks-preview")) {
  // Turbolinks is displaying a preview
  $(".field_with_errors").hide(); // or whatever
}
```

**Comment by packagethief** [comment]
This surprised me too, but I can explain why it happens. `Turbolinks.visit` is async, so while the cache is cleared after the visit starts, it won't finish until sometime later. When it does, the current page (the one with the validation errors) will be cached before the new page is rendered.

For this to work like you intend, you'd have to clear the cache _after_ the visit has finished. You should be able to prove this by doing something like this in your `create` response:

```js
var clearCacheOnce = function() {
  Turbolinks.clearCache()
  document.removeEventListener("turbolinks:load", clearCacheOnce)
}

document.addEventListener("turbolinks:load", clearCacheOnce)
```

I'd do as @nateberkopec suggested, though, and disable the preview cache on pages where you display validation errors. That's what we do at Basecamp.

I recall now that the [Rails engine's redirect_to response](https://github.com/turbolinks/turbolinks-rails/blob/3210d14/lib/turbolinks/redirection.rb#L30-L31) suffers from the same problem, so it would be nice to fix this. In an earlier version of Turbolinks 5, `visit` returned a Promise that was resolved when the visit finished. That would be handy here: `Turbolinks.visit(...).then(Turbolinks.clearCache)` :smile:

**Comment by gregblass** [comment]
Awesome. Great advice, thank you both!

**Comment by gregblass** [comment]
So I thought the simplest way would be to do this in the <head>:

`<% if action_name == "new" %>
  	<meta name="turbolinks-cache-control" content="no-preview">
  <% end %>`

But thats not being evaluated unless I refresh the page? Is there another strategy that you'd recommend to use this on certain pages?

**Comment by packagethief** [comment]
@gregblass, that's pretty much what we do in Basecamp. We use a controller concern to define a declarative syntax for use in a `before_action`. By default, we disable the preview cache for the `:new` and `:edit` actions.

```ruby
# app/controllers/concerns/turbolinks_cache_control.rb
module TurbolinksCacheControl
  extend ActiveSupport::Concern

  included do
    before_action :disable_turbolinks_preview_cache, only: [ :new, :edit ]
  end

  private
    def enable_turbolinks_cache
      @turbolinks_cache_control = 'cache'
    end

    def disable_turbolinks_cache
      @turbolinks_cache_control = 'no-cache'
    end

    def disable_turbolinks_preview_cache
      @turbolinks_cache_control = 'no-preview'
    end
end
```

Then, we use a helper method to render the meta tag:

```ruby
def turbolinks_cache_control_meta_tag
  tag :meta, name: 'turbolinks-cache-control', content: @turbolinks_cache_control || 'cache'
end
```

Then, in the layout:

```erb
<%= turbolinks_cache_control_meta_tag %>
```

**Comment by gregblass** [comment]
Awesome, thanks so much! This is great. And you place the meta tag in the head, correct? Or does it need to go inside the body since that's whats being replaced (but meta tags belong in the head, right?)

**Comment by packagethief** [comment]
In the `<head>`, correct. The head is merged; provisional elements, like meta tags, are replaced.

**Comment by gregblass** [comment]
Ah, I did not know! Thanks again!

**Comment by gregblass** [comment]
This worked perfectly in my production app (as expected). Gonna use this pattern in all my Rails/Turbolinks client apps.

**Comment by kstratis** [comment]
A bit late to the party, but [this guy on stackoverflow](https://stackoverflow.com/a/39801052/178728) has an even easier solution (same concept though):

Throw this in the layout:
```ruby
<% if content_for?(:head) %>
  <%= yield(:head) %>
<% end %>
```

and then inside the view we don't want to cache we simply do:

```ruby
<% content_for :head do %>
  <meta name="turbolinks-cache-control" content="no-cache">
<% end %>
```

For the record, the both solutions worked for me even through the concern-based is technically far more sophisticated.
