### ISSUE TITLE
Does not degrade gracefully on IE9

### ISSUE THREAD

**Issue by fschwahn** [turbolinks/turbolinks#89]
When loading a page which includes turbolinks in IE9, Turbolinks causes an error. I think the reason is that IE9 does not implement `classList` - however adding the polyfill from https://developer.mozilla.org/en/docs/Web/API/Element/classList didn't make the error go away. If I remove turbolinks completely, the javascript error goes away.

I'd expect Turbolinks not to cause an error, even if included in a browser which is not supported.

**Comment by jonchay** [comment]
👍 on this issue. We have an error raised:
```
SCRIPT5007: Unable to get value of the property 'add': object is null or undefined
```

**Comment by nateberkopec** [comment]
Agreed, can you guys check out #90 and see if that fixes the issue for you?
