### ISSUE TITLE
"Uncaught ReferenceError: Turbolinks is not defined" when required with Browserify

### ISSUE THREAD

**Issue by ChristianTreubig** [turbolinks/turbolinks#91]
We are using Browserify to build our front-end assets. We successfully installed the `turbolinks` npm package and compiled the assets, but when the page loads in the browser, `Uncaught ReferenceError: Turbolinks is not defined` is raised in the package code `dist/turbolinks.js` at `Turbolinks.copyObject=function(t){var e,r,n;r={}; ...`

Oddly, we are able to use the package if we paste the raw `dist/turbolinks.js` into a script tag in the html head.

Are there any steps we need to take in order to get this package to work with Browserify? If Browserify is currently unsupported, are you open to pull requests to introduce support? Any pointers would be appreciated.

Thanks

**Comment by nateberkopec** [comment]
Ping @justin808

**Comment by justin808** [comment]
I've never used browserify. Any reason not to use webpack?

**Comment by jeremy** [comment]
In the same vein as #13.
