### ISSUE TITLE
How to reset turbo links on links added by JS ?

### ISSUE THREAD

**Issue by Activee** [turbolinks/turbolinks#92]
I've changed this post many time so I'm sorry for that, I am really tirred.

So when a link is added with JS, I get that I can listen to dom change events as it's described in the readme but then what ? How can one reset turbolink for a node ? 

Or is one expected to run Turbolinks.visit("/edit", { action: "replace" })  on the newly added links ? I'm not a fan of that.

**Comment by packagethief** [comment]
Programmatically inserted link elements should work fine (I just tested to confirm). I may be misunderstanding what you mean by "reset turbolinks on a node", though. Can you clarify?

**Comment by Activee** [comment]
The response status code for that special link I was inserting was 301. It's because I'm using something that removes the extension of url and I forgot to remove the extension in the link.

so: 

```
<a href="blablabla">link working</a>
<a href="blablabla.xhtml">link not working</a>
```

cheers
