### ISSUE TITLE
Non-id hash breaks navigation

### ISSUE THREAD

**Issue by nanaya** [turbolinks/turbolinks#95]
1. visit a turbolink page with non-id hash (`http://somewhere.com/a#123`)
2. navigate within turbolinks scope
3. go back
4. `SyntaxError: An invalid or illegal string was specified` is raised when calling `snapshot.coffee`'s `hasAnchor`

I tried fixing it by replacing with `getElementById` but noticed the variable doesn't have the function so I replaced it by [prepending the call with `try`](/turbolinks/turbolinks/compare/master...nanaya:any-hash) and it seems to work. I can't reopen the pull request though (probably because it's force-pushed?) and since there's no example of `try` usage in codebase I'm opening this issue instead (and maybe someone else have better idea).

**Comment by packagethief** [comment]
Thanks @nanaya! I think `try` is appropriate here and your change looks good. I'm not sure why you can't open a PR. If you want to try again, I'd be happy to merge.

**Comment by nanaya** [comment]
Not that I can't open, I just can't reopen previous one and creating another PR immediately doesn't feel right (and I might've missed something else). Anyway, opened another PR. Thanks.

**Comment by javan** [comment]
I suggest using `@body.querySelector("[id='#{anchor}']")` instead:

<img width="421" alt="screen shot 2016-05-12 at 10 43 31 am" src="https://cloud.githubusercontent.com/assets/5355/15218596/a80c7e08-182e-11e6-819d-709be01e1663.png">

**Comment by nanaya** [comment]
Interesting, id from starting by a number (as per validator) is not allowed in html 4 but later it's allowed in html5 except for some reason `querySelector` is not updated to handle it.

**Comment by nanaya** [comment]
Oh, it's explained [here](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector)

> To match ID or selectors that do not follow the CSS syntax (by using a colon or space inappropriately for example), you must escape the character with a back slash. As the backslash is an escape character in JavaScript, if you are entering a literal string, you must escape it twice (once for the JavaScript string, and another time for querySelector):

I learned something today.

**Comment by packagethief** [comment]
The nice thing about @javan's suggestion is that we'd still be able to select elements like `id=123`, which are legit in HTML5. It's still possible to produce an invalid selector though (e.g., suppose your anchor is `#'`), so we should keep the `try`. In the future we can probably remove the need for it by escaping `anchor`.

```coffee
  try @body.querySelector("[id='#{anchor}']")?
```

Mind updating your PR to change the selector @nanaya?
