### ISSUE TITLE
Rails 5.0.0.rc1 Turbolinks displays older value before showing the new one

### ISSUE THREAD

**Issue by dlcmh** [turbolinks/turbolinks#97]
Created a new, minimal Rails app with the following:

```
rails new quicktest --pre
cd quicktest
rails g scaffold quick title
```

Modified `/app/views/quicks/new.html.erb` to contain the following code:

```ruby
<h1><%= sleep 0.2; Time.now %></h1>

<%= render 'form', quick: @quick %>

<%= link_to 'New', new_quick_path %>
```

Below is a screencap of me clicking the `New` link in `localhost:3001/quicks/new` repeatedly - any idea why the older Time value is displayed prior to showing the new one?

![out](https://cloud.githubusercontent.com/assets/116972/15268002/67990c7e-1a04-11e6-8e9c-8a814cfc6f59.gif)

**Comment by nateberkopec** [comment]
[That's the preview cache in action](https://github.com/turbolinks/turbolinks#understanding-caching). It would probably be appropriate to disable it in this context.

**Comment by dlcmh** [comment]
Thanks Nate - that did the trick!

I ended up with the following `tag` code (http://edgeapi.rubyonrails.org/classes/ActionView/Helpers/TagHelper.html#method-i-content_tag) in `<head>` to disable caching only for a specific route:

```
<%= tag("meta", {name: "turbolinks-cache-control", content: "no-cache"}, true) if current_page?(pick_random_cards_path) %>
```

**Comment by nateberkopec** [comment]
@dlcmh A cleaner way might be a `content_for` block.

In your view:

```
<h1><%= sleep 0.2; Time.now %></h1>

<%= render 'form', quick: @quick %>

<%= link_to 'New', new_quick_path %>

<% content_for :head do %>
  <%= tag("meta", {name: "turbolinks-cache-control", content: "no-cache"}, true) %>
<% end%>
```

In your head section:

```
<%= yield :head %>
```

**Comment by dlcmh** [comment]
Thanks again, Nate. I'm going with your suggestion.
